package co.gov.dafp.sigep2.bean;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ArchivoCargueLogExample {
	/**
	 * 
	 */
	private int limitInit;
	/**
	 * 
	 */
	private int limitEnd;
	
	/**
	 * @return the limitInit
	 */
	public int getLimitInit() {
		return limitInit;
	}

	/**
	 * @param limitInit the limitInit to set
	 */
	public void setLimitInit(int limitInit) {
		this.limitInit = limitInit;
	}
	
	
	
    /**
	 * @return the limitEnd
	 */
	public int getLimitEnd() {
		return limitEnd;
	}

	/**
	 * @param limitEnd the limitEnd to set
	 */
	public void setLimitEnd(int limitEnd) {
		this.limitEnd = limitEnd;
	}
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ARCHIVO_CARGUE_LOG
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ARCHIVO_CARGUE_LOG
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ARCHIVO_CARGUE_LOG
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARCHIVO_CARGUE_LOG
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    public ArchivoCargueLogExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARCHIVO_CARGUE_LOG
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARCHIVO_CARGUE_LOG
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARCHIVO_CARGUE_LOG
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARCHIVO_CARGUE_LOG
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARCHIVO_CARGUE_LOG
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARCHIVO_CARGUE_LOG
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARCHIVO_CARGUE_LOG
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARCHIVO_CARGUE_LOG
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARCHIVO_CARGUE_LOG
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARCHIVO_CARGUE_LOG
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ARCHIVO_CARGUE_LOG
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCodArchivoCargueLogIsNull() {
            addCriterion("COD_ARCHIVO_CARGUE_LOG is null");
            return (Criteria) this;
        }

        public Criteria andCodArchivoCargueLogIsNotNull() {
            addCriterion("COD_ARCHIVO_CARGUE_LOG is not null");
            return (Criteria) this;
        }

        public Criteria andCodArchivoCargueLogEqualTo(BigDecimal value) {
            addCriterion("COD_ARCHIVO_CARGUE_LOG =", value, "codArchivoCargueLog");
            return (Criteria) this;
        }

        public Criteria andCodArchivoCargueLogNotEqualTo(BigDecimal value) {
            addCriterion("COD_ARCHIVO_CARGUE_LOG <>", value, "codArchivoCargueLog");
            return (Criteria) this;
        }

        public Criteria andCodArchivoCargueLogGreaterThan(BigDecimal value) {
            addCriterion("COD_ARCHIVO_CARGUE_LOG >", value, "codArchivoCargueLog");
            return (Criteria) this;
        }

        public Criteria andCodArchivoCargueLogGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("COD_ARCHIVO_CARGUE_LOG >=", value, "codArchivoCargueLog");
            return (Criteria) this;
        }

        public Criteria andCodArchivoCargueLogLessThan(BigDecimal value) {
            addCriterion("COD_ARCHIVO_CARGUE_LOG <", value, "codArchivoCargueLog");
            return (Criteria) this;
        }

        public Criteria andCodArchivoCargueLogLessThanOrEqualTo(BigDecimal value) {
            addCriterion("COD_ARCHIVO_CARGUE_LOG <=", value, "codArchivoCargueLog");
            return (Criteria) this;
        }

        public Criteria andCodArchivoCargueLogIn(List<BigDecimal> values) {
            addCriterion("COD_ARCHIVO_CARGUE_LOG in", values, "codArchivoCargueLog");
            return (Criteria) this;
        }

        public Criteria andCodArchivoCargueLogNotIn(List<BigDecimal> values) {
            addCriterion("COD_ARCHIVO_CARGUE_LOG not in", values, "codArchivoCargueLog");
            return (Criteria) this;
        }

        public Criteria andCodArchivoCargueLogBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("COD_ARCHIVO_CARGUE_LOG between", value1, value2, "codArchivoCargueLog");
            return (Criteria) this;
        }

        public Criteria andCodArchivoCargueLogNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("COD_ARCHIVO_CARGUE_LOG not between", value1, value2, "codArchivoCargueLog");
            return (Criteria) this;
        }

        public Criteria andCodArchivoCargueIsNull() {
            addCriterion("COD_ARCHIVO_CARGUE is null");
            return (Criteria) this;
        }

        public Criteria andCodArchivoCargueIsNotNull() {
            addCriterion("COD_ARCHIVO_CARGUE is not null");
            return (Criteria) this;
        }

        public Criteria andCodArchivoCargueEqualTo(BigDecimal value) {
            addCriterion("COD_ARCHIVO_CARGUE =", value, "codArchivoCargue");
            return (Criteria) this;
        }

        public Criteria andCodArchivoCargueNotEqualTo(BigDecimal value) {
            addCriterion("COD_ARCHIVO_CARGUE <>", value, "codArchivoCargue");
            return (Criteria) this;
        }

        public Criteria andCodArchivoCargueGreaterThan(BigDecimal value) {
            addCriterion("COD_ARCHIVO_CARGUE >", value, "codArchivoCargue");
            return (Criteria) this;
        }

        public Criteria andCodArchivoCargueGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("COD_ARCHIVO_CARGUE >=", value, "codArchivoCargue");
            return (Criteria) this;
        }

        public Criteria andCodArchivoCargueLessThan(BigDecimal value) {
            addCriterion("COD_ARCHIVO_CARGUE <", value, "codArchivoCargue");
            return (Criteria) this;
        }

        public Criteria andCodArchivoCargueLessThanOrEqualTo(BigDecimal value) {
            addCriterion("COD_ARCHIVO_CARGUE <=", value, "codArchivoCargue");
            return (Criteria) this;
        }

        public Criteria andCodArchivoCargueIn(List<BigDecimal> values) {
            addCriterion("COD_ARCHIVO_CARGUE in", values, "codArchivoCargue");
            return (Criteria) this;
        }

        public Criteria andCodArchivoCargueNotIn(List<BigDecimal> values) {
            addCriterion("COD_ARCHIVO_CARGUE not in", values, "codArchivoCargue");
            return (Criteria) this;
        }

        public Criteria andCodArchivoCargueBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("COD_ARCHIVO_CARGUE between", value1, value2, "codArchivoCargue");
            return (Criteria) this;
        }

        public Criteria andCodArchivoCargueNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("COD_ARCHIVO_CARGUE not between", value1, value2, "codArchivoCargue");
            return (Criteria) this;
        }

        public Criteria andErrorIsNull() {
            addCriterion("ERROR is null");
            return (Criteria) this;
        }

        public Criteria andErrorIsNotNull() {
            addCriterion("ERROR is not null");
            return (Criteria) this;
        }

        public Criteria andErrorEqualTo(String value) {
            addCriterion("ERROR =", value, "error");
            return (Criteria) this;
        }

        public Criteria andErrorNotEqualTo(String value) {
            addCriterion("ERROR <>", value, "error");
            return (Criteria) this;
        }

        public Criteria andErrorGreaterThan(String value) {
            addCriterion("ERROR >", value, "error");
            return (Criteria) this;
        }

        public Criteria andErrorGreaterThanOrEqualTo(String value) {
            addCriterion("ERROR >=", value, "error");
            return (Criteria) this;
        }

        public Criteria andErrorLessThan(String value) {
            addCriterion("ERROR <", value, "error");
            return (Criteria) this;
        }

        public Criteria andErrorLessThanOrEqualTo(String value) {
            addCriterion("ERROR <=", value, "error");
            return (Criteria) this;
        }

        public Criteria andErrorLike(String value) {
            addCriterion("ERROR like", value, "error");
            return (Criteria) this;
        }

        public Criteria andErrorNotLike(String value) {
            addCriterion("ERROR not like", value, "error");
            return (Criteria) this;
        }

        public Criteria andErrorIn(List<String> values) {
            addCriterion("ERROR in", values, "error");
            return (Criteria) this;
        }

        public Criteria andErrorNotIn(List<String> values) {
            addCriterion("ERROR not in", values, "error");
            return (Criteria) this;
        }

        public Criteria andErrorBetween(String value1, String value2) {
            addCriterion("ERROR between", value1, value2, "error");
            return (Criteria) this;
        }

        public Criteria andErrorNotBetween(String value1, String value2) {
            addCriterion("ERROR not between", value1, value2, "error");
            return (Criteria) this;
        }

        public Criteria andValidacionIsNull() {
            addCriterion("VALIDACION is null");
            return (Criteria) this;
        }

        public Criteria andValidacionIsNotNull() {
            addCriterion("VALIDACION is not null");
            return (Criteria) this;
        }

        public Criteria andValidacionEqualTo(String value) {
            addCriterion("VALIDACION =", value, "validacion");
            return (Criteria) this;
        }

        public Criteria andValidacionNotEqualTo(String value) {
            addCriterion("VALIDACION <>", value, "validacion");
            return (Criteria) this;
        }

        public Criteria andValidacionGreaterThan(String value) {
            addCriterion("VALIDACION >", value, "validacion");
            return (Criteria) this;
        }

        public Criteria andValidacionGreaterThanOrEqualTo(String value) {
            addCriterion("VALIDACION >=", value, "validacion");
            return (Criteria) this;
        }

        public Criteria andValidacionLessThan(String value) {
            addCriterion("VALIDACION <", value, "validacion");
            return (Criteria) this;
        }

        public Criteria andValidacionLessThanOrEqualTo(String value) {
            addCriterion("VALIDACION <=", value, "validacion");
            return (Criteria) this;
        }

        public Criteria andValidacionLike(String value) {
            addCriterion("VALIDACION like", value, "validacion");
            return (Criteria) this;
        }

        public Criteria andValidacionNotLike(String value) {
            addCriterion("VALIDACION not like", value, "validacion");
            return (Criteria) this;
        }

        public Criteria andValidacionIn(List<String> values) {
            addCriterion("VALIDACION in", values, "validacion");
            return (Criteria) this;
        }

        public Criteria andValidacionNotIn(List<String> values) {
            addCriterion("VALIDACION not in", values, "validacion");
            return (Criteria) this;
        }

        public Criteria andValidacionBetween(String value1, String value2) {
            addCriterion("VALIDACION between", value1, value2, "validacion");
            return (Criteria) this;
        }

        public Criteria andValidacionNotBetween(String value1, String value2) {
            addCriterion("VALIDACION not between", value1, value2, "validacion");
            return (Criteria) this;
        }

        public Criteria andRegistroIsNull() {
            addCriterion("REGISTRO is null");
            return (Criteria) this;
        }

        public Criteria andRegistroIsNotNull() {
            addCriterion("REGISTRO is not null");
            return (Criteria) this;
        }

        public Criteria andRegistroEqualTo(String value) {
            addCriterion("REGISTRO =", value, "registro");
            return (Criteria) this;
        }

        public Criteria andRegistroNotEqualTo(String value) {
            addCriterion("REGISTRO <>", value, "registro");
            return (Criteria) this;
        }

        public Criteria andRegistroGreaterThan(String value) {
            addCriterion("REGISTRO >", value, "registro");
            return (Criteria) this;
        }

        public Criteria andRegistroGreaterThanOrEqualTo(String value) {
            addCriterion("REGISTRO >=", value, "registro");
            return (Criteria) this;
        }

        public Criteria andRegistroLessThan(String value) {
            addCriterion("REGISTRO <", value, "registro");
            return (Criteria) this;
        }

        public Criteria andRegistroLessThanOrEqualTo(String value) {
            addCriterion("REGISTRO <=", value, "registro");
            return (Criteria) this;
        }

        public Criteria andRegistroLike(String value) {
            addCriterion("REGISTRO like", value, "registro");
            return (Criteria) this;
        }

        public Criteria andRegistroNotLike(String value) {
            addCriterion("REGISTRO not like", value, "registro");
            return (Criteria) this;
        }

        public Criteria andRegistroIn(List<String> values) {
            addCriterion("REGISTRO in", values, "registro");
            return (Criteria) this;
        }

        public Criteria andRegistroNotIn(List<String> values) {
            addCriterion("REGISTRO not in", values, "registro");
            return (Criteria) this;
        }

        public Criteria andRegistroBetween(String value1, String value2) {
            addCriterion("REGISTRO between", value1, value2, "registro");
            return (Criteria) this;
        }

        public Criteria andRegistroNotBetween(String value1, String value2) {
            addCriterion("REGISTRO not between", value1, value2, "registro");
            return (Criteria) this;
        }

        public Criteria andFlgLogExitosoIsNull() {
            addCriterion("FLG_LOG_EXITOSO is null");
            return (Criteria) this;
        }

        public Criteria andFlgLogExitosoIsNotNull() {
            addCriterion("FLG_LOG_EXITOSO is not null");
            return (Criteria) this;
        }

        public Criteria andFlgLogExitosoEqualTo(Short value) {
            addCriterion("FLG_LOG_EXITOSO =", value, "flgLogExitoso");
            return (Criteria) this;
        }

        public Criteria andFlgLogExitosoNotEqualTo(Short value) {
            addCriterion("FLG_LOG_EXITOSO <>", value, "flgLogExitoso");
            return (Criteria) this;
        }

        public Criteria andFlgLogExitosoGreaterThan(Short value) {
            addCriterion("FLG_LOG_EXITOSO >", value, "flgLogExitoso");
            return (Criteria) this;
        }

        public Criteria andFlgLogExitosoGreaterThanOrEqualTo(Short value) {
            addCriterion("FLG_LOG_EXITOSO >=", value, "flgLogExitoso");
            return (Criteria) this;
        }

        public Criteria andFlgLogExitosoLessThan(Short value) {
            addCriterion("FLG_LOG_EXITOSO <", value, "flgLogExitoso");
            return (Criteria) this;
        }

        public Criteria andFlgLogExitosoLessThanOrEqualTo(Short value) {
            addCriterion("FLG_LOG_EXITOSO <=", value, "flgLogExitoso");
            return (Criteria) this;
        }

        public Criteria andFlgLogExitosoIn(List<Short> values) {
            addCriterion("FLG_LOG_EXITOSO in", values, "flgLogExitoso");
            return (Criteria) this;
        }

        public Criteria andFlgLogExitosoNotIn(List<Short> values) {
            addCriterion("FLG_LOG_EXITOSO not in", values, "flgLogExitoso");
            return (Criteria) this;
        }

        public Criteria andFlgLogExitosoBetween(Short value1, Short value2) {
            addCriterion("FLG_LOG_EXITOSO between", value1, value2, "flgLogExitoso");
            return (Criteria) this;
        }

        public Criteria andFlgLogExitosoNotBetween(Short value1, Short value2) {
            addCriterion("FLG_LOG_EXITOSO not between", value1, value2, "flgLogExitoso");
            return (Criteria) this;
        }

        public Criteria andFlgEstadoIsNull() {
            addCriterion("FLG_ESTADO is null");
            return (Criteria) this;
        }

        public Criteria andFlgEstadoIsNotNull() {
            addCriterion("FLG_ESTADO is not null");
            return (Criteria) this;
        }

        public Criteria andFlgEstadoEqualTo(Short value) {
            addCriterion("FLG_ESTADO =", value, "flgEstado");
            return (Criteria) this;
        }

        public Criteria andFlgEstadoNotEqualTo(Short value) {
            addCriterion("FLG_ESTADO <>", value, "flgEstado");
            return (Criteria) this;
        }

        public Criteria andFlgEstadoGreaterThan(Short value) {
            addCriterion("FLG_ESTADO >", value, "flgEstado");
            return (Criteria) this;
        }

        public Criteria andFlgEstadoGreaterThanOrEqualTo(Short value) {
            addCriterion("FLG_ESTADO >=", value, "flgEstado");
            return (Criteria) this;
        }

        public Criteria andFlgEstadoLessThan(Short value) {
            addCriterion("FLG_ESTADO <", value, "flgEstado");
            return (Criteria) this;
        }

        public Criteria andFlgEstadoLessThanOrEqualTo(Short value) {
            addCriterion("FLG_ESTADO <=", value, "flgEstado");
            return (Criteria) this;
        }

        public Criteria andFlgEstadoIn(List<Short> values) {
            addCriterion("FLG_ESTADO in", values, "flgEstado");
            return (Criteria) this;
        }

        public Criteria andFlgEstadoNotIn(List<Short> values) {
            addCriterion("FLG_ESTADO not in", values, "flgEstado");
            return (Criteria) this;
        }

        public Criteria andFlgEstadoBetween(Short value1, Short value2) {
            addCriterion("FLG_ESTADO between", value1, value2, "flgEstado");
            return (Criteria) this;
        }

        public Criteria andFlgEstadoNotBetween(Short value1, Short value2) {
            addCriterion("FLG_ESTADO not between", value1, value2, "flgEstado");
            return (Criteria) this;
        }

        public Criteria andAudFechaModificacionIsNull() {
            addCriterion("AUD_FECHA_MODIFICACION is null");
            return (Criteria) this;
        }

        public Criteria andAudFechaModificacionIsNotNull() {
            addCriterion("AUD_FECHA_MODIFICACION is not null");
            return (Criteria) this;
        }

        public Criteria andAudFechaModificacionEqualTo(Date value) {
            addCriterion("AUD_FECHA_MODIFICACION =", value, "audFechaModificacion");
            return (Criteria) this;
        }

        public Criteria andAudFechaModificacionNotEqualTo(Date value) {
            addCriterion("AUD_FECHA_MODIFICACION <>", value, "audFechaModificacion");
            return (Criteria) this;
        }

        public Criteria andAudFechaModificacionGreaterThan(Date value) {
            addCriterion("AUD_FECHA_MODIFICACION >", value, "audFechaModificacion");
            return (Criteria) this;
        }

        public Criteria andAudFechaModificacionGreaterThanOrEqualTo(Date value) {
            addCriterion("AUD_FECHA_MODIFICACION >=", value, "audFechaModificacion");
            return (Criteria) this;
        }

        public Criteria andAudFechaModificacionLessThan(Date value) {
            addCriterion("AUD_FECHA_MODIFICACION <", value, "audFechaModificacion");
            return (Criteria) this;
        }

        public Criteria andAudFechaModificacionLessThanOrEqualTo(Date value) {
            addCriterion("AUD_FECHA_MODIFICACION <=", value, "audFechaModificacion");
            return (Criteria) this;
        }

        public Criteria andAudFechaModificacionIn(List<Date> values) {
            addCriterion("AUD_FECHA_MODIFICACION in", values, "audFechaModificacion");
            return (Criteria) this;
        }

        public Criteria andAudFechaModificacionNotIn(List<Date> values) {
            addCriterion("AUD_FECHA_MODIFICACION not in", values, "audFechaModificacion");
            return (Criteria) this;
        }

        public Criteria andAudFechaModificacionBetween(Date value1, Date value2) {
            addCriterion("AUD_FECHA_MODIFICACION between", value1, value2, "audFechaModificacion");
            return (Criteria) this;
        }

        public Criteria andAudFechaModificacionNotBetween(Date value1, Date value2) {
            addCriterion("AUD_FECHA_MODIFICACION not between", value1, value2, "audFechaModificacion");
            return (Criteria) this;
        }

        public Criteria andAudCodUsuarioIsNull() {
            addCriterion("AUD_COD_USUARIO is null");
            return (Criteria) this;
        }

        public Criteria andAudCodUsuarioIsNotNull() {
            addCriterion("AUD_COD_USUARIO is not null");
            return (Criteria) this;
        }

        public Criteria andAudCodUsuarioEqualTo(BigDecimal value) {
            addCriterion("AUD_COD_USUARIO =", value, "audCodUsuario");
            return (Criteria) this;
        }

        public Criteria andAudCodUsuarioNotEqualTo(BigDecimal value) {
            addCriterion("AUD_COD_USUARIO <>", value, "audCodUsuario");
            return (Criteria) this;
        }

        public Criteria andAudCodUsuarioGreaterThan(BigDecimal value) {
            addCriterion("AUD_COD_USUARIO >", value, "audCodUsuario");
            return (Criteria) this;
        }

        public Criteria andAudCodUsuarioGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("AUD_COD_USUARIO >=", value, "audCodUsuario");
            return (Criteria) this;
        }

        public Criteria andAudCodUsuarioLessThan(BigDecimal value) {
            addCriterion("AUD_COD_USUARIO <", value, "audCodUsuario");
            return (Criteria) this;
        }

        public Criteria andAudCodUsuarioLessThanOrEqualTo(BigDecimal value) {
            addCriterion("AUD_COD_USUARIO <=", value, "audCodUsuario");
            return (Criteria) this;
        }

        public Criteria andAudCodUsuarioIn(List<BigDecimal> values) {
            addCriterion("AUD_COD_USUARIO in", values, "audCodUsuario");
            return (Criteria) this;
        }

        public Criteria andAudCodUsuarioNotIn(List<BigDecimal> values) {
            addCriterion("AUD_COD_USUARIO not in", values, "audCodUsuario");
            return (Criteria) this;
        }

        public Criteria andAudCodUsuarioBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AUD_COD_USUARIO between", value1, value2, "audCodUsuario");
            return (Criteria) this;
        }

        public Criteria andAudCodUsuarioNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AUD_COD_USUARIO not between", value1, value2, "audCodUsuario");
            return (Criteria) this;
        }

        public Criteria andAudCodRolIsNull() {
            addCriterion("AUD_COD_ROL is null");
            return (Criteria) this;
        }

        public Criteria andAudCodRolIsNotNull() {
            addCriterion("AUD_COD_ROL is not null");
            return (Criteria) this;
        }

        public Criteria andAudCodRolEqualTo(BigDecimal value) {
            addCriterion("AUD_COD_ROL =", value, "audCodRol");
            return (Criteria) this;
        }

        public Criteria andAudCodRolNotEqualTo(BigDecimal value) {
            addCriterion("AUD_COD_ROL <>", value, "audCodRol");
            return (Criteria) this;
        }

        public Criteria andAudCodRolGreaterThan(BigDecimal value) {
            addCriterion("AUD_COD_ROL >", value, "audCodRol");
            return (Criteria) this;
        }

        public Criteria andAudCodRolGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("AUD_COD_ROL >=", value, "audCodRol");
            return (Criteria) this;
        }

        public Criteria andAudCodRolLessThan(BigDecimal value) {
            addCriterion("AUD_COD_ROL <", value, "audCodRol");
            return (Criteria) this;
        }

        public Criteria andAudCodRolLessThanOrEqualTo(BigDecimal value) {
            addCriterion("AUD_COD_ROL <=", value, "audCodRol");
            return (Criteria) this;
        }

        public Criteria andAudCodRolIn(List<BigDecimal> values) {
            addCriterion("AUD_COD_ROL in", values, "audCodRol");
            return (Criteria) this;
        }

        public Criteria andAudCodRolNotIn(List<BigDecimal> values) {
            addCriterion("AUD_COD_ROL not in", values, "audCodRol");
            return (Criteria) this;
        }

        public Criteria andAudCodRolBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AUD_COD_ROL between", value1, value2, "audCodRol");
            return (Criteria) this;
        }

        public Criteria andAudCodRolNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AUD_COD_ROL not between", value1, value2, "audCodRol");
            return (Criteria) this;
        }

        public Criteria andAudAccionIsNull() {
            addCriterion("AUD_ACCION is null");
            return (Criteria) this;
        }

        public Criteria andAudAccionIsNotNull() {
            addCriterion("AUD_ACCION is not null");
            return (Criteria) this;
        }

        public Criteria andAudAccionEqualTo(String value) {
            addCriterion("AUD_ACCION =", value, "audAccion");
            return (Criteria) this;
        }

        public Criteria andAudAccionNotEqualTo(String value) {
            addCriterion("AUD_ACCION <>", value, "audAccion");
            return (Criteria) this;
        }

        public Criteria andAudAccionGreaterThan(String value) {
            addCriterion("AUD_ACCION >", value, "audAccion");
            return (Criteria) this;
        }

        public Criteria andAudAccionGreaterThanOrEqualTo(String value) {
            addCriterion("AUD_ACCION >=", value, "audAccion");
            return (Criteria) this;
        }

        public Criteria andAudAccionLessThan(String value) {
            addCriterion("AUD_ACCION <", value, "audAccion");
            return (Criteria) this;
        }

        public Criteria andAudAccionLessThanOrEqualTo(String value) {
            addCriterion("AUD_ACCION <=", value, "audAccion");
            return (Criteria) this;
        }

        public Criteria andAudAccionLike(String value) {
            addCriterion("AUD_ACCION like", value, "audAccion");
            return (Criteria) this;
        }

        public Criteria andAudAccionNotLike(String value) {
            addCriterion("AUD_ACCION not like", value, "audAccion");
            return (Criteria) this;
        }

        public Criteria andAudAccionIn(List<String> values) {
            addCriterion("AUD_ACCION in", values, "audAccion");
            return (Criteria) this;
        }

        public Criteria andAudAccionNotIn(List<String> values) {
            addCriterion("AUD_ACCION not in", values, "audAccion");
            return (Criteria) this;
        }

        public Criteria andAudAccionBetween(String value1, String value2) {
            addCriterion("AUD_ACCION between", value1, value2, "audAccion");
            return (Criteria) this;
        }

        public Criteria andAudAccionNotBetween(String value1, String value2) {
            addCriterion("AUD_ACCION not between", value1, value2, "audAccion");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ARCHIVO_CARGUE_LOG
     *
     * @mbg.generated do_not_delete_during_merge Mon Jan 29 14:57:36 COT 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ARCHIVO_CARGUE_LOG
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}