package co.gov.dafp.sigep2.bean;

import java.math.BigDecimal;
import java.util.Date;

import co.gov.dafp.sigep2.utils.ErrorMensajes;

public class CalidadDeDatos  extends ErrorMensajes{
    /**
	 * 
	 */
	private static final long serialVersionUID = 4860406225770139008L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CALIDAD_DE_DATOS.COD_CALIDAD_DE_DATOS
     *
     * @mbg.generated Fri Nov 12 20:20:17 COT 2021
     */
    private BigDecimal codCalidadDeDatos;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CALIDAD_DE_DATOS.DATO_ORIGEN
     *
     * @mbg.generated Fri Nov 12 20:20:17 COT 2021
     */
    private String datoOrigen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CALIDAD_DE_DATOS.DATO_DESTINO
     *
     * @mbg.generated Fri Nov 12 20:20:17 COT 2021
     */
    private String datoDestino;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CALIDAD_DE_DATOS.TIPO
     *
     * @mbg.generated Fri Nov 12 20:20:17 COT 2021
     */
    private String tipo;
    
    private BigDecimal procesado;
    private BigDecimal codNotificacion;
    private Date fechaProceso;
    

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CALIDAD_DE_DATOS.COD_CALIDAD_DE_DATOS
     *
     * @return the value of CALIDAD_DE_DATOS.COD_CALIDAD_DE_DATOS
     *
     * @mbg.generated Fri Nov 12 20:20:17 COT 2021
     */
    public BigDecimal getCodCalidadDeDatos() {
        return codCalidadDeDatos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CALIDAD_DE_DATOS.COD_CALIDAD_DE_DATOS
     *
     * @param codCalidadDeDatos the value for CALIDAD_DE_DATOS.COD_CALIDAD_DE_DATOS
     *
     * @mbg.generated Fri Nov 12 20:20:17 COT 2021
     */
    public void setCodCalidadDeDatos(BigDecimal codCalidadDeDatos) {
        this.codCalidadDeDatos = codCalidadDeDatos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CALIDAD_DE_DATOS.DATO_ORIGEN
     *
     * @return the value of CALIDAD_DE_DATOS.DATO_ORIGEN
     *
     * @mbg.generated Fri Nov 12 20:20:17 COT 2021
     */
    public String getDatoOrigen() {
        return datoOrigen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CALIDAD_DE_DATOS.DATO_ORIGEN
     *
     * @param datoOrigen the value for CALIDAD_DE_DATOS.DATO_ORIGEN
     *
     * @mbg.generated Fri Nov 12 20:20:17 COT 2021
     */
    public void setDatoOrigen(String datoOrigen) {
        this.datoOrigen = datoOrigen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CALIDAD_DE_DATOS.DATO_DESTINO
     *
     * @return the value of CALIDAD_DE_DATOS.DATO_DESTINO
     *
     * @mbg.generated Fri Nov 12 20:20:17 COT 2021
     */
    public String getDatoDestino() {
        return datoDestino;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CALIDAD_DE_DATOS.DATO_DESTINO
     *
     * @param datoDestino the value for CALIDAD_DE_DATOS.DATO_DESTINO
     *
     * @mbg.generated Fri Nov 12 20:20:17 COT 2021
     */
    public void setDatoDestino(String datoDestino) {
        this.datoDestino = datoDestino;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CALIDAD_DE_DATOS.TIPO
     *
     * @return the value of CALIDAD_DE_DATOS.TIPO
     *
     * @mbg.generated Fri Nov 12 20:20:17 COT 2021
     */
    public String getTipo() {
        return tipo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CALIDAD_DE_DATOS.TIPO
     *
     * @param tipo the value for CALIDAD_DE_DATOS.TIPO
     *
     * @mbg.generated Fri Nov 12 20:20:17 COT 2021
     */
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

	public BigDecimal getProcesado() {
		return procesado;
	}

	public void setProcesado(BigDecimal procesado) {
		this.procesado = procesado;
	}

	public BigDecimal getCodNotificacion() {
		return codNotificacion;
	}

	public void setCodNotificacion(BigDecimal codNotificacion) {
		this.codNotificacion = codNotificacion;
	}

	public Date getFechaProceso() {
		return fechaProceso;
	}

	public void setFechaProceso(Date fechaProceso) {
		this.fechaProceso = fechaProceso;
	}
}