package co.gov.dafp.sigep2.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.math.BigDecimal;

public class CmActivarUsuariosExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table CM_ACTIVAR_USUARIOS
	 * @mbg.generated  Thu Aug 16 07:59:13 COT 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table CM_ACTIVAR_USUARIOS
	 * @mbg.generated  Thu Aug 16 07:59:13 COT 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table CM_ACTIVAR_USUARIOS
	 * @mbg.generated  Thu Aug 16 07:59:13 COT 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CM_ACTIVAR_USUARIOS
	 * @mbg.generated  Thu Aug 16 07:59:13 COT 2018
	 */
	public CmActivarUsuariosExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CM_ACTIVAR_USUARIOS
	 * @mbg.generated  Thu Aug 16 07:59:13 COT 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CM_ACTIVAR_USUARIOS
	 * @mbg.generated  Thu Aug 16 07:59:13 COT 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CM_ACTIVAR_USUARIOS
	 * @mbg.generated  Thu Aug 16 07:59:13 COT 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CM_ACTIVAR_USUARIOS
	 * @mbg.generated  Thu Aug 16 07:59:13 COT 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CM_ACTIVAR_USUARIOS
	 * @mbg.generated  Thu Aug 16 07:59:13 COT 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CM_ACTIVAR_USUARIOS
	 * @mbg.generated  Thu Aug 16 07:59:13 COT 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CM_ACTIVAR_USUARIOS
	 * @mbg.generated  Thu Aug 16 07:59:13 COT 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CM_ACTIVAR_USUARIOS
	 * @mbg.generated  Thu Aug 16 07:59:13 COT 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CM_ACTIVAR_USUARIOS
	 * @mbg.generated  Thu Aug 16 07:59:13 COT 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CM_ACTIVAR_USUARIOS
	 * @mbg.generated  Thu Aug 16 07:59:13 COT 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table CM_ACTIVAR_USUARIOS
	 * @mbg.generated  Thu Aug 16 07:59:13 COT 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andCodCmActivarUsuariosIsNull() {
			addCriterion("COD_CM_ACTIVAR_USUARIOS is null");
			return (Criteria) this;
		}

		public Criteria andCodCmActivarUsuariosIsNotNull() {
			addCriterion("COD_CM_ACTIVAR_USUARIOS is not null");
			return (Criteria) this;
		}

		public Criteria andCodCmActivarUsuariosEqualTo(Long value) {
			addCriterion("COD_CM_ACTIVAR_USUARIOS =", value, "codCmActivarUsuarios");
			return (Criteria) this;
		}

		public Criteria andCodCmActivarUsuariosNotEqualTo(Long value) {
			addCriterion("COD_CM_ACTIVAR_USUARIOS <>", value, "codCmActivarUsuarios");
			return (Criteria) this;
		}

		public Criteria andCodCmActivarUsuariosGreaterThan(Long value) {
			addCriterion("COD_CM_ACTIVAR_USUARIOS >", value, "codCmActivarUsuarios");
			return (Criteria) this;
		}

		public Criteria andCodCmActivarUsuariosGreaterThanOrEqualTo(Long value) {
			addCriterion("COD_CM_ACTIVAR_USUARIOS >=", value, "codCmActivarUsuarios");
			return (Criteria) this;
		}

		public Criteria andCodCmActivarUsuariosLessThan(Long value) {
			addCriterion("COD_CM_ACTIVAR_USUARIOS <", value, "codCmActivarUsuarios");
			return (Criteria) this;
		}

		public Criteria andCodCmActivarUsuariosLessThanOrEqualTo(Long value) {
			addCriterion("COD_CM_ACTIVAR_USUARIOS <=", value, "codCmActivarUsuarios");
			return (Criteria) this;
		}

		public Criteria andCodCmActivarUsuariosIn(List<Long> values) {
			addCriterion("COD_CM_ACTIVAR_USUARIOS in", values, "codCmActivarUsuarios");
			return (Criteria) this;
		}

		public Criteria andCodCmActivarUsuariosNotIn(List<Long> values) {
			addCriterion("COD_CM_ACTIVAR_USUARIOS not in", values, "codCmActivarUsuarios");
			return (Criteria) this;
		}

		public Criteria andCodCmActivarUsuariosBetween(Long value1, Long value2) {
			addCriterion("COD_CM_ACTIVAR_USUARIOS between", value1, value2, "codCmActivarUsuarios");
			return (Criteria) this;
		}

		public Criteria andCodCmActivarUsuariosNotBetween(Long value1, Long value2) {
			addCriterion("COD_CM_ACTIVAR_USUARIOS not between", value1, value2, "codCmActivarUsuarios");
			return (Criteria) this;
		}

		public Criteria andCodTipoIdentificacionIsNull() {
			addCriterion("COD_TIPO_IDENTIFICACION is null");
			return (Criteria) this;
		}

		public Criteria andCodTipoIdentificacionIsNotNull() {
			addCriterion("COD_TIPO_IDENTIFICACION is not null");
			return (Criteria) this;
		}

		public Criteria andCodTipoIdentificacionEqualTo(BigDecimal value) {
			addCriterion("COD_TIPO_IDENTIFICACION =", value, "codTipoIdentificacion");
			return (Criteria) this;
		}

		public Criteria andCodTipoIdentificacionNotEqualTo(BigDecimal value) {
			addCriterion("COD_TIPO_IDENTIFICACION <>", value, "codTipoIdentificacion");
			return (Criteria) this;
		}

		public Criteria andCodTipoIdentificacionGreaterThan(BigDecimal value) {
			addCriterion("COD_TIPO_IDENTIFICACION >", value, "codTipoIdentificacion");
			return (Criteria) this;
		}

		public Criteria andCodTipoIdentificacionGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("COD_TIPO_IDENTIFICACION >=", value, "codTipoIdentificacion");
			return (Criteria) this;
		}

		public Criteria andCodTipoIdentificacionLessThan(BigDecimal value) {
			addCriterion("COD_TIPO_IDENTIFICACION <", value, "codTipoIdentificacion");
			return (Criteria) this;
		}

		public Criteria andCodTipoIdentificacionLessThanOrEqualTo(BigDecimal value) {
			addCriterion("COD_TIPO_IDENTIFICACION <=", value, "codTipoIdentificacion");
			return (Criteria) this;
		}

		public Criteria andCodTipoIdentificacionIn(List<BigDecimal> values) {
			addCriterion("COD_TIPO_IDENTIFICACION in", values, "codTipoIdentificacion");
			return (Criteria) this;
		}

		public Criteria andCodTipoIdentificacionNotIn(List<BigDecimal> values) {
			addCriterion("COD_TIPO_IDENTIFICACION not in", values, "codTipoIdentificacion");
			return (Criteria) this;
		}

		public Criteria andCodTipoIdentificacionBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("COD_TIPO_IDENTIFICACION between", value1, value2, "codTipoIdentificacion");
			return (Criteria) this;
		}

		public Criteria andCodTipoIdentificacionNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("COD_TIPO_IDENTIFICACION not between", value1, value2, "codTipoIdentificacion");
			return (Criteria) this;
		}

		public Criteria andNumeroIdentificacionIsNull() {
			addCriterion("NUMERO_IDENTIFICACION is null");
			return (Criteria) this;
		}

		public Criteria andNumeroIdentificacionIsNotNull() {
			addCriterion("NUMERO_IDENTIFICACION is not null");
			return (Criteria) this;
		}

		public Criteria andNumeroIdentificacionEqualTo(String value) {
			addCriterion("NUMERO_IDENTIFICACION =", value, "numeroIdentificacion");
			return (Criteria) this;
		}

		public Criteria andNumeroIdentificacionNotEqualTo(String value) {
			addCriterion("NUMERO_IDENTIFICACION <>", value, "numeroIdentificacion");
			return (Criteria) this;
		}

		public Criteria andNumeroIdentificacionGreaterThan(String value) {
			addCriterion("NUMERO_IDENTIFICACION >", value, "numeroIdentificacion");
			return (Criteria) this;
		}

		public Criteria andNumeroIdentificacionGreaterThanOrEqualTo(String value) {
			addCriterion("NUMERO_IDENTIFICACION >=", value, "numeroIdentificacion");
			return (Criteria) this;
		}

		public Criteria andNumeroIdentificacionLessThan(String value) {
			addCriterion("NUMERO_IDENTIFICACION <", value, "numeroIdentificacion");
			return (Criteria) this;
		}

		public Criteria andNumeroIdentificacionLessThanOrEqualTo(String value) {
			addCriterion("NUMERO_IDENTIFICACION <=", value, "numeroIdentificacion");
			return (Criteria) this;
		}

		public Criteria andNumeroIdentificacionLike(String value) {
			addCriterion("NUMERO_IDENTIFICACION like", value, "numeroIdentificacion");
			return (Criteria) this;
		}

		public Criteria andNumeroIdentificacionNotLike(String value) {
			addCriterion("NUMERO_IDENTIFICACION not like", value, "numeroIdentificacion");
			return (Criteria) this;
		}

		public Criteria andNumeroIdentificacionIn(List<String> values) {
			addCriterion("NUMERO_IDENTIFICACION in", values, "numeroIdentificacion");
			return (Criteria) this;
		}

		public Criteria andNumeroIdentificacionNotIn(List<String> values) {
			addCriterion("NUMERO_IDENTIFICACION not in", values, "numeroIdentificacion");
			return (Criteria) this;
		}

		public Criteria andNumeroIdentificacionBetween(String value1, String value2) {
			addCriterion("NUMERO_IDENTIFICACION between", value1, value2, "numeroIdentificacion");
			return (Criteria) this;
		}

		public Criteria andNumeroIdentificacionNotBetween(String value1, String value2) {
			addCriterion("NUMERO_IDENTIFICACION not between", value1, value2, "numeroIdentificacion");
			return (Criteria) this;
		}

		public Criteria andPrimerNombreIsNull() {
			addCriterion("PRIMER_NOMBRE is null");
			return (Criteria) this;
		}

		public Criteria andPrimerNombreIsNotNull() {
			addCriterion("PRIMER_NOMBRE is not null");
			return (Criteria) this;
		}

		public Criteria andPrimerNombreEqualTo(String value) {
			addCriterion("PRIMER_NOMBRE =", value, "primerNombre");
			return (Criteria) this;
		}

		public Criteria andPrimerNombreNotEqualTo(String value) {
			addCriterion("PRIMER_NOMBRE <>", value, "primerNombre");
			return (Criteria) this;
		}

		public Criteria andPrimerNombreGreaterThan(String value) {
			addCriterion("PRIMER_NOMBRE >", value, "primerNombre");
			return (Criteria) this;
		}

		public Criteria andPrimerNombreGreaterThanOrEqualTo(String value) {
			addCriterion("PRIMER_NOMBRE >=", value, "primerNombre");
			return (Criteria) this;
		}

		public Criteria andPrimerNombreLessThan(String value) {
			addCriterion("PRIMER_NOMBRE <", value, "primerNombre");
			return (Criteria) this;
		}

		public Criteria andPrimerNombreLessThanOrEqualTo(String value) {
			addCriterion("PRIMER_NOMBRE <=", value, "primerNombre");
			return (Criteria) this;
		}

		public Criteria andPrimerNombreLike(String value) {
			addCriterion("PRIMER_NOMBRE like", value, "primerNombre");
			return (Criteria) this;
		}

		public Criteria andPrimerNombreNotLike(String value) {
			addCriterion("PRIMER_NOMBRE not like", value, "primerNombre");
			return (Criteria) this;
		}

		public Criteria andPrimerNombreIn(List<String> values) {
			addCriterion("PRIMER_NOMBRE in", values, "primerNombre");
			return (Criteria) this;
		}

		public Criteria andPrimerNombreNotIn(List<String> values) {
			addCriterion("PRIMER_NOMBRE not in", values, "primerNombre");
			return (Criteria) this;
		}

		public Criteria andPrimerNombreBetween(String value1, String value2) {
			addCriterion("PRIMER_NOMBRE between", value1, value2, "primerNombre");
			return (Criteria) this;
		}

		public Criteria andPrimerNombreNotBetween(String value1, String value2) {
			addCriterion("PRIMER_NOMBRE not between", value1, value2, "primerNombre");
			return (Criteria) this;
		}

		public Criteria andSegundoNombreIsNull() {
			addCriterion("SEGUNDO_NOMBRE is null");
			return (Criteria) this;
		}

		public Criteria andSegundoNombreIsNotNull() {
			addCriterion("SEGUNDO_NOMBRE is not null");
			return (Criteria) this;
		}

		public Criteria andSegundoNombreEqualTo(String value) {
			addCriterion("SEGUNDO_NOMBRE =", value, "segundoNombre");
			return (Criteria) this;
		}

		public Criteria andSegundoNombreNotEqualTo(String value) {
			addCriterion("SEGUNDO_NOMBRE <>", value, "segundoNombre");
			return (Criteria) this;
		}

		public Criteria andSegundoNombreGreaterThan(String value) {
			addCriterion("SEGUNDO_NOMBRE >", value, "segundoNombre");
			return (Criteria) this;
		}

		public Criteria andSegundoNombreGreaterThanOrEqualTo(String value) {
			addCriterion("SEGUNDO_NOMBRE >=", value, "segundoNombre");
			return (Criteria) this;
		}

		public Criteria andSegundoNombreLessThan(String value) {
			addCriterion("SEGUNDO_NOMBRE <", value, "segundoNombre");
			return (Criteria) this;
		}

		public Criteria andSegundoNombreLessThanOrEqualTo(String value) {
			addCriterion("SEGUNDO_NOMBRE <=", value, "segundoNombre");
			return (Criteria) this;
		}

		public Criteria andSegundoNombreLike(String value) {
			addCriterion("SEGUNDO_NOMBRE like", value, "segundoNombre");
			return (Criteria) this;
		}

		public Criteria andSegundoNombreNotLike(String value) {
			addCriterion("SEGUNDO_NOMBRE not like", value, "segundoNombre");
			return (Criteria) this;
		}

		public Criteria andSegundoNombreIn(List<String> values) {
			addCriterion("SEGUNDO_NOMBRE in", values, "segundoNombre");
			return (Criteria) this;
		}

		public Criteria andSegundoNombreNotIn(List<String> values) {
			addCriterion("SEGUNDO_NOMBRE not in", values, "segundoNombre");
			return (Criteria) this;
		}

		public Criteria andSegundoNombreBetween(String value1, String value2) {
			addCriterion("SEGUNDO_NOMBRE between", value1, value2, "segundoNombre");
			return (Criteria) this;
		}

		public Criteria andSegundoNombreNotBetween(String value1, String value2) {
			addCriterion("SEGUNDO_NOMBRE not between", value1, value2, "segundoNombre");
			return (Criteria) this;
		}

		public Criteria andPrimerApellidoIsNull() {
			addCriterion("PRIMER_APELLIDO is null");
			return (Criteria) this;
		}

		public Criteria andPrimerApellidoIsNotNull() {
			addCriterion("PRIMER_APELLIDO is not null");
			return (Criteria) this;
		}

		public Criteria andPrimerApellidoEqualTo(String value) {
			addCriterion("PRIMER_APELLIDO =", value, "primerApellido");
			return (Criteria) this;
		}

		public Criteria andPrimerApellidoNotEqualTo(String value) {
			addCriterion("PRIMER_APELLIDO <>", value, "primerApellido");
			return (Criteria) this;
		}

		public Criteria andPrimerApellidoGreaterThan(String value) {
			addCriterion("PRIMER_APELLIDO >", value, "primerApellido");
			return (Criteria) this;
		}

		public Criteria andPrimerApellidoGreaterThanOrEqualTo(String value) {
			addCriterion("PRIMER_APELLIDO >=", value, "primerApellido");
			return (Criteria) this;
		}

		public Criteria andPrimerApellidoLessThan(String value) {
			addCriterion("PRIMER_APELLIDO <", value, "primerApellido");
			return (Criteria) this;
		}

		public Criteria andPrimerApellidoLessThanOrEqualTo(String value) {
			addCriterion("PRIMER_APELLIDO <=", value, "primerApellido");
			return (Criteria) this;
		}

		public Criteria andPrimerApellidoLike(String value) {
			addCriterion("PRIMER_APELLIDO like", value, "primerApellido");
			return (Criteria) this;
		}

		public Criteria andPrimerApellidoNotLike(String value) {
			addCriterion("PRIMER_APELLIDO not like", value, "primerApellido");
			return (Criteria) this;
		}

		public Criteria andPrimerApellidoIn(List<String> values) {
			addCriterion("PRIMER_APELLIDO in", values, "primerApellido");
			return (Criteria) this;
		}

		public Criteria andPrimerApellidoNotIn(List<String> values) {
			addCriterion("PRIMER_APELLIDO not in", values, "primerApellido");
			return (Criteria) this;
		}

		public Criteria andPrimerApellidoBetween(String value1, String value2) {
			addCriterion("PRIMER_APELLIDO between", value1, value2, "primerApellido");
			return (Criteria) this;
		}

		public Criteria andPrimerApellidoNotBetween(String value1, String value2) {
			addCriterion("PRIMER_APELLIDO not between", value1, value2, "primerApellido");
			return (Criteria) this;
		}

		public Criteria andSegundoApellidoIsNull() {
			addCriterion("SEGUNDO_APELLIDO is null");
			return (Criteria) this;
		}

		public Criteria andSegundoApellidoIsNotNull() {
			addCriterion("SEGUNDO_APELLIDO is not null");
			return (Criteria) this;
		}

		public Criteria andSegundoApellidoEqualTo(String value) {
			addCriterion("SEGUNDO_APELLIDO =", value, "segundoApellido");
			return (Criteria) this;
		}

		public Criteria andSegundoApellidoNotEqualTo(String value) {
			addCriterion("SEGUNDO_APELLIDO <>", value, "segundoApellido");
			return (Criteria) this;
		}

		public Criteria andSegundoApellidoGreaterThan(String value) {
			addCriterion("SEGUNDO_APELLIDO >", value, "segundoApellido");
			return (Criteria) this;
		}

		public Criteria andSegundoApellidoGreaterThanOrEqualTo(String value) {
			addCriterion("SEGUNDO_APELLIDO >=", value, "segundoApellido");
			return (Criteria) this;
		}

		public Criteria andSegundoApellidoLessThan(String value) {
			addCriterion("SEGUNDO_APELLIDO <", value, "segundoApellido");
			return (Criteria) this;
		}

		public Criteria andSegundoApellidoLessThanOrEqualTo(String value) {
			addCriterion("SEGUNDO_APELLIDO <=", value, "segundoApellido");
			return (Criteria) this;
		}

		public Criteria andSegundoApellidoLike(String value) {
			addCriterion("SEGUNDO_APELLIDO like", value, "segundoApellido");
			return (Criteria) this;
		}

		public Criteria andSegundoApellidoNotLike(String value) {
			addCriterion("SEGUNDO_APELLIDO not like", value, "segundoApellido");
			return (Criteria) this;
		}

		public Criteria andSegundoApellidoIn(List<String> values) {
			addCriterion("SEGUNDO_APELLIDO in", values, "segundoApellido");
			return (Criteria) this;
		}

		public Criteria andSegundoApellidoNotIn(List<String> values) {
			addCriterion("SEGUNDO_APELLIDO not in", values, "segundoApellido");
			return (Criteria) this;
		}

		public Criteria andSegundoApellidoBetween(String value1, String value2) {
			addCriterion("SEGUNDO_APELLIDO between", value1, value2, "segundoApellido");
			return (Criteria) this;
		}

		public Criteria andSegundoApellidoNotBetween(String value1, String value2) {
			addCriterion("SEGUNDO_APELLIDO not between", value1, value2, "segundoApellido");
			return (Criteria) this;
		}

		public Criteria andCodTipoAsociacionIsNull() {
			addCriterion("COD_TIPO_ASOCIACION is null");
			return (Criteria) this;
		}

		public Criteria andCodTipoAsociacionIsNotNull() {
			addCriterion("COD_TIPO_ASOCIACION is not null");
			return (Criteria) this;
		}

		public Criteria andCodTipoAsociacionEqualTo(BigDecimal value) {
			addCriterion("COD_TIPO_ASOCIACION =", value, "codTipoAsociacion");
			return (Criteria) this;
		}

		public Criteria andCodTipoAsociacionNotEqualTo(BigDecimal value) {
			addCriterion("COD_TIPO_ASOCIACION <>", value, "codTipoAsociacion");
			return (Criteria) this;
		}

		public Criteria andCodTipoAsociacionGreaterThan(BigDecimal value) {
			addCriterion("COD_TIPO_ASOCIACION >", value, "codTipoAsociacion");
			return (Criteria) this;
		}

		public Criteria andCodTipoAsociacionGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("COD_TIPO_ASOCIACION >=", value, "codTipoAsociacion");
			return (Criteria) this;
		}

		public Criteria andCodTipoAsociacionLessThan(BigDecimal value) {
			addCriterion("COD_TIPO_ASOCIACION <", value, "codTipoAsociacion");
			return (Criteria) this;
		}

		public Criteria andCodTipoAsociacionLessThanOrEqualTo(BigDecimal value) {
			addCriterion("COD_TIPO_ASOCIACION <=", value, "codTipoAsociacion");
			return (Criteria) this;
		}

		public Criteria andCodTipoAsociacionIn(List<BigDecimal> values) {
			addCriterion("COD_TIPO_ASOCIACION in", values, "codTipoAsociacion");
			return (Criteria) this;
		}

		public Criteria andCodTipoAsociacionNotIn(List<BigDecimal> values) {
			addCriterion("COD_TIPO_ASOCIACION not in", values, "codTipoAsociacion");
			return (Criteria) this;
		}

		public Criteria andCodTipoAsociacionBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("COD_TIPO_ASOCIACION between", value1, value2, "codTipoAsociacion");
			return (Criteria) this;
		}

		public Criteria andCodTipoAsociacionNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("COD_TIPO_ASOCIACION not between", value1, value2, "codTipoAsociacion");
			return (Criteria) this;
		}

		public Criteria andAudFechaActualizacionIsNull() {
			addCriterion("AUD_FECHA_ACTUALIZACION is null");
			return (Criteria) this;
		}

		public Criteria andAudFechaActualizacionIsNotNull() {
			addCriterion("AUD_FECHA_ACTUALIZACION is not null");
			return (Criteria) this;
		}

		public Criteria andAudFechaActualizacionEqualTo(Date value) {
			addCriterion("AUD_FECHA_ACTUALIZACION =", value, "audFechaActualizacion");
			return (Criteria) this;
		}

		public Criteria andAudFechaActualizacionNotEqualTo(Date value) {
			addCriterion("AUD_FECHA_ACTUALIZACION <>", value, "audFechaActualizacion");
			return (Criteria) this;
		}

		public Criteria andAudFechaActualizacionGreaterThan(Date value) {
			addCriterion("AUD_FECHA_ACTUALIZACION >", value, "audFechaActualizacion");
			return (Criteria) this;
		}

		public Criteria andAudFechaActualizacionGreaterThanOrEqualTo(Date value) {
			addCriterion("AUD_FECHA_ACTUALIZACION >=", value, "audFechaActualizacion");
			return (Criteria) this;
		}

		public Criteria andAudFechaActualizacionLessThan(Date value) {
			addCriterion("AUD_FECHA_ACTUALIZACION <", value, "audFechaActualizacion");
			return (Criteria) this;
		}

		public Criteria andAudFechaActualizacionLessThanOrEqualTo(Date value) {
			addCriterion("AUD_FECHA_ACTUALIZACION <=", value, "audFechaActualizacion");
			return (Criteria) this;
		}

		public Criteria andAudFechaActualizacionIn(List<Date> values) {
			addCriterion("AUD_FECHA_ACTUALIZACION in", values, "audFechaActualizacion");
			return (Criteria) this;
		}

		public Criteria andAudFechaActualizacionNotIn(List<Date> values) {
			addCriterion("AUD_FECHA_ACTUALIZACION not in", values, "audFechaActualizacion");
			return (Criteria) this;
		}

		public Criteria andAudFechaActualizacionBetween(Date value1, Date value2) {
			addCriterion("AUD_FECHA_ACTUALIZACION between", value1, value2, "audFechaActualizacion");
			return (Criteria) this;
		}

		public Criteria andAudFechaActualizacionNotBetween(Date value1, Date value2) {
			addCriterion("AUD_FECHA_ACTUALIZACION not between", value1, value2, "audFechaActualizacion");
			return (Criteria) this;
		}

		public Criteria andAudCodUsuarioIsNull() {
			addCriterion("AUD_COD_USUARIO is null");
			return (Criteria) this;
		}

		public Criteria andAudCodUsuarioIsNotNull() {
			addCriterion("AUD_COD_USUARIO is not null");
			return (Criteria) this;
		}

		public Criteria andAudCodUsuarioEqualTo(Long value) {
			addCriterion("AUD_COD_USUARIO =", value, "audCodUsuario");
			return (Criteria) this;
		}

		public Criteria andAudCodUsuarioNotEqualTo(Long value) {
			addCriterion("AUD_COD_USUARIO <>", value, "audCodUsuario");
			return (Criteria) this;
		}

		public Criteria andAudCodUsuarioGreaterThan(Long value) {
			addCriterion("AUD_COD_USUARIO >", value, "audCodUsuario");
			return (Criteria) this;
		}

		public Criteria andAudCodUsuarioGreaterThanOrEqualTo(Long value) {
			addCriterion("AUD_COD_USUARIO >=", value, "audCodUsuario");
			return (Criteria) this;
		}

		public Criteria andAudCodUsuarioLessThan(Long value) {
			addCriterion("AUD_COD_USUARIO <", value, "audCodUsuario");
			return (Criteria) this;
		}

		public Criteria andAudCodUsuarioLessThanOrEqualTo(Long value) {
			addCriterion("AUD_COD_USUARIO <=", value, "audCodUsuario");
			return (Criteria) this;
		}

		public Criteria andAudCodUsuarioIn(List<Long> values) {
			addCriterion("AUD_COD_USUARIO in", values, "audCodUsuario");
			return (Criteria) this;
		}

		public Criteria andAudCodUsuarioNotIn(List<Long> values) {
			addCriterion("AUD_COD_USUARIO not in", values, "audCodUsuario");
			return (Criteria) this;
		}

		public Criteria andAudCodUsuarioBetween(Long value1, Long value2) {
			addCriterion("AUD_COD_USUARIO between", value1, value2, "audCodUsuario");
			return (Criteria) this;
		}

		public Criteria andAudCodUsuarioNotBetween(Long value1, Long value2) {
			addCriterion("AUD_COD_USUARIO not between", value1, value2, "audCodUsuario");
			return (Criteria) this;
		}

		public Criteria andAudCodRolIsNull() {
			addCriterion("AUD_COD_ROL is null");
			return (Criteria) this;
		}

		public Criteria andAudCodRolIsNotNull() {
			addCriterion("AUD_COD_ROL is not null");
			return (Criteria) this;
		}

		public Criteria andAudCodRolEqualTo(Integer value) {
			addCriterion("AUD_COD_ROL =", value, "audCodRol");
			return (Criteria) this;
		}

		public Criteria andAudCodRolNotEqualTo(Integer value) {
			addCriterion("AUD_COD_ROL <>", value, "audCodRol");
			return (Criteria) this;
		}

		public Criteria andAudCodRolGreaterThan(Integer value) {
			addCriterion("AUD_COD_ROL >", value, "audCodRol");
			return (Criteria) this;
		}

		public Criteria andAudCodRolGreaterThanOrEqualTo(Integer value) {
			addCriterion("AUD_COD_ROL >=", value, "audCodRol");
			return (Criteria) this;
		}

		public Criteria andAudCodRolLessThan(Integer value) {
			addCriterion("AUD_COD_ROL <", value, "audCodRol");
			return (Criteria) this;
		}

		public Criteria andAudCodRolLessThanOrEqualTo(Integer value) {
			addCriterion("AUD_COD_ROL <=", value, "audCodRol");
			return (Criteria) this;
		}

		public Criteria andAudCodRolIn(List<Integer> values) {
			addCriterion("AUD_COD_ROL in", values, "audCodRol");
			return (Criteria) this;
		}

		public Criteria andAudCodRolNotIn(List<Integer> values) {
			addCriterion("AUD_COD_ROL not in", values, "audCodRol");
			return (Criteria) this;
		}

		public Criteria andAudCodRolBetween(Integer value1, Integer value2) {
			addCriterion("AUD_COD_ROL between", value1, value2, "audCodRol");
			return (Criteria) this;
		}

		public Criteria andAudCodRolNotBetween(Integer value1, Integer value2) {
			addCriterion("AUD_COD_ROL not between", value1, value2, "audCodRol");
			return (Criteria) this;
		}

		public Criteria andAudAccionIsNull() {
			addCriterion("AUD_ACCION is null");
			return (Criteria) this;
		}

		public Criteria andAudAccionIsNotNull() {
			addCriterion("AUD_ACCION is not null");
			return (Criteria) this;
		}

		public Criteria andAudAccionEqualTo(Integer value) {
			addCriterion("AUD_ACCION =", value, "audAccion");
			return (Criteria) this;
		}

		public Criteria andAudAccionNotEqualTo(Integer value) {
			addCriterion("AUD_ACCION <>", value, "audAccion");
			return (Criteria) this;
		}

		public Criteria andAudAccionGreaterThan(Integer value) {
			addCriterion("AUD_ACCION >", value, "audAccion");
			return (Criteria) this;
		}

		public Criteria andAudAccionGreaterThanOrEqualTo(Integer value) {
			addCriterion("AUD_ACCION >=", value, "audAccion");
			return (Criteria) this;
		}

		public Criteria andAudAccionLessThan(Integer value) {
			addCriterion("AUD_ACCION <", value, "audAccion");
			return (Criteria) this;
		}

		public Criteria andAudAccionLessThanOrEqualTo(Integer value) {
			addCriterion("AUD_ACCION <=", value, "audAccion");
			return (Criteria) this;
		}

		public Criteria andAudAccionIn(List<Integer> values) {
			addCriterion("AUD_ACCION in", values, "audAccion");
			return (Criteria) this;
		}

		public Criteria andAudAccionNotIn(List<Integer> values) {
			addCriterion("AUD_ACCION not in", values, "audAccion");
			return (Criteria) this;
		}

		public Criteria andAudAccionBetween(Integer value1, Integer value2) {
			addCriterion("AUD_ACCION between", value1, value2, "audAccion");
			return (Criteria) this;
		}

		public Criteria andAudAccionNotBetween(Integer value1, Integer value2) {
			addCriterion("AUD_ACCION not between", value1, value2, "audAccion");
			return (Criteria) this;
		}

		public Criteria andCodProcesoCargaMasivaIsNull() {
			addCriterion("COD_PROCESO_CARGA_MASIVA is null");
			return (Criteria) this;
		}

		public Criteria andCodProcesoCargaMasivaIsNotNull() {
			addCriterion("COD_PROCESO_CARGA_MASIVA is not null");
			return (Criteria) this;
		}

		public Criteria andCodProcesoCargaMasivaEqualTo(Short value) {
			addCriterion("COD_PROCESO_CARGA_MASIVA =", value, "codProcesoCargaMasiva");
			return (Criteria) this;
		}

		public Criteria andCodProcesoCargaMasivaNotEqualTo(Short value) {
			addCriterion("COD_PROCESO_CARGA_MASIVA <>", value, "codProcesoCargaMasiva");
			return (Criteria) this;
		}

		public Criteria andCodProcesoCargaMasivaGreaterThan(Short value) {
			addCriterion("COD_PROCESO_CARGA_MASIVA >", value, "codProcesoCargaMasiva");
			return (Criteria) this;
		}

		public Criteria andCodProcesoCargaMasivaGreaterThanOrEqualTo(Short value) {
			addCriterion("COD_PROCESO_CARGA_MASIVA >=", value, "codProcesoCargaMasiva");
			return (Criteria) this;
		}

		public Criteria andCodProcesoCargaMasivaLessThan(Short value) {
			addCriterion("COD_PROCESO_CARGA_MASIVA <", value, "codProcesoCargaMasiva");
			return (Criteria) this;
		}

		public Criteria andCodProcesoCargaMasivaLessThanOrEqualTo(Short value) {
			addCriterion("COD_PROCESO_CARGA_MASIVA <=", value, "codProcesoCargaMasiva");
			return (Criteria) this;
		}

		public Criteria andCodProcesoCargaMasivaIn(List<Short> values) {
			addCriterion("COD_PROCESO_CARGA_MASIVA in", values, "codProcesoCargaMasiva");
			return (Criteria) this;
		}

		public Criteria andCodProcesoCargaMasivaNotIn(List<Short> values) {
			addCriterion("COD_PROCESO_CARGA_MASIVA not in", values, "codProcesoCargaMasiva");
			return (Criteria) this;
		}

		public Criteria andCodProcesoCargaMasivaBetween(Short value1, Short value2) {
			addCriterion("COD_PROCESO_CARGA_MASIVA between", value1, value2, "codProcesoCargaMasiva");
			return (Criteria) this;
		}

		public Criteria andCodProcesoCargaMasivaNotBetween(Short value1, Short value2) {
			addCriterion("COD_PROCESO_CARGA_MASIVA not between", value1, value2, "codProcesoCargaMasiva");
			return (Criteria) this;
		}

		public Criteria andResultadoIsNull() {
			addCriterion("RESULTADO is null");
			return (Criteria) this;
		}

		public Criteria andResultadoIsNotNull() {
			addCriterion("RESULTADO is not null");
			return (Criteria) this;
		}

		public Criteria andResultadoEqualTo(String value) {
			addCriterion("RESULTADO =", value, "resultado");
			return (Criteria) this;
		}

		public Criteria andResultadoNotEqualTo(String value) {
			addCriterion("RESULTADO <>", value, "resultado");
			return (Criteria) this;
		}

		public Criteria andResultadoGreaterThan(String value) {
			addCriterion("RESULTADO >", value, "resultado");
			return (Criteria) this;
		}

		public Criteria andResultadoGreaterThanOrEqualTo(String value) {
			addCriterion("RESULTADO >=", value, "resultado");
			return (Criteria) this;
		}

		public Criteria andResultadoLessThan(String value) {
			addCriterion("RESULTADO <", value, "resultado");
			return (Criteria) this;
		}

		public Criteria andResultadoLessThanOrEqualTo(String value) {
			addCriterion("RESULTADO <=", value, "resultado");
			return (Criteria) this;
		}

		public Criteria andResultadoLike(String value) {
			addCriterion("RESULTADO like", value, "resultado");
			return (Criteria) this;
		}

		public Criteria andResultadoNotLike(String value) {
			addCriterion("RESULTADO not like", value, "resultado");
			return (Criteria) this;
		}

		public Criteria andResultadoIn(List<String> values) {
			addCriterion("RESULTADO in", values, "resultado");
			return (Criteria) this;
		}

		public Criteria andResultadoNotIn(List<String> values) {
			addCriterion("RESULTADO not in", values, "resultado");
			return (Criteria) this;
		}

		public Criteria andResultadoBetween(String value1, String value2) {
			addCriterion("RESULTADO between", value1, value2, "resultado");
			return (Criteria) this;
		}

		public Criteria andResultadoNotBetween(String value1, String value2) {
			addCriterion("RESULTADO not between", value1, value2, "resultado");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table CM_ACTIVAR_USUARIOS
	 * @mbg.generated  Thu Aug 16 07:59:13 COT 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CM_ACTIVAR_USUARIOS
     *
     * @mbg.generated do_not_delete_during_merge Wed May 23 14:06:24 COT 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}