package co.gov.dafp.sigep2.bean;

import java.math.BigDecimal;
import java.util.Date;

import co.gov.dafp.sigep2.utils.ErrorMensajes;

public class CmActivarUsuarios extends ErrorMensajes{
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CM_ACTIVAR_USUARIOS.COD_CM_ACTIVAR_USUARIOS
	 * @mbg.generated  Thu Aug 16 07:59:13 COT 2018
	 */
	private Long codCmActivarUsuarios;


	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CM_ACTIVAR_USUARIOS.COD_TIPO_IDENTIFICACION
	 * @mbg.generated  Thu Aug 16 07:59:13 COT 2018
	 */
	private String codTipoIdentificacion;


	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CM_ACTIVAR_USUARIOS.NUMERO_IDENTIFICACION
	 * @mbg.generated  Thu Aug 16 07:59:13 COT 2018
	 */
	private String numeroIdentificacion;


	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CM_ACTIVAR_USUARIOS.PRIMER_NOMBRE
	 * @mbg.generated  Thu Aug 16 07:59:13 COT 2018
	 */
	private String primerNombre;


	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CM_ACTIVAR_USUARIOS.SEGUNDO_NOMBRE
	 * @mbg.generated  Thu Aug 16 07:59:13 COT 2018
	 */
	private String segundoNombre;


	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CM_ACTIVAR_USUARIOS.PRIMER_APELLIDO
	 * @mbg.generated  Thu Aug 16 07:59:13 COT 2018
	 */
	private String primerApellido;


	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CM_ACTIVAR_USUARIOS.SEGUNDO_APELLIDO
	 * @mbg.generated  Thu Aug 16 07:59:13 COT 2018
	 */
	private String segundoApellido;


	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CM_ACTIVAR_USUARIOS.COD_TIPO_ASOCIACION
	 * @mbg.generated  Thu Aug 16 07:59:13 COT 2018
	 */
	private String codTipoAsociacion;


	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CM_ACTIVAR_USUARIOS.AUD_FECHA_ACTUALIZACION
	 * @mbg.generated  Thu Aug 16 07:59:13 COT 2018
	 */
	private Date audFechaActualizacion;


	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CM_ACTIVAR_USUARIOS.AUD_COD_USUARIO
	 * @mbg.generated  Thu Aug 16 07:59:13 COT 2018
	 */
	private Long audCodUsuario;


	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CM_ACTIVAR_USUARIOS.AUD_COD_ROL
	 * @mbg.generated  Thu Aug 16 07:59:13 COT 2018
	 */
	private Integer audCodRol;


	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CM_ACTIVAR_USUARIOS.AUD_ACCION
	 * @mbg.generated  Thu Aug 16 07:59:13 COT 2018
	 */
	private Integer audAccion;


	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CM_ACTIVAR_USUARIOS.COD_PROCESO_CARGA_MASIVA
	 * @mbg.generated  Thu Aug 16 07:59:13 COT 2018
	 */
	private Short codProcesoCargaMasiva;


	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CM_ACTIVAR_USUARIOS.RESULTADO
	 * @mbg.generated  Thu Aug 16 07:59:13 COT 2018
	 */
	private String resultado;
	
	private String correoElectronico;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CM_ACTIVAR_USUARIOS.COD_CM_ACTIVAR_USUARIOS
	 * @return  the value of CM_ACTIVAR_USUARIOS.COD_CM_ACTIVAR_USUARIOS
	 * @mbg.generated  Thu Aug 16 07:59:13 COT 2018
	 */
	public Long getCodCmActivarUsuarios() {
		return codCmActivarUsuarios;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CM_ACTIVAR_USUARIOS.COD_CM_ACTIVAR_USUARIOS
	 * @param codCmActivarUsuarios  the value for CM_ACTIVAR_USUARIOS.COD_CM_ACTIVAR_USUARIOS
	 * @mbg.generated  Thu Aug 16 07:59:13 COT 2018
	 */
	public void setCodCmActivarUsuarios(Long codCmActivarUsuarios) {
		this.codCmActivarUsuarios = codCmActivarUsuarios;
	}


	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CM_ACTIVAR_USUARIOS.NUMERO_IDENTIFICACION
	 * @return  the value of CM_ACTIVAR_USUARIOS.NUMERO_IDENTIFICACION
	 * @mbg.generated  Thu Aug 16 07:59:13 COT 2018
	 */
	public String getNumeroIdentificacion() {
		return numeroIdentificacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CM_ACTIVAR_USUARIOS.NUMERO_IDENTIFICACION
	 * @param numeroIdentificacion  the value for CM_ACTIVAR_USUARIOS.NUMERO_IDENTIFICACION
	 * @mbg.generated  Thu Aug 16 07:59:13 COT 2018
	 */
	public void setNumeroIdentificacion(String numeroIdentificacion) {
		this.numeroIdentificacion = numeroIdentificacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CM_ACTIVAR_USUARIOS.PRIMER_NOMBRE
	 * @return  the value of CM_ACTIVAR_USUARIOS.PRIMER_NOMBRE
	 * @mbg.generated  Thu Aug 16 07:59:13 COT 2018
	 */
	public String getPrimerNombre() {
		return primerNombre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CM_ACTIVAR_USUARIOS.PRIMER_NOMBRE
	 * @param primerNombre  the value for CM_ACTIVAR_USUARIOS.PRIMER_NOMBRE
	 * @mbg.generated  Thu Aug 16 07:59:13 COT 2018
	 */
	public void setPrimerNombre(String primerNombre) {
		this.primerNombre = primerNombre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CM_ACTIVAR_USUARIOS.SEGUNDO_NOMBRE
	 * @return  the value of CM_ACTIVAR_USUARIOS.SEGUNDO_NOMBRE
	 * @mbg.generated  Thu Aug 16 07:59:13 COT 2018
	 */
	public String getSegundoNombre() {
		return segundoNombre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CM_ACTIVAR_USUARIOS.SEGUNDO_NOMBRE
	 * @param segundoNombre  the value for CM_ACTIVAR_USUARIOS.SEGUNDO_NOMBRE
	 * @mbg.generated  Thu Aug 16 07:59:13 COT 2018
	 */
	public void setSegundoNombre(String segundoNombre) {
		this.segundoNombre = segundoNombre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CM_ACTIVAR_USUARIOS.PRIMER_APELLIDO
	 * @return  the value of CM_ACTIVAR_USUARIOS.PRIMER_APELLIDO
	 * @mbg.generated  Thu Aug 16 07:59:13 COT 2018
	 */
	public String getPrimerApellido() {
		return primerApellido;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CM_ACTIVAR_USUARIOS.PRIMER_APELLIDO
	 * @param primerApellido  the value for CM_ACTIVAR_USUARIOS.PRIMER_APELLIDO
	 * @mbg.generated  Thu Aug 16 07:59:13 COT 2018
	 */
	public void setPrimerApellido(String primerApellido) {
		this.primerApellido = primerApellido;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CM_ACTIVAR_USUARIOS.SEGUNDO_APELLIDO
	 * @return  the value of CM_ACTIVAR_USUARIOS.SEGUNDO_APELLIDO
	 * @mbg.generated  Thu Aug 16 07:59:13 COT 2018
	 */
	public String getSegundoApellido() {
		return segundoApellido;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CM_ACTIVAR_USUARIOS.SEGUNDO_APELLIDO
	 * @param segundoApellido  the value for CM_ACTIVAR_USUARIOS.SEGUNDO_APELLIDO
	 * @mbg.generated  Thu Aug 16 07:59:13 COT 2018
	 */
	public void setSegundoApellido(String segundoApellido) {
		this.segundoApellido = segundoApellido;
	}

	

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CM_ACTIVAR_USUARIOS.AUD_FECHA_ACTUALIZACION
	 * @return  the value of CM_ACTIVAR_USUARIOS.AUD_FECHA_ACTUALIZACION
	 * @mbg.generated  Thu Aug 16 07:59:13 COT 2018
	 */
	public Date getAudFechaActualizacion() {
		return audFechaActualizacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CM_ACTIVAR_USUARIOS.AUD_FECHA_ACTUALIZACION
	 * @param audFechaActualizacion  the value for CM_ACTIVAR_USUARIOS.AUD_FECHA_ACTUALIZACION
	 * @mbg.generated  Thu Aug 16 07:59:13 COT 2018
	 */
	public void setAudFechaActualizacion(Date audFechaActualizacion) {
		this.audFechaActualizacion = audFechaActualizacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CM_ACTIVAR_USUARIOS.AUD_COD_USUARIO
	 * @return  the value of CM_ACTIVAR_USUARIOS.AUD_COD_USUARIO
	 * @mbg.generated  Thu Aug 16 07:59:13 COT 2018
	 */
	public Long getAudCodUsuario() {
		return audCodUsuario;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CM_ACTIVAR_USUARIOS.AUD_COD_USUARIO
	 * @param audCodUsuario  the value for CM_ACTIVAR_USUARIOS.AUD_COD_USUARIO
	 * @mbg.generated  Thu Aug 16 07:59:13 COT 2018
	 */
	public void setAudCodUsuario(Long audCodUsuario) {
		this.audCodUsuario = audCodUsuario;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CM_ACTIVAR_USUARIOS.AUD_COD_ROL
	 * @return  the value of CM_ACTIVAR_USUARIOS.AUD_COD_ROL
	 * @mbg.generated  Thu Aug 16 07:59:13 COT 2018
	 */
	public Integer getAudCodRol() {
		return audCodRol;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CM_ACTIVAR_USUARIOS.AUD_COD_ROL
	 * @param audCodRol  the value for CM_ACTIVAR_USUARIOS.AUD_COD_ROL
	 * @mbg.generated  Thu Aug 16 07:59:13 COT 2018
	 */
	public void setAudCodRol(Integer audCodRol) {
		this.audCodRol = audCodRol;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CM_ACTIVAR_USUARIOS.AUD_ACCION
	 * @return  the value of CM_ACTIVAR_USUARIOS.AUD_ACCION
	 * @mbg.generated  Thu Aug 16 07:59:13 COT 2018
	 */
	public Integer getAudAccion() {
		return audAccion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CM_ACTIVAR_USUARIOS.AUD_ACCION
	 * @param audAccion  the value for CM_ACTIVAR_USUARIOS.AUD_ACCION
	 * @mbg.generated  Thu Aug 16 07:59:13 COT 2018
	 */
	public void setAudAccion(Integer audAccion) {
		this.audAccion = audAccion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CM_ACTIVAR_USUARIOS.COD_PROCESO_CARGA_MASIVA
	 * @return  the value of CM_ACTIVAR_USUARIOS.COD_PROCESO_CARGA_MASIVA
	 * @mbg.generated  Thu Aug 16 07:59:13 COT 2018
	 */
	public Short getCodProcesoCargaMasiva() {
		return codProcesoCargaMasiva;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CM_ACTIVAR_USUARIOS.COD_PROCESO_CARGA_MASIVA
	 * @param codProcesoCargaMasiva  the value for CM_ACTIVAR_USUARIOS.COD_PROCESO_CARGA_MASIVA
	 * @mbg.generated  Thu Aug 16 07:59:13 COT 2018
	 */
	public void setCodProcesoCargaMasiva(Short codProcesoCargaMasiva) {
		this.codProcesoCargaMasiva = codProcesoCargaMasiva;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CM_ACTIVAR_USUARIOS.RESULTADO
	 * @return  the value of CM_ACTIVAR_USUARIOS.RESULTADO
	 * @mbg.generated  Thu Aug 16 07:59:13 COT 2018
	 */
	public String getResultado() {
		return resultado;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CM_ACTIVAR_USUARIOS.RESULTADO
	 * @param resultado  the value for CM_ACTIVAR_USUARIOS.RESULTADO
	 * @mbg.generated  Thu Aug 16 07:59:13 COT 2018
	 */
	public void setResultado(String resultado) {
		this.resultado = resultado;
	}

	/**
	 * 
	 */
	private static final long serialVersionUID = -8475418621510066557L;

	/**
	 * @return the limitInit
	 */
	public int getLimitInit() {
		return limitInit;
	}

	/**
	 * @param limitInit the limitInit to set
	 */
	public void setLimitInit(int limitInit) {
		this.limitInit = limitInit;
	}

	/**
	 * @return the limitEnd
	 */
	public int getLimitEnd() {
		return limitEnd;
	}

	/**
	 * @param limitEnd the limitEnd to set
	 */
	public void setLimitEnd(int limitEnd) {
		this.limitEnd = limitEnd;
	}

	
	public String getCorreoElectronico() {
		return correoElectronico;
	}

	public void setCorreoElectronico(String correoElectronico) {
		this.correoElectronico = correoElectronico;
	}

	private int limitInit;
    
    
    private int limitEnd;
    
}