package co.gov.dafp.sigep2.bean;

import java.math.BigDecimal;
import java.util.Date;

import co.gov.dafp.sigep2.utils.ErrorMensajes;

public class DependenciaHojaVida extends ErrorMensajes {

	private static final long serialVersionUID = -3812171930253534051L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEPENDENCIA_HOJA_VIDA.COD_DEPENDENCIA_HOJA_VIDA
     *
     * @mbggenerated Thu Apr 30 14:44:49 COT 2020
     */
    private BigDecimal codDependenciaHojaVida;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEPENDENCIA_HOJA_VIDA.NOMBRE_DEPENDENCIA
     *
     * @mbggenerated Thu Apr 30 14:44:49 COT 2020
     */
    private String nombreDependencia;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEPENDENCIA_HOJA_VIDA.FLG_ACTIVO
     *
     * @mbggenerated Thu Apr 30 14:44:49 COT 2020
     */
    private Short flgActivo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEPENDENCIA_HOJA_VIDA.AUD_FECHA_ACTUALIZACION
     *
     * @mbggenerated Thu Apr 30 14:44:49 COT 2020
     */
    private Date audFechaActualizacion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEPENDENCIA_HOJA_VIDA.AUD_COD_USUARIO
     *
     * @mbggenerated Thu Apr 30 14:44:49 COT 2020
     */
    private BigDecimal audCodUsuario;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEPENDENCIA_HOJA_VIDA.AUD_COD_ROL
     *
     * @mbggenerated Thu Apr 30 14:44:49 COT 2020
     */
    private BigDecimal audCodRol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEPENDENCIA_HOJA_VIDA.AUD_ACCION
     *
     * @mbggenerated Thu Apr 30 14:44:49 COT 2020
     */
    private BigDecimal audAccion;

    /**
	 * @return the codDependenciaHojaVida
	 */
	public BigDecimal getCodDependenciaHojaVida() {
		return codDependenciaHojaVida;
	}

	/**
	 * @param codDependenciaHojaVida the codDependenciaHojaVida to set
	 */
	public void setCodDependenciaHojaVida(BigDecimal codDependenciaHojaVida) {
		this.codDependenciaHojaVida = codDependenciaHojaVida;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEPENDENCIA_HOJA_VIDA.NOMBRE_DEPENDENCIA
     *
     * @return the value of DEPENDENCIA_HOJA_VIDA.NOMBRE_DEPENDENCIA
     *
     * @mbggenerated Thu Apr 30 14:44:49 COT 2020
     */
    public String getNombreDependencia() {
        return nombreDependencia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEPENDENCIA_HOJA_VIDA.NOMBRE_DEPENDENCIA
     *
     * @param nombreDependencia the value for DEPENDENCIA_HOJA_VIDA.NOMBRE_DEPENDENCIA
     *
     * @mbggenerated Thu Apr 30 14:44:49 COT 2020
     */
    public void setNombreDependencia(String nombreDependencia) {
        this.nombreDependencia = nombreDependencia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEPENDENCIA_HOJA_VIDA.FLG_ACTIVO
     *
     * @return the value of DEPENDENCIA_HOJA_VIDA.FLG_ACTIVO
     *
     * @mbggenerated Thu Apr 30 14:44:49 COT 2020
     */
    public Short getFlgActivo() {
        return flgActivo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEPENDENCIA_HOJA_VIDA.FLG_ACTIVO
     *
     * @param flgActivo the value for DEPENDENCIA_HOJA_VIDA.FLG_ACTIVO
     *
     * @mbggenerated Thu Apr 30 14:44:49 COT 2020
     */
    public void setFlgActivo(Short flgActivo) {
        this.flgActivo = flgActivo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEPENDENCIA_HOJA_VIDA.AUD_FECHA_ACTUALIZACION
     *
     * @return the value of DEPENDENCIA_HOJA_VIDA.AUD_FECHA_ACTUALIZACION
     *
     * @mbggenerated Thu Apr 30 14:44:49 COT 2020
     */
    public Date getAudFechaActualizacion() {
        return audFechaActualizacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEPENDENCIA_HOJA_VIDA.AUD_FECHA_ACTUALIZACION
     *
     * @param audFechaActualizacion the value for DEPENDENCIA_HOJA_VIDA.AUD_FECHA_ACTUALIZACION
     *
     * @mbggenerated Thu Apr 30 14:44:49 COT 2020
     */
    public void setAudFechaActualizacion(Date audFechaActualizacion) {
        this.audFechaActualizacion = audFechaActualizacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEPENDENCIA_HOJA_VIDA.AUD_COD_USUARIO
     *
     * @return the value of DEPENDENCIA_HOJA_VIDA.AUD_COD_USUARIO
     *
     * @mbggenerated Thu Apr 30 14:44:49 COT 2020
     */
    public BigDecimal getAudCodUsuario() {
        return audCodUsuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEPENDENCIA_HOJA_VIDA.AUD_COD_USUARIO
     *
     * @param audCodUsuario the value for DEPENDENCIA_HOJA_VIDA.AUD_COD_USUARIO
     *
     * @mbggenerated Thu Apr 30 14:44:49 COT 2020
     */
    public void setAudCodUsuario(BigDecimal audCodUsuario) {
        this.audCodUsuario = audCodUsuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEPENDENCIA_HOJA_VIDA.AUD_COD_ROL
     *
     * @return the value of DEPENDENCIA_HOJA_VIDA.AUD_COD_ROL
     *
     * @mbggenerated Thu Apr 30 14:44:49 COT 2020
     */
    public BigDecimal getAudCodRol() {
        return audCodRol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEPENDENCIA_HOJA_VIDA.AUD_COD_ROL
     *
     * @param audCodRol the value for DEPENDENCIA_HOJA_VIDA.AUD_COD_ROL
     *
     * @mbggenerated Thu Apr 30 14:44:49 COT 2020
     */
    public void setAudCodRol(BigDecimal audCodRol) {
        this.audCodRol = audCodRol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEPENDENCIA_HOJA_VIDA.AUD_ACCION
     *
     * @return the value of DEPENDENCIA_HOJA_VIDA.AUD_ACCION
     *
     * @mbggenerated Thu Apr 30 14:44:49 COT 2020
     */
    public BigDecimal getAudAccion() {
        return audAccion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEPENDENCIA_HOJA_VIDA.AUD_ACCION
     *
     * @param audAccion the value for DEPENDENCIA_HOJA_VIDA.AUD_ACCION
     *
     * @mbggenerated Thu Apr 30 14:44:49 COT 2020
     */
    public void setAudAccion(BigDecimal audAccion) {
        this.audAccion = audAccion;
    }

}