package co.gov.dafp.sigep2.bean;

import java.math.BigDecimal;
import java.util.Date;

import co.gov.dafp.sigep2.utils.ErrorMensajes;

public class FormacionTrabajo extends ErrorMensajes{
    /**
	 * 
	 */
	private static final long serialVersionUID = -5601501745172588482L;


	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FORMACION_TRABAJO.COD_FORMACION_TRABAJO
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	private Long codFormacionTrabajo;


	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FORMACION_TRABAJO.COD_PERSONA
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	private BigDecimal codPersona;


	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FORMACION_TRABAJO.COD_TIPO_FORMACION
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	private Integer codTipoFormacion;


	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FORMACION_TRABAJO.INTENSIDAD_HORAS
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	private Integer intensidadHoras;


	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FORMACION_TRABAJO.NOMBRE_INSTITUCION
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	private String nombreInstitucion;


	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FORMACION_TRABAJO.COD_PAIS
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	private Integer codPais;


	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FORMACION_TRABAJO.COD_DEPARTAMENTO
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	private Integer codDepartamento;


	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FORMACION_TRABAJO.COD_MUNICIPIO
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	private Integer codMunicipio;


	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FORMACION_TRABAJO.FECHA_INICIO
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	private Date fechaInicio;


	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FORMACION_TRABAJO.FECHA_TERMINACION
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	private Date fechaTerminacion;


	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FORMACION_TRABAJO.AUD_FECHA_ACTUALIZACION
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	private Date audFechaActualizacion;


	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FORMACION_TRABAJO.AUD_COD_USUARIO
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	private BigDecimal audCodUsuario;


	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FORMACION_TRABAJO.AUD_COD_ROL
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	private Integer audCodRol;


	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FORMACION_TRABAJO.AUD_ACCION
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	private Integer audAccion;



	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FORMACION_TRABAJO.COD_FORMACION_TRABAJO
	 * @return  the value of FORMACION_TRABAJO.COD_FORMACION_TRABAJO
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public Long getCodFormacionTrabajo() {
		return codFormacionTrabajo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FORMACION_TRABAJO.COD_FORMACION_TRABAJO
	 * @param codFormacionTrabajo  the value for FORMACION_TRABAJO.COD_FORMACION_TRABAJO
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public void setCodFormacionTrabajo(Long codFormacionTrabajo) {
		this.codFormacionTrabajo = codFormacionTrabajo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FORMACION_TRABAJO.COD_PERSONA
	 * @return  the value of FORMACION_TRABAJO.COD_PERSONA
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public BigDecimal getCodPersona() {
		return codPersona;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FORMACION_TRABAJO.COD_PERSONA
	 * @param codPersona  the value for FORMACION_TRABAJO.COD_PERSONA
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public void setCodPersona(BigDecimal codPersona) {
		this.codPersona = codPersona;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FORMACION_TRABAJO.COD_TIPO_FORMACION
	 * @return  the value of FORMACION_TRABAJO.COD_TIPO_FORMACION
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public Integer getCodTipoFormacion() {
		return codTipoFormacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FORMACION_TRABAJO.COD_TIPO_FORMACION
	 * @param codTipoFormacion  the value for FORMACION_TRABAJO.COD_TIPO_FORMACION
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public void setCodTipoFormacion(Integer codTipoFormacion) {
		this.codTipoFormacion = codTipoFormacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FORMACION_TRABAJO.INTENSIDAD_HORAS
	 * @return  the value of FORMACION_TRABAJO.INTENSIDAD_HORAS
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public Integer getIntensidadHoras() {
		return intensidadHoras;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FORMACION_TRABAJO.INTENSIDAD_HORAS
	 * @param intensidadHoras  the value for FORMACION_TRABAJO.INTENSIDAD_HORAS
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public void setIntensidadHoras(Integer intensidadHoras) {
		this.intensidadHoras = intensidadHoras;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FORMACION_TRABAJO.NOMBRE_INSTITUCION
	 * @return  the value of FORMACION_TRABAJO.NOMBRE_INSTITUCION
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public String getNombreInstitucion() {
		return nombreInstitucion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FORMACION_TRABAJO.NOMBRE_INSTITUCION
	 * @param nombreInstitucion  the value for FORMACION_TRABAJO.NOMBRE_INSTITUCION
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public void setNombreInstitucion(String nombreInstitucion) {
		this.nombreInstitucion = nombreInstitucion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FORMACION_TRABAJO.COD_PAIS
	 * @return  the value of FORMACION_TRABAJO.COD_PAIS
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public Integer getCodPais() {
		return codPais;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FORMACION_TRABAJO.COD_PAIS
	 * @param codPais  the value for FORMACION_TRABAJO.COD_PAIS
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public void setCodPais(Integer codPais) {
		this.codPais = codPais;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FORMACION_TRABAJO.COD_DEPARTAMENTO
	 * @return  the value of FORMACION_TRABAJO.COD_DEPARTAMENTO
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public Integer getCodDepartamento() {
		return codDepartamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FORMACION_TRABAJO.COD_DEPARTAMENTO
	 * @param codDepartamento  the value for FORMACION_TRABAJO.COD_DEPARTAMENTO
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public void setCodDepartamento(Integer codDepartamento) {
		this.codDepartamento = codDepartamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FORMACION_TRABAJO.COD_MUNICIPIO
	 * @return  the value of FORMACION_TRABAJO.COD_MUNICIPIO
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public Integer getCodMunicipio() {
		return codMunicipio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FORMACION_TRABAJO.COD_MUNICIPIO
	 * @param codMunicipio  the value for FORMACION_TRABAJO.COD_MUNICIPIO
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public void setCodMunicipio(Integer codMunicipio) {
		this.codMunicipio = codMunicipio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FORMACION_TRABAJO.FECHA_INICIO
	 * @return  the value of FORMACION_TRABAJO.FECHA_INICIO
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public Date getFechaInicio() {
		return fechaInicio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FORMACION_TRABAJO.FECHA_INICIO
	 * @param fechaInicio  the value for FORMACION_TRABAJO.FECHA_INICIO
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FORMACION_TRABAJO.FECHA_TERMINACION
	 * @return  the value of FORMACION_TRABAJO.FECHA_TERMINACION
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public Date getFechaTerminacion() {
		return fechaTerminacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FORMACION_TRABAJO.FECHA_TERMINACION
	 * @param fechaTerminacion  the value for FORMACION_TRABAJO.FECHA_TERMINACION
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public void setFechaTerminacion(Date fechaTerminacion) {
		this.fechaTerminacion = fechaTerminacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FORMACION_TRABAJO.AUD_FECHA_ACTUALIZACION
	 * @return  the value of FORMACION_TRABAJO.AUD_FECHA_ACTUALIZACION
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public Date getAudFechaActualizacion() {
		return audFechaActualizacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FORMACION_TRABAJO.AUD_FECHA_ACTUALIZACION
	 * @param audFechaActualizacion  the value for FORMACION_TRABAJO.AUD_FECHA_ACTUALIZACION
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public void setAudFechaActualizacion(Date audFechaActualizacion) {
		this.audFechaActualizacion = audFechaActualizacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FORMACION_TRABAJO.AUD_COD_USUARIO
	 * @return  the value of FORMACION_TRABAJO.AUD_COD_USUARIO
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public BigDecimal getAudCodUsuario() {
		return audCodUsuario;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FORMACION_TRABAJO.AUD_COD_USUARIO
	 * @param audCodUsuario  the value for FORMACION_TRABAJO.AUD_COD_USUARIO
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public void setAudCodUsuario(BigDecimal audCodUsuario) {
		this.audCodUsuario = audCodUsuario;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FORMACION_TRABAJO.AUD_COD_ROL
	 * @return  the value of FORMACION_TRABAJO.AUD_COD_ROL
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public Integer getAudCodRol() {
		return audCodRol;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FORMACION_TRABAJO.AUD_COD_ROL
	 * @param audCodRol  the value for FORMACION_TRABAJO.AUD_COD_ROL
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public void setAudCodRol(Integer audCodRol) {
		this.audCodRol = audCodRol;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FORMACION_TRABAJO.AUD_ACCION
	 * @return  the value of FORMACION_TRABAJO.AUD_ACCION
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public Integer getAudAccion() {
		return audAccion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FORMACION_TRABAJO.AUD_ACCION
	 * @param audAccion  the value for FORMACION_TRABAJO.AUD_ACCION
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public void setAudAccion(Integer audAccion) {
		this.audAccion = audAccion;
	}

	private int limitInit;
    
    
    private int limitEnd;
    
    
    
    /**
	 * @return the limitInit
	 */
	public int getLimitInit() {
		return limitInit;
	}

	/**
	 * @param limitInit the limitInit to set
	 */
	public void setLimitInit(int limitInit) {
		this.limitInit = limitInit;
	}
    
    
	/**
	 * @return the limitEnd
	 */
	public int getLimitEnd() {
		return limitEnd;
	}

	/**
	 * @param limitEnd the limitEnd to set
	 */
	public void setLimitEnd(int limitEnd) {
		this.limitEnd = limitEnd;
	}
}