package co.gov.dafp.sigep2.bean;

import java.math.BigDecimal;
import java.util.Date;

import co.gov.dafp.sigep2.utils.ErrorMensajes;

public class IdiomaPersona extends ErrorMensajes{
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IDIOMA_PERSONA.COD_IDIOMA_PERSONA
	 * @mbg.generated  Wed Mar 07 10:54:49 COT 2018
	 */
	private BigDecimal codIdiomaPersona;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IDIOMA_PERSONA.COD_PERSONA
	 * @mbg.generated  Wed Mar 07 10:54:49 COT 2018
	 */
	private BigDecimal codPersona;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IDIOMA_PERSONA.COD_IDIOMA
	 * @mbg.generated  Wed Mar 07 10:54:49 COT 2018
	 */
	private Long codIdioma;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IDIOMA_PERSONA.COD_NIVEL_CONVERSACION
	 * @mbg.generated  Wed Mar 07 10:54:49 COT 2018
	 */
	private Integer codNivelConversacion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IDIOMA_PERSONA.COD_NIVEL_LECTURA
	 * @mbg.generated  Wed Mar 07 10:54:49 COT 2018
	 */
	private Integer codNivelLectura;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IDIOMA_PERSONA.COD_NIVEL_ESCRITURA
	 * @mbg.generated  Wed Mar 07 10:54:49 COT 2018
	 */
	private Integer codNivelEscritura;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IDIOMA_PERSONA.URL_CERTIFICACION
	 * @mbg.generated  Wed Mar 07 10:54:49 COT 2018
	 */
	private String urlCertificacion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IDIOMA_PERSONA.AUD_FECHA_ACTUALIZACION
	 * @mbg.generated  Wed Mar 07 10:54:49 COT 2018
	 */
	private Date audFechaActualizacion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IDIOMA_PERSONA.AUD_COD_USUARIO
	 * @mbg.generated  Wed Mar 07 10:54:49 COT 2018
	 */
	private BigDecimal audCodUsuario;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IDIOMA_PERSONA.AUD_COD_ROL
	 * @mbg.generated  Wed Mar 07 10:54:49 COT 2018
	 */
	private Integer audCodRol;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IDIOMA_PERSONA.AUD_ACCION
	 * @mbg.generated  Wed Mar 07 10:54:49 COT 2018
	 */
	private Integer audAccion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IDIOMA_PERSONA.FLG_IDIOMA_NATIVO
	 * @mbg.generated  Wed Mar 07 10:54:49 COT 2018
	 */
	private Short flgIdiomaNativo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IDIOMA_PERSONA.FECHA_CERTIFICACION
	 * @mbg.generated  Wed Mar 07 10:54:49 COT 2018
	 */
	private Date fechaCertificacion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column IDIOMA_PERSONA.FLG_ACTIVO
	 * @mbg.generated  Wed Mar 07 10:54:49 COT 2018
	 */
	private Short flgActivo;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IDIOMA_PERSONA.COD_IDIOMA_PERSONA
	 * @return  the value of IDIOMA_PERSONA.COD_IDIOMA_PERSONA
	 * @mbg.generated  Wed Mar 07 10:54:49 COT 2018
	 */
	public BigDecimal getCodIdiomaPersona() {
		return codIdiomaPersona;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IDIOMA_PERSONA.COD_IDIOMA_PERSONA
	 * @param codIdiomaPersona  the value for IDIOMA_PERSONA.COD_IDIOMA_PERSONA
	 * @mbg.generated  Wed Mar 07 10:54:49 COT 2018
	 */
	public void setCodIdiomaPersona(BigDecimal codIdiomaPersona) {
		this.codIdiomaPersona = codIdiomaPersona;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IDIOMA_PERSONA.COD_PERSONA
	 * @return  the value of IDIOMA_PERSONA.COD_PERSONA
	 * @mbg.generated  Wed Mar 07 10:54:49 COT 2018
	 */
	public BigDecimal getCodPersona() {
		return codPersona;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IDIOMA_PERSONA.COD_PERSONA
	 * @param codPersona  the value for IDIOMA_PERSONA.COD_PERSONA
	 * @mbg.generated  Wed Mar 07 10:54:49 COT 2018
	 */
	public void setCodPersona(BigDecimal codPersona) {
		this.codPersona = codPersona;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IDIOMA_PERSONA.COD_IDIOMA
	 * @return  the value of IDIOMA_PERSONA.COD_IDIOMA
	 * @mbg.generated  Wed Mar 07 10:54:49 COT 2018
	 */
	public Long getCodIdioma() {
		return codIdioma;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IDIOMA_PERSONA.COD_IDIOMA
	 * @param codIdioma  the value for IDIOMA_PERSONA.COD_IDIOMA
	 * @mbg.generated  Wed Mar 07 10:54:49 COT 2018
	 */
	public void setCodIdioma(Long codIdioma) {
		this.codIdioma = codIdioma;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IDIOMA_PERSONA.COD_NIVEL_CONVERSACION
	 * @return  the value of IDIOMA_PERSONA.COD_NIVEL_CONVERSACION
	 * @mbg.generated  Wed Mar 07 10:54:49 COT 2018
	 */
	public Integer getCodNivelConversacion() {
		return codNivelConversacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IDIOMA_PERSONA.COD_NIVEL_CONVERSACION
	 * @param codNivelConversacion  the value for IDIOMA_PERSONA.COD_NIVEL_CONVERSACION
	 * @mbg.generated  Wed Mar 07 10:54:49 COT 2018
	 */
	public void setCodNivelConversacion(Integer codNivelConversacion) {
		this.codNivelConversacion = codNivelConversacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IDIOMA_PERSONA.COD_NIVEL_LECTURA
	 * @return  the value of IDIOMA_PERSONA.COD_NIVEL_LECTURA
	 * @mbg.generated  Wed Mar 07 10:54:49 COT 2018
	 */
	public Integer getCodNivelLectura() {
		return codNivelLectura;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IDIOMA_PERSONA.COD_NIVEL_LECTURA
	 * @param codNivelLectura  the value for IDIOMA_PERSONA.COD_NIVEL_LECTURA
	 * @mbg.generated  Wed Mar 07 10:54:49 COT 2018
	 */
	public void setCodNivelLectura(Integer codNivelLectura) {
		this.codNivelLectura = codNivelLectura;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IDIOMA_PERSONA.COD_NIVEL_ESCRITURA
	 * @return  the value of IDIOMA_PERSONA.COD_NIVEL_ESCRITURA
	 * @mbg.generated  Wed Mar 07 10:54:49 COT 2018
	 */
	public Integer getCodNivelEscritura() {
		return codNivelEscritura;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IDIOMA_PERSONA.COD_NIVEL_ESCRITURA
	 * @param codNivelEscritura  the value for IDIOMA_PERSONA.COD_NIVEL_ESCRITURA
	 * @mbg.generated  Wed Mar 07 10:54:49 COT 2018
	 */
	public void setCodNivelEscritura(Integer codNivelEscritura) {
		this.codNivelEscritura = codNivelEscritura;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IDIOMA_PERSONA.URL_CERTIFICACION
	 * @return  the value of IDIOMA_PERSONA.URL_CERTIFICACION
	 * @mbg.generated  Wed Mar 07 10:54:49 COT 2018
	 */
	public String getUrlCertificacion() {
		return urlCertificacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IDIOMA_PERSONA.URL_CERTIFICACION
	 * @param urlCertificacion  the value for IDIOMA_PERSONA.URL_CERTIFICACION
	 * @mbg.generated  Wed Mar 07 10:54:49 COT 2018
	 */
	public void setUrlCertificacion(String urlCertificacion) {
		this.urlCertificacion = urlCertificacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IDIOMA_PERSONA.AUD_FECHA_ACTUALIZACION
	 * @return  the value of IDIOMA_PERSONA.AUD_FECHA_ACTUALIZACION
	 * @mbg.generated  Wed Mar 07 10:54:49 COT 2018
	 */
	public Date getAudFechaActualizacion() {
		return audFechaActualizacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IDIOMA_PERSONA.AUD_FECHA_ACTUALIZACION
	 * @param audFechaActualizacion  the value for IDIOMA_PERSONA.AUD_FECHA_ACTUALIZACION
	 * @mbg.generated  Wed Mar 07 10:54:49 COT 2018
	 */
	public void setAudFechaActualizacion(Date audFechaActualizacion) {
		this.audFechaActualizacion = audFechaActualizacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IDIOMA_PERSONA.AUD_COD_USUARIO
	 * @return  the value of IDIOMA_PERSONA.AUD_COD_USUARIO
	 * @mbg.generated  Wed Mar 07 10:54:49 COT 2018
	 */
	public BigDecimal getAudCodUsuario() {
		return audCodUsuario;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IDIOMA_PERSONA.AUD_COD_USUARIO
	 * @param audCodUsuario  the value for IDIOMA_PERSONA.AUD_COD_USUARIO
	 * @mbg.generated  Wed Mar 07 10:54:49 COT 2018
	 */
	public void setAudCodUsuario(BigDecimal audCodUsuario) {
		this.audCodUsuario = audCodUsuario;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IDIOMA_PERSONA.AUD_COD_ROL
	 * @return  the value of IDIOMA_PERSONA.AUD_COD_ROL
	 * @mbg.generated  Wed Mar 07 10:54:49 COT 2018
	 */
	public Integer getAudCodRol() {
		return audCodRol;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IDIOMA_PERSONA.AUD_COD_ROL
	 * @param audCodRol  the value for IDIOMA_PERSONA.AUD_COD_ROL
	 * @mbg.generated  Wed Mar 07 10:54:49 COT 2018
	 */
	public void setAudCodRol(Integer audCodRol) {
		this.audCodRol = audCodRol;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IDIOMA_PERSONA.AUD_ACCION
	 * @return  the value of IDIOMA_PERSONA.AUD_ACCION
	 * @mbg.generated  Wed Mar 07 10:54:49 COT 2018
	 */
	public Integer getAudAccion() {
		return audAccion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IDIOMA_PERSONA.AUD_ACCION
	 * @param audAccion  the value for IDIOMA_PERSONA.AUD_ACCION
	 * @mbg.generated  Wed Mar 07 10:54:49 COT 2018
	 */
	public void setAudAccion(Integer audAccion) {
		this.audAccion = audAccion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IDIOMA_PERSONA.FLG_IDIOMA_NATIVO
	 * @return  the value of IDIOMA_PERSONA.FLG_IDIOMA_NATIVO
	 * @mbg.generated  Wed Mar 07 10:54:49 COT 2018
	 */
	public Short getFlgIdiomaNativo() {
		return flgIdiomaNativo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IDIOMA_PERSONA.FLG_IDIOMA_NATIVO
	 * @param flgIdiomaNativo  the value for IDIOMA_PERSONA.FLG_IDIOMA_NATIVO
	 * @mbg.generated  Wed Mar 07 10:54:49 COT 2018
	 */
	public void setFlgIdiomaNativo(Short flgIdiomaNativo) {
		this.flgIdiomaNativo = flgIdiomaNativo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IDIOMA_PERSONA.FECHA_CERTIFICACION
	 * @return  the value of IDIOMA_PERSONA.FECHA_CERTIFICACION
	 * @mbg.generated  Wed Mar 07 10:54:49 COT 2018
	 */
	public Date getFechaCertificacion() {
		return fechaCertificacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IDIOMA_PERSONA.FECHA_CERTIFICACION
	 * @param fechaCertificacion  the value for IDIOMA_PERSONA.FECHA_CERTIFICACION
	 * @mbg.generated  Wed Mar 07 10:54:49 COT 2018
	 */
	public void setFechaCertificacion(Date fechaCertificacion) {
		this.fechaCertificacion = fechaCertificacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column IDIOMA_PERSONA.FLG_ACTIVO
	 * @return  the value of IDIOMA_PERSONA.FLG_ACTIVO
	 * @mbg.generated  Wed Mar 07 10:54:49 COT 2018
	 */
	public Short getFlgActivo() {
		return flgActivo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column IDIOMA_PERSONA.FLG_ACTIVO
	 * @param flgActivo  the value for IDIOMA_PERSONA.FLG_ACTIVO
	 * @mbg.generated  Wed Mar 07 10:54:49 COT 2018
	 */
	public void setFlgActivo(Short flgActivo) {
		this.flgActivo = flgActivo;
	}

	/**
	 * 
	 */
	private static final long serialVersionUID = -9018322212976974136L;
}