package co.gov.dafp.sigep2.bean;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class InstitucionEducativaExample {
	/**
	 * 
	 */
	private int limitInit;
	/**
	 * 
	 */
	private int limitEnd;
	
	/**
	 * @return the limitInit
	 */
	public int getLimitInit() {
		return limitInit;
	}

	/**
	 * @param limitInit the limitInit to set
	 */
	public void setLimitInit(int limitInit) {
		this.limitInit = limitInit;
	}
	
	
	
    /**
	 * @return the limitEnd
	 */
	public int getLimitEnd() {
		return limitEnd;
	}

	/**
	 * @param limitEnd the limitEnd to set
	 */
	public void setLimitEnd(int limitEnd) {
		this.limitEnd = limitEnd;
	}
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table INSTITUCION_EDUCATIVA
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table INSTITUCION_EDUCATIVA
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table INSTITUCION_EDUCATIVA
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table INSTITUCION_EDUCATIVA
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public InstitucionEducativaExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table INSTITUCION_EDUCATIVA
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table INSTITUCION_EDUCATIVA
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table INSTITUCION_EDUCATIVA
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table INSTITUCION_EDUCATIVA
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table INSTITUCION_EDUCATIVA
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table INSTITUCION_EDUCATIVA
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table INSTITUCION_EDUCATIVA
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table INSTITUCION_EDUCATIVA
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table INSTITUCION_EDUCATIVA
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table INSTITUCION_EDUCATIVA
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table INSTITUCION_EDUCATIVA
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andCodInstitucionEducativaIsNull() {
			addCriterion("COD_INSTITUCION_EDUCATIVA is null");
			return (Criteria) this;
		}

		public Criteria andCodInstitucionEducativaIsNotNull() {
			addCriterion("COD_INSTITUCION_EDUCATIVA is not null");
			return (Criteria) this;
		}

		public Criteria andCodInstitucionEducativaEqualTo(Long value) {
			addCriterion("COD_INSTITUCION_EDUCATIVA =", value, "codInstitucionEducativa");
			return (Criteria) this;
		}

		public Criteria andCodInstitucionEducativaNotEqualTo(Long value) {
			addCriterion("COD_INSTITUCION_EDUCATIVA <>", value, "codInstitucionEducativa");
			return (Criteria) this;
		}

		public Criteria andCodInstitucionEducativaGreaterThan(Long value) {
			addCriterion("COD_INSTITUCION_EDUCATIVA >", value, "codInstitucionEducativa");
			return (Criteria) this;
		}

		public Criteria andCodInstitucionEducativaGreaterThanOrEqualTo(Long value) {
			addCriterion("COD_INSTITUCION_EDUCATIVA >=", value, "codInstitucionEducativa");
			return (Criteria) this;
		}

		public Criteria andCodInstitucionEducativaLessThan(Long value) {
			addCriterion("COD_INSTITUCION_EDUCATIVA <", value, "codInstitucionEducativa");
			return (Criteria) this;
		}

		public Criteria andCodInstitucionEducativaLessThanOrEqualTo(Long value) {
			addCriterion("COD_INSTITUCION_EDUCATIVA <=", value, "codInstitucionEducativa");
			return (Criteria) this;
		}

		public Criteria andCodInstitucionEducativaIn(List<Long> values) {
			addCriterion("COD_INSTITUCION_EDUCATIVA in", values, "codInstitucionEducativa");
			return (Criteria) this;
		}

		public Criteria andCodInstitucionEducativaNotIn(List<Long> values) {
			addCriterion("COD_INSTITUCION_EDUCATIVA not in", values, "codInstitucionEducativa");
			return (Criteria) this;
		}

		public Criteria andCodInstitucionEducativaBetween(Long value1, Long value2) {
			addCriterion("COD_INSTITUCION_EDUCATIVA between", value1, value2, "codInstitucionEducativa");
			return (Criteria) this;
		}

		public Criteria andCodInstitucionEducativaNotBetween(Long value1, Long value2) {
			addCriterion("COD_INSTITUCION_EDUCATIVA not between", value1, value2, "codInstitucionEducativa");
			return (Criteria) this;
		}

		public Criteria andCodInstitucionMenIsNull() {
			addCriterion("COD_INSTITUCION_MEN is null");
			return (Criteria) this;
		}

		public Criteria andCodInstitucionMenIsNotNull() {
			addCriterion("COD_INSTITUCION_MEN is not null");
			return (Criteria) this;
		}

		public Criteria andCodInstitucionMenEqualTo(Long value) {
			addCriterion("COD_INSTITUCION_MEN =", value, "codInstitucionMen");
			return (Criteria) this;
		}

		public Criteria andCodInstitucionMenNotEqualTo(Long value) {
			addCriterion("COD_INSTITUCION_MEN <>", value, "codInstitucionMen");
			return (Criteria) this;
		}

		public Criteria andCodInstitucionMenGreaterThan(Long value) {
			addCriterion("COD_INSTITUCION_MEN >", value, "codInstitucionMen");
			return (Criteria) this;
		}

		public Criteria andCodInstitucionMenGreaterThanOrEqualTo(Long value) {
			addCriterion("COD_INSTITUCION_MEN >=", value, "codInstitucionMen");
			return (Criteria) this;
		}

		public Criteria andCodInstitucionMenLessThan(Long value) {
			addCriterion("COD_INSTITUCION_MEN <", value, "codInstitucionMen");
			return (Criteria) this;
		}

		public Criteria andCodInstitucionMenLessThanOrEqualTo(Long value) {
			addCriterion("COD_INSTITUCION_MEN <=", value, "codInstitucionMen");
			return (Criteria) this;
		}

		public Criteria andCodInstitucionMenIn(List<Long> values) {
			addCriterion("COD_INSTITUCION_MEN in", values, "codInstitucionMen");
			return (Criteria) this;
		}

		public Criteria andCodInstitucionMenNotIn(List<Long> values) {
			addCriterion("COD_INSTITUCION_MEN not in", values, "codInstitucionMen");
			return (Criteria) this;
		}

		public Criteria andCodInstitucionMenBetween(Long value1, Long value2) {
			addCriterion("COD_INSTITUCION_MEN between", value1, value2, "codInstitucionMen");
			return (Criteria) this;
		}

		public Criteria andCodInstitucionMenNotBetween(Long value1, Long value2) {
			addCriterion("COD_INSTITUCION_MEN not between", value1, value2, "codInstitucionMen");
			return (Criteria) this;
		}

		public Criteria andCodTipoInstitucionIsNull() {
			addCriterion("COD_TIPO_INSTITUCION is null");
			return (Criteria) this;
		}

		public Criteria andCodTipoInstitucionIsNotNull() {
			addCriterion("COD_TIPO_INSTITUCION is not null");
			return (Criteria) this;
		}

		public Criteria andCodTipoInstitucionEqualTo(Integer value) {
			addCriterion("COD_TIPO_INSTITUCION =", value, "codTipoInstitucion");
			return (Criteria) this;
		}

		public Criteria andCodTipoInstitucionNotEqualTo(Integer value) {
			addCriterion("COD_TIPO_INSTITUCION <>", value, "codTipoInstitucion");
			return (Criteria) this;
		}

		public Criteria andCodTipoInstitucionGreaterThan(Integer value) {
			addCriterion("COD_TIPO_INSTITUCION >", value, "codTipoInstitucion");
			return (Criteria) this;
		}

		public Criteria andCodTipoInstitucionGreaterThanOrEqualTo(Integer value) {
			addCriterion("COD_TIPO_INSTITUCION >=", value, "codTipoInstitucion");
			return (Criteria) this;
		}

		public Criteria andCodTipoInstitucionLessThan(Integer value) {
			addCriterion("COD_TIPO_INSTITUCION <", value, "codTipoInstitucion");
			return (Criteria) this;
		}

		public Criteria andCodTipoInstitucionLessThanOrEqualTo(Integer value) {
			addCriterion("COD_TIPO_INSTITUCION <=", value, "codTipoInstitucion");
			return (Criteria) this;
		}

		public Criteria andCodTipoInstitucionIn(List<Integer> values) {
			addCriterion("COD_TIPO_INSTITUCION in", values, "codTipoInstitucion");
			return (Criteria) this;
		}

		public Criteria andCodTipoInstitucionNotIn(List<Integer> values) {
			addCriterion("COD_TIPO_INSTITUCION not in", values, "codTipoInstitucion");
			return (Criteria) this;
		}

		public Criteria andCodTipoInstitucionBetween(Integer value1, Integer value2) {
			addCriterion("COD_TIPO_INSTITUCION between", value1, value2, "codTipoInstitucion");
			return (Criteria) this;
		}

		public Criteria andCodTipoInstitucionNotBetween(Integer value1, Integer value2) {
			addCriterion("COD_TIPO_INSTITUCION not between", value1, value2, "codTipoInstitucion");
			return (Criteria) this;
		}

		public Criteria andNombreInstitucionIsNull() {
			addCriterion("NOMBRE_INSTITUCION is null");
			return (Criteria) this;
		}

		public Criteria andNombreInstitucionIsNotNull() {
			addCriterion("NOMBRE_INSTITUCION is not null");
			return (Criteria) this;
		}

		public Criteria andNombreInstitucionEqualTo(String value) {
			addCriterion("NOMBRE_INSTITUCION =", value, "nombreInstitucion");
			return (Criteria) this;
		}

		public Criteria andNombreInstitucionNotEqualTo(String value) {
			addCriterion("NOMBRE_INSTITUCION <>", value, "nombreInstitucion");
			return (Criteria) this;
		}

		public Criteria andNombreInstitucionGreaterThan(String value) {
			addCriterion("NOMBRE_INSTITUCION >", value, "nombreInstitucion");
			return (Criteria) this;
		}

		public Criteria andNombreInstitucionGreaterThanOrEqualTo(String value) {
			addCriterion("NOMBRE_INSTITUCION >=", value, "nombreInstitucion");
			return (Criteria) this;
		}

		public Criteria andNombreInstitucionLessThan(String value) {
			addCriterion("NOMBRE_INSTITUCION <", value, "nombreInstitucion");
			return (Criteria) this;
		}

		public Criteria andNombreInstitucionLessThanOrEqualTo(String value) {
			addCriterion("NOMBRE_INSTITUCION <=", value, "nombreInstitucion");
			return (Criteria) this;
		}

		public Criteria andNombreInstitucionLike(String value) {
			addCriterion("NOMBRE_INSTITUCION like", value, "nombreInstitucion");
			return (Criteria) this;
		}

		public Criteria andNombreInstitucionNotLike(String value) {
			addCriterion("NOMBRE_INSTITUCION not like", value, "nombreInstitucion");
			return (Criteria) this;
		}

		public Criteria andNombreInstitucionIn(List<String> values) {
			addCriterion("NOMBRE_INSTITUCION in", values, "nombreInstitucion");
			return (Criteria) this;
		}

		public Criteria andNombreInstitucionNotIn(List<String> values) {
			addCriterion("NOMBRE_INSTITUCION not in", values, "nombreInstitucion");
			return (Criteria) this;
		}

		public Criteria andNombreInstitucionBetween(String value1, String value2) {
			addCriterion("NOMBRE_INSTITUCION between", value1, value2, "nombreInstitucion");
			return (Criteria) this;
		}

		public Criteria andNombreInstitucionNotBetween(String value1, String value2) {
			addCriterion("NOMBRE_INSTITUCION not between", value1, value2, "nombreInstitucion");
			return (Criteria) this;
		}

		public Criteria andAudFechaActualizacionIsNull() {
			addCriterion("AUD_FECHA_ACTUALIZACION is null");
			return (Criteria) this;
		}

		public Criteria andAudFechaActualizacionIsNotNull() {
			addCriterion("AUD_FECHA_ACTUALIZACION is not null");
			return (Criteria) this;
		}

		public Criteria andAudFechaActualizacionEqualTo(Date value) {
			addCriterion("AUD_FECHA_ACTUALIZACION =", value, "audFechaActualizacion");
			return (Criteria) this;
		}

		public Criteria andAudFechaActualizacionNotEqualTo(Date value) {
			addCriterion("AUD_FECHA_ACTUALIZACION <>", value, "audFechaActualizacion");
			return (Criteria) this;
		}

		public Criteria andAudFechaActualizacionGreaterThan(Date value) {
			addCriterion("AUD_FECHA_ACTUALIZACION >", value, "audFechaActualizacion");
			return (Criteria) this;
		}

		public Criteria andAudFechaActualizacionGreaterThanOrEqualTo(Date value) {
			addCriterion("AUD_FECHA_ACTUALIZACION >=", value, "audFechaActualizacion");
			return (Criteria) this;
		}

		public Criteria andAudFechaActualizacionLessThan(Date value) {
			addCriterion("AUD_FECHA_ACTUALIZACION <", value, "audFechaActualizacion");
			return (Criteria) this;
		}

		public Criteria andAudFechaActualizacionLessThanOrEqualTo(Date value) {
			addCriterion("AUD_FECHA_ACTUALIZACION <=", value, "audFechaActualizacion");
			return (Criteria) this;
		}

		public Criteria andAudFechaActualizacionIn(List<Date> values) {
			addCriterion("AUD_FECHA_ACTUALIZACION in", values, "audFechaActualizacion");
			return (Criteria) this;
		}

		public Criteria andAudFechaActualizacionNotIn(List<Date> values) {
			addCriterion("AUD_FECHA_ACTUALIZACION not in", values, "audFechaActualizacion");
			return (Criteria) this;
		}

		public Criteria andAudFechaActualizacionBetween(Date value1, Date value2) {
			addCriterion("AUD_FECHA_ACTUALIZACION between", value1, value2, "audFechaActualizacion");
			return (Criteria) this;
		}

		public Criteria andAudFechaActualizacionNotBetween(Date value1, Date value2) {
			addCriterion("AUD_FECHA_ACTUALIZACION not between", value1, value2, "audFechaActualizacion");
			return (Criteria) this;
		}

		public Criteria andAudCodUsuarioIsNull() {
			addCriterion("AUD_COD_USUARIO is null");
			return (Criteria) this;
		}

		public Criteria andAudCodUsuarioIsNotNull() {
			addCriterion("AUD_COD_USUARIO is not null");
			return (Criteria) this;
		}

		public Criteria andAudCodUsuarioEqualTo(BigDecimal value) {
			addCriterion("AUD_COD_USUARIO =", value, "audCodUsuario");
			return (Criteria) this;
		}

		public Criteria andAudCodUsuarioNotEqualTo(BigDecimal value) {
			addCriterion("AUD_COD_USUARIO <>", value, "audCodUsuario");
			return (Criteria) this;
		}

		public Criteria andAudCodUsuarioGreaterThan(BigDecimal value) {
			addCriterion("AUD_COD_USUARIO >", value, "audCodUsuario");
			return (Criteria) this;
		}

		public Criteria andAudCodUsuarioGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("AUD_COD_USUARIO >=", value, "audCodUsuario");
			return (Criteria) this;
		}

		public Criteria andAudCodUsuarioLessThan(BigDecimal value) {
			addCriterion("AUD_COD_USUARIO <", value, "audCodUsuario");
			return (Criteria) this;
		}

		public Criteria andAudCodUsuarioLessThanOrEqualTo(BigDecimal value) {
			addCriterion("AUD_COD_USUARIO <=", value, "audCodUsuario");
			return (Criteria) this;
		}

		public Criteria andAudCodUsuarioIn(List<BigDecimal> values) {
			addCriterion("AUD_COD_USUARIO in", values, "audCodUsuario");
			return (Criteria) this;
		}

		public Criteria andAudCodUsuarioNotIn(List<BigDecimal> values) {
			addCriterion("AUD_COD_USUARIO not in", values, "audCodUsuario");
			return (Criteria) this;
		}

		public Criteria andAudCodUsuarioBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("AUD_COD_USUARIO between", value1, value2, "audCodUsuario");
			return (Criteria) this;
		}

		public Criteria andAudCodUsuarioNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("AUD_COD_USUARIO not between", value1, value2, "audCodUsuario");
			return (Criteria) this;
		}

		public Criteria andAudCodRolIsNull() {
			addCriterion("AUD_COD_ROL is null");
			return (Criteria) this;
		}

		public Criteria andAudCodRolIsNotNull() {
			addCriterion("AUD_COD_ROL is not null");
			return (Criteria) this;
		}

		public Criteria andAudCodRolEqualTo(Integer value) {
			addCriterion("AUD_COD_ROL =", value, "audCodRol");
			return (Criteria) this;
		}

		public Criteria andAudCodRolNotEqualTo(Integer value) {
			addCriterion("AUD_COD_ROL <>", value, "audCodRol");
			return (Criteria) this;
		}

		public Criteria andAudCodRolGreaterThan(Integer value) {
			addCriterion("AUD_COD_ROL >", value, "audCodRol");
			return (Criteria) this;
		}

		public Criteria andAudCodRolGreaterThanOrEqualTo(Integer value) {
			addCriterion("AUD_COD_ROL >=", value, "audCodRol");
			return (Criteria) this;
		}

		public Criteria andAudCodRolLessThan(Integer value) {
			addCriterion("AUD_COD_ROL <", value, "audCodRol");
			return (Criteria) this;
		}

		public Criteria andAudCodRolLessThanOrEqualTo(Integer value) {
			addCriterion("AUD_COD_ROL <=", value, "audCodRol");
			return (Criteria) this;
		}

		public Criteria andAudCodRolIn(List<Integer> values) {
			addCriterion("AUD_COD_ROL in", values, "audCodRol");
			return (Criteria) this;
		}

		public Criteria andAudCodRolNotIn(List<Integer> values) {
			addCriterion("AUD_COD_ROL not in", values, "audCodRol");
			return (Criteria) this;
		}

		public Criteria andAudCodRolBetween(Integer value1, Integer value2) {
			addCriterion("AUD_COD_ROL between", value1, value2, "audCodRol");
			return (Criteria) this;
		}

		public Criteria andAudCodRolNotBetween(Integer value1, Integer value2) {
			addCriterion("AUD_COD_ROL not between", value1, value2, "audCodRol");
			return (Criteria) this;
		}

		public Criteria andAudAccionIsNull() {
			addCriterion("AUD_ACCION is null");
			return (Criteria) this;
		}

		public Criteria andAudAccionIsNotNull() {
			addCriterion("AUD_ACCION is not null");
			return (Criteria) this;
		}

		public Criteria andAudAccionEqualTo(Integer value) {
			addCriterion("AUD_ACCION =", value, "audAccion");
			return (Criteria) this;
		}

		public Criteria andAudAccionNotEqualTo(Integer value) {
			addCriterion("AUD_ACCION <>", value, "audAccion");
			return (Criteria) this;
		}

		public Criteria andAudAccionGreaterThan(Integer value) {
			addCriterion("AUD_ACCION >", value, "audAccion");
			return (Criteria) this;
		}

		public Criteria andAudAccionGreaterThanOrEqualTo(Integer value) {
			addCriterion("AUD_ACCION >=", value, "audAccion");
			return (Criteria) this;
		}

		public Criteria andAudAccionLessThan(Integer value) {
			addCriterion("AUD_ACCION <", value, "audAccion");
			return (Criteria) this;
		}

		public Criteria andAudAccionLessThanOrEqualTo(Integer value) {
			addCriterion("AUD_ACCION <=", value, "audAccion");
			return (Criteria) this;
		}

		public Criteria andAudAccionIn(List<Integer> values) {
			addCriterion("AUD_ACCION in", values, "audAccion");
			return (Criteria) this;
		}

		public Criteria andAudAccionNotIn(List<Integer> values) {
			addCriterion("AUD_ACCION not in", values, "audAccion");
			return (Criteria) this;
		}

		public Criteria andAudAccionBetween(Integer value1, Integer value2) {
			addCriterion("AUD_ACCION between", value1, value2, "audAccion");
			return (Criteria) this;
		}

		public Criteria andAudAccionNotBetween(Integer value1, Integer value2) {
			addCriterion("AUD_ACCION not between", value1, value2, "audAccion");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table INSTITUCION_EDUCATIVA
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table INSTITUCION_EDUCATIVA
     *
     * @mbg.generated do_not_delete_during_merge Mon Jan 29 14:57:36 COT 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}