package co.gov.dafp.sigep2.bean;

import java.math.BigDecimal;
import java.util.Date;

import co.gov.dafp.sigep2.utils.ErrorMensajes;

public class ModificacionContrato extends ErrorMensajes{
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MODIFICACION_CONTRATO.COD_MODIFICACION_CONTRATO
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	private Long codModificacionContrato;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MODIFICACION_CONTRATO.COD_CONTRATO
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	private Long codContrato;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MODIFICACION_CONTRATO.COD_TIPO_MODIFICACION_CONTRATO
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	private Integer codTipoModificacionContrato;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MODIFICACION_CONTRATO.NUEVO_MONTO_CONTRATO
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	private BigDecimal nuevoMontoContrato;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MODIFICACION_CONTRATO.FECHA_INICIO_MODIFICACION
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	private Date fechaInicioModificacion;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MODIFICACION_CONTRATO.FECHA_FIN_MODIFICACION
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	private Date fechaFinModificacion;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MODIFICACION_CONTRATO.FECHA_AUTORIZACION_MODIFICACION
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	private Date fechaAutorizacionModificacion;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MODIFICACION_CONTRATO.JUSTIFICACION_MODIFICACION
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	private String justificacionModificacion;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MODIFICACION_CONTRATO.VALOR_ADICION
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	private BigDecimal valorAdicion;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MODIFICACION_CONTRATO.NUEVO_ALCANCE_CONTRATO
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	private String nuevoAlcanceContrato;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MODIFICACION_CONTRATO.COD_MOTIVO_SUSPENCION
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	private Integer codMotivoSuspencion;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MODIFICACION_CONTRATO.COD_CONTRATISTA_INICIAL
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	private Long codContratistaInicial;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MODIFICACION_CONTRATO.COD_NUEVO_CONTRATISTA
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	private Long codNuevoContratista;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MODIFICACION_CONTRATO.COD_NUEVO_SUPERVISOR
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	private BigDecimal codNuevoSupervisor;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MODIFICACION_CONTRATO.AUD_FECHA_ACTUALIZACION
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	private Date audFechaActualizacion;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MODIFICACION_CONTRATO.AUD_COD_USUARIO
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	private BigDecimal audCodUsuario;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MODIFICACION_CONTRATO.AUD_COD_ROL
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	private Integer audCodRol;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MODIFICACION_CONTRATO.AUD_ACCION
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	private Integer audAccion;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MODIFICACION_CONTRATO.FLG_ACTIVO
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	private Short flgActivo;
	
	private Date fechaFinRegistroContrato;
	
	private Integer montoRegistroContrato;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MODIFICACION_CONTRATO.COD_MODIFICACION_CONTRATO
	 * @return  the value of MODIFICACION_CONTRATO.COD_MODIFICACION_CONTRATO
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	public Long getCodModificacionContrato() {
		return codModificacionContrato;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MODIFICACION_CONTRATO.COD_MODIFICACION_CONTRATO
	 * @param codModificacionContrato  the value for MODIFICACION_CONTRATO.COD_MODIFICACION_CONTRATO
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	public void setCodModificacionContrato(Long codModificacionContrato) {
		this.codModificacionContrato = codModificacionContrato;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MODIFICACION_CONTRATO.COD_CONTRATO
	 * @return  the value of MODIFICACION_CONTRATO.COD_CONTRATO
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	public Long getCodContrato() {
		return codContrato;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MODIFICACION_CONTRATO.COD_CONTRATO
	 * @param codContrato  the value for MODIFICACION_CONTRATO.COD_CONTRATO
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	public void setCodContrato(Long codContrato) {
		this.codContrato = codContrato;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MODIFICACION_CONTRATO.COD_TIPO_MODIFICACION_CONTRATO
	 * @return  the value of MODIFICACION_CONTRATO.COD_TIPO_MODIFICACION_CONTRATO
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	public Integer getCodTipoModificacionContrato() {
		return codTipoModificacionContrato;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MODIFICACION_CONTRATO.COD_TIPO_MODIFICACION_CONTRATO
	 * @param codTipoModificacionContrato  the value for MODIFICACION_CONTRATO.COD_TIPO_MODIFICACION_CONTRATO
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	public void setCodTipoModificacionContrato(Integer codTipoModificacionContrato) {
		this.codTipoModificacionContrato = codTipoModificacionContrato;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MODIFICACION_CONTRATO.NUEVO_MONTO_CONTRATO
	 * @return  the value of MODIFICACION_CONTRATO.NUEVO_MONTO_CONTRATO
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	public BigDecimal getNuevoMontoContrato() {
		return nuevoMontoContrato;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MODIFICACION_CONTRATO.NUEVO_MONTO_CONTRATO
	 * @param nuevoMontoContrato  the value for MODIFICACION_CONTRATO.NUEVO_MONTO_CONTRATO
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	public void setNuevoMontoContrato(BigDecimal nuevoMontoContrato) {
		this.nuevoMontoContrato = nuevoMontoContrato;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MODIFICACION_CONTRATO.FECHA_INICIO_MODIFICACION
	 * @return  the value of MODIFICACION_CONTRATO.FECHA_INICIO_MODIFICACION
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	public Date getFechaInicioModificacion() {
		return fechaInicioModificacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MODIFICACION_CONTRATO.FECHA_INICIO_MODIFICACION
	 * @param fechaInicioModificacion  the value for MODIFICACION_CONTRATO.FECHA_INICIO_MODIFICACION
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	public void setFechaInicioModificacion(Date fechaInicioModificacion) {
		this.fechaInicioModificacion = fechaInicioModificacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MODIFICACION_CONTRATO.FECHA_FIN_MODIFICACION
	 * @return  the value of MODIFICACION_CONTRATO.FECHA_FIN_MODIFICACION
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	public Date getFechaFinModificacion() {
		return fechaFinModificacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MODIFICACION_CONTRATO.FECHA_FIN_MODIFICACION
	 * @param fechaFinModificacion  the value for MODIFICACION_CONTRATO.FECHA_FIN_MODIFICACION
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	public void setFechaFinModificacion(Date fechaFinModificacion) {
		this.fechaFinModificacion = fechaFinModificacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MODIFICACION_CONTRATO.FECHA_AUTORIZACION_MODIFICACION
	 * @return  the value of MODIFICACION_CONTRATO.FECHA_AUTORIZACION_MODIFICACION
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	public Date getFechaAutorizacionModificacion() {
		return fechaAutorizacionModificacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MODIFICACION_CONTRATO.FECHA_AUTORIZACION_MODIFICACION
	 * @param fechaAutorizacionModificacion  the value for MODIFICACION_CONTRATO.FECHA_AUTORIZACION_MODIFICACION
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	public void setFechaAutorizacionModificacion(Date fechaAutorizacionModificacion) {
		this.fechaAutorizacionModificacion = fechaAutorizacionModificacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MODIFICACION_CONTRATO.JUSTIFICACION_MODIFICACION
	 * @return  the value of MODIFICACION_CONTRATO.JUSTIFICACION_MODIFICACION
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	public String getJustificacionModificacion() {
		return justificacionModificacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MODIFICACION_CONTRATO.JUSTIFICACION_MODIFICACION
	 * @param justificacionModificacion  the value for MODIFICACION_CONTRATO.JUSTIFICACION_MODIFICACION
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	public void setJustificacionModificacion(String justificacionModificacion) {
		this.justificacionModificacion = justificacionModificacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MODIFICACION_CONTRATO.VALOR_ADICION
	 * @return  the value of MODIFICACION_CONTRATO.VALOR_ADICION
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	public BigDecimal getValorAdicion() {
		return valorAdicion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MODIFICACION_CONTRATO.VALOR_ADICION
	 * @param valorAdicion  the value for MODIFICACION_CONTRATO.VALOR_ADICION
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	public void setValorAdicion(BigDecimal valorAdicion) {
		this.valorAdicion = valorAdicion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MODIFICACION_CONTRATO.NUEVO_ALCANCE_CONTRATO
	 * @return  the value of MODIFICACION_CONTRATO.NUEVO_ALCANCE_CONTRATO
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	public String getNuevoAlcanceContrato() {
		return nuevoAlcanceContrato;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MODIFICACION_CONTRATO.NUEVO_ALCANCE_CONTRATO
	 * @param nuevoAlcanceContrato  the value for MODIFICACION_CONTRATO.NUEVO_ALCANCE_CONTRATO
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	public void setNuevoAlcanceContrato(String nuevoAlcanceContrato) {
		this.nuevoAlcanceContrato = nuevoAlcanceContrato;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MODIFICACION_CONTRATO.COD_MOTIVO_SUSPENCION
	 * @return  the value of MODIFICACION_CONTRATO.COD_MOTIVO_SUSPENCION
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	public Integer getCodMotivoSuspencion() {
		return codMotivoSuspencion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MODIFICACION_CONTRATO.COD_MOTIVO_SUSPENCION
	 * @param codMotivoSuspencion  the value for MODIFICACION_CONTRATO.COD_MOTIVO_SUSPENCION
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	public void setCodMotivoSuspencion(Integer codMotivoSuspencion) {
		this.codMotivoSuspencion = codMotivoSuspencion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MODIFICACION_CONTRATO.COD_CONTRATISTA_INICIAL
	 * @return  the value of MODIFICACION_CONTRATO.COD_CONTRATISTA_INICIAL
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	public Long getCodContratistaInicial() {
		return codContratistaInicial;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MODIFICACION_CONTRATO.COD_CONTRATISTA_INICIAL
	 * @param codContratistaInicial  the value for MODIFICACION_CONTRATO.COD_CONTRATISTA_INICIAL
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	public void setCodContratistaInicial(Long codContratistaInicial) {
		this.codContratistaInicial = codContratistaInicial;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MODIFICACION_CONTRATO.COD_NUEVO_CONTRATISTA
	 * @return  the value of MODIFICACION_CONTRATO.COD_NUEVO_CONTRATISTA
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	public Long getCodNuevoContratista() {
		return codNuevoContratista;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MODIFICACION_CONTRATO.COD_NUEVO_CONTRATISTA
	 * @param codNuevoContratista  the value for MODIFICACION_CONTRATO.COD_NUEVO_CONTRATISTA
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	public void setCodNuevoContratista(Long codNuevoContratista) {
		this.codNuevoContratista = codNuevoContratista;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MODIFICACION_CONTRATO.COD_NUEVO_SUPERVISOR
	 * @return  the value of MODIFICACION_CONTRATO.COD_NUEVO_SUPERVISOR
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	public BigDecimal getCodNuevoSupervisor() {
		return codNuevoSupervisor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MODIFICACION_CONTRATO.COD_NUEVO_SUPERVISOR
	 * @param codNuevoSupervisor  the value for MODIFICACION_CONTRATO.COD_NUEVO_SUPERVISOR
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	public void setCodNuevoSupervisor(BigDecimal codNuevoSupervisor) {
		this.codNuevoSupervisor = codNuevoSupervisor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MODIFICACION_CONTRATO.AUD_FECHA_ACTUALIZACION
	 * @return  the value of MODIFICACION_CONTRATO.AUD_FECHA_ACTUALIZACION
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	public Date getAudFechaActualizacion() {
		return audFechaActualizacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MODIFICACION_CONTRATO.AUD_FECHA_ACTUALIZACION
	 * @param audFechaActualizacion  the value for MODIFICACION_CONTRATO.AUD_FECHA_ACTUALIZACION
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	public void setAudFechaActualizacion(Date audFechaActualizacion) {
		this.audFechaActualizacion = audFechaActualizacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MODIFICACION_CONTRATO.AUD_COD_USUARIO
	 * @return  the value of MODIFICACION_CONTRATO.AUD_COD_USUARIO
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	public BigDecimal getAudCodUsuario() {
		return audCodUsuario;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MODIFICACION_CONTRATO.AUD_COD_USUARIO
	 * @param audCodUsuario  the value for MODIFICACION_CONTRATO.AUD_COD_USUARIO
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	public void setAudCodUsuario(BigDecimal audCodUsuario) {
		this.audCodUsuario = audCodUsuario;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MODIFICACION_CONTRATO.AUD_COD_ROL
	 * @return  the value of MODIFICACION_CONTRATO.AUD_COD_ROL
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	public Integer getAudCodRol() {
		return audCodRol;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MODIFICACION_CONTRATO.AUD_COD_ROL
	 * @param audCodRol  the value for MODIFICACION_CONTRATO.AUD_COD_ROL
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	public void setAudCodRol(Integer audCodRol) {
		this.audCodRol = audCodRol;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MODIFICACION_CONTRATO.AUD_ACCION
	 * @return  the value of MODIFICACION_CONTRATO.AUD_ACCION
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	public Integer getAudAccion() {
		return audAccion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MODIFICACION_CONTRATO.AUD_ACCION
	 * @param audAccion  the value for MODIFICACION_CONTRATO.AUD_ACCION
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	public void setAudAccion(Integer audAccion) {
		this.audAccion = audAccion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MODIFICACION_CONTRATO.FLG_ACTIVO
	 * @return  the value of MODIFICACION_CONTRATO.FLG_ACTIVO
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	public Short getFlgActivo() {
		return flgActivo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MODIFICACION_CONTRATO.FLG_ACTIVO
	 * @param flgActivo  the value for MODIFICACION_CONTRATO.FLG_ACTIVO
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	public void setFlgActivo(Short flgActivo) {
		this.flgActivo = flgActivo;
	}

	/**
	 * @return the fechaFinRegistroContrato
	 */
	public Date getFechaFinRegistroContrato() {
		return fechaFinRegistroContrato;
	}

	/**
	 * @param fechaFinRegistroContrato the fechaFinRegistroContrato to set
	 */
	public void setFechaFinRegistroContrato(Date fechaFinRegistroContrato) {
		this.fechaFinRegistroContrato = fechaFinRegistroContrato;
	}

	/**
	 * @return the montoRegistroContrato
	 */
	public Integer getMontoRegistroContrato() {
		return montoRegistroContrato;
	}

	/**
	 * @param montoRegistroContrato the montoRegistroContrato to set
	 */
	public void setMontoRegistroContrato(Integer montoRegistroContrato) {
		this.montoRegistroContrato = montoRegistroContrato;
	}



	/**
	 * 
	 */
	private static final long serialVersionUID = -7599541673711373607L;

	/**
     * 
     */
    private int limitIni;
    /**
     * 
     */
    private int limitFin;

    /**
	 * @return the limitIni
	 */
	public int getLimitIni() {
		return limitIni;
	}

	/**
	 * @param limitIni the limitIni to set
	 */
	public void setLimitIni(int limitIni) {
		this.limitIni = limitIni;
	}

	/**
	 * @return the limitFin
	 */
	public int getLimitFin() {
		return limitFin;
	}

	/**
	 * @param limitFin the limitFin to set
	 */
	public void setLimitFin(int limitFin) {
		this.limitFin = limitFin;
	}
	
	
}