package co.gov.dafp.sigep2.bean;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ModificacionContratoExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table MODIFICACION_CONTRATO
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table MODIFICACION_CONTRATO
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table MODIFICACION_CONTRATO
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MODIFICACION_CONTRATO
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	public ModificacionContratoExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MODIFICACION_CONTRATO
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MODIFICACION_CONTRATO
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MODIFICACION_CONTRATO
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MODIFICACION_CONTRATO
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MODIFICACION_CONTRATO
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MODIFICACION_CONTRATO
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MODIFICACION_CONTRATO
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MODIFICACION_CONTRATO
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MODIFICACION_CONTRATO
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MODIFICACION_CONTRATO
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table MODIFICACION_CONTRATO
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andCodModificacionContratoIsNull() {
			addCriterion("COD_MODIFICACION_CONTRATO is null");
			return (Criteria) this;
		}

		public Criteria andCodModificacionContratoIsNotNull() {
			addCriterion("COD_MODIFICACION_CONTRATO is not null");
			return (Criteria) this;
		}

		public Criteria andCodModificacionContratoEqualTo(Long value) {
			addCriterion("COD_MODIFICACION_CONTRATO =", value, "codModificacionContrato");
			return (Criteria) this;
		}

		public Criteria andCodModificacionContratoNotEqualTo(Long value) {
			addCriterion("COD_MODIFICACION_CONTRATO <>", value, "codModificacionContrato");
			return (Criteria) this;
		}

		public Criteria andCodModificacionContratoGreaterThan(Long value) {
			addCriterion("COD_MODIFICACION_CONTRATO >", value, "codModificacionContrato");
			return (Criteria) this;
		}

		public Criteria andCodModificacionContratoGreaterThanOrEqualTo(Long value) {
			addCriterion("COD_MODIFICACION_CONTRATO >=", value, "codModificacionContrato");
			return (Criteria) this;
		}

		public Criteria andCodModificacionContratoLessThan(Long value) {
			addCriterion("COD_MODIFICACION_CONTRATO <", value, "codModificacionContrato");
			return (Criteria) this;
		}

		public Criteria andCodModificacionContratoLessThanOrEqualTo(Long value) {
			addCriterion("COD_MODIFICACION_CONTRATO <=", value, "codModificacionContrato");
			return (Criteria) this;
		}

		public Criteria andCodModificacionContratoIn(List<Long> values) {
			addCriterion("COD_MODIFICACION_CONTRATO in", values, "codModificacionContrato");
			return (Criteria) this;
		}

		public Criteria andCodModificacionContratoNotIn(List<Long> values) {
			addCriterion("COD_MODIFICACION_CONTRATO not in", values, "codModificacionContrato");
			return (Criteria) this;
		}

		public Criteria andCodModificacionContratoBetween(Long value1, Long value2) {
			addCriterion("COD_MODIFICACION_CONTRATO between", value1, value2, "codModificacionContrato");
			return (Criteria) this;
		}

		public Criteria andCodModificacionContratoNotBetween(Long value1, Long value2) {
			addCriterion("COD_MODIFICACION_CONTRATO not between", value1, value2, "codModificacionContrato");
			return (Criteria) this;
		}

		public Criteria andCodContratoIsNull() {
			addCriterion("COD_CONTRATO is null");
			return (Criteria) this;
		}

		public Criteria andCodContratoIsNotNull() {
			addCriterion("COD_CONTRATO is not null");
			return (Criteria) this;
		}

		public Criteria andCodContratoEqualTo(Long value) {
			addCriterion("COD_CONTRATO =", value, "codContrato");
			return (Criteria) this;
		}

		public Criteria andCodContratoNotEqualTo(Long value) {
			addCriterion("COD_CONTRATO <>", value, "codContrato");
			return (Criteria) this;
		}

		public Criteria andCodContratoGreaterThan(Long value) {
			addCriterion("COD_CONTRATO >", value, "codContrato");
			return (Criteria) this;
		}

		public Criteria andCodContratoGreaterThanOrEqualTo(Long value) {
			addCriterion("COD_CONTRATO >=", value, "codContrato");
			return (Criteria) this;
		}

		public Criteria andCodContratoLessThan(Long value) {
			addCriterion("COD_CONTRATO <", value, "codContrato");
			return (Criteria) this;
		}

		public Criteria andCodContratoLessThanOrEqualTo(Long value) {
			addCriterion("COD_CONTRATO <=", value, "codContrato");
			return (Criteria) this;
		}

		public Criteria andCodContratoIn(List<Long> values) {
			addCriterion("COD_CONTRATO in", values, "codContrato");
			return (Criteria) this;
		}

		public Criteria andCodContratoNotIn(List<Long> values) {
			addCriterion("COD_CONTRATO not in", values, "codContrato");
			return (Criteria) this;
		}

		public Criteria andCodContratoBetween(Long value1, Long value2) {
			addCriterion("COD_CONTRATO between", value1, value2, "codContrato");
			return (Criteria) this;
		}

		public Criteria andCodContratoNotBetween(Long value1, Long value2) {
			addCriterion("COD_CONTRATO not between", value1, value2, "codContrato");
			return (Criteria) this;
		}

		public Criteria andCodTipoModificacionContratoIsNull() {
			addCriterion("COD_TIPO_MODIFICACION_CONTRATO is null");
			return (Criteria) this;
		}

		public Criteria andCodTipoModificacionContratoIsNotNull() {
			addCriterion("COD_TIPO_MODIFICACION_CONTRATO is not null");
			return (Criteria) this;
		}

		public Criteria andCodTipoModificacionContratoEqualTo(Integer value) {
			addCriterion("COD_TIPO_MODIFICACION_CONTRATO =", value, "codTipoModificacionContrato");
			return (Criteria) this;
		}

		public Criteria andCodTipoModificacionContratoNotEqualTo(Integer value) {
			addCriterion("COD_TIPO_MODIFICACION_CONTRATO <>", value, "codTipoModificacionContrato");
			return (Criteria) this;
		}

		public Criteria andCodTipoModificacionContratoGreaterThan(Integer value) {
			addCriterion("COD_TIPO_MODIFICACION_CONTRATO >", value, "codTipoModificacionContrato");
			return (Criteria) this;
		}

		public Criteria andCodTipoModificacionContratoGreaterThanOrEqualTo(Integer value) {
			addCriterion("COD_TIPO_MODIFICACION_CONTRATO >=", value, "codTipoModificacionContrato");
			return (Criteria) this;
		}

		public Criteria andCodTipoModificacionContratoLessThan(Integer value) {
			addCriterion("COD_TIPO_MODIFICACION_CONTRATO <", value, "codTipoModificacionContrato");
			return (Criteria) this;
		}

		public Criteria andCodTipoModificacionContratoLessThanOrEqualTo(Integer value) {
			addCriterion("COD_TIPO_MODIFICACION_CONTRATO <=", value, "codTipoModificacionContrato");
			return (Criteria) this;
		}

		public Criteria andCodTipoModificacionContratoIn(List<Integer> values) {
			addCriterion("COD_TIPO_MODIFICACION_CONTRATO in", values, "codTipoModificacionContrato");
			return (Criteria) this;
		}

		public Criteria andCodTipoModificacionContratoNotIn(List<Integer> values) {
			addCriterion("COD_TIPO_MODIFICACION_CONTRATO not in", values, "codTipoModificacionContrato");
			return (Criteria) this;
		}

		public Criteria andCodTipoModificacionContratoBetween(Integer value1, Integer value2) {
			addCriterion("COD_TIPO_MODIFICACION_CONTRATO between", value1, value2, "codTipoModificacionContrato");
			return (Criteria) this;
		}

		public Criteria andCodTipoModificacionContratoNotBetween(Integer value1, Integer value2) {
			addCriterion("COD_TIPO_MODIFICACION_CONTRATO not between", value1, value2, "codTipoModificacionContrato");
			return (Criteria) this;
		}

		public Criteria andNuevoMontoContratoIsNull() {
			addCriterion("NUEVO_MONTO_CONTRATO is null");
			return (Criteria) this;
		}

		public Criteria andNuevoMontoContratoIsNotNull() {
			addCriterion("NUEVO_MONTO_CONTRATO is not null");
			return (Criteria) this;
		}

		public Criteria andNuevoMontoContratoEqualTo(BigDecimal value) {
			addCriterion("NUEVO_MONTO_CONTRATO =", value, "nuevoMontoContrato");
			return (Criteria) this;
		}

		public Criteria andNuevoMontoContratoNotEqualTo(BigDecimal value) {
			addCriterion("NUEVO_MONTO_CONTRATO <>", value, "nuevoMontoContrato");
			return (Criteria) this;
		}

		public Criteria andNuevoMontoContratoGreaterThan(BigDecimal value) {
			addCriterion("NUEVO_MONTO_CONTRATO >", value, "nuevoMontoContrato");
			return (Criteria) this;
		}

		public Criteria andNuevoMontoContratoGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("NUEVO_MONTO_CONTRATO >=", value, "nuevoMontoContrato");
			return (Criteria) this;
		}

		public Criteria andNuevoMontoContratoLessThan(BigDecimal value) {
			addCriterion("NUEVO_MONTO_CONTRATO <", value, "nuevoMontoContrato");
			return (Criteria) this;
		}

		public Criteria andNuevoMontoContratoLessThanOrEqualTo(BigDecimal value) {
			addCriterion("NUEVO_MONTO_CONTRATO <=", value, "nuevoMontoContrato");
			return (Criteria) this;
		}

		public Criteria andNuevoMontoContratoIn(List<BigDecimal> values) {
			addCriterion("NUEVO_MONTO_CONTRATO in", values, "nuevoMontoContrato");
			return (Criteria) this;
		}

		public Criteria andNuevoMontoContratoNotIn(List<BigDecimal> values) {
			addCriterion("NUEVO_MONTO_CONTRATO not in", values, "nuevoMontoContrato");
			return (Criteria) this;
		}

		public Criteria andNuevoMontoContratoBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("NUEVO_MONTO_CONTRATO between", value1, value2, "nuevoMontoContrato");
			return (Criteria) this;
		}

		public Criteria andNuevoMontoContratoNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("NUEVO_MONTO_CONTRATO not between", value1, value2, "nuevoMontoContrato");
			return (Criteria) this;
		}

		public Criteria andFechaInicioModificacionIsNull() {
			addCriterion("FECHA_INICIO_MODIFICACION is null");
			return (Criteria) this;
		}

		public Criteria andFechaInicioModificacionIsNotNull() {
			addCriterion("FECHA_INICIO_MODIFICACION is not null");
			return (Criteria) this;
		}

		public Criteria andFechaInicioModificacionEqualTo(Date value) {
			addCriterion("FECHA_INICIO_MODIFICACION =", value, "fechaInicioModificacion");
			return (Criteria) this;
		}

		public Criteria andFechaInicioModificacionNotEqualTo(Date value) {
			addCriterion("FECHA_INICIO_MODIFICACION <>", value, "fechaInicioModificacion");
			return (Criteria) this;
		}

		public Criteria andFechaInicioModificacionGreaterThan(Date value) {
			addCriterion("FECHA_INICIO_MODIFICACION >", value, "fechaInicioModificacion");
			return (Criteria) this;
		}

		public Criteria andFechaInicioModificacionGreaterThanOrEqualTo(Date value) {
			addCriterion("FECHA_INICIO_MODIFICACION >=", value, "fechaInicioModificacion");
			return (Criteria) this;
		}

		public Criteria andFechaInicioModificacionLessThan(Date value) {
			addCriterion("FECHA_INICIO_MODIFICACION <", value, "fechaInicioModificacion");
			return (Criteria) this;
		}

		public Criteria andFechaInicioModificacionLessThanOrEqualTo(Date value) {
			addCriterion("FECHA_INICIO_MODIFICACION <=", value, "fechaInicioModificacion");
			return (Criteria) this;
		}

		public Criteria andFechaInicioModificacionIn(List<Date> values) {
			addCriterion("FECHA_INICIO_MODIFICACION in", values, "fechaInicioModificacion");
			return (Criteria) this;
		}

		public Criteria andFechaInicioModificacionNotIn(List<Date> values) {
			addCriterion("FECHA_INICIO_MODIFICACION not in", values, "fechaInicioModificacion");
			return (Criteria) this;
		}

		public Criteria andFechaInicioModificacionBetween(Date value1, Date value2) {
			addCriterion("FECHA_INICIO_MODIFICACION between", value1, value2, "fechaInicioModificacion");
			return (Criteria) this;
		}

		public Criteria andFechaInicioModificacionNotBetween(Date value1, Date value2) {
			addCriterion("FECHA_INICIO_MODIFICACION not between", value1, value2, "fechaInicioModificacion");
			return (Criteria) this;
		}

		public Criteria andFechaFinModificacionIsNull() {
			addCriterion("FECHA_FIN_MODIFICACION is null");
			return (Criteria) this;
		}

		public Criteria andFechaFinModificacionIsNotNull() {
			addCriterion("FECHA_FIN_MODIFICACION is not null");
			return (Criteria) this;
		}

		public Criteria andFechaFinModificacionEqualTo(Date value) {
			addCriterion("FECHA_FIN_MODIFICACION =", value, "fechaFinModificacion");
			return (Criteria) this;
		}

		public Criteria andFechaFinModificacionNotEqualTo(Date value) {
			addCriterion("FECHA_FIN_MODIFICACION <>", value, "fechaFinModificacion");
			return (Criteria) this;
		}

		public Criteria andFechaFinModificacionGreaterThan(Date value) {
			addCriterion("FECHA_FIN_MODIFICACION >", value, "fechaFinModificacion");
			return (Criteria) this;
		}

		public Criteria andFechaFinModificacionGreaterThanOrEqualTo(Date value) {
			addCriterion("FECHA_FIN_MODIFICACION >=", value, "fechaFinModificacion");
			return (Criteria) this;
		}

		public Criteria andFechaFinModificacionLessThan(Date value) {
			addCriterion("FECHA_FIN_MODIFICACION <", value, "fechaFinModificacion");
			return (Criteria) this;
		}

		public Criteria andFechaFinModificacionLessThanOrEqualTo(Date value) {
			addCriterion("FECHA_FIN_MODIFICACION <=", value, "fechaFinModificacion");
			return (Criteria) this;
		}

		public Criteria andFechaFinModificacionIn(List<Date> values) {
			addCriterion("FECHA_FIN_MODIFICACION in", values, "fechaFinModificacion");
			return (Criteria) this;
		}

		public Criteria andFechaFinModificacionNotIn(List<Date> values) {
			addCriterion("FECHA_FIN_MODIFICACION not in", values, "fechaFinModificacion");
			return (Criteria) this;
		}

		public Criteria andFechaFinModificacionBetween(Date value1, Date value2) {
			addCriterion("FECHA_FIN_MODIFICACION between", value1, value2, "fechaFinModificacion");
			return (Criteria) this;
		}

		public Criteria andFechaFinModificacionNotBetween(Date value1, Date value2) {
			addCriterion("FECHA_FIN_MODIFICACION not between", value1, value2, "fechaFinModificacion");
			return (Criteria) this;
		}

		public Criteria andFechaAutorizacionModificacionIsNull() {
			addCriterion("FECHA_AUTORIZACION_MODIFICACION is null");
			return (Criteria) this;
		}

		public Criteria andFechaAutorizacionModificacionIsNotNull() {
			addCriterion("FECHA_AUTORIZACION_MODIFICACION is not null");
			return (Criteria) this;
		}

		public Criteria andFechaAutorizacionModificacionEqualTo(Date value) {
			addCriterion("FECHA_AUTORIZACION_MODIFICACION =", value, "fechaAutorizacionModificacion");
			return (Criteria) this;
		}

		public Criteria andFechaAutorizacionModificacionNotEqualTo(Date value) {
			addCriterion("FECHA_AUTORIZACION_MODIFICACION <>", value, "fechaAutorizacionModificacion");
			return (Criteria) this;
		}

		public Criteria andFechaAutorizacionModificacionGreaterThan(Date value) {
			addCriterion("FECHA_AUTORIZACION_MODIFICACION >", value, "fechaAutorizacionModificacion");
			return (Criteria) this;
		}

		public Criteria andFechaAutorizacionModificacionGreaterThanOrEqualTo(Date value) {
			addCriterion("FECHA_AUTORIZACION_MODIFICACION >=", value, "fechaAutorizacionModificacion");
			return (Criteria) this;
		}

		public Criteria andFechaAutorizacionModificacionLessThan(Date value) {
			addCriterion("FECHA_AUTORIZACION_MODIFICACION <", value, "fechaAutorizacionModificacion");
			return (Criteria) this;
		}

		public Criteria andFechaAutorizacionModificacionLessThanOrEqualTo(Date value) {
			addCriterion("FECHA_AUTORIZACION_MODIFICACION <=", value, "fechaAutorizacionModificacion");
			return (Criteria) this;
		}

		public Criteria andFechaAutorizacionModificacionIn(List<Date> values) {
			addCriterion("FECHA_AUTORIZACION_MODIFICACION in", values, "fechaAutorizacionModificacion");
			return (Criteria) this;
		}

		public Criteria andFechaAutorizacionModificacionNotIn(List<Date> values) {
			addCriterion("FECHA_AUTORIZACION_MODIFICACION not in", values, "fechaAutorizacionModificacion");
			return (Criteria) this;
		}

		public Criteria andFechaAutorizacionModificacionBetween(Date value1, Date value2) {
			addCriterion("FECHA_AUTORIZACION_MODIFICACION between", value1, value2, "fechaAutorizacionModificacion");
			return (Criteria) this;
		}

		public Criteria andFechaAutorizacionModificacionNotBetween(Date value1, Date value2) {
			addCriterion("FECHA_AUTORIZACION_MODIFICACION not between", value1, value2,
					"fechaAutorizacionModificacion");
			return (Criteria) this;
		}

		public Criteria andJustificacionModificacionIsNull() {
			addCriterion("JUSTIFICACION_MODIFICACION is null");
			return (Criteria) this;
		}

		public Criteria andJustificacionModificacionIsNotNull() {
			addCriterion("JUSTIFICACION_MODIFICACION is not null");
			return (Criteria) this;
		}

		public Criteria andJustificacionModificacionEqualTo(String value) {
			addCriterion("JUSTIFICACION_MODIFICACION =", value, "justificacionModificacion");
			return (Criteria) this;
		}

		public Criteria andJustificacionModificacionNotEqualTo(String value) {
			addCriterion("JUSTIFICACION_MODIFICACION <>", value, "justificacionModificacion");
			return (Criteria) this;
		}

		public Criteria andJustificacionModificacionGreaterThan(String value) {
			addCriterion("JUSTIFICACION_MODIFICACION >", value, "justificacionModificacion");
			return (Criteria) this;
		}

		public Criteria andJustificacionModificacionGreaterThanOrEqualTo(String value) {
			addCriterion("JUSTIFICACION_MODIFICACION >=", value, "justificacionModificacion");
			return (Criteria) this;
		}

		public Criteria andJustificacionModificacionLessThan(String value) {
			addCriterion("JUSTIFICACION_MODIFICACION <", value, "justificacionModificacion");
			return (Criteria) this;
		}

		public Criteria andJustificacionModificacionLessThanOrEqualTo(String value) {
			addCriterion("JUSTIFICACION_MODIFICACION <=", value, "justificacionModificacion");
			return (Criteria) this;
		}

		public Criteria andJustificacionModificacionLike(String value) {
			addCriterion("JUSTIFICACION_MODIFICACION like", value, "justificacionModificacion");
			return (Criteria) this;
		}

		public Criteria andJustificacionModificacionNotLike(String value) {
			addCriterion("JUSTIFICACION_MODIFICACION not like", value, "justificacionModificacion");
			return (Criteria) this;
		}

		public Criteria andJustificacionModificacionIn(List<String> values) {
			addCriterion("JUSTIFICACION_MODIFICACION in", values, "justificacionModificacion");
			return (Criteria) this;
		}

		public Criteria andJustificacionModificacionNotIn(List<String> values) {
			addCriterion("JUSTIFICACION_MODIFICACION not in", values, "justificacionModificacion");
			return (Criteria) this;
		}

		public Criteria andJustificacionModificacionBetween(String value1, String value2) {
			addCriterion("JUSTIFICACION_MODIFICACION between", value1, value2, "justificacionModificacion");
			return (Criteria) this;
		}

		public Criteria andJustificacionModificacionNotBetween(String value1, String value2) {
			addCriterion("JUSTIFICACION_MODIFICACION not between", value1, value2, "justificacionModificacion");
			return (Criteria) this;
		}

		public Criteria andValorAdicionIsNull() {
			addCriterion("VALOR_ADICION is null");
			return (Criteria) this;
		}

		public Criteria andValorAdicionIsNotNull() {
			addCriterion("VALOR_ADICION is not null");
			return (Criteria) this;
		}

		public Criteria andValorAdicionEqualTo(BigDecimal value) {
			addCriterion("VALOR_ADICION =", value, "valorAdicion");
			return (Criteria) this;
		}

		public Criteria andValorAdicionNotEqualTo(BigDecimal value) {
			addCriterion("VALOR_ADICION <>", value, "valorAdicion");
			return (Criteria) this;
		}

		public Criteria andValorAdicionGreaterThan(BigDecimal value) {
			addCriterion("VALOR_ADICION >", value, "valorAdicion");
			return (Criteria) this;
		}

		public Criteria andValorAdicionGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("VALOR_ADICION >=", value, "valorAdicion");
			return (Criteria) this;
		}

		public Criteria andValorAdicionLessThan(BigDecimal value) {
			addCriterion("VALOR_ADICION <", value, "valorAdicion");
			return (Criteria) this;
		}

		public Criteria andValorAdicionLessThanOrEqualTo(BigDecimal value) {
			addCriterion("VALOR_ADICION <=", value, "valorAdicion");
			return (Criteria) this;
		}

		public Criteria andValorAdicionIn(List<BigDecimal> values) {
			addCriterion("VALOR_ADICION in", values, "valorAdicion");
			return (Criteria) this;
		}

		public Criteria andValorAdicionNotIn(List<BigDecimal> values) {
			addCriterion("VALOR_ADICION not in", values, "valorAdicion");
			return (Criteria) this;
		}

		public Criteria andValorAdicionBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("VALOR_ADICION between", value1, value2, "valorAdicion");
			return (Criteria) this;
		}

		public Criteria andValorAdicionNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("VALOR_ADICION not between", value1, value2, "valorAdicion");
			return (Criteria) this;
		}

		public Criteria andNuevoAlcanceContratoIsNull() {
			addCriterion("NUEVO_ALCANCE_CONTRATO is null");
			return (Criteria) this;
		}

		public Criteria andNuevoAlcanceContratoIsNotNull() {
			addCriterion("NUEVO_ALCANCE_CONTRATO is not null");
			return (Criteria) this;
		}

		public Criteria andNuevoAlcanceContratoEqualTo(String value) {
			addCriterion("NUEVO_ALCANCE_CONTRATO =", value, "nuevoAlcanceContrato");
			return (Criteria) this;
		}

		public Criteria andNuevoAlcanceContratoNotEqualTo(String value) {
			addCriterion("NUEVO_ALCANCE_CONTRATO <>", value, "nuevoAlcanceContrato");
			return (Criteria) this;
		}

		public Criteria andNuevoAlcanceContratoGreaterThan(String value) {
			addCriterion("NUEVO_ALCANCE_CONTRATO >", value, "nuevoAlcanceContrato");
			return (Criteria) this;
		}

		public Criteria andNuevoAlcanceContratoGreaterThanOrEqualTo(String value) {
			addCriterion("NUEVO_ALCANCE_CONTRATO >=", value, "nuevoAlcanceContrato");
			return (Criteria) this;
		}

		public Criteria andNuevoAlcanceContratoLessThan(String value) {
			addCriterion("NUEVO_ALCANCE_CONTRATO <", value, "nuevoAlcanceContrato");
			return (Criteria) this;
		}

		public Criteria andNuevoAlcanceContratoLessThanOrEqualTo(String value) {
			addCriterion("NUEVO_ALCANCE_CONTRATO <=", value, "nuevoAlcanceContrato");
			return (Criteria) this;
		}

		public Criteria andNuevoAlcanceContratoLike(String value) {
			addCriterion("NUEVO_ALCANCE_CONTRATO like", value, "nuevoAlcanceContrato");
			return (Criteria) this;
		}

		public Criteria andNuevoAlcanceContratoNotLike(String value) {
			addCriterion("NUEVO_ALCANCE_CONTRATO not like", value, "nuevoAlcanceContrato");
			return (Criteria) this;
		}

		public Criteria andNuevoAlcanceContratoIn(List<String> values) {
			addCriterion("NUEVO_ALCANCE_CONTRATO in", values, "nuevoAlcanceContrato");
			return (Criteria) this;
		}

		public Criteria andNuevoAlcanceContratoNotIn(List<String> values) {
			addCriterion("NUEVO_ALCANCE_CONTRATO not in", values, "nuevoAlcanceContrato");
			return (Criteria) this;
		}

		public Criteria andNuevoAlcanceContratoBetween(String value1, String value2) {
			addCriterion("NUEVO_ALCANCE_CONTRATO between", value1, value2, "nuevoAlcanceContrato");
			return (Criteria) this;
		}

		public Criteria andNuevoAlcanceContratoNotBetween(String value1, String value2) {
			addCriterion("NUEVO_ALCANCE_CONTRATO not between", value1, value2, "nuevoAlcanceContrato");
			return (Criteria) this;
		}

		public Criteria andCodMotivoSuspencionIsNull() {
			addCriterion("COD_MOTIVO_SUSPENCION is null");
			return (Criteria) this;
		}

		public Criteria andCodMotivoSuspencionIsNotNull() {
			addCriterion("COD_MOTIVO_SUSPENCION is not null");
			return (Criteria) this;
		}

		public Criteria andCodMotivoSuspencionEqualTo(Integer value) {
			addCriterion("COD_MOTIVO_SUSPENCION =", value, "codMotivoSuspencion");
			return (Criteria) this;
		}

		public Criteria andCodMotivoSuspencionNotEqualTo(Integer value) {
			addCriterion("COD_MOTIVO_SUSPENCION <>", value, "codMotivoSuspencion");
			return (Criteria) this;
		}

		public Criteria andCodMotivoSuspencionGreaterThan(Integer value) {
			addCriterion("COD_MOTIVO_SUSPENCION >", value, "codMotivoSuspencion");
			return (Criteria) this;
		}

		public Criteria andCodMotivoSuspencionGreaterThanOrEqualTo(Integer value) {
			addCriterion("COD_MOTIVO_SUSPENCION >=", value, "codMotivoSuspencion");
			return (Criteria) this;
		}

		public Criteria andCodMotivoSuspencionLessThan(Integer value) {
			addCriterion("COD_MOTIVO_SUSPENCION <", value, "codMotivoSuspencion");
			return (Criteria) this;
		}

		public Criteria andCodMotivoSuspencionLessThanOrEqualTo(Integer value) {
			addCriterion("COD_MOTIVO_SUSPENCION <=", value, "codMotivoSuspencion");
			return (Criteria) this;
		}

		public Criteria andCodMotivoSuspencionIn(List<Integer> values) {
			addCriterion("COD_MOTIVO_SUSPENCION in", values, "codMotivoSuspencion");
			return (Criteria) this;
		}

		public Criteria andCodMotivoSuspencionNotIn(List<Integer> values) {
			addCriterion("COD_MOTIVO_SUSPENCION not in", values, "codMotivoSuspencion");
			return (Criteria) this;
		}

		public Criteria andCodMotivoSuspencionBetween(Integer value1, Integer value2) {
			addCriterion("COD_MOTIVO_SUSPENCION between", value1, value2, "codMotivoSuspencion");
			return (Criteria) this;
		}

		public Criteria andCodMotivoSuspencionNotBetween(Integer value1, Integer value2) {
			addCriterion("COD_MOTIVO_SUSPENCION not between", value1, value2, "codMotivoSuspencion");
			return (Criteria) this;
		}

		public Criteria andCodContratistaInicialIsNull() {
			addCriterion("COD_CONTRATISTA_INICIAL is null");
			return (Criteria) this;
		}

		public Criteria andCodContratistaInicialIsNotNull() {
			addCriterion("COD_CONTRATISTA_INICIAL is not null");
			return (Criteria) this;
		}

		public Criteria andCodContratistaInicialEqualTo(Long value) {
			addCriterion("COD_CONTRATISTA_INICIAL =", value, "codContratistaInicial");
			return (Criteria) this;
		}

		public Criteria andCodContratistaInicialNotEqualTo(Long value) {
			addCriterion("COD_CONTRATISTA_INICIAL <>", value, "codContratistaInicial");
			return (Criteria) this;
		}

		public Criteria andCodContratistaInicialGreaterThan(Long value) {
			addCriterion("COD_CONTRATISTA_INICIAL >", value, "codContratistaInicial");
			return (Criteria) this;
		}

		public Criteria andCodContratistaInicialGreaterThanOrEqualTo(Long value) {
			addCriterion("COD_CONTRATISTA_INICIAL >=", value, "codContratistaInicial");
			return (Criteria) this;
		}

		public Criteria andCodContratistaInicialLessThan(Long value) {
			addCriterion("COD_CONTRATISTA_INICIAL <", value, "codContratistaInicial");
			return (Criteria) this;
		}

		public Criteria andCodContratistaInicialLessThanOrEqualTo(Long value) {
			addCriterion("COD_CONTRATISTA_INICIAL <=", value, "codContratistaInicial");
			return (Criteria) this;
		}

		public Criteria andCodContratistaInicialIn(List<Long> values) {
			addCriterion("COD_CONTRATISTA_INICIAL in", values, "codContratistaInicial");
			return (Criteria) this;
		}

		public Criteria andCodContratistaInicialNotIn(List<Long> values) {
			addCriterion("COD_CONTRATISTA_INICIAL not in", values, "codContratistaInicial");
			return (Criteria) this;
		}

		public Criteria andCodContratistaInicialBetween(Long value1, Long value2) {
			addCriterion("COD_CONTRATISTA_INICIAL between", value1, value2, "codContratistaInicial");
			return (Criteria) this;
		}

		public Criteria andCodContratistaInicialNotBetween(Long value1, Long value2) {
			addCriterion("COD_CONTRATISTA_INICIAL not between", value1, value2, "codContratistaInicial");
			return (Criteria) this;
		}

		public Criteria andCodNuevoContratistaIsNull() {
			addCriterion("COD_NUEVO_CONTRATISTA is null");
			return (Criteria) this;
		}

		public Criteria andCodNuevoContratistaIsNotNull() {
			addCriterion("COD_NUEVO_CONTRATISTA is not null");
			return (Criteria) this;
		}

		public Criteria andCodNuevoContratistaEqualTo(Long value) {
			addCriterion("COD_NUEVO_CONTRATISTA =", value, "codNuevoContratista");
			return (Criteria) this;
		}

		public Criteria andCodNuevoContratistaNotEqualTo(Long value) {
			addCriterion("COD_NUEVO_CONTRATISTA <>", value, "codNuevoContratista");
			return (Criteria) this;
		}

		public Criteria andCodNuevoContratistaGreaterThan(Long value) {
			addCriterion("COD_NUEVO_CONTRATISTA >", value, "codNuevoContratista");
			return (Criteria) this;
		}

		public Criteria andCodNuevoContratistaGreaterThanOrEqualTo(Long value) {
			addCriterion("COD_NUEVO_CONTRATISTA >=", value, "codNuevoContratista");
			return (Criteria) this;
		}

		public Criteria andCodNuevoContratistaLessThan(Long value) {
			addCriterion("COD_NUEVO_CONTRATISTA <", value, "codNuevoContratista");
			return (Criteria) this;
		}

		public Criteria andCodNuevoContratistaLessThanOrEqualTo(Long value) {
			addCriterion("COD_NUEVO_CONTRATISTA <=", value, "codNuevoContratista");
			return (Criteria) this;
		}

		public Criteria andCodNuevoContratistaIn(List<Long> values) {
			addCriterion("COD_NUEVO_CONTRATISTA in", values, "codNuevoContratista");
			return (Criteria) this;
		}

		public Criteria andCodNuevoContratistaNotIn(List<Long> values) {
			addCriterion("COD_NUEVO_CONTRATISTA not in", values, "codNuevoContratista");
			return (Criteria) this;
		}

		public Criteria andCodNuevoContratistaBetween(Long value1, Long value2) {
			addCriterion("COD_NUEVO_CONTRATISTA between", value1, value2, "codNuevoContratista");
			return (Criteria) this;
		}

		public Criteria andCodNuevoContratistaNotBetween(Long value1, Long value2) {
			addCriterion("COD_NUEVO_CONTRATISTA not between", value1, value2, "codNuevoContratista");
			return (Criteria) this;
		}

		public Criteria andCodNuevoSupervisorIsNull() {
			addCriterion("COD_NUEVO_SUPERVISOR is null");
			return (Criteria) this;
		}

		public Criteria andCodNuevoSupervisorIsNotNull() {
			addCriterion("COD_NUEVO_SUPERVISOR is not null");
			return (Criteria) this;
		}

		public Criteria andCodNuevoSupervisorEqualTo(BigDecimal value) {
			addCriterion("COD_NUEVO_SUPERVISOR =", value, "codNuevoSupervisor");
			return (Criteria) this;
		}

		public Criteria andCodNuevoSupervisorNotEqualTo(BigDecimal value) {
			addCriterion("COD_NUEVO_SUPERVISOR <>", value, "codNuevoSupervisor");
			return (Criteria) this;
		}

		public Criteria andCodNuevoSupervisorGreaterThan(BigDecimal value) {
			addCriterion("COD_NUEVO_SUPERVISOR >", value, "codNuevoSupervisor");
			return (Criteria) this;
		}

		public Criteria andCodNuevoSupervisorGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("COD_NUEVO_SUPERVISOR >=", value, "codNuevoSupervisor");
			return (Criteria) this;
		}

		public Criteria andCodNuevoSupervisorLessThan(BigDecimal value) {
			addCriterion("COD_NUEVO_SUPERVISOR <", value, "codNuevoSupervisor");
			return (Criteria) this;
		}

		public Criteria andCodNuevoSupervisorLessThanOrEqualTo(BigDecimal value) {
			addCriterion("COD_NUEVO_SUPERVISOR <=", value, "codNuevoSupervisor");
			return (Criteria) this;
		}

		public Criteria andCodNuevoSupervisorIn(List<BigDecimal> values) {
			addCriterion("COD_NUEVO_SUPERVISOR in", values, "codNuevoSupervisor");
			return (Criteria) this;
		}

		public Criteria andCodNuevoSupervisorNotIn(List<BigDecimal> values) {
			addCriterion("COD_NUEVO_SUPERVISOR not in", values, "codNuevoSupervisor");
			return (Criteria) this;
		}

		public Criteria andCodNuevoSupervisorBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("COD_NUEVO_SUPERVISOR between", value1, value2, "codNuevoSupervisor");
			return (Criteria) this;
		}

		public Criteria andCodNuevoSupervisorNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("COD_NUEVO_SUPERVISOR not between", value1, value2, "codNuevoSupervisor");
			return (Criteria) this;
		}

		public Criteria andAudFechaActualizacionIsNull() {
			addCriterion("AUD_FECHA_ACTUALIZACION is null");
			return (Criteria) this;
		}

		public Criteria andAudFechaActualizacionIsNotNull() {
			addCriterion("AUD_FECHA_ACTUALIZACION is not null");
			return (Criteria) this;
		}

		public Criteria andAudFechaActualizacionEqualTo(Date value) {
			addCriterion("AUD_FECHA_ACTUALIZACION =", value, "audFechaActualizacion");
			return (Criteria) this;
		}

		public Criteria andAudFechaActualizacionNotEqualTo(Date value) {
			addCriterion("AUD_FECHA_ACTUALIZACION <>", value, "audFechaActualizacion");
			return (Criteria) this;
		}

		public Criteria andAudFechaActualizacionGreaterThan(Date value) {
			addCriterion("AUD_FECHA_ACTUALIZACION >", value, "audFechaActualizacion");
			return (Criteria) this;
		}

		public Criteria andAudFechaActualizacionGreaterThanOrEqualTo(Date value) {
			addCriterion("AUD_FECHA_ACTUALIZACION >=", value, "audFechaActualizacion");
			return (Criteria) this;
		}

		public Criteria andAudFechaActualizacionLessThan(Date value) {
			addCriterion("AUD_FECHA_ACTUALIZACION <", value, "audFechaActualizacion");
			return (Criteria) this;
		}

		public Criteria andAudFechaActualizacionLessThanOrEqualTo(Date value) {
			addCriterion("AUD_FECHA_ACTUALIZACION <=", value, "audFechaActualizacion");
			return (Criteria) this;
		}

		public Criteria andAudFechaActualizacionIn(List<Date> values) {
			addCriterion("AUD_FECHA_ACTUALIZACION in", values, "audFechaActualizacion");
			return (Criteria) this;
		}

		public Criteria andAudFechaActualizacionNotIn(List<Date> values) {
			addCriterion("AUD_FECHA_ACTUALIZACION not in", values, "audFechaActualizacion");
			return (Criteria) this;
		}

		public Criteria andAudFechaActualizacionBetween(Date value1, Date value2) {
			addCriterion("AUD_FECHA_ACTUALIZACION between", value1, value2, "audFechaActualizacion");
			return (Criteria) this;
		}

		public Criteria andAudFechaActualizacionNotBetween(Date value1, Date value2) {
			addCriterion("AUD_FECHA_ACTUALIZACION not between", value1, value2, "audFechaActualizacion");
			return (Criteria) this;
		}

		public Criteria andAudCodUsuarioIsNull() {
			addCriterion("AUD_COD_USUARIO is null");
			return (Criteria) this;
		}

		public Criteria andAudCodUsuarioIsNotNull() {
			addCriterion("AUD_COD_USUARIO is not null");
			return (Criteria) this;
		}

		public Criteria andAudCodUsuarioEqualTo(BigDecimal value) {
			addCriterion("AUD_COD_USUARIO =", value, "audCodUsuario");
			return (Criteria) this;
		}

		public Criteria andAudCodUsuarioNotEqualTo(BigDecimal value) {
			addCriterion("AUD_COD_USUARIO <>", value, "audCodUsuario");
			return (Criteria) this;
		}

		public Criteria andAudCodUsuarioGreaterThan(BigDecimal value) {
			addCriterion("AUD_COD_USUARIO >", value, "audCodUsuario");
			return (Criteria) this;
		}

		public Criteria andAudCodUsuarioGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("AUD_COD_USUARIO >=", value, "audCodUsuario");
			return (Criteria) this;
		}

		public Criteria andAudCodUsuarioLessThan(BigDecimal value) {
			addCriterion("AUD_COD_USUARIO <", value, "audCodUsuario");
			return (Criteria) this;
		}

		public Criteria andAudCodUsuarioLessThanOrEqualTo(BigDecimal value) {
			addCriterion("AUD_COD_USUARIO <=", value, "audCodUsuario");
			return (Criteria) this;
		}

		public Criteria andAudCodUsuarioIn(List<BigDecimal> values) {
			addCriterion("AUD_COD_USUARIO in", values, "audCodUsuario");
			return (Criteria) this;
		}

		public Criteria andAudCodUsuarioNotIn(List<BigDecimal> values) {
			addCriterion("AUD_COD_USUARIO not in", values, "audCodUsuario");
			return (Criteria) this;
		}

		public Criteria andAudCodUsuarioBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("AUD_COD_USUARIO between", value1, value2, "audCodUsuario");
			return (Criteria) this;
		}

		public Criteria andAudCodUsuarioNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("AUD_COD_USUARIO not between", value1, value2, "audCodUsuario");
			return (Criteria) this;
		}

		public Criteria andAudCodRolIsNull() {
			addCriterion("AUD_COD_ROL is null");
			return (Criteria) this;
		}

		public Criteria andAudCodRolIsNotNull() {
			addCriterion("AUD_COD_ROL is not null");
			return (Criteria) this;
		}

		public Criteria andAudCodRolEqualTo(Integer value) {
			addCriterion("AUD_COD_ROL =", value, "audCodRol");
			return (Criteria) this;
		}

		public Criteria andAudCodRolNotEqualTo(Integer value) {
			addCriterion("AUD_COD_ROL <>", value, "audCodRol");
			return (Criteria) this;
		}

		public Criteria andAudCodRolGreaterThan(Integer value) {
			addCriterion("AUD_COD_ROL >", value, "audCodRol");
			return (Criteria) this;
		}

		public Criteria andAudCodRolGreaterThanOrEqualTo(Integer value) {
			addCriterion("AUD_COD_ROL >=", value, "audCodRol");
			return (Criteria) this;
		}

		public Criteria andAudCodRolLessThan(Integer value) {
			addCriterion("AUD_COD_ROL <", value, "audCodRol");
			return (Criteria) this;
		}

		public Criteria andAudCodRolLessThanOrEqualTo(Integer value) {
			addCriterion("AUD_COD_ROL <=", value, "audCodRol");
			return (Criteria) this;
		}

		public Criteria andAudCodRolIn(List<Integer> values) {
			addCriterion("AUD_COD_ROL in", values, "audCodRol");
			return (Criteria) this;
		}

		public Criteria andAudCodRolNotIn(List<Integer> values) {
			addCriterion("AUD_COD_ROL not in", values, "audCodRol");
			return (Criteria) this;
		}

		public Criteria andAudCodRolBetween(Integer value1, Integer value2) {
			addCriterion("AUD_COD_ROL between", value1, value2, "audCodRol");
			return (Criteria) this;
		}

		public Criteria andAudCodRolNotBetween(Integer value1, Integer value2) {
			addCriterion("AUD_COD_ROL not between", value1, value2, "audCodRol");
			return (Criteria) this;
		}

		public Criteria andAudAccionIsNull() {
			addCriterion("AUD_ACCION is null");
			return (Criteria) this;
		}

		public Criteria andAudAccionIsNotNull() {
			addCriterion("AUD_ACCION is not null");
			return (Criteria) this;
		}

		public Criteria andAudAccionEqualTo(Integer value) {
			addCriterion("AUD_ACCION =", value, "audAccion");
			return (Criteria) this;
		}

		public Criteria andAudAccionNotEqualTo(Integer value) {
			addCriterion("AUD_ACCION <>", value, "audAccion");
			return (Criteria) this;
		}

		public Criteria andAudAccionGreaterThan(Integer value) {
			addCriterion("AUD_ACCION >", value, "audAccion");
			return (Criteria) this;
		}

		public Criteria andAudAccionGreaterThanOrEqualTo(Integer value) {
			addCriterion("AUD_ACCION >=", value, "audAccion");
			return (Criteria) this;
		}

		public Criteria andAudAccionLessThan(Integer value) {
			addCriterion("AUD_ACCION <", value, "audAccion");
			return (Criteria) this;
		}

		public Criteria andAudAccionLessThanOrEqualTo(Integer value) {
			addCriterion("AUD_ACCION <=", value, "audAccion");
			return (Criteria) this;
		}

		public Criteria andAudAccionIn(List<Integer> values) {
			addCriterion("AUD_ACCION in", values, "audAccion");
			return (Criteria) this;
		}

		public Criteria andAudAccionNotIn(List<Integer> values) {
			addCriterion("AUD_ACCION not in", values, "audAccion");
			return (Criteria) this;
		}

		public Criteria andAudAccionBetween(Integer value1, Integer value2) {
			addCriterion("AUD_ACCION between", value1, value2, "audAccion");
			return (Criteria) this;
		}

		public Criteria andAudAccionNotBetween(Integer value1, Integer value2) {
			addCriterion("AUD_ACCION not between", value1, value2, "audAccion");
			return (Criteria) this;
		}

		public Criteria andFlgActivoIsNull() {
			addCriterion("FLG_ACTIVO is null");
			return (Criteria) this;
		}

		public Criteria andFlgActivoIsNotNull() {
			addCriterion("FLG_ACTIVO is not null");
			return (Criteria) this;
		}

		public Criteria andFlgActivoEqualTo(Short value) {
			addCriterion("FLG_ACTIVO =", value, "flgActivo");
			return (Criteria) this;
		}

		public Criteria andFlgActivoNotEqualTo(Short value) {
			addCriterion("FLG_ACTIVO <>", value, "flgActivo");
			return (Criteria) this;
		}

		public Criteria andFlgActivoGreaterThan(Short value) {
			addCriterion("FLG_ACTIVO >", value, "flgActivo");
			return (Criteria) this;
		}

		public Criteria andFlgActivoGreaterThanOrEqualTo(Short value) {
			addCriterion("FLG_ACTIVO >=", value, "flgActivo");
			return (Criteria) this;
		}

		public Criteria andFlgActivoLessThan(Short value) {
			addCriterion("FLG_ACTIVO <", value, "flgActivo");
			return (Criteria) this;
		}

		public Criteria andFlgActivoLessThanOrEqualTo(Short value) {
			addCriterion("FLG_ACTIVO <=", value, "flgActivo");
			return (Criteria) this;
		}

		public Criteria andFlgActivoIn(List<Short> values) {
			addCriterion("FLG_ACTIVO in", values, "flgActivo");
			return (Criteria) this;
		}

		public Criteria andFlgActivoNotIn(List<Short> values) {
			addCriterion("FLG_ACTIVO not in", values, "flgActivo");
			return (Criteria) this;
		}

		public Criteria andFlgActivoBetween(Short value1, Short value2) {
			addCriterion("FLG_ACTIVO between", value1, value2, "flgActivo");
			return (Criteria) this;
		}

		public Criteria andFlgActivoNotBetween(Short value1, Short value2) {
			addCriterion("FLG_ACTIVO not between", value1, value2, "flgActivo");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table MODIFICACION_CONTRATO
	 * @mbg.generated  Mon Apr 02 07:22:35 COT 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MODIFICACION_CONTRATO
     *
     * @mbg.generated do_not_delete_during_merge Tue Mar 13 07:24:43 COT 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}