package co.gov.dafp.sigep2.bean;

import java.math.BigDecimal;
import java.util.Date;

import co.gov.dafp.sigep2.utils.ErrorMensajes;

public class ModificacionSituacionAdministrativa extends ErrorMensajes{
    /**
	 * 
	 */
	private static final long serialVersionUID = 634669634083175765L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MODIFICACION_SITUACION_ADMINISTRATIVA.COD_MODIFICACION
     *
     * @mbg.generated Mon Apr 30 14:47:40 COT 2018
     */
    private Long codModificacion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MODIFICACION_SITUACION_ADMINISTRATIVA.COD_SITUACION_ADMINISTRATIVA_VINCULACION
     *
     * @mbg.generated Mon Apr 30 14:47:40 COT 2018
     */
    private Long codSituacionAdministrativaVinculacion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MODIFICACION_SITUACION_ADMINISTRATIVA.FECHA_INICIAL_PRORROGA
     *
     * @mbg.generated Mon Apr 30 14:47:40 COT 2018
     */
    private Date fechaInicialProrroga;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MODIFICACION_SITUACION_ADMINISTRATIVA.FECHA_FIN_PRORROGA
     *
     * @mbg.generated Mon Apr 30 14:47:40 COT 2018
     */
    private Date fechaFinProrroga;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MODIFICACION_SITUACION_ADMINISTRATIVA.DESCRIPCION_MODIFICACION
     *
     * @mbg.generated Mon Apr 30 14:47:40 COT 2018
     */
    private String descripcionModificacion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MODIFICACION_SITUACION_ADMINISTRATIVA.FECHA_INGRESO_PRORROGA
     *
     * @mbg.generated Mon Apr 30 14:47:40 COT 2018
     */
    private Date fechaIngresoProrroga;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MODIFICACION_SITUACION_ADMINISTRATIVA.USUARIO_PRORROGA
     *
     * @mbg.generated Mon Apr 30 14:47:40 COT 2018
     */
    private Long usuarioProrroga;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MODIFICACION_SITUACION_ADMINISTRATIVA.AUD_FECHA_MODIFICACION
     *
     * @mbg.generated Mon Apr 30 14:47:40 COT 2018
     */
    private Date audFechaModificacion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MODIFICACION_SITUACION_ADMINISTRATIVA.AUD_COD_USUARIO
     *
     * @mbg.generated Mon Apr 30 14:47:40 COT 2018
     */
    private BigDecimal audCodUsuario;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MODIFICACION_SITUACION_ADMINISTRATIVA.AUD_COD_ROL
     *
     * @mbg.generated Mon Apr 30 14:47:40 COT 2018
     */
    private Integer audCodRol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MODIFICACION_SITUACION_ADMINISTRATIVA.AUD_ACCION
     *
     * @mbg.generated Mon Apr 30 14:47:40 COT 2018
     */
    private Integer audAccion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MODIFICACION_SITUACION_ADMINISTRATIVA.COD_MODIFICACION
     *
     * @return the value of MODIFICACION_SITUACION_ADMINISTRATIVA.COD_MODIFICACION
     *
     * @mbg.generated Mon Apr 30 14:47:40 COT 2018
     */
    
    

	private int limitInit;
    
    
    private int limitEnd;
    
    public Long getCodModificacion() {
        return codModificacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MODIFICACION_SITUACION_ADMINISTRATIVA.COD_MODIFICACION
     *
     * @param codModificacion the value for MODIFICACION_SITUACION_ADMINISTRATIVA.COD_MODIFICACION
     *
     * @mbg.generated Mon Apr 30 14:47:40 COT 2018
     */
    public void setCodModificacion(Long codModificacion) {
        this.codModificacion = codModificacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MODIFICACION_SITUACION_ADMINISTRATIVA.COD_SITUACION_ADMINISTRATIVA_VINCULACION
     *
     * @return the value of MODIFICACION_SITUACION_ADMINISTRATIVA.COD_SITUACION_ADMINISTRATIVA_VINCULACION
     *
     * @mbg.generated Mon Apr 30 14:47:40 COT 2018
     */
    public Long getCodSituacionAdministrativaVinculacion() {
        return codSituacionAdministrativaVinculacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MODIFICACION_SITUACION_ADMINISTRATIVA.COD_SITUACION_ADMINISTRATIVA_VINCULACION
     *
     * @param codSituacionAdministrativaVinculacion the value for MODIFICACION_SITUACION_ADMINISTRATIVA.COD_SITUACION_ADMINISTRATIVA_VINCULACION
     *
     * @mbg.generated Mon Apr 30 14:47:40 COT 2018
     */
    public void setCodSituacionAdministrativaVinculacion(Long codSituacionAdministrativaVinculacion) {
        this.codSituacionAdministrativaVinculacion = codSituacionAdministrativaVinculacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MODIFICACION_SITUACION_ADMINISTRATIVA.FECHA_INICIAL_PRORROGA
     *
     * @return the value of MODIFICACION_SITUACION_ADMINISTRATIVA.FECHA_INICIAL_PRORROGA
     *
     * @mbg.generated Mon Apr 30 14:47:40 COT 2018
     */
    public Date getFechaInicialProrroga() {
        return fechaInicialProrroga;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MODIFICACION_SITUACION_ADMINISTRATIVA.FECHA_INICIAL_PRORROGA
     *
     * @param fechaInicialProrroga the value for MODIFICACION_SITUACION_ADMINISTRATIVA.FECHA_INICIAL_PRORROGA
     *
     * @mbg.generated Mon Apr 30 14:47:40 COT 2018
     */
    public void setFechaInicialProrroga(Date fechaInicialProrroga) {
        this.fechaInicialProrroga = fechaInicialProrroga;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MODIFICACION_SITUACION_ADMINISTRATIVA.FECHA_FIN_PRORROGA
     *
     * @return the value of MODIFICACION_SITUACION_ADMINISTRATIVA.FECHA_FIN_PRORROGA
     *
     * @mbg.generated Mon Apr 30 14:47:40 COT 2018
     */
    public Date getFechaFinProrroga() {
        return fechaFinProrroga;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MODIFICACION_SITUACION_ADMINISTRATIVA.FECHA_FIN_PRORROGA
     *
     * @param fechaFinProrroga the value for MODIFICACION_SITUACION_ADMINISTRATIVA.FECHA_FIN_PRORROGA
     *
     * @mbg.generated Mon Apr 30 14:47:40 COT 2018
     */
    public void setFechaFinProrroga(Date fechaFinProrroga) {
        this.fechaFinProrroga = fechaFinProrroga;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MODIFICACION_SITUACION_ADMINISTRATIVA.DESCRIPCION_MODIFICACION
     *
     * @return the value of MODIFICACION_SITUACION_ADMINISTRATIVA.DESCRIPCION_MODIFICACION
     *
     * @mbg.generated Mon Apr 30 14:47:40 COT 2018
     */
    public String getDescripcionModificacion() {
        return descripcionModificacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MODIFICACION_SITUACION_ADMINISTRATIVA.DESCRIPCION_MODIFICACION
     *
     * @param descripcionModificacion the value for MODIFICACION_SITUACION_ADMINISTRATIVA.DESCRIPCION_MODIFICACION
     *
     * @mbg.generated Mon Apr 30 14:47:40 COT 2018
     */
    public void setDescripcionModificacion(String descripcionModificacion) {
        this.descripcionModificacion = descripcionModificacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MODIFICACION_SITUACION_ADMINISTRATIVA.FECHA_INGRESO_PRORROGA
     *
     * @return the value of MODIFICACION_SITUACION_ADMINISTRATIVA.FECHA_INGRESO_PRORROGA
     *
     * @mbg.generated Mon Apr 30 14:47:40 COT 2018
     */
    public Date getFechaIngresoProrroga() {
        return fechaIngresoProrroga;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MODIFICACION_SITUACION_ADMINISTRATIVA.FECHA_INGRESO_PRORROGA
     *
     * @param fechaIngresoProrroga the value for MODIFICACION_SITUACION_ADMINISTRATIVA.FECHA_INGRESO_PRORROGA
     *
     * @mbg.generated Mon Apr 30 14:47:40 COT 2018
     */
    public void setFechaIngresoProrroga(Date fechaIngresoProrroga) {
        this.fechaIngresoProrroga = fechaIngresoProrroga;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MODIFICACION_SITUACION_ADMINISTRATIVA.USUARIO_PRORROGA
     *
     * @return the value of MODIFICACION_SITUACION_ADMINISTRATIVA.USUARIO_PRORROGA
     *
     * @mbg.generated Mon Apr 30 14:47:40 COT 2018
     */
    public Long getUsuarioProrroga() {
        return usuarioProrroga;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MODIFICACION_SITUACION_ADMINISTRATIVA.USUARIO_PRORROGA
     *
     * @param usuarioProrroga the value for MODIFICACION_SITUACION_ADMINISTRATIVA.USUARIO_PRORROGA
     *
     * @mbg.generated Mon Apr 30 14:47:40 COT 2018
     */
    public void setUsuarioProrroga(Long usuarioProrroga) {
        this.usuarioProrroga = usuarioProrroga;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MODIFICACION_SITUACION_ADMINISTRATIVA.AUD_FECHA_MODIFICACION
     *
     * @return the value of MODIFICACION_SITUACION_ADMINISTRATIVA.AUD_FECHA_MODIFICACION
     *
     * @mbg.generated Mon Apr 30 14:47:40 COT 2018
     */
    public Date getAudFechaModificacion() {
        return audFechaModificacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MODIFICACION_SITUACION_ADMINISTRATIVA.AUD_FECHA_MODIFICACION
     *
     * @param audFechaModificacion the value for MODIFICACION_SITUACION_ADMINISTRATIVA.AUD_FECHA_MODIFICACION
     *
     * @mbg.generated Mon Apr 30 14:47:40 COT 2018
     */
    public void setAudFechaModificacion(Date audFechaModificacion) {
        this.audFechaModificacion = audFechaModificacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MODIFICACION_SITUACION_ADMINISTRATIVA.AUD_COD_USUARIO
     *
     * @return the value of MODIFICACION_SITUACION_ADMINISTRATIVA.AUD_COD_USUARIO
     *
     * @mbg.generated Mon Apr 30 14:47:40 COT 2018
     */
    public BigDecimal getAudCodUsuario() {
        return audCodUsuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MODIFICACION_SITUACION_ADMINISTRATIVA.AUD_COD_USUARIO
     *
     * @param audCodUsuario the value for MODIFICACION_SITUACION_ADMINISTRATIVA.AUD_COD_USUARIO
     *
     * @mbg.generated Mon Apr 30 14:47:40 COT 2018
     */
    public void setAudCodUsuario(BigDecimal audCodUsuario) {
        this.audCodUsuario = audCodUsuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MODIFICACION_SITUACION_ADMINISTRATIVA.AUD_COD_ROL
     *
     * @return the value of MODIFICACION_SITUACION_ADMINISTRATIVA.AUD_COD_ROL
     *
     * @mbg.generated Mon Apr 30 14:47:40 COT 2018
     */
    public Integer getAudCodRol() {
        return audCodRol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MODIFICACION_SITUACION_ADMINISTRATIVA.AUD_COD_ROL
     *
     * @param audCodRol the value for MODIFICACION_SITUACION_ADMINISTRATIVA.AUD_COD_ROL
     *
     * @mbg.generated Mon Apr 30 14:47:40 COT 2018
     */
    public void setAudCodRol(Integer audCodRol) {
        this.audCodRol = audCodRol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MODIFICACION_SITUACION_ADMINISTRATIVA.AUD_ACCION
     *
     * @return the value of MODIFICACION_SITUACION_ADMINISTRATIVA.AUD_ACCION
     *
     * @mbg.generated Mon Apr 30 14:47:40 COT 2018
     */
    public Integer getAudAccion() {
        return audAccion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MODIFICACION_SITUACION_ADMINISTRATIVA.AUD_ACCION
     *
     * @param audAccion the value for MODIFICACION_SITUACION_ADMINISTRATIVA.AUD_ACCION
     *
     * @mbg.generated Mon Apr 30 14:47:40 COT 2018
     */
    public void setAudAccion(Integer audAccion) {
        this.audAccion = audAccion;
    }

	public int getLimitInit() {
		return limitInit;
	}

	public void setLimitInit(int limitInit) {
		this.limitInit = limitInit;
	}

	public int getLimitEnd() {
		return limitEnd;
	}

	public void setLimitEnd(int limitEnd) {
		this.limitEnd = limitEnd;
	}
    
    
    
    
}