package co.gov.dafp.sigep2.bean;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PermisoRolAccionExample {
	/**
	 * 
	 */
	private int limitInit;
	/**
	 * 
	 */
	private int limitEnd;
	
	/**
	 * @return the limitInit
	 */
	public int getLimitInit() {
		return limitInit;
	}

	/**
	 * @param limitInit the limitInit to set
	 */
	public void setLimitInit(int limitInit) {
		this.limitInit = limitInit;
	}
	
	
	
    /**
	 * @return the limitEnd
	 */
	public int getLimitEnd() {
		return limitEnd;
	}

	/**
	 * @param limitEnd the limitEnd to set
	 */
	public void setLimitEnd(int limitEnd) {
		this.limitEnd = limitEnd;
	}
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table PERMISO_ROL_ACCION
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table PERMISO_ROL_ACCION
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table PERMISO_ROL_ACCION
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERMISO_ROL_ACCION
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public PermisoRolAccionExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERMISO_ROL_ACCION
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERMISO_ROL_ACCION
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERMISO_ROL_ACCION
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERMISO_ROL_ACCION
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERMISO_ROL_ACCION
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERMISO_ROL_ACCION
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERMISO_ROL_ACCION
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERMISO_ROL_ACCION
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERMISO_ROL_ACCION
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERMISO_ROL_ACCION
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table PERMISO_ROL_ACCION
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andCodPermisoRolAccionesIsNull() {
			addCriterion("COD_PERMISO_ROL_ACCIONES is null");
			return (Criteria) this;
		}

		public Criteria andCodPermisoRolAccionesIsNotNull() {
			addCriterion("COD_PERMISO_ROL_ACCIONES is not null");
			return (Criteria) this;
		}

		public Criteria andCodPermisoRolAccionesEqualTo(BigDecimal value) {
			addCriterion("COD_PERMISO_ROL_ACCIONES =", value, "codPermisoRolAcciones");
			return (Criteria) this;
		}

		public Criteria andCodPermisoRolAccionesNotEqualTo(BigDecimal value) {
			addCriterion("COD_PERMISO_ROL_ACCIONES <>", value, "codPermisoRolAcciones");
			return (Criteria) this;
		}

		public Criteria andCodPermisoRolAccionesGreaterThan(BigDecimal value) {
			addCriterion("COD_PERMISO_ROL_ACCIONES >", value, "codPermisoRolAcciones");
			return (Criteria) this;
		}

		public Criteria andCodPermisoRolAccionesGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("COD_PERMISO_ROL_ACCIONES >=", value, "codPermisoRolAcciones");
			return (Criteria) this;
		}

		public Criteria andCodPermisoRolAccionesLessThan(BigDecimal value) {
			addCriterion("COD_PERMISO_ROL_ACCIONES <", value, "codPermisoRolAcciones");
			return (Criteria) this;
		}

		public Criteria andCodPermisoRolAccionesLessThanOrEqualTo(BigDecimal value) {
			addCriterion("COD_PERMISO_ROL_ACCIONES <=", value, "codPermisoRolAcciones");
			return (Criteria) this;
		}

		public Criteria andCodPermisoRolAccionesIn(List<BigDecimal> values) {
			addCriterion("COD_PERMISO_ROL_ACCIONES in", values, "codPermisoRolAcciones");
			return (Criteria) this;
		}

		public Criteria andCodPermisoRolAccionesNotIn(List<BigDecimal> values) {
			addCriterion("COD_PERMISO_ROL_ACCIONES not in", values, "codPermisoRolAcciones");
			return (Criteria) this;
		}

		public Criteria andCodPermisoRolAccionesBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("COD_PERMISO_ROL_ACCIONES between", value1, value2, "codPermisoRolAcciones");
			return (Criteria) this;
		}

		public Criteria andCodPermisoRolAccionesNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("COD_PERMISO_ROL_ACCIONES not between", value1, value2, "codPermisoRolAcciones");
			return (Criteria) this;
		}

		public Criteria andCodPermisoRolIsNull() {
			addCriterion("COD_PERMISO_ROL is null");
			return (Criteria) this;
		}

		public Criteria andCodPermisoRolIsNotNull() {
			addCriterion("COD_PERMISO_ROL is not null");
			return (Criteria) this;
		}

		public Criteria andCodPermisoRolEqualTo(BigDecimal value) {
			addCriterion("COD_PERMISO_ROL =", value, "codPermisoRol");
			return (Criteria) this;
		}

		public Criteria andCodPermisoRolNotEqualTo(BigDecimal value) {
			addCriterion("COD_PERMISO_ROL <>", value, "codPermisoRol");
			return (Criteria) this;
		}

		public Criteria andCodPermisoRolGreaterThan(BigDecimal value) {
			addCriterion("COD_PERMISO_ROL >", value, "codPermisoRol");
			return (Criteria) this;
		}

		public Criteria andCodPermisoRolGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("COD_PERMISO_ROL >=", value, "codPermisoRol");
			return (Criteria) this;
		}

		public Criteria andCodPermisoRolLessThan(BigDecimal value) {
			addCriterion("COD_PERMISO_ROL <", value, "codPermisoRol");
			return (Criteria) this;
		}

		public Criteria andCodPermisoRolLessThanOrEqualTo(BigDecimal value) {
			addCriterion("COD_PERMISO_ROL <=", value, "codPermisoRol");
			return (Criteria) this;
		}

		public Criteria andCodPermisoRolIn(List<BigDecimal> values) {
			addCriterion("COD_PERMISO_ROL in", values, "codPermisoRol");
			return (Criteria) this;
		}

		public Criteria andCodPermisoRolNotIn(List<BigDecimal> values) {
			addCriterion("COD_PERMISO_ROL not in", values, "codPermisoRol");
			return (Criteria) this;
		}

		public Criteria andCodPermisoRolBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("COD_PERMISO_ROL between", value1, value2, "codPermisoRol");
			return (Criteria) this;
		}

		public Criteria andCodPermisoRolNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("COD_PERMISO_ROL not between", value1, value2, "codPermisoRol");
			return (Criteria) this;
		}

		public Criteria andAccionIsNull() {
			addCriterion("ACCION is null");
			return (Criteria) this;
		}

		public Criteria andAccionIsNotNull() {
			addCriterion("ACCION is not null");
			return (Criteria) this;
		}

		public Criteria andAccionEqualTo(String value) {
			addCriterion("ACCION =", value, "accion");
			return (Criteria) this;
		}

		public Criteria andAccionNotEqualTo(String value) {
			addCriterion("ACCION <>", value, "accion");
			return (Criteria) this;
		}

		public Criteria andAccionGreaterThan(String value) {
			addCriterion("ACCION >", value, "accion");
			return (Criteria) this;
		}

		public Criteria andAccionGreaterThanOrEqualTo(String value) {
			addCriterion("ACCION >=", value, "accion");
			return (Criteria) this;
		}

		public Criteria andAccionLessThan(String value) {
			addCriterion("ACCION <", value, "accion");
			return (Criteria) this;
		}

		public Criteria andAccionLessThanOrEqualTo(String value) {
			addCriterion("ACCION <=", value, "accion");
			return (Criteria) this;
		}

		public Criteria andAccionLike(String value) {
			addCriterion("ACCION like", value, "accion");
			return (Criteria) this;
		}

		public Criteria andAccionNotLike(String value) {
			addCriterion("ACCION not like", value, "accion");
			return (Criteria) this;
		}

		public Criteria andAccionIn(List<String> values) {
			addCriterion("ACCION in", values, "accion");
			return (Criteria) this;
		}

		public Criteria andAccionNotIn(List<String> values) {
			addCriterion("ACCION not in", values, "accion");
			return (Criteria) this;
		}

		public Criteria andAccionBetween(String value1, String value2) {
			addCriterion("ACCION between", value1, value2, "accion");
			return (Criteria) this;
		}

		public Criteria andAccionNotBetween(String value1, String value2) {
			addCriterion("ACCION not between", value1, value2, "accion");
			return (Criteria) this;
		}

		public Criteria andControlHtmlIsNull() {
			addCriterion("CONTROL_HTML is null");
			return (Criteria) this;
		}

		public Criteria andControlHtmlIsNotNull() {
			addCriterion("CONTROL_HTML is not null");
			return (Criteria) this;
		}

		public Criteria andControlHtmlEqualTo(String value) {
			addCriterion("CONTROL_HTML =", value, "controlHtml");
			return (Criteria) this;
		}

		public Criteria andControlHtmlNotEqualTo(String value) {
			addCriterion("CONTROL_HTML <>", value, "controlHtml");
			return (Criteria) this;
		}

		public Criteria andControlHtmlGreaterThan(String value) {
			addCriterion("CONTROL_HTML >", value, "controlHtml");
			return (Criteria) this;
		}

		public Criteria andControlHtmlGreaterThanOrEqualTo(String value) {
			addCriterion("CONTROL_HTML >=", value, "controlHtml");
			return (Criteria) this;
		}

		public Criteria andControlHtmlLessThan(String value) {
			addCriterion("CONTROL_HTML <", value, "controlHtml");
			return (Criteria) this;
		}

		public Criteria andControlHtmlLessThanOrEqualTo(String value) {
			addCriterion("CONTROL_HTML <=", value, "controlHtml");
			return (Criteria) this;
		}

		public Criteria andControlHtmlLike(String value) {
			addCriterion("CONTROL_HTML like", value, "controlHtml");
			return (Criteria) this;
		}

		public Criteria andControlHtmlNotLike(String value) {
			addCriterion("CONTROL_HTML not like", value, "controlHtml");
			return (Criteria) this;
		}

		public Criteria andControlHtmlIn(List<String> values) {
			addCriterion("CONTROL_HTML in", values, "controlHtml");
			return (Criteria) this;
		}

		public Criteria andControlHtmlNotIn(List<String> values) {
			addCriterion("CONTROL_HTML not in", values, "controlHtml");
			return (Criteria) this;
		}

		public Criteria andControlHtmlBetween(String value1, String value2) {
			addCriterion("CONTROL_HTML between", value1, value2, "controlHtml");
			return (Criteria) this;
		}

		public Criteria andControlHtmlNotBetween(String value1, String value2) {
			addCriterion("CONTROL_HTML not between", value1, value2, "controlHtml");
			return (Criteria) this;
		}

		public Criteria andFlgActivoIsNull() {
			addCriterion("FLG_ACTIVO is null");
			return (Criteria) this;
		}

		public Criteria andFlgActivoIsNotNull() {
			addCriterion("FLG_ACTIVO is not null");
			return (Criteria) this;
		}

		public Criteria andFlgActivoEqualTo(Short value) {
			addCriterion("FLG_ACTIVO =", value, "flgActivo");
			return (Criteria) this;
		}

		public Criteria andFlgActivoNotEqualTo(Short value) {
			addCriterion("FLG_ACTIVO <>", value, "flgActivo");
			return (Criteria) this;
		}

		public Criteria andFlgActivoGreaterThan(Short value) {
			addCriterion("FLG_ACTIVO >", value, "flgActivo");
			return (Criteria) this;
		}

		public Criteria andFlgActivoGreaterThanOrEqualTo(Short value) {
			addCriterion("FLG_ACTIVO >=", value, "flgActivo");
			return (Criteria) this;
		}

		public Criteria andFlgActivoLessThan(Short value) {
			addCriterion("FLG_ACTIVO <", value, "flgActivo");
			return (Criteria) this;
		}

		public Criteria andFlgActivoLessThanOrEqualTo(Short value) {
			addCriterion("FLG_ACTIVO <=", value, "flgActivo");
			return (Criteria) this;
		}

		public Criteria andFlgActivoIn(List<Short> values) {
			addCriterion("FLG_ACTIVO in", values, "flgActivo");
			return (Criteria) this;
		}

		public Criteria andFlgActivoNotIn(List<Short> values) {
			addCriterion("FLG_ACTIVO not in", values, "flgActivo");
			return (Criteria) this;
		}

		public Criteria andFlgActivoBetween(Short value1, Short value2) {
			addCriterion("FLG_ACTIVO between", value1, value2, "flgActivo");
			return (Criteria) this;
		}

		public Criteria andFlgActivoNotBetween(Short value1, Short value2) {
			addCriterion("FLG_ACTIVO not between", value1, value2, "flgActivo");
			return (Criteria) this;
		}

		public Criteria andAudFechaActualizacionIsNull() {
			addCriterion("AUD_FECHA_ACTUALIZACION is null");
			return (Criteria) this;
		}

		public Criteria andAudFechaActualizacionIsNotNull() {
			addCriterion("AUD_FECHA_ACTUALIZACION is not null");
			return (Criteria) this;
		}

		public Criteria andAudFechaActualizacionEqualTo(Date value) {
			addCriterion("AUD_FECHA_ACTUALIZACION =", value, "audFechaActualizacion");
			return (Criteria) this;
		}

		public Criteria andAudFechaActualizacionNotEqualTo(Date value) {
			addCriterion("AUD_FECHA_ACTUALIZACION <>", value, "audFechaActualizacion");
			return (Criteria) this;
		}

		public Criteria andAudFechaActualizacionGreaterThan(Date value) {
			addCriterion("AUD_FECHA_ACTUALIZACION >", value, "audFechaActualizacion");
			return (Criteria) this;
		}

		public Criteria andAudFechaActualizacionGreaterThanOrEqualTo(Date value) {
			addCriterion("AUD_FECHA_ACTUALIZACION >=", value, "audFechaActualizacion");
			return (Criteria) this;
		}

		public Criteria andAudFechaActualizacionLessThan(Date value) {
			addCriterion("AUD_FECHA_ACTUALIZACION <", value, "audFechaActualizacion");
			return (Criteria) this;
		}

		public Criteria andAudFechaActualizacionLessThanOrEqualTo(Date value) {
			addCriterion("AUD_FECHA_ACTUALIZACION <=", value, "audFechaActualizacion");
			return (Criteria) this;
		}

		public Criteria andAudFechaActualizacionIn(List<Date> values) {
			addCriterion("AUD_FECHA_ACTUALIZACION in", values, "audFechaActualizacion");
			return (Criteria) this;
		}

		public Criteria andAudFechaActualizacionNotIn(List<Date> values) {
			addCriterion("AUD_FECHA_ACTUALIZACION not in", values, "audFechaActualizacion");
			return (Criteria) this;
		}

		public Criteria andAudFechaActualizacionBetween(Date value1, Date value2) {
			addCriterion("AUD_FECHA_ACTUALIZACION between", value1, value2, "audFechaActualizacion");
			return (Criteria) this;
		}

		public Criteria andAudFechaActualizacionNotBetween(Date value1, Date value2) {
			addCriterion("AUD_FECHA_ACTUALIZACION not between", value1, value2, "audFechaActualizacion");
			return (Criteria) this;
		}

		public Criteria andAudCodUsuarioIsNull() {
			addCriterion("AUD_COD_USUARIO is null");
			return (Criteria) this;
		}

		public Criteria andAudCodUsuarioIsNotNull() {
			addCriterion("AUD_COD_USUARIO is not null");
			return (Criteria) this;
		}

		public Criteria andAudCodUsuarioEqualTo(Short value) {
			addCriterion("AUD_COD_USUARIO =", value, "audCodUsuario");
			return (Criteria) this;
		}

		public Criteria andAudCodUsuarioNotEqualTo(Short value) {
			addCriterion("AUD_COD_USUARIO <>", value, "audCodUsuario");
			return (Criteria) this;
		}

		public Criteria andAudCodUsuarioGreaterThan(Short value) {
			addCriterion("AUD_COD_USUARIO >", value, "audCodUsuario");
			return (Criteria) this;
		}

		public Criteria andAudCodUsuarioGreaterThanOrEqualTo(Short value) {
			addCriterion("AUD_COD_USUARIO >=", value, "audCodUsuario");
			return (Criteria) this;
		}

		public Criteria andAudCodUsuarioLessThan(Short value) {
			addCriterion("AUD_COD_USUARIO <", value, "audCodUsuario");
			return (Criteria) this;
		}

		public Criteria andAudCodUsuarioLessThanOrEqualTo(Short value) {
			addCriterion("AUD_COD_USUARIO <=", value, "audCodUsuario");
			return (Criteria) this;
		}

		public Criteria andAudCodUsuarioIn(List<Short> values) {
			addCriterion("AUD_COD_USUARIO in", values, "audCodUsuario");
			return (Criteria) this;
		}

		public Criteria andAudCodUsuarioNotIn(List<Short> values) {
			addCriterion("AUD_COD_USUARIO not in", values, "audCodUsuario");
			return (Criteria) this;
		}

		public Criteria andAudCodUsuarioBetween(Short value1, Short value2) {
			addCriterion("AUD_COD_USUARIO between", value1, value2, "audCodUsuario");
			return (Criteria) this;
		}

		public Criteria andAudCodUsuarioNotBetween(Short value1, Short value2) {
			addCriterion("AUD_COD_USUARIO not between", value1, value2, "audCodUsuario");
			return (Criteria) this;
		}

		public Criteria andAudCodRolIsNull() {
			addCriterion("AUD_COD_ROL is null");
			return (Criteria) this;
		}

		public Criteria andAudCodRolIsNotNull() {
			addCriterion("AUD_COD_ROL is not null");
			return (Criteria) this;
		}

		public Criteria andAudCodRolEqualTo(Short value) {
			addCriterion("AUD_COD_ROL =", value, "audCodRol");
			return (Criteria) this;
		}

		public Criteria andAudCodRolNotEqualTo(Short value) {
			addCriterion("AUD_COD_ROL <>", value, "audCodRol");
			return (Criteria) this;
		}

		public Criteria andAudCodRolGreaterThan(Short value) {
			addCriterion("AUD_COD_ROL >", value, "audCodRol");
			return (Criteria) this;
		}

		public Criteria andAudCodRolGreaterThanOrEqualTo(Short value) {
			addCriterion("AUD_COD_ROL >=", value, "audCodRol");
			return (Criteria) this;
		}

		public Criteria andAudCodRolLessThan(Short value) {
			addCriterion("AUD_COD_ROL <", value, "audCodRol");
			return (Criteria) this;
		}

		public Criteria andAudCodRolLessThanOrEqualTo(Short value) {
			addCriterion("AUD_COD_ROL <=", value, "audCodRol");
			return (Criteria) this;
		}

		public Criteria andAudCodRolIn(List<Short> values) {
			addCriterion("AUD_COD_ROL in", values, "audCodRol");
			return (Criteria) this;
		}

		public Criteria andAudCodRolNotIn(List<Short> values) {
			addCriterion("AUD_COD_ROL not in", values, "audCodRol");
			return (Criteria) this;
		}

		public Criteria andAudCodRolBetween(Short value1, Short value2) {
			addCriterion("AUD_COD_ROL between", value1, value2, "audCodRol");
			return (Criteria) this;
		}

		public Criteria andAudCodRolNotBetween(Short value1, Short value2) {
			addCriterion("AUD_COD_ROL not between", value1, value2, "audCodRol");
			return (Criteria) this;
		}

		public Criteria andAudAccionIsNull() {
			addCriterion("AUD_ACCION is null");
			return (Criteria) this;
		}

		public Criteria andAudAccionIsNotNull() {
			addCriterion("AUD_ACCION is not null");
			return (Criteria) this;
		}

		public Criteria andAudAccionEqualTo(Short value) {
			addCriterion("AUD_ACCION =", value, "audAccion");
			return (Criteria) this;
		}

		public Criteria andAudAccionNotEqualTo(Short value) {
			addCriterion("AUD_ACCION <>", value, "audAccion");
			return (Criteria) this;
		}

		public Criteria andAudAccionGreaterThan(Short value) {
			addCriterion("AUD_ACCION >", value, "audAccion");
			return (Criteria) this;
		}

		public Criteria andAudAccionGreaterThanOrEqualTo(Short value) {
			addCriterion("AUD_ACCION >=", value, "audAccion");
			return (Criteria) this;
		}

		public Criteria andAudAccionLessThan(Short value) {
			addCriterion("AUD_ACCION <", value, "audAccion");
			return (Criteria) this;
		}

		public Criteria andAudAccionLessThanOrEqualTo(Short value) {
			addCriterion("AUD_ACCION <=", value, "audAccion");
			return (Criteria) this;
		}

		public Criteria andAudAccionIn(List<Short> values) {
			addCriterion("AUD_ACCION in", values, "audAccion");
			return (Criteria) this;
		}

		public Criteria andAudAccionNotIn(List<Short> values) {
			addCriterion("AUD_ACCION not in", values, "audAccion");
			return (Criteria) this;
		}

		public Criteria andAudAccionBetween(Short value1, Short value2) {
			addCriterion("AUD_ACCION between", value1, value2, "audAccion");
			return (Criteria) this;
		}

		public Criteria andAudAccionNotBetween(Short value1, Short value2) {
			addCriterion("AUD_ACCION not between", value1, value2, "audAccion");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table PERMISO_ROL_ACCION
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PERMISO_ROL_ACCION
     *
     * @mbg.generated do_not_delete_during_merge Thu Jan 25 12:04:19 COT 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}