package co.gov.dafp.sigep2.bean;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RangoEdadExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table RANGO_EDAD
	 * @mbg.generated  Tue May 07 15:49:48 COT 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table RANGO_EDAD
	 * @mbg.generated  Tue May 07 15:49:48 COT 2019
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table RANGO_EDAD
	 * @mbg.generated  Tue May 07 15:49:48 COT 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RANGO_EDAD
	 * @mbg.generated  Tue May 07 15:49:48 COT 2019
	 */
	public RangoEdadExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RANGO_EDAD
	 * @mbg.generated  Tue May 07 15:49:48 COT 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RANGO_EDAD
	 * @mbg.generated  Tue May 07 15:49:48 COT 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RANGO_EDAD
	 * @mbg.generated  Tue May 07 15:49:48 COT 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RANGO_EDAD
	 * @mbg.generated  Tue May 07 15:49:48 COT 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RANGO_EDAD
	 * @mbg.generated  Tue May 07 15:49:48 COT 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RANGO_EDAD
	 * @mbg.generated  Tue May 07 15:49:48 COT 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RANGO_EDAD
	 * @mbg.generated  Tue May 07 15:49:48 COT 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RANGO_EDAD
	 * @mbg.generated  Tue May 07 15:49:48 COT 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RANGO_EDAD
	 * @mbg.generated  Tue May 07 15:49:48 COT 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table RANGO_EDAD
	 * @mbg.generated  Tue May 07 15:49:48 COT 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table RANGO_EDAD
	 * @mbg.generated  Tue May 07 15:49:48 COT 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andCodRangoEdadIsNull() {
			addCriterion("COD_RANGO_EDAD is null");
			return (Criteria) this;
		}

		public Criteria andCodRangoEdadIsNotNull() {
			addCriterion("COD_RANGO_EDAD is not null");
			return (Criteria) this;
		}

		public Criteria andCodRangoEdadEqualTo(Long value) {
			addCriterion("COD_RANGO_EDAD =", value, "codRangoEdad");
			return (Criteria) this;
		}

		public Criteria andCodRangoEdadNotEqualTo(Long value) {
			addCriterion("COD_RANGO_EDAD <>", value, "codRangoEdad");
			return (Criteria) this;
		}

		public Criteria andCodRangoEdadGreaterThan(Long value) {
			addCriterion("COD_RANGO_EDAD >", value, "codRangoEdad");
			return (Criteria) this;
		}

		public Criteria andCodRangoEdadGreaterThanOrEqualTo(Long value) {
			addCriterion("COD_RANGO_EDAD >=", value, "codRangoEdad");
			return (Criteria) this;
		}

		public Criteria andCodRangoEdadLessThan(Long value) {
			addCriterion("COD_RANGO_EDAD <", value, "codRangoEdad");
			return (Criteria) this;
		}

		public Criteria andCodRangoEdadLessThanOrEqualTo(Long value) {
			addCriterion("COD_RANGO_EDAD <=", value, "codRangoEdad");
			return (Criteria) this;
		}

		public Criteria andCodRangoEdadIn(List<Long> values) {
			addCriterion("COD_RANGO_EDAD in", values, "codRangoEdad");
			return (Criteria) this;
		}

		public Criteria andCodRangoEdadNotIn(List<Long> values) {
			addCriterion("COD_RANGO_EDAD not in", values, "codRangoEdad");
			return (Criteria) this;
		}

		public Criteria andCodRangoEdadBetween(Long value1, Long value2) {
			addCriterion("COD_RANGO_EDAD between", value1, value2, "codRangoEdad");
			return (Criteria) this;
		}

		public Criteria andCodRangoEdadNotBetween(Long value1, Long value2) {
			addCriterion("COD_RANGO_EDAD not between", value1, value2, "codRangoEdad");
			return (Criteria) this;
		}

		public Criteria andNombreRangoIsNull() {
			addCriterion("NOMBRE_RANGO is null");
			return (Criteria) this;
		}

		public Criteria andNombreRangoIsNotNull() {
			addCriterion("NOMBRE_RANGO is not null");
			return (Criteria) this;
		}

		public Criteria andNombreRangoEqualTo(String value) {
			addCriterion("NOMBRE_RANGO =", value, "nombreRango");
			return (Criteria) this;
		}

		public Criteria andNombreRangoNotEqualTo(String value) {
			addCriterion("NOMBRE_RANGO <>", value, "nombreRango");
			return (Criteria) this;
		}

		public Criteria andNombreRangoGreaterThan(String value) {
			addCriterion("NOMBRE_RANGO >", value, "nombreRango");
			return (Criteria) this;
		}

		public Criteria andNombreRangoGreaterThanOrEqualTo(String value) {
			addCriterion("NOMBRE_RANGO >=", value, "nombreRango");
			return (Criteria) this;
		}

		public Criteria andNombreRangoLessThan(String value) {
			addCriterion("NOMBRE_RANGO <", value, "nombreRango");
			return (Criteria) this;
		}

		public Criteria andNombreRangoLessThanOrEqualTo(String value) {
			addCriterion("NOMBRE_RANGO <=", value, "nombreRango");
			return (Criteria) this;
		}

		public Criteria andNombreRangoLike(String value) {
			addCriterion("NOMBRE_RANGO like", value, "nombreRango");
			return (Criteria) this;
		}

		public Criteria andNombreRangoNotLike(String value) {
			addCriterion("NOMBRE_RANGO not like", value, "nombreRango");
			return (Criteria) this;
		}

		public Criteria andNombreRangoIn(List<String> values) {
			addCriterion("NOMBRE_RANGO in", values, "nombreRango");
			return (Criteria) this;
		}

		public Criteria andNombreRangoNotIn(List<String> values) {
			addCriterion("NOMBRE_RANGO not in", values, "nombreRango");
			return (Criteria) this;
		}

		public Criteria andNombreRangoBetween(String value1, String value2) {
			addCriterion("NOMBRE_RANGO between", value1, value2, "nombreRango");
			return (Criteria) this;
		}

		public Criteria andNombreRangoNotBetween(String value1, String value2) {
			addCriterion("NOMBRE_RANGO not between", value1, value2, "nombreRango");
			return (Criteria) this;
		}

		public Criteria andLimiteInferiorIsNull() {
			addCriterion("LIMITE_INFERIOR is null");
			return (Criteria) this;
		}

		public Criteria andLimiteInferiorIsNotNull() {
			addCriterion("LIMITE_INFERIOR is not null");
			return (Criteria) this;
		}

		public Criteria andLimiteInferiorEqualTo(Short value) {
			addCriterion("LIMITE_INFERIOR =", value, "limiteInferior");
			return (Criteria) this;
		}

		public Criteria andLimiteInferiorNotEqualTo(Short value) {
			addCriterion("LIMITE_INFERIOR <>", value, "limiteInferior");
			return (Criteria) this;
		}

		public Criteria andLimiteInferiorGreaterThan(Short value) {
			addCriterion("LIMITE_INFERIOR >", value, "limiteInferior");
			return (Criteria) this;
		}

		public Criteria andLimiteInferiorGreaterThanOrEqualTo(Short value) {
			addCriterion("LIMITE_INFERIOR >=", value, "limiteInferior");
			return (Criteria) this;
		}

		public Criteria andLimiteInferiorLessThan(Short value) {
			addCriterion("LIMITE_INFERIOR <", value, "limiteInferior");
			return (Criteria) this;
		}

		public Criteria andLimiteInferiorLessThanOrEqualTo(Short value) {
			addCriterion("LIMITE_INFERIOR <=", value, "limiteInferior");
			return (Criteria) this;
		}

		public Criteria andLimiteInferiorIn(List<Short> values) {
			addCriterion("LIMITE_INFERIOR in", values, "limiteInferior");
			return (Criteria) this;
		}

		public Criteria andLimiteInferiorNotIn(List<Short> values) {
			addCriterion("LIMITE_INFERIOR not in", values, "limiteInferior");
			return (Criteria) this;
		}

		public Criteria andLimiteInferiorBetween(Short value1, Short value2) {
			addCriterion("LIMITE_INFERIOR between", value1, value2, "limiteInferior");
			return (Criteria) this;
		}

		public Criteria andLimiteInferiorNotBetween(Short value1, Short value2) {
			addCriterion("LIMITE_INFERIOR not between", value1, value2, "limiteInferior");
			return (Criteria) this;
		}

		public Criteria andLimiteSuperiorIsNull() {
			addCriterion("LIMITE_SUPERIOR is null");
			return (Criteria) this;
		}

		public Criteria andLimiteSuperiorIsNotNull() {
			addCriterion("LIMITE_SUPERIOR is not null");
			return (Criteria) this;
		}

		public Criteria andLimiteSuperiorEqualTo(Short value) {
			addCriterion("LIMITE_SUPERIOR =", value, "limiteSuperior");
			return (Criteria) this;
		}

		public Criteria andLimiteSuperiorNotEqualTo(Short value) {
			addCriterion("LIMITE_SUPERIOR <>", value, "limiteSuperior");
			return (Criteria) this;
		}

		public Criteria andLimiteSuperiorGreaterThan(Short value) {
			addCriterion("LIMITE_SUPERIOR >", value, "limiteSuperior");
			return (Criteria) this;
		}

		public Criteria andLimiteSuperiorGreaterThanOrEqualTo(Short value) {
			addCriterion("LIMITE_SUPERIOR >=", value, "limiteSuperior");
			return (Criteria) this;
		}

		public Criteria andLimiteSuperiorLessThan(Short value) {
			addCriterion("LIMITE_SUPERIOR <", value, "limiteSuperior");
			return (Criteria) this;
		}

		public Criteria andLimiteSuperiorLessThanOrEqualTo(Short value) {
			addCriterion("LIMITE_SUPERIOR <=", value, "limiteSuperior");
			return (Criteria) this;
		}

		public Criteria andLimiteSuperiorIn(List<Short> values) {
			addCriterion("LIMITE_SUPERIOR in", values, "limiteSuperior");
			return (Criteria) this;
		}

		public Criteria andLimiteSuperiorNotIn(List<Short> values) {
			addCriterion("LIMITE_SUPERIOR not in", values, "limiteSuperior");
			return (Criteria) this;
		}

		public Criteria andLimiteSuperiorBetween(Short value1, Short value2) {
			addCriterion("LIMITE_SUPERIOR between", value1, value2, "limiteSuperior");
			return (Criteria) this;
		}

		public Criteria andLimiteSuperiorNotBetween(Short value1, Short value2) {
			addCriterion("LIMITE_SUPERIOR not between", value1, value2, "limiteSuperior");
			return (Criteria) this;
		}

		public Criteria andFlgActivoIsNull() {
			addCriterion("FLG_ACTIVO is null");
			return (Criteria) this;
		}

		public Criteria andFlgActivoIsNotNull() {
			addCriterion("FLG_ACTIVO is not null");
			return (Criteria) this;
		}

		public Criteria andFlgActivoEqualTo(Short value) {
			addCriterion("FLG_ACTIVO =", value, "flgActivo");
			return (Criteria) this;
		}

		public Criteria andFlgActivoNotEqualTo(Short value) {
			addCriterion("FLG_ACTIVO <>", value, "flgActivo");
			return (Criteria) this;
		}

		public Criteria andFlgActivoGreaterThan(Short value) {
			addCriterion("FLG_ACTIVO >", value, "flgActivo");
			return (Criteria) this;
		}

		public Criteria andFlgActivoGreaterThanOrEqualTo(Short value) {
			addCriterion("FLG_ACTIVO >=", value, "flgActivo");
			return (Criteria) this;
		}

		public Criteria andFlgActivoLessThan(Short value) {
			addCriterion("FLG_ACTIVO <", value, "flgActivo");
			return (Criteria) this;
		}

		public Criteria andFlgActivoLessThanOrEqualTo(Short value) {
			addCriterion("FLG_ACTIVO <=", value, "flgActivo");
			return (Criteria) this;
		}

		public Criteria andFlgActivoIn(List<Short> values) {
			addCriterion("FLG_ACTIVO in", values, "flgActivo");
			return (Criteria) this;
		}

		public Criteria andFlgActivoNotIn(List<Short> values) {
			addCriterion("FLG_ACTIVO not in", values, "flgActivo");
			return (Criteria) this;
		}

		public Criteria andFlgActivoBetween(Short value1, Short value2) {
			addCriterion("FLG_ACTIVO between", value1, value2, "flgActivo");
			return (Criteria) this;
		}

		public Criteria andFlgActivoNotBetween(Short value1, Short value2) {
			addCriterion("FLG_ACTIVO not between", value1, value2, "flgActivo");
			return (Criteria) this;
		}

		public Criteria andAudFechaActualizacionIsNull() {
			addCriterion("AUD_FECHA_ACTUALIZACION is null");
			return (Criteria) this;
		}

		public Criteria andAudFechaActualizacionIsNotNull() {
			addCriterion("AUD_FECHA_ACTUALIZACION is not null");
			return (Criteria) this;
		}

		public Criteria andAudFechaActualizacionEqualTo(Date value) {
			addCriterion("AUD_FECHA_ACTUALIZACION =", value, "audFechaActualizacion");
			return (Criteria) this;
		}

		public Criteria andAudFechaActualizacionNotEqualTo(Date value) {
			addCriterion("AUD_FECHA_ACTUALIZACION <>", value, "audFechaActualizacion");
			return (Criteria) this;
		}

		public Criteria andAudFechaActualizacionGreaterThan(Date value) {
			addCriterion("AUD_FECHA_ACTUALIZACION >", value, "audFechaActualizacion");
			return (Criteria) this;
		}

		public Criteria andAudFechaActualizacionGreaterThanOrEqualTo(Date value) {
			addCriterion("AUD_FECHA_ACTUALIZACION >=", value, "audFechaActualizacion");
			return (Criteria) this;
		}

		public Criteria andAudFechaActualizacionLessThan(Date value) {
			addCriterion("AUD_FECHA_ACTUALIZACION <", value, "audFechaActualizacion");
			return (Criteria) this;
		}

		public Criteria andAudFechaActualizacionLessThanOrEqualTo(Date value) {
			addCriterion("AUD_FECHA_ACTUALIZACION <=", value, "audFechaActualizacion");
			return (Criteria) this;
		}

		public Criteria andAudFechaActualizacionIn(List<Date> values) {
			addCriterion("AUD_FECHA_ACTUALIZACION in", values, "audFechaActualizacion");
			return (Criteria) this;
		}

		public Criteria andAudFechaActualizacionNotIn(List<Date> values) {
			addCriterion("AUD_FECHA_ACTUALIZACION not in", values, "audFechaActualizacion");
			return (Criteria) this;
		}

		public Criteria andAudFechaActualizacionBetween(Date value1, Date value2) {
			addCriterion("AUD_FECHA_ACTUALIZACION between", value1, value2, "audFechaActualizacion");
			return (Criteria) this;
		}

		public Criteria andAudFechaActualizacionNotBetween(Date value1, Date value2) {
			addCriterion("AUD_FECHA_ACTUALIZACION not between", value1, value2, "audFechaActualizacion");
			return (Criteria) this;
		}

		public Criteria andAudCodUsuarioIsNull() {
			addCriterion("AUD_COD_USUARIO is null");
			return (Criteria) this;
		}

		public Criteria andAudCodUsuarioIsNotNull() {
			addCriterion("AUD_COD_USUARIO is not null");
			return (Criteria) this;
		}

		public Criteria andAudCodUsuarioEqualTo(BigDecimal value) {
			addCriterion("AUD_COD_USUARIO =", value, "audCodUsuario");
			return (Criteria) this;
		}

		public Criteria andAudCodUsuarioNotEqualTo(BigDecimal value) {
			addCriterion("AUD_COD_USUARIO <>", value, "audCodUsuario");
			return (Criteria) this;
		}

		public Criteria andAudCodUsuarioGreaterThan(BigDecimal value) {
			addCriterion("AUD_COD_USUARIO >", value, "audCodUsuario");
			return (Criteria) this;
		}

		public Criteria andAudCodUsuarioGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("AUD_COD_USUARIO >=", value, "audCodUsuario");
			return (Criteria) this;
		}

		public Criteria andAudCodUsuarioLessThan(BigDecimal value) {
			addCriterion("AUD_COD_USUARIO <", value, "audCodUsuario");
			return (Criteria) this;
		}

		public Criteria andAudCodUsuarioLessThanOrEqualTo(BigDecimal value) {
			addCriterion("AUD_COD_USUARIO <=", value, "audCodUsuario");
			return (Criteria) this;
		}

		public Criteria andAudCodUsuarioIn(List<BigDecimal> values) {
			addCriterion("AUD_COD_USUARIO in", values, "audCodUsuario");
			return (Criteria) this;
		}

		public Criteria andAudCodUsuarioNotIn(List<BigDecimal> values) {
			addCriterion("AUD_COD_USUARIO not in", values, "audCodUsuario");
			return (Criteria) this;
		}

		public Criteria andAudCodUsuarioBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("AUD_COD_USUARIO between", value1, value2, "audCodUsuario");
			return (Criteria) this;
		}

		public Criteria andAudCodUsuarioNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("AUD_COD_USUARIO not between", value1, value2, "audCodUsuario");
			return (Criteria) this;
		}

		public Criteria andAudCodRolIsNull() {
			addCriterion("AUD_COD_ROL is null");
			return (Criteria) this;
		}

		public Criteria andAudCodRolIsNotNull() {
			addCriterion("AUD_COD_ROL is not null");
			return (Criteria) this;
		}

		public Criteria andAudCodRolEqualTo(Integer value) {
			addCriterion("AUD_COD_ROL =", value, "audCodRol");
			return (Criteria) this;
		}

		public Criteria andAudCodRolNotEqualTo(Integer value) {
			addCriterion("AUD_COD_ROL <>", value, "audCodRol");
			return (Criteria) this;
		}

		public Criteria andAudCodRolGreaterThan(Integer value) {
			addCriterion("AUD_COD_ROL >", value, "audCodRol");
			return (Criteria) this;
		}

		public Criteria andAudCodRolGreaterThanOrEqualTo(Integer value) {
			addCriterion("AUD_COD_ROL >=", value, "audCodRol");
			return (Criteria) this;
		}

		public Criteria andAudCodRolLessThan(Integer value) {
			addCriterion("AUD_COD_ROL <", value, "audCodRol");
			return (Criteria) this;
		}

		public Criteria andAudCodRolLessThanOrEqualTo(Integer value) {
			addCriterion("AUD_COD_ROL <=", value, "audCodRol");
			return (Criteria) this;
		}

		public Criteria andAudCodRolIn(List<Integer> values) {
			addCriterion("AUD_COD_ROL in", values, "audCodRol");
			return (Criteria) this;
		}

		public Criteria andAudCodRolNotIn(List<Integer> values) {
			addCriterion("AUD_COD_ROL not in", values, "audCodRol");
			return (Criteria) this;
		}

		public Criteria andAudCodRolBetween(Integer value1, Integer value2) {
			addCriterion("AUD_COD_ROL between", value1, value2, "audCodRol");
			return (Criteria) this;
		}

		public Criteria andAudCodRolNotBetween(Integer value1, Integer value2) {
			addCriterion("AUD_COD_ROL not between", value1, value2, "audCodRol");
			return (Criteria) this;
		}

		public Criteria andAudAccionIsNull() {
			addCriterion("AUD_ACCION is null");
			return (Criteria) this;
		}

		public Criteria andAudAccionIsNotNull() {
			addCriterion("AUD_ACCION is not null");
			return (Criteria) this;
		}

		public Criteria andAudAccionEqualTo(Integer value) {
			addCriterion("AUD_ACCION =", value, "audAccion");
			return (Criteria) this;
		}

		public Criteria andAudAccionNotEqualTo(Integer value) {
			addCriterion("AUD_ACCION <>", value, "audAccion");
			return (Criteria) this;
		}

		public Criteria andAudAccionGreaterThan(Integer value) {
			addCriterion("AUD_ACCION >", value, "audAccion");
			return (Criteria) this;
		}

		public Criteria andAudAccionGreaterThanOrEqualTo(Integer value) {
			addCriterion("AUD_ACCION >=", value, "audAccion");
			return (Criteria) this;
		}

		public Criteria andAudAccionLessThan(Integer value) {
			addCriterion("AUD_ACCION <", value, "audAccion");
			return (Criteria) this;
		}

		public Criteria andAudAccionLessThanOrEqualTo(Integer value) {
			addCriterion("AUD_ACCION <=", value, "audAccion");
			return (Criteria) this;
		}

		public Criteria andAudAccionIn(List<Integer> values) {
			addCriterion("AUD_ACCION in", values, "audAccion");
			return (Criteria) this;
		}

		public Criteria andAudAccionNotIn(List<Integer> values) {
			addCriterion("AUD_ACCION not in", values, "audAccion");
			return (Criteria) this;
		}

		public Criteria andAudAccionBetween(Integer value1, Integer value2) {
			addCriterion("AUD_ACCION between", value1, value2, "audAccion");
			return (Criteria) this;
		}

		public Criteria andAudAccionNotBetween(Integer value1, Integer value2) {
			addCriterion("AUD_ACCION not between", value1, value2, "audAccion");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table RANGO_EDAD
	 * @mbg.generated  Tue May 07 15:49:48 COT 2019
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table RANGO_EDAD
     *
     * @mbg.generated do_not_delete_during_merge Tue May 07 15:49:48 COT 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}