package co.gov.dafp.sigep2.bean;

import java.util.Date;

public class UrlMigProd {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column URL_MIG_PROD.COD_URL_DATA_NO_ESTRUCTURADA
     *
     * @mbg.generated Wed Nov 10 10:09:08 COT 2021
     */
    private Long codUrlDataNoEstructurada;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column URL_MIG_PROD.NUMERO_IDENTIFICACION
     *
     * @mbg.generated Wed Nov 10 10:09:08 COT 2021
     */
    private String numeroIdentificacion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column URL_MIG_PROD.ID_REGISTRO
     *
     * @mbg.generated Wed Nov 10 10:09:08 COT 2021
     */
    private String idRegistro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column URL_MIG_PROD.RUTA_ARCHIVO
     *
     * @mbg.generated Wed Nov 10 10:09:08 COT 2021
     */
    private String rutaArchivo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column URL_MIG_PROD.TABLA_DESTINO
     *
     * @mbg.generated Wed Nov 10 10:09:08 COT 2021
     */
    private String tablaDestino;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column URL_MIG_PROD.NOMBRE_CAMPO
     *
     * @mbg.generated Wed Nov 10 10:09:08 COT 2021
     */
    private String nombreCampo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column URL_MIG_PROD.URL_GENERADA
     *
     * @mbg.generated Wed Nov 10 10:09:08 COT 2021
     */
    private String urlGenerada;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column URL_MIG_PROD.PROCESADO
     *
     * @mbg.generated Wed Nov 10 10:09:08 COT 2021
     */
    private String procesado;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column URL_MIG_PROD.FECHA_EJECUCION
     *
     * @mbg.generated Wed Nov 10 10:09:08 COT 2021
     */
    private Date fechaEjecucion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column URL_MIG_PROD.CODIGO_ESTADO
     *
     * @mbg.generated Wed Nov 10 10:09:08 COT 2021
     */
    private String codigoEstado;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column URL_MIG_PROD.MENSAGE_ESTADO
     *
     * @mbg.generated Wed Nov 10 10:09:08 COT 2021
     */
    private String mensageEstado;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column URL_MIG_PROD.ACTIVO
     *
     * @mbg.generated Wed Nov 10 10:09:08 COT 2021
     */
    private Short activo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column URL_MIG_PROD.PROD
     *
     * @mbg.generated Wed Nov 10 10:09:08 COT 2021
     */
    private String prod;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column URL_MIG_PROD.COD_URL_DATA_NO_ESTRUCTURADA
     *
     * @return the value of URL_MIG_PROD.COD_URL_DATA_NO_ESTRUCTURADA
     *
     * @mbg.generated Wed Nov 10 10:09:08 COT 2021
     */
    public Long getCodUrlDataNoEstructurada() {
        return codUrlDataNoEstructurada;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column URL_MIG_PROD.COD_URL_DATA_NO_ESTRUCTURADA
     *
     * @param codUrlDataNoEstructurada the value for URL_MIG_PROD.COD_URL_DATA_NO_ESTRUCTURADA
     *
     * @mbg.generated Wed Nov 10 10:09:08 COT 2021
     */
    public void setCodUrlDataNoEstructurada(Long codUrlDataNoEstructurada) {
        this.codUrlDataNoEstructurada = codUrlDataNoEstructurada;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column URL_MIG_PROD.NUMERO_IDENTIFICACION
     *
     * @return the value of URL_MIG_PROD.NUMERO_IDENTIFICACION
     *
     * @mbg.generated Wed Nov 10 10:09:08 COT 2021
     */
    public String getNumeroIdentificacion() {
        return numeroIdentificacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column URL_MIG_PROD.NUMERO_IDENTIFICACION
     *
     * @param numeroIdentificacion the value for URL_MIG_PROD.NUMERO_IDENTIFICACION
     *
     * @mbg.generated Wed Nov 10 10:09:08 COT 2021
     */
    public void setNumeroIdentificacion(String numeroIdentificacion) {
        this.numeroIdentificacion = numeroIdentificacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column URL_MIG_PROD.ID_REGISTRO
     *
     * @return the value of URL_MIG_PROD.ID_REGISTRO
     *
     * @mbg.generated Wed Nov 10 10:09:08 COT 2021
     */
    public String getIdRegistro() {
        return idRegistro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column URL_MIG_PROD.ID_REGISTRO
     *
     * @param idRegistro the value for URL_MIG_PROD.ID_REGISTRO
     *
     * @mbg.generated Wed Nov 10 10:09:08 COT 2021
     */
    public void setIdRegistro(String idRegistro) {
        this.idRegistro = idRegistro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column URL_MIG_PROD.RUTA_ARCHIVO
     *
     * @return the value of URL_MIG_PROD.RUTA_ARCHIVO
     *
     * @mbg.generated Wed Nov 10 10:09:08 COT 2021
     */
    public String getRutaArchivo() {
        return rutaArchivo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column URL_MIG_PROD.RUTA_ARCHIVO
     *
     * @param rutaArchivo the value for URL_MIG_PROD.RUTA_ARCHIVO
     *
     * @mbg.generated Wed Nov 10 10:09:08 COT 2021
     */
    public void setRutaArchivo(String rutaArchivo) {
        this.rutaArchivo = rutaArchivo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column URL_MIG_PROD.TABLA_DESTINO
     *
     * @return the value of URL_MIG_PROD.TABLA_DESTINO
     *
     * @mbg.generated Wed Nov 10 10:09:08 COT 2021
     */
    public String getTablaDestino() {
        return tablaDestino;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column URL_MIG_PROD.TABLA_DESTINO
     *
     * @param tablaDestino the value for URL_MIG_PROD.TABLA_DESTINO
     *
     * @mbg.generated Wed Nov 10 10:09:08 COT 2021
     */
    public void setTablaDestino(String tablaDestino) {
        this.tablaDestino = tablaDestino;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column URL_MIG_PROD.NOMBRE_CAMPO
     *
     * @return the value of URL_MIG_PROD.NOMBRE_CAMPO
     *
     * @mbg.generated Wed Nov 10 10:09:08 COT 2021
     */
    public String getNombreCampo() {
        return nombreCampo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column URL_MIG_PROD.NOMBRE_CAMPO
     *
     * @param nombreCampo the value for URL_MIG_PROD.NOMBRE_CAMPO
     *
     * @mbg.generated Wed Nov 10 10:09:08 COT 2021
     */
    public void setNombreCampo(String nombreCampo) {
        this.nombreCampo = nombreCampo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column URL_MIG_PROD.URL_GENERADA
     *
     * @return the value of URL_MIG_PROD.URL_GENERADA
     *
     * @mbg.generated Wed Nov 10 10:09:08 COT 2021
     */
    public String getUrlGenerada() {
        return urlGenerada;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column URL_MIG_PROD.URL_GENERADA
     *
     * @param urlGenerada the value for URL_MIG_PROD.URL_GENERADA
     *
     * @mbg.generated Wed Nov 10 10:09:08 COT 2021
     */
    public void setUrlGenerada(String urlGenerada) {
        this.urlGenerada = urlGenerada;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column URL_MIG_PROD.PROCESADO
     *
     * @return the value of URL_MIG_PROD.PROCESADO
     *
     * @mbg.generated Wed Nov 10 10:09:08 COT 2021
     */
    public String getProcesado() {
        return procesado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column URL_MIG_PROD.PROCESADO
     *
     * @param procesado the value for URL_MIG_PROD.PROCESADO
     *
     * @mbg.generated Wed Nov 10 10:09:08 COT 2021
     */
    public void setProcesado(String procesado) {
        this.procesado = procesado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column URL_MIG_PROD.FECHA_EJECUCION
     *
     * @return the value of URL_MIG_PROD.FECHA_EJECUCION
     *
     * @mbg.generated Wed Nov 10 10:09:08 COT 2021
     */
    public Date getFechaEjecucion() {
        return fechaEjecucion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column URL_MIG_PROD.FECHA_EJECUCION
     *
     * @param fechaEjecucion the value for URL_MIG_PROD.FECHA_EJECUCION
     *
     * @mbg.generated Wed Nov 10 10:09:08 COT 2021
     */
    public void setFechaEjecucion(Date fechaEjecucion) {
        this.fechaEjecucion = fechaEjecucion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column URL_MIG_PROD.CODIGO_ESTADO
     *
     * @return the value of URL_MIG_PROD.CODIGO_ESTADO
     *
     * @mbg.generated Wed Nov 10 10:09:08 COT 2021
     */
    public String getCodigoEstado() {
        return codigoEstado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column URL_MIG_PROD.CODIGO_ESTADO
     *
     * @param codigoEstado the value for URL_MIG_PROD.CODIGO_ESTADO
     *
     * @mbg.generated Wed Nov 10 10:09:08 COT 2021
     */
    public void setCodigoEstado(String codigoEstado) {
        this.codigoEstado = codigoEstado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column URL_MIG_PROD.MENSAGE_ESTADO
     *
     * @return the value of URL_MIG_PROD.MENSAGE_ESTADO
     *
     * @mbg.generated Wed Nov 10 10:09:08 COT 2021
     */
    public String getMensageEstado() {
        return mensageEstado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column URL_MIG_PROD.MENSAGE_ESTADO
     *
     * @param mensageEstado the value for URL_MIG_PROD.MENSAGE_ESTADO
     *
     * @mbg.generated Wed Nov 10 10:09:08 COT 2021
     */
    public void setMensageEstado(String mensageEstado) {
        this.mensageEstado = mensageEstado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column URL_MIG_PROD.ACTIVO
     *
     * @return the value of URL_MIG_PROD.ACTIVO
     *
     * @mbg.generated Wed Nov 10 10:09:08 COT 2021
     */
    public Short getActivo() {
        return activo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column URL_MIG_PROD.ACTIVO
     *
     * @param activo the value for URL_MIG_PROD.ACTIVO
     *
     * @mbg.generated Wed Nov 10 10:09:08 COT 2021
     */
    public void setActivo(Short activo) {
        this.activo = activo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column URL_MIG_PROD.PROD
     *
     * @return the value of URL_MIG_PROD.PROD
     *
     * @mbg.generated Wed Nov 10 10:09:08 COT 2021
     */
    public String getProd() {
        return prod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column URL_MIG_PROD.PROD
     *
     * @param prod the value for URL_MIG_PROD.PROD
     *
     * @mbg.generated Wed Nov 10 10:09:08 COT 2021
     */
    public void setProd(String prod) {
        this.prod = prod;
    }
}