package co.gov.dafp.sigep2.entities;

import java.math.BigDecimal;
import java.util.Date;

import co.gov.dafp.sigep2.utils.ErrorMensajes;

public class AuditoriaConfiguracion extends ErrorMensajes  {
    /**
	 * 
	 */
	private static final long serialVersionUID = -260392947884074727L;


	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column AUDITORIA_CONFIGURACION.COD_TABLA_AUDITORIA
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	private Short codTablaAuditoria;
	
	


	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column AUDITORIA_CONFIGURACION.NOMBRE_TABLA
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	private String nombreTabla;


	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column AUDITORIA_CONFIGURACION.DESCRIPCION_TABLA
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	private String descripcionTabla;


	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column AUDITORIA_CONFIGURACION.FLG_INSERT
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	private Short flgInsert;


	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column AUDITORIA_CONFIGURACION.FLG_DELETE
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	private Short flgDelete;


	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column AUDITORIA_CONFIGURACION.FLG_UPDATE
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	private Short flgUpdate;


	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column AUDITORIA_CONFIGURACION.FLG_SELECT
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	private Short flgSelect;


	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column AUDITORIA_CONFIGURACION.FECHA_INICIO_AUDITORIA
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	private Date fechaInicioAuditoria;


	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column AUDITORIA_CONFIGURACION.FECHA_FIN_AUDITORIA
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	private Date fechaFinAuditoria;


	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column AUDITORIA_CONFIGURACION.AUD_FECHA_ACTUALIZACION
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	private Date audFechaActualizacion;


	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column AUDITORIA_CONFIGURACION.AUD_COD_USUARIO
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	private BigDecimal audCodUsuario;


	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column AUDITORIA_CONFIGURACION.AUD_COD_ROL
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	private Integer audCodRol;


	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column AUDITORIA_CONFIGURACION.AUD_ACCION
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	private Integer audAccion;
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column AUDITORIA_CONFIGURACION.NOMBRE_FUNCIONAL
	 * @mbg.generated  Fri Jan 11 09:41:27 COT 2019
	 */
	private String nombreFuncional;



	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column AUDITORIA_CONFIGURACION.COD_TABLA_AUDITORIA
	 * @return  the value of AUDITORIA_CONFIGURACION.COD_TABLA_AUDITORIA
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public Short getCodTablaAuditoria() {
		return codTablaAuditoria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column AUDITORIA_CONFIGURACION.COD_TABLA_AUDITORIA
	 * @param codTablaAuditoria  the value for AUDITORIA_CONFIGURACION.COD_TABLA_AUDITORIA
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public void setCodTablaAuditoria(Short codTablaAuditoria) {
		this.codTablaAuditoria = codTablaAuditoria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column AUDITORIA_CONFIGURACION.NOMBRE_TABLA
	 * @return  the value of AUDITORIA_CONFIGURACION.NOMBRE_TABLA
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public String getNombreTabla() {
		return nombreTabla;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column AUDITORIA_CONFIGURACION.NOMBRE_TABLA
	 * @param nombreTabla  the value for AUDITORIA_CONFIGURACION.NOMBRE_TABLA
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public void setNombreTabla(String nombreTabla) {
		this.nombreTabla = nombreTabla;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column AUDITORIA_CONFIGURACION.DESCRIPCION_TABLA
	 * @return  the value of AUDITORIA_CONFIGURACION.DESCRIPCION_TABLA
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public String getDescripcionTabla() {
		return descripcionTabla;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column AUDITORIA_CONFIGURACION.DESCRIPCION_TABLA
	 * @param descripcionTabla  the value for AUDITORIA_CONFIGURACION.DESCRIPCION_TABLA
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public void setDescripcionTabla(String descripcionTabla) {
		this.descripcionTabla = descripcionTabla;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column AUDITORIA_CONFIGURACION.FLG_INSERT
	 * @return  the value of AUDITORIA_CONFIGURACION.FLG_INSERT
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public boolean getFlgInsert() {
		if(this.flgInsert!=null && this.flgInsert.intValue()==1)
		{
			return true;
		}
		else
		{
			return false;	
		}
		
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column AUDITORIA_CONFIGURACION.FLG_INSERT
	 * @param flgInsert  the value for AUDITORIA_CONFIGURACION.FLG_INSERT
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public void setFlgInsert(Short flgInsert) {
		this.flgInsert = flgInsert;
	}

	
	public void setFlgInsert(boolean flgInsert) {
		if(flgInsert)
		{
			this.flgInsert=1;
		}
		else {
			this.flgInsert=0;
		}
		
		
	}
	
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column AUDITORIA_CONFIGURACION.FLG_DELETE
	 * @return  the value of AUDITORIA_CONFIGURACION.FLG_DELETE
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public boolean getFlgDelete() {
		if(this.flgDelete!=null && this.flgDelete.intValue()==1)
		{
			return true;
		}
		else
		{
			return false;
		}
		
	}

	

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column AUDITORIA_CONFIGURACION.FLG_DELETE
	 * @param flgDelete  the value for AUDITORIA_CONFIGURACION.FLG_DELETE
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public void setFlgDelete(Short flgDelete) {
		this.flgDelete = flgDelete;
	}

	public void setFlgDelete(boolean flgDelete) {
		if(flgDelete)
		{
			this.flgDelete=1;
		}else{
			this.flgDelete=0;
		}
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column AUDITORIA_CONFIGURACION.FLG_UPDATE
	 * @return  the value of AUDITORIA_CONFIGURACION.FLG_UPDATE
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public boolean getFlgUpdate() {
		if(this.flgUpdate!= null && flgUpdate.intValue()==1)
		{
			return true;
		}
		return false;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column AUDITORIA_CONFIGURACION.FLG_UPDATE
	 * @param flgUpdate  the value for AUDITORIA_CONFIGURACION.FLG_UPDATE
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public void setFlgUpdate(Short flgUpdate) {
		this.flgUpdate = flgUpdate;
	}

	public void setFlgUpdate(boolean flgUpdate) {
		if(flgUpdate)
		{
			this.flgUpdate=1;
		}else{
			this.flgUpdate=0;
		}
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column AUDITORIA_CONFIGURACION.FLG_SELECT
	 * @return  the value of AUDITORIA_CONFIGURACION.FLG_SELECT
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public boolean getFlgSelect() {
		if(this.flgSelect != null && this.flgSelect.intValue()==1)
		{
			return true;
		}
		return false;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column AUDITORIA_CONFIGURACION.FLG_SELECT
	 * @param flgSelect  the value for AUDITORIA_CONFIGURACION.FLG_SELECT
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public void setFlgSelect(Short flgSelect) {
		this.flgSelect = flgSelect;
	}
	
	public void setFlgSelect(boolean flgSelect) {
		if(flgSelect)
		{
			this.flgSelect=1;
		}
		
		else {
			this.flgSelect=0;
		}
		
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column AUDITORIA_CONFIGURACION.FECHA_INICIO_AUDITORIA
	 * @return  the value of AUDITORIA_CONFIGURACION.FECHA_INICIO_AUDITORIA
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public Date getFechaInicioAuditoria() {
		return fechaInicioAuditoria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column AUDITORIA_CONFIGURACION.FECHA_INICIO_AUDITORIA
	 * @param fechaInicioAuditoria  the value for AUDITORIA_CONFIGURACION.FECHA_INICIO_AUDITORIA
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public void setFechaInicioAuditoria(Date fechaInicioAuditoria) {
		this.fechaInicioAuditoria = fechaInicioAuditoria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column AUDITORIA_CONFIGURACION.FECHA_FIN_AUDITORIA
	 * @return  the value of AUDITORIA_CONFIGURACION.FECHA_FIN_AUDITORIA
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public Date getFechaFinAuditoria() {
		return fechaFinAuditoria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column AUDITORIA_CONFIGURACION.FECHA_FIN_AUDITORIA
	 * @param fechaFinAuditoria  the value for AUDITORIA_CONFIGURACION.FECHA_FIN_AUDITORIA
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public void setFechaFinAuditoria(Date fechaFinAuditoria) {
		this.fechaFinAuditoria = fechaFinAuditoria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column AUDITORIA_CONFIGURACION.AUD_FECHA_ACTUALIZACION
	 * @return  the value of AUDITORIA_CONFIGURACION.AUD_FECHA_ACTUALIZACION
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public Date getAudFechaActualizacion() {
		return audFechaActualizacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column AUDITORIA_CONFIGURACION.AUD_FECHA_ACTUALIZACION
	 * @param audFechaActualizacion  the value for AUDITORIA_CONFIGURACION.AUD_FECHA_ACTUALIZACION
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public void setAudFechaActualizacion(Date audFechaActualizacion) {
		this.audFechaActualizacion = audFechaActualizacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column AUDITORIA_CONFIGURACION.AUD_COD_USUARIO
	 * @return  the value of AUDITORIA_CONFIGURACION.AUD_COD_USUARIO
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public BigDecimal getAudCodUsuario() {
		return audCodUsuario;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column AUDITORIA_CONFIGURACION.AUD_COD_USUARIO
	 * @param audCodUsuario  the value for AUDITORIA_CONFIGURACION.AUD_COD_USUARIO
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public void setAudCodUsuario(BigDecimal audCodUsuario) {
		this.audCodUsuario = audCodUsuario;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column AUDITORIA_CONFIGURACION.AUD_COD_ROL
	 * @return  the value of AUDITORIA_CONFIGURACION.AUD_COD_ROL
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public Integer getAudCodRol() {
		return audCodRol;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column AUDITORIA_CONFIGURACION.AUD_COD_ROL
	 * @param audCodRol  the value for AUDITORIA_CONFIGURACION.AUD_COD_ROL
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public void setAudCodRol(Integer audCodRol) {
		this.audCodRol = audCodRol;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column AUDITORIA_CONFIGURACION.AUD_ACCION
	 * @return  the value of AUDITORIA_CONFIGURACION.AUD_ACCION
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public Integer getAudAccion() {
		return audAccion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column AUDITORIA_CONFIGURACION.AUD_ACCION
	 * @param audAccion  the value for AUDITORIA_CONFIGURACION.AUD_ACCION
	 * @mbg.generated  Tue Jan 30 14:07:49 COT 2018
	 */
	public void setAudAccion(Integer audAccion) {
		this.audAccion = audAccion;
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column AUDITORIA_CONFIGURACION.NOMBRE_FUNCIONAL
	 * @return  the value of AUDITORIA_CONFIGURACION.NOMBRE_FUNCIONAL
	 * @mbg.generated  Fri Jan 11 09:41:27 COT 2019
	 */
	public String getNombreFuncional() {
		return nombreFuncional;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column AUDITORIA_CONFIGURACION.NOMBRE_FUNCIONAL
	 * @param nombreFuncional  the value for AUDITORIA_CONFIGURACION.NOMBRE_FUNCIONAL
	 * @mbg.generated  Fri Jan 11 09:41:27 COT 2019
	 */
	public void setNombreFuncional(String nombreFuncional) {
		this.nombreFuncional = nombreFuncional;
	}

	
	private int total;
	private int limitInit;
    private int limitEnd;
    
    
    
    /**
	 * @return the limitInit
	 */
	public int getLimitInit() {
		return limitInit;
	}

	/**
	 * @param limitInit the limitInit to set
	 */
	public void setLimitInit(int limitInit) {
		this.limitInit = limitInit;
	}
    
    
	/**
	 * @return the limitEnd
	 */
	public int getLimitEnd() {
		return limitEnd;
	}

	/**
	 * @param limitEnd the limitEnd to set
	 */
	public void setLimitEnd(int limitEnd) {
		this.limitEnd = limitEnd;
	}

	/**
	 * @return the total
	 */
	public int getTotal() {
		return total;
	}

	/**
	 * @param total the total to set
	 */
	public void setTotal(int total) {
		this.total = total;
	}
}