package co.gov.dafp.sigep2.entities;

import java.math.BigDecimal;
import java.util.Date;

import co.gov.dafp.sigep2.utils.ErrorMensajes;

public class BienesPatrimonio extends ErrorMensajes{
    /**
	 * 
	 */
	private static final long serialVersionUID = -1036354561583445639L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BIENES_PATRIMONIO.COD_BIEN_PATRIMONIO
	 * @mbg.generated  Tue Mar 13 09:39:59 COT 2018
	 */
	private Long codBienPatrimonio;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BIENES_PATRIMONIO.COD_DECLARACION
	 * @mbg.generated  Tue Mar 13 09:39:59 COT 2018
	 */
	private BigDecimal codDeclaracion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BIENES_PATRIMONIO.COD_TIPO_BIEN
	 * @mbg.generated  Tue Mar 13 09:39:59 COT 2018
	 */
	private Integer codTipoBien;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BIENES_PATRIMONIO.TIPO_BIEN_MIG
	 * @mbg.generated  Tue Mar 13 09:39:59 COT 2018
	 */
	private String tipoBienMig;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BIENES_PATRIMONIO.IDENTIFICACION
	 * @mbg.generated  Tue Mar 13 09:39:59 COT 2018
	 */
	private String identificacion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BIENES_PATRIMONIO.VALOR
	 * @mbg.generated  Tue Mar 13 09:39:59 COT 2018
	 */
	private BigDecimal valor;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BIENES_PATRIMONIO.AUD_FECHA_ACTUALIZACION
	 * @mbg.generated  Tue Mar 13 09:39:59 COT 2018
	 */
	private Date audFechaActualizacion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BIENES_PATRIMONIO.AUD_COD_USUARIO
	 * @mbg.generated  Tue Mar 13 09:39:59 COT 2018
	 */
	private BigDecimal audCodUsuario;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BIENES_PATRIMONIO.AUD_COD_ROL
	 * @mbg.generated  Tue Mar 13 09:39:59 COT 2018
	 */
	private Integer audCodRol;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BIENES_PATRIMONIO.AUD_ACCION
	 * @mbg.generated  Tue Mar 13 09:39:59 COT 2018
	 */
	private Integer audAccion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column BIENES_PATRIMONIO.FLG_ACTIVO
	 * @mbg.generated  Tue Mar 13 09:39:59 COT 2018
	 */
	private Short flgActivo;
	
	/**
	 * 
	 */
	private int limitIni;
	
	/**
	 * 
	 */
	private int limitFin;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BIENES_PATRIMONIO.COD_BIEN_PATRIMONIO
	 * @return  the value of BIENES_PATRIMONIO.COD_BIEN_PATRIMONIO
	 * @mbg.generated  Tue Mar 13 09:39:59 COT 2018
	 */
	public Long getCodBienPatrimonio() {
		return codBienPatrimonio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BIENES_PATRIMONIO.COD_BIEN_PATRIMONIO
	 * @param codBienPatrimonio  the value for BIENES_PATRIMONIO.COD_BIEN_PATRIMONIO
	 * @mbg.generated  Tue Mar 13 09:39:59 COT 2018
	 */
	public void setCodBienPatrimonio(Long codBienPatrimonio) {
		this.codBienPatrimonio = codBienPatrimonio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BIENES_PATRIMONIO.COD_DECLARACION
	 * @return  the value of BIENES_PATRIMONIO.COD_DECLARACION
	 * @mbg.generated  Tue Mar 13 09:39:59 COT 2018
	 */
	public BigDecimal getCodDeclaracion() {
		return codDeclaracion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BIENES_PATRIMONIO.COD_DECLARACION
	 * @param codDeclaracion  the value for BIENES_PATRIMONIO.COD_DECLARACION
	 * @mbg.generated  Tue Mar 13 09:39:59 COT 2018
	 */
	public void setCodDeclaracion(BigDecimal codDeclaracion) {
		this.codDeclaracion = codDeclaracion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BIENES_PATRIMONIO.COD_TIPO_BIEN
	 * @return  the value of BIENES_PATRIMONIO.COD_TIPO_BIEN
	 * @mbg.generated  Tue Mar 13 09:39:59 COT 2018
	 */
	public Integer getCodTipoBien() {
		return codTipoBien;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BIENES_PATRIMONIO.COD_TIPO_BIEN
	 * @param codTipoBien  the value for BIENES_PATRIMONIO.COD_TIPO_BIEN
	 * @mbg.generated  Tue Mar 13 09:39:59 COT 2018
	 */
	public void setCodTipoBien(Integer codTipoBien) {
		this.codTipoBien = codTipoBien;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BIENES_PATRIMONIO.TIPO_BIEN_MIG
	 * @return  the value of BIENES_PATRIMONIO.TIPO_BIEN_MIG
	 * @mbg.generated  Tue Mar 13 09:39:59 COT 2018
	 */
	public String getTipoBienMig() {
		return tipoBienMig;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BIENES_PATRIMONIO.TIPO_BIEN_MIG
	 * @param tipoBienMig  the value for BIENES_PATRIMONIO.TIPO_BIEN_MIG
	 * @mbg.generated  Tue Mar 13 09:39:59 COT 2018
	 */
	public void setTipoBienMig(String tipoBienMig) {
		this.tipoBienMig = tipoBienMig;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BIENES_PATRIMONIO.IDENTIFICACION
	 * @return  the value of BIENES_PATRIMONIO.IDENTIFICACION
	 * @mbg.generated  Tue Mar 13 09:39:59 COT 2018
	 */
	public String getIdentificacion() {
		return identificacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BIENES_PATRIMONIO.IDENTIFICACION
	 * @param identificacion  the value for BIENES_PATRIMONIO.IDENTIFICACION
	 * @mbg.generated  Tue Mar 13 09:39:59 COT 2018
	 */
	public void setIdentificacion(String identificacion) {
		this.identificacion = identificacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BIENES_PATRIMONIO.VALOR
	 * @return  the value of BIENES_PATRIMONIO.VALOR
	 * @mbg.generated  Tue Mar 13 09:39:59 COT 2018
	 */
	public BigDecimal getValor() {
		return valor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BIENES_PATRIMONIO.VALOR
	 * @param valor  the value for BIENES_PATRIMONIO.VALOR
	 * @mbg.generated  Tue Mar 13 09:39:59 COT 2018
	 */
	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BIENES_PATRIMONIO.AUD_FECHA_ACTUALIZACION
	 * @return  the value of BIENES_PATRIMONIO.AUD_FECHA_ACTUALIZACION
	 * @mbg.generated  Tue Mar 13 09:39:59 COT 2018
	 */
	public Date getAudFechaActualizacion() {
		return audFechaActualizacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BIENES_PATRIMONIO.AUD_FECHA_ACTUALIZACION
	 * @param audFechaActualizacion  the value for BIENES_PATRIMONIO.AUD_FECHA_ACTUALIZACION
	 * @mbg.generated  Tue Mar 13 09:39:59 COT 2018
	 */
	public void setAudFechaActualizacion(Date audFechaActualizacion) {
		this.audFechaActualizacion = audFechaActualizacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BIENES_PATRIMONIO.AUD_COD_USUARIO
	 * @return  the value of BIENES_PATRIMONIO.AUD_COD_USUARIO
	 * @mbg.generated  Tue Mar 13 09:39:59 COT 2018
	 */
	public BigDecimal getAudCodUsuario() {
		return audCodUsuario;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BIENES_PATRIMONIO.AUD_COD_USUARIO
	 * @param audCodUsuario  the value for BIENES_PATRIMONIO.AUD_COD_USUARIO
	 * @mbg.generated  Tue Mar 13 09:39:59 COT 2018
	 */
	public void setAudCodUsuario(BigDecimal audCodUsuario) {
		this.audCodUsuario = audCodUsuario;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BIENES_PATRIMONIO.AUD_COD_ROL
	 * @return  the value of BIENES_PATRIMONIO.AUD_COD_ROL
	 * @mbg.generated  Tue Mar 13 09:39:59 COT 2018
	 */
	public Integer getAudCodRol() {
		return audCodRol;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BIENES_PATRIMONIO.AUD_COD_ROL
	 * @param audCodRol  the value for BIENES_PATRIMONIO.AUD_COD_ROL
	 * @mbg.generated  Tue Mar 13 09:39:59 COT 2018
	 */
	public void setAudCodRol(Integer audCodRol) {
		this.audCodRol = audCodRol;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BIENES_PATRIMONIO.AUD_ACCION
	 * @return  the value of BIENES_PATRIMONIO.AUD_ACCION
	 * @mbg.generated  Tue Mar 13 09:39:59 COT 2018
	 */
	public Integer getAudAccion() {
		return audAccion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BIENES_PATRIMONIO.AUD_ACCION
	 * @param audAccion  the value for BIENES_PATRIMONIO.AUD_ACCION
	 * @mbg.generated  Tue Mar 13 09:39:59 COT 2018
	 */
	public void setAudAccion(Integer audAccion) {
		this.audAccion = audAccion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column BIENES_PATRIMONIO.FLG_ACTIVO
	 * @return  the value of BIENES_PATRIMONIO.FLG_ACTIVO
	 * @mbg.generated  Tue Mar 13 09:39:59 COT 2018
	 */
	public Short getFlgActivo() {
		return flgActivo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column BIENES_PATRIMONIO.FLG_ACTIVO
	 * @param flgActivo  the value for BIENES_PATRIMONIO.FLG_ACTIVO
	 * @mbg.generated  Tue Mar 13 09:39:59 COT 2018
	 */
	public void setFlgActivo(Short flgActivo) {
		this.flgActivo = flgActivo;
	}

	/**
	 * @return the limitIni
	 */
	public int getLimitIni() {
		return limitIni;
	}

	/**
	 * @param limitIni the limitIni to set
	 */
	public void setLimitIni(int limitIni) {
		this.limitIni = limitIni;
	}

	/**
	 * @return the limitFin
	 */
	public int getLimitFin() {
		return limitFin;
	}

	/**
	 * @param limitFin the limitFin to set
	 */
	public void setLimitFin(int limitFin) {
		this.limitFin = limitFin;
	}

}