package co.gov.dafp.sigep2.entities;

import java.util.Date;

import co.gov.dafp.sigep2.utils.ErrorMensajes;

public class CmCrearNomenclaturaSalarial extends ErrorMensajes{
    /**
	 * 
	 */
	private static final long serialVersionUID = -8117969714219595902L;

	 /**
		 * This field was generated by MyBatis Generator. This field corresponds to the database column CM_CREAR_NOMENCLATURA_SALARIAL.COD_CM_CREAR_NOMENCLATURA_SALARIAL
		 * @mbg.generated  Tue Jan 29 15:29:43 COT 2019
		 */
		private Long codCmCrearNomenclaturaSalarial;
		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the database column CM_CREAR_NOMENCLATURA_SALARIAL.TIPO_NORMA
		 * @mbg.generated  Tue Jan 29 15:29:43 COT 2019
		 */
		private String tipoNorma;
		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the database column CM_CREAR_NOMENCLATURA_SALARIAL.FECHA_NORMA
		 * @mbg.generated  Tue Jan 29 15:29:43 COT 2019
		 */
		private String fechaNorma;
		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the database column CM_CREAR_NOMENCLATURA_SALARIAL.NUMERO_NORMA
		 * @mbg.generated  Tue Jan 29 15:29:43 COT 2019
		 */
		private String numeroNorma;
		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the database column CM_CREAR_NOMENCLATURA_SALARIAL.NOMBRE_NOMENCLATURA
		 * @mbg.generated  Tue Jan 29 15:29:43 COT 2019
		 */
		private String nombreNomenclatura;
		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the database column CM_CREAR_NOMENCLATURA_SALARIAL.NIVEL_CARGO
		 * @mbg.generated  Tue Jan 29 15:29:43 COT 2019
		 */
		private String nivelCargo;
		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the database column CM_CREAR_NOMENCLATURA_SALARIAL.DENOMINACION_NOMENCLATURA
		 * @mbg.generated  Tue Jan 29 15:29:43 COT 2019
		 */
		private String denominacionNomenclatura;
		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the database column CM_CREAR_NOMENCLATURA_SALARIAL.CODIGO_NOMENCLATURA
		 * @mbg.generated  Tue Jan 29 15:29:43 COT 2019
		 */
		private String codigoNomenclatura;
		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the database column CM_CREAR_NOMENCLATURA_SALARIAL.GRADO_NOMENCLATURA
		 * @mbg.generated  Tue Jan 29 15:29:43 COT 2019
		 */
		private String gradoNomenclatura;
		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the database column CM_CREAR_NOMENCLATURA_SALARIAL.TIPO_MONEDA
		 * @mbg.generated  Tue Jan 29 15:29:43 COT 2019
		 */
		private String tipoMoneda;
		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the database column CM_CREAR_NOMENCLATURA_SALARIAL.CODIGO_ESCALA
		 * @mbg.generated  Tue Jan 29 15:29:43 COT 2019
		 */
		private String codigoEscala;
		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the database column CM_CREAR_NOMENCLATURA_SALARIAL.GRADO_ESCALA
		 * @mbg.generated  Tue Jan 29 15:29:43 COT 2019
		 */
		private String gradoEscala;
		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the database column CM_CREAR_NOMENCLATURA_SALARIAL.DENOMINACION_ESCALA
		 * @mbg.generated  Tue Jan 29 15:29:43 COT 2019
		 */
		private String denominacionEscala;
		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the database column CM_CREAR_NOMENCLATURA_SALARIAL.ASIGNACION_BASICA
		 * @mbg.generated  Tue Jan 29 15:29:43 COT 2019
		 */
		private String asignacionBasica;
		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the database column CM_CREAR_NOMENCLATURA_SALARIAL.AUD_FECHA_ACTUALIZACION
		 * @mbg.generated  Tue Jan 29 15:29:43 COT 2019
		 */
		private Date audFechaActualizacion;
		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the database column CM_CREAR_NOMENCLATURA_SALARIAL.AUD_COD_USUARIO
		 * @mbg.generated  Tue Jan 29 15:29:43 COT 2019
		 */
		private Long audCodUsuario;
		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the database column CM_CREAR_NOMENCLATURA_SALARIAL.AUD_COD_ROL
		 * @mbg.generated  Tue Jan 29 15:29:43 COT 2019
		 */
		private Integer audCodRol;
		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the database column CM_CREAR_NOMENCLATURA_SALARIAL.AUD_ACCION
		 * @mbg.generated  Tue Jan 29 15:29:43 COT 2019
		 */
		private Integer audAccion;
		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the database column CM_CREAR_NOMENCLATURA_SALARIAL.COD_PROCESO_CARGA_MASIVA
		 * @mbg.generated  Tue Jan 29 15:29:43 COT 2019
		 */
		private Long codProcesoCargaMasiva;
		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the database column CM_CREAR_NOMENCLATURA_SALARIAL.RESULTADO
		 * @mbg.generated  Tue Jan 29 15:29:43 COT 2019
		 */
		private String resultado;
		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the database column CM_CREAR_NOMENCLATURA_SALARIAL.CLASIFICACION_ORGANICA
		 * @mbg.generated  Tue Jan 29 15:29:43 COT 2019
		 */
		private String clasificacionOrganica;
		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the database column CM_CREAR_NOMENCLATURA_SALARIAL.SISTEMA_CARRERA
		 * @mbg.generated  Tue Jan 29 15:29:43 COT 2019
		 */
		private String sistemaCarrera;

		/**
		 * This method was generated by MyBatis Generator. This method returns the value of the database column CM_CREAR_NOMENCLATURA_SALARIAL.COD_CM_CREAR_NOMENCLATURA_SALARIAL
		 * @return  the value of CM_CREAR_NOMENCLATURA_SALARIAL.COD_CM_CREAR_NOMENCLATURA_SALARIAL
		 * @mbg.generated  Tue Jan 29 15:29:43 COT 2019
		 */
		public Long getCodCmCrearNomenclaturaSalarial() {
			return codCmCrearNomenclaturaSalarial;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the value of the database column CM_CREAR_NOMENCLATURA_SALARIAL.COD_CM_CREAR_NOMENCLATURA_SALARIAL
		 * @param codCmCrearNomenclaturaSalarial  the value for CM_CREAR_NOMENCLATURA_SALARIAL.COD_CM_CREAR_NOMENCLATURA_SALARIAL
		 * @mbg.generated  Tue Jan 29 15:29:43 COT 2019
		 */
		public void setCodCmCrearNomenclaturaSalarial(Long codCmCrearNomenclaturaSalarial) {
			this.codCmCrearNomenclaturaSalarial = codCmCrearNomenclaturaSalarial;
		}

		/**
		 * This method was generated by MyBatis Generator. This method returns the value of the database column CM_CREAR_NOMENCLATURA_SALARIAL.TIPO_NORMA
		 * @return  the value of CM_CREAR_NOMENCLATURA_SALARIAL.TIPO_NORMA
		 * @mbg.generated  Tue Jan 29 15:29:43 COT 2019
		 */
		public String getTipoNorma() {
			return tipoNorma;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the value of the database column CM_CREAR_NOMENCLATURA_SALARIAL.TIPO_NORMA
		 * @param tipoNorma  the value for CM_CREAR_NOMENCLATURA_SALARIAL.TIPO_NORMA
		 * @mbg.generated  Tue Jan 29 15:29:43 COT 2019
		 */
		public void setTipoNorma(String tipoNorma) {
			this.tipoNorma = tipoNorma;
		}

		/**
		 * This method was generated by MyBatis Generator. This method returns the value of the database column CM_CREAR_NOMENCLATURA_SALARIAL.FECHA_NORMA
		 * @return  the value of CM_CREAR_NOMENCLATURA_SALARIAL.FECHA_NORMA
		 * @mbg.generated  Tue Jan 29 15:29:43 COT 2019
		 */
		public String getFechaNorma() {
			return fechaNorma;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the value of the database column CM_CREAR_NOMENCLATURA_SALARIAL.FECHA_NORMA
		 * @param fechaNorma  the value for CM_CREAR_NOMENCLATURA_SALARIAL.FECHA_NORMA
		 * @mbg.generated  Tue Jan 29 15:29:43 COT 2019
		 */
		public void setFechaNorma(String fechaNorma) {
			this.fechaNorma = fechaNorma;
		}

		/**
		 * This method was generated by MyBatis Generator. This method returns the value of the database column CM_CREAR_NOMENCLATURA_SALARIAL.NUMERO_NORMA
		 * @return  the value of CM_CREAR_NOMENCLATURA_SALARIAL.NUMERO_NORMA
		 * @mbg.generated  Tue Jan 29 15:29:43 COT 2019
		 */
		public String getNumeroNorma() {
			return numeroNorma;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the value of the database column CM_CREAR_NOMENCLATURA_SALARIAL.NUMERO_NORMA
		 * @param numeroNorma  the value for CM_CREAR_NOMENCLATURA_SALARIAL.NUMERO_NORMA
		 * @mbg.generated  Tue Jan 29 15:29:43 COT 2019
		 */
		public void setNumeroNorma(String numeroNorma) {
			this.numeroNorma = numeroNorma;
		}

		/**
		 * This method was generated by MyBatis Generator. This method returns the value of the database column CM_CREAR_NOMENCLATURA_SALARIAL.NOMBRE_NOMENCLATURA
		 * @return  the value of CM_CREAR_NOMENCLATURA_SALARIAL.NOMBRE_NOMENCLATURA
		 * @mbg.generated  Tue Jan 29 15:29:43 COT 2019
		 */
		public String getNombreNomenclatura() {
			return nombreNomenclatura;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the value of the database column CM_CREAR_NOMENCLATURA_SALARIAL.NOMBRE_NOMENCLATURA
		 * @param nombreNomenclatura  the value for CM_CREAR_NOMENCLATURA_SALARIAL.NOMBRE_NOMENCLATURA
		 * @mbg.generated  Tue Jan 29 15:29:43 COT 2019
		 */
		public void setNombreNomenclatura(String nombreNomenclatura) {
			this.nombreNomenclatura = nombreNomenclatura;
		}

		/**
		 * This method was generated by MyBatis Generator. This method returns the value of the database column CM_CREAR_NOMENCLATURA_SALARIAL.NIVEL_CARGO
		 * @return  the value of CM_CREAR_NOMENCLATURA_SALARIAL.NIVEL_CARGO
		 * @mbg.generated  Tue Jan 29 15:29:43 COT 2019
		 */
		public String getNivelCargo() {
			return nivelCargo;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the value of the database column CM_CREAR_NOMENCLATURA_SALARIAL.NIVEL_CARGO
		 * @param nivelCargo  the value for CM_CREAR_NOMENCLATURA_SALARIAL.NIVEL_CARGO
		 * @mbg.generated  Tue Jan 29 15:29:43 COT 2019
		 */
		public void setNivelCargo(String nivelCargo) {
			this.nivelCargo = nivelCargo;
		}

		/**
		 * This method was generated by MyBatis Generator. This method returns the value of the database column CM_CREAR_NOMENCLATURA_SALARIAL.DENOMINACION_NOMENCLATURA
		 * @return  the value of CM_CREAR_NOMENCLATURA_SALARIAL.DENOMINACION_NOMENCLATURA
		 * @mbg.generated  Tue Jan 29 15:29:43 COT 2019
		 */
		public String getDenominacionNomenclatura() {
			return denominacionNomenclatura;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the value of the database column CM_CREAR_NOMENCLATURA_SALARIAL.DENOMINACION_NOMENCLATURA
		 * @param denominacionNomenclatura  the value for CM_CREAR_NOMENCLATURA_SALARIAL.DENOMINACION_NOMENCLATURA
		 * @mbg.generated  Tue Jan 29 15:29:43 COT 2019
		 */
		public void setDenominacionNomenclatura(String denominacionNomenclatura) {
			this.denominacionNomenclatura = denominacionNomenclatura;
		}

		/**
		 * This method was generated by MyBatis Generator. This method returns the value of the database column CM_CREAR_NOMENCLATURA_SALARIAL.CODIGO_NOMENCLATURA
		 * @return  the value of CM_CREAR_NOMENCLATURA_SALARIAL.CODIGO_NOMENCLATURA
		 * @mbg.generated  Tue Jan 29 15:29:43 COT 2019
		 */
		public String getCodigoNomenclatura() {
			return codigoNomenclatura;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the value of the database column CM_CREAR_NOMENCLATURA_SALARIAL.CODIGO_NOMENCLATURA
		 * @param codigoNomenclatura  the value for CM_CREAR_NOMENCLATURA_SALARIAL.CODIGO_NOMENCLATURA
		 * @mbg.generated  Tue Jan 29 15:29:43 COT 2019
		 */
		public void setCodigoNomenclatura(String codigoNomenclatura) {
			this.codigoNomenclatura = codigoNomenclatura;
		}

		/**
		 * This method was generated by MyBatis Generator. This method returns the value of the database column CM_CREAR_NOMENCLATURA_SALARIAL.GRADO_NOMENCLATURA
		 * @return  the value of CM_CREAR_NOMENCLATURA_SALARIAL.GRADO_NOMENCLATURA
		 * @mbg.generated  Tue Jan 29 15:29:43 COT 2019
		 */
		public String getGradoNomenclatura() {
			return gradoNomenclatura;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the value of the database column CM_CREAR_NOMENCLATURA_SALARIAL.GRADO_NOMENCLATURA
		 * @param gradoNomenclatura  the value for CM_CREAR_NOMENCLATURA_SALARIAL.GRADO_NOMENCLATURA
		 * @mbg.generated  Tue Jan 29 15:29:43 COT 2019
		 */
		public void setGradoNomenclatura(String gradoNomenclatura) {
			this.gradoNomenclatura = gradoNomenclatura;
		}

		/**
		 * This method was generated by MyBatis Generator. This method returns the value of the database column CM_CREAR_NOMENCLATURA_SALARIAL.TIPO_MONEDA
		 * @return  the value of CM_CREAR_NOMENCLATURA_SALARIAL.TIPO_MONEDA
		 * @mbg.generated  Tue Jan 29 15:29:43 COT 2019
		 */
		public String getTipoMoneda() {
			return tipoMoneda;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the value of the database column CM_CREAR_NOMENCLATURA_SALARIAL.TIPO_MONEDA
		 * @param tipoMoneda  the value for CM_CREAR_NOMENCLATURA_SALARIAL.TIPO_MONEDA
		 * @mbg.generated  Tue Jan 29 15:29:43 COT 2019
		 */
		public void setTipoMoneda(String tipoMoneda) {
			this.tipoMoneda = tipoMoneda;
		}

		/**
		 * This method was generated by MyBatis Generator. This method returns the value of the database column CM_CREAR_NOMENCLATURA_SALARIAL.CODIGO_ESCALA
		 * @return  the value of CM_CREAR_NOMENCLATURA_SALARIAL.CODIGO_ESCALA
		 * @mbg.generated  Tue Jan 29 15:29:43 COT 2019
		 */
		public String getCodigoEscala() {
			return codigoEscala;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the value of the database column CM_CREAR_NOMENCLATURA_SALARIAL.CODIGO_ESCALA
		 * @param codigoEscala  the value for CM_CREAR_NOMENCLATURA_SALARIAL.CODIGO_ESCALA
		 * @mbg.generated  Tue Jan 29 15:29:43 COT 2019
		 */
		public void setCodigoEscala(String codigoEscala) {
			this.codigoEscala = codigoEscala;
		}

		/**
		 * This method was generated by MyBatis Generator. This method returns the value of the database column CM_CREAR_NOMENCLATURA_SALARIAL.GRADO_ESCALA
		 * @return  the value of CM_CREAR_NOMENCLATURA_SALARIAL.GRADO_ESCALA
		 * @mbg.generated  Tue Jan 29 15:29:43 COT 2019
		 */
		public String getGradoEscala() {
			return gradoEscala;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the value of the database column CM_CREAR_NOMENCLATURA_SALARIAL.GRADO_ESCALA
		 * @param gradoEscala  the value for CM_CREAR_NOMENCLATURA_SALARIAL.GRADO_ESCALA
		 * @mbg.generated  Tue Jan 29 15:29:43 COT 2019
		 */
		public void setGradoEscala(String gradoEscala) {
			this.gradoEscala = gradoEscala;
		}

		/**
		 * This method was generated by MyBatis Generator. This method returns the value of the database column CM_CREAR_NOMENCLATURA_SALARIAL.DENOMINACION_ESCALA
		 * @return  the value of CM_CREAR_NOMENCLATURA_SALARIAL.DENOMINACION_ESCALA
		 * @mbg.generated  Tue Jan 29 15:29:43 COT 2019
		 */
		public String getDenominacionEscala() {
			return denominacionEscala;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the value of the database column CM_CREAR_NOMENCLATURA_SALARIAL.DENOMINACION_ESCALA
		 * @param denominacionEscala  the value for CM_CREAR_NOMENCLATURA_SALARIAL.DENOMINACION_ESCALA
		 * @mbg.generated  Tue Jan 29 15:29:43 COT 2019
		 */
		public void setDenominacionEscala(String denominacionEscala) {
			this.denominacionEscala = denominacionEscala;
		}

		/**
		 * This method was generated by MyBatis Generator. This method returns the value of the database column CM_CREAR_NOMENCLATURA_SALARIAL.ASIGNACION_BASICA
		 * @return  the value of CM_CREAR_NOMENCLATURA_SALARIAL.ASIGNACION_BASICA
		 * @mbg.generated  Tue Jan 29 15:29:43 COT 2019
		 */
		public String getAsignacionBasica() {
			return asignacionBasica;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the value of the database column CM_CREAR_NOMENCLATURA_SALARIAL.ASIGNACION_BASICA
		 * @param asignacionBasica  the value for CM_CREAR_NOMENCLATURA_SALARIAL.ASIGNACION_BASICA
		 * @mbg.generated  Tue Jan 29 15:29:43 COT 2019
		 */
		public void setAsignacionBasica(String asignacionBasica) {
			this.asignacionBasica = asignacionBasica;
		}

		/**
		 * This method was generated by MyBatis Generator. This method returns the value of the database column CM_CREAR_NOMENCLATURA_SALARIAL.AUD_FECHA_ACTUALIZACION
		 * @return  the value of CM_CREAR_NOMENCLATURA_SALARIAL.AUD_FECHA_ACTUALIZACION
		 * @mbg.generated  Tue Jan 29 15:29:43 COT 2019
		 */
		public Date getAudFechaActualizacion() {
			return audFechaActualizacion;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the value of the database column CM_CREAR_NOMENCLATURA_SALARIAL.AUD_FECHA_ACTUALIZACION
		 * @param audFechaActualizacion  the value for CM_CREAR_NOMENCLATURA_SALARIAL.AUD_FECHA_ACTUALIZACION
		 * @mbg.generated  Tue Jan 29 15:29:43 COT 2019
		 */
		public void setAudFechaActualizacion(Date audFechaActualizacion) {
			this.audFechaActualizacion = audFechaActualizacion;
		}

		/**
		 * This method was generated by MyBatis Generator. This method returns the value of the database column CM_CREAR_NOMENCLATURA_SALARIAL.AUD_COD_USUARIO
		 * @return  the value of CM_CREAR_NOMENCLATURA_SALARIAL.AUD_COD_USUARIO
		 * @mbg.generated  Tue Jan 29 15:29:43 COT 2019
		 */
		public Long getAudCodUsuario() {
			return audCodUsuario;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the value of the database column CM_CREAR_NOMENCLATURA_SALARIAL.AUD_COD_USUARIO
		 * @param audCodUsuario  the value for CM_CREAR_NOMENCLATURA_SALARIAL.AUD_COD_USUARIO
		 * @mbg.generated  Tue Jan 29 15:29:43 COT 2019
		 */
		public void setAudCodUsuario(Long audCodUsuario) {
			this.audCodUsuario = audCodUsuario;
		}

		/**
		 * This method was generated by MyBatis Generator. This method returns the value of the database column CM_CREAR_NOMENCLATURA_SALARIAL.AUD_COD_ROL
		 * @return  the value of CM_CREAR_NOMENCLATURA_SALARIAL.AUD_COD_ROL
		 * @mbg.generated  Tue Jan 29 15:29:43 COT 2019
		 */
		public Integer getAudCodRol() {
			return audCodRol;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the value of the database column CM_CREAR_NOMENCLATURA_SALARIAL.AUD_COD_ROL
		 * @param audCodRol  the value for CM_CREAR_NOMENCLATURA_SALARIAL.AUD_COD_ROL
		 * @mbg.generated  Tue Jan 29 15:29:43 COT 2019
		 */
		public void setAudCodRol(Integer audCodRol) {
			this.audCodRol = audCodRol;
		}

		/**
		 * This method was generated by MyBatis Generator. This method returns the value of the database column CM_CREAR_NOMENCLATURA_SALARIAL.AUD_ACCION
		 * @return  the value of CM_CREAR_NOMENCLATURA_SALARIAL.AUD_ACCION
		 * @mbg.generated  Tue Jan 29 15:29:43 COT 2019
		 */
		public Integer getAudAccion() {
			return audAccion;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the value of the database column CM_CREAR_NOMENCLATURA_SALARIAL.AUD_ACCION
		 * @param audAccion  the value for CM_CREAR_NOMENCLATURA_SALARIAL.AUD_ACCION
		 * @mbg.generated  Tue Jan 29 15:29:43 COT 2019
		 */
		public void setAudAccion(Integer audAccion) {
			this.audAccion = audAccion;
		}

		/**
		 * This method was generated by MyBatis Generator. This method returns the value of the database column CM_CREAR_NOMENCLATURA_SALARIAL.COD_PROCESO_CARGA_MASIVA
		 * @return  the value of CM_CREAR_NOMENCLATURA_SALARIAL.COD_PROCESO_CARGA_MASIVA
		 * @mbg.generated  Tue Jan 29 15:29:43 COT 2019
		 */
		public Long getCodProcesoCargaMasiva() {
			return codProcesoCargaMasiva;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the value of the database column CM_CREAR_NOMENCLATURA_SALARIAL.COD_PROCESO_CARGA_MASIVA
		 * @param codProcesoCargaMasiva  the value for CM_CREAR_NOMENCLATURA_SALARIAL.COD_PROCESO_CARGA_MASIVA
		 * @mbg.generated  Tue Jan 29 15:29:43 COT 2019
		 */
		public void setCodProcesoCargaMasiva(Long codProcesoCargaMasiva) {
			this.codProcesoCargaMasiva = codProcesoCargaMasiva;
		}

		/**
		 * This method was generated by MyBatis Generator. This method returns the value of the database column CM_CREAR_NOMENCLATURA_SALARIAL.RESULTADO
		 * @return  the value of CM_CREAR_NOMENCLATURA_SALARIAL.RESULTADO
		 * @mbg.generated  Tue Jan 29 15:29:43 COT 2019
		 */
		public String getResultado() {
			return resultado;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the value of the database column CM_CREAR_NOMENCLATURA_SALARIAL.RESULTADO
		 * @param resultado  the value for CM_CREAR_NOMENCLATURA_SALARIAL.RESULTADO
		 * @mbg.generated  Tue Jan 29 15:29:43 COT 2019
		 */
		public void setResultado(String resultado) {
			this.resultado = resultado;
		}

		/**
		 * This method was generated by MyBatis Generator. This method returns the value of the database column CM_CREAR_NOMENCLATURA_SALARIAL.CLASIFICACION_ORGANICA
		 * @return  the value of CM_CREAR_NOMENCLATURA_SALARIAL.CLASIFICACION_ORGANICA
		 * @mbg.generated  Tue Jan 29 15:29:43 COT 2019
		 */
		public String getClasificacionOrganica() {
			return clasificacionOrganica;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the value of the database column CM_CREAR_NOMENCLATURA_SALARIAL.CLASIFICACION_ORGANICA
		 * @param clasificacionOrganica  the value for CM_CREAR_NOMENCLATURA_SALARIAL.CLASIFICACION_ORGANICA
		 * @mbg.generated  Tue Jan 29 15:29:43 COT 2019
		 */
		public void setClasificacionOrganica(String clasificacionOrganica) {
			this.clasificacionOrganica = clasificacionOrganica;
		}

		/**
		 * This method was generated by MyBatis Generator. This method returns the value of the database column CM_CREAR_NOMENCLATURA_SALARIAL.SISTEMA_CARRERA
		 * @return  the value of CM_CREAR_NOMENCLATURA_SALARIAL.SISTEMA_CARRERA
		 * @mbg.generated  Tue Jan 29 15:29:43 COT 2019
		 */
		public String getSistemaCarrera() {
			return sistemaCarrera;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the value of the database column CM_CREAR_NOMENCLATURA_SALARIAL.SISTEMA_CARRERA
		 * @param sistemaCarrera  the value for CM_CREAR_NOMENCLATURA_SALARIAL.SISTEMA_CARRERA
		 * @mbg.generated  Tue Jan 29 15:29:43 COT 2019
		 */
		public void setSistemaCarrera(String sistemaCarrera) {
			this.sistemaCarrera = sistemaCarrera;
		}
}