package co.gov.dafp.sigep2.entities;

import java.math.BigDecimal;
import java.util.Date;

import co.gov.dafp.sigep2.utils.ErrorMensajes;

public class CuentasDeclaracion extends ErrorMensajes {
    private static final long serialVersionUID = 1732693072909456894L;
    private Long codCuentaDeclaracion;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column CUENTAS_DECLARACION.COD_DECLARACION
     * 
     * @mbg.generated Thu Mar 22 07:42:52 COT 2018
     */
    private BigDecimal codDeclaracion;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column CUENTAS_DECLARACION.COD_TIPO_CUENTA
     * 
     * @mbg.generated Thu Mar 22 07:42:52 COT 2018
     */
    private Integer codTipoCuenta;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column CUENTAS_DECLARACION.ENTIDAD
     * 
     * @mbg.generated Thu Mar 22 07:42:52 COT 2018
     */
    private String entidad;
    
    private String nombreCuenta;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column CUENTAS_DECLARACION.NUMERO_CUENTA
     * 
     * @mbg.generated Thu Mar 22 07:42:52 COT 2018
     */
    private String numeroCuenta;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column CUENTAS_DECLARACION.SALDO
     * 
     * @mbg.generated Thu Mar 22 07:42:52 COT 2018
     */
    private BigDecimal saldo;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column CUENTAS_DECLARACION.SEDE_CUENTA
     * 
     * @mbg.generated Thu Mar 22 07:42:52 COT 2018
     */
    private String sedeCuenta;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column CUENTAS_DECLARACION.AUD_FECHA_ACTUALIZACION
     * 
     * @mbg.generated Thu Mar 22 07:42:52 COT 2018
     */
    private Date audFechaActualizacion;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column CUENTAS_DECLARACION.AUD_COD_USUARIO
     * 
     * @mbg.generated Thu Mar 22 07:42:52 COT 2018
     */
    private BigDecimal audCodUsuario;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column CUENTAS_DECLARACION.AUD_COD_ROL
     * 
     * @mbg.generated Thu Mar 22 07:42:52 COT 2018
     */
    private Integer audCodRol;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column CUENTAS_DECLARACION.AUD_ACCION
     * 
     * @mbg.generated Thu Mar 22 07:42:52 COT 2018
     */
    private Integer audAccion;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column CUENTAS_DECLARACION.FLG_ACTIVO
     * 
     * @mbg.generated Thu Mar 22 07:42:52 COT 2018
     */
    private Short flgActivo;

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column CUENTAS_DECLARACION.COD_CUENTA_DECLARACION
     * 
     * @return the value of CUENTAS_DECLARACION.COD_CUENTA_DECLARACION
     * @mbg.generated Thu Mar 22 07:42:52 COT 2018
     */
    public Long getCodCuentaDeclaracion() {
	return codCuentaDeclaracion;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column CUENTAS_DECLARACION.COD_CUENTA_DECLARACION
     * 
     * @param codCuentaDeclaracion the value for
     *                             CUENTAS_DECLARACION.COD_CUENTA_DECLARACION
     * @mbg.generated Thu Mar 22 07:42:52 COT 2018
     */
    public void setCodCuentaDeclaracion(Long codCuentaDeclaracion) {
	this.codCuentaDeclaracion = codCuentaDeclaracion;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column CUENTAS_DECLARACION.COD_DECLARACION
     * 
     * @return the value of CUENTAS_DECLARACION.COD_DECLARACION
     * @mbg.generated Thu Mar 22 07:42:52 COT 2018
     */
    public BigDecimal getCodDeclaracion() {
	return codDeclaracion;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column CUENTAS_DECLARACION.COD_DECLARACION
     * 
     * @param codDeclaracion the value for CUENTAS_DECLARACION.COD_DECLARACION
     * @mbg.generated Thu Mar 22 07:42:52 COT 2018
     */
    public void setCodDeclaracion(BigDecimal codDeclaracion) {
	this.codDeclaracion = codDeclaracion;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column CUENTAS_DECLARACION.COD_TIPO_CUENTA
     * 
     * @return the value of CUENTAS_DECLARACION.COD_TIPO_CUENTA
     * @mbg.generated Thu Mar 22 07:42:52 COT 2018
     */
    public Integer getCodTipoCuenta() {
	return codTipoCuenta;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column CUENTAS_DECLARACION.COD_TIPO_CUENTA
     * 
     * @param codTipoCuenta the value for CUENTAS_DECLARACION.COD_TIPO_CUENTA
     * @mbg.generated Thu Mar 22 07:42:52 COT 2018
     */
    public void setCodTipoCuenta(Integer codTipoCuenta) {
	this.codTipoCuenta = codTipoCuenta;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column CUENTAS_DECLARACION.ENTIDAD
     * 
     * @return the value of CUENTAS_DECLARACION.ENTIDAD
     * @mbg.generated Thu Mar 22 07:42:52 COT 2018
     */
    public String getEntidad() {
	return entidad;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column CUENTAS_DECLARACION.ENTIDAD
     * 
     * @param entidad the value for CUENTAS_DECLARACION.ENTIDAD
     * @mbg.generated Thu Mar 22 07:42:52 COT 2018
     */
    public void setEntidad(String entidad) {
	this.entidad = entidad;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column CUENTAS_DECLARACION.NUMERO_CUENTA
     * 
     * @return the value of CUENTAS_DECLARACION.NUMERO_CUENTA
     * @mbg.generated Thu Mar 22 07:42:52 COT 2018
     */
    public String getNumeroCuenta() {
	return numeroCuenta;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column CUENTAS_DECLARACION.NUMERO_CUENTA
     * 
     * @param numeroCuenta the value for CUENTAS_DECLARACION.NUMERO_CUENTA
     * @mbg.generated Thu Mar 22 07:42:52 COT 2018
     */
    public void setNumeroCuenta(String numeroCuenta) {
	this.numeroCuenta = numeroCuenta;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column CUENTAS_DECLARACION.SALDO
     * 
     * @return the value of CUENTAS_DECLARACION.SALDO
     * @mbg.generated Thu Mar 22 07:42:52 COT 2018
     */
    public BigDecimal getSaldo() {
	return saldo;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column CUENTAS_DECLARACION.SALDO
     * 
     * @param saldo the value for CUENTAS_DECLARACION.SALDO
     * @mbg.generated Thu Mar 22 07:42:52 COT 2018
     */
    public void setSaldo(BigDecimal saldo) {
	this.saldo = saldo;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column CUENTAS_DECLARACION.SEDE_CUENTA
     * 
     * @return the value of CUENTAS_DECLARACION.SEDE_CUENTA
     * @mbg.generated Thu Mar 22 07:42:52 COT 2018
     */
    public String getSedeCuenta() {
	return sedeCuenta;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column CUENTAS_DECLARACION.SEDE_CUENTA
     * 
     * @param sedeCuenta the value for CUENTAS_DECLARACION.SEDE_CUENTA
     * @mbg.generated Thu Mar 22 07:42:52 COT 2018
     */
    public void setSedeCuenta(String sedeCuenta) {
	this.sedeCuenta = sedeCuenta;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column CUENTAS_DECLARACION.AUD_FECHA_ACTUALIZACION
     * 
     * @return the value of CUENTAS_DECLARACION.AUD_FECHA_ACTUALIZACION
     * @mbg.generated Thu Mar 22 07:42:52 COT 2018
     */
    public Date getAudFechaActualizacion() {
	return audFechaActualizacion;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column CUENTAS_DECLARACION.AUD_FECHA_ACTUALIZACION
     * 
     * @param audFechaActualizacion the value for
     *                              CUENTAS_DECLARACION.AUD_FECHA_ACTUALIZACION
     * @mbg.generated Thu Mar 22 07:42:52 COT 2018
     */
    public void setAudFechaActualizacion(Date audFechaActualizacion) {
	this.audFechaActualizacion = audFechaActualizacion;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column CUENTAS_DECLARACION.AUD_COD_USUARIO
     * 
     * @return the value of CUENTAS_DECLARACION.AUD_COD_USUARIO
     * @mbg.generated Thu Mar 22 07:42:52 COT 2018
     */
    public BigDecimal getAudCodUsuario() {
	return audCodUsuario;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column CUENTAS_DECLARACION.AUD_COD_USUARIO
     * 
     * @param audCodUsuario the value for CUENTAS_DECLARACION.AUD_COD_USUARIO
     * @mbg.generated Thu Mar 22 07:42:52 COT 2018
     */
    public void setAudCodUsuario(BigDecimal audCodUsuario) {
	this.audCodUsuario = audCodUsuario;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column CUENTAS_DECLARACION.AUD_COD_ROL
     * 
     * @return the value of CUENTAS_DECLARACION.AUD_COD_ROL
     * @mbg.generated Thu Mar 22 07:42:52 COT 2018
     */
    public Integer getAudCodRol() {
	return audCodRol;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column CUENTAS_DECLARACION.AUD_COD_ROL
     * 
     * @param audCodRol the value for CUENTAS_DECLARACION.AUD_COD_ROL
     * @mbg.generated Thu Mar 22 07:42:52 COT 2018
     */
    public void setAudCodRol(Integer audCodRol) {
	this.audCodRol = audCodRol;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column CUENTAS_DECLARACION.AUD_ACCION
     * 
     * @return the value of CUENTAS_DECLARACION.AUD_ACCION
     * @mbg.generated Thu Mar 22 07:42:52 COT 2018
     */
    public Integer getAudAccion() {
	return audAccion;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column CUENTAS_DECLARACION.AUD_ACCION
     * 
     * @param audAccion the value for CUENTAS_DECLARACION.AUD_ACCION
     * @mbg.generated Thu Mar 22 07:42:52 COT 2018
     */
    public void setAudAccion(Integer audAccion) {
	this.audAccion = audAccion;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column CUENTAS_DECLARACION.FLG_ACTIVO
     * 
     * @return the value of CUENTAS_DECLARACION.FLG_ACTIVO
     * @mbg.generated Thu Mar 22 07:42:52 COT 2018
     */
    public Short getFlgActivo() {
	return flgActivo;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column CUENTAS_DECLARACION.FLG_ACTIVO
     * 
     * @param flgActivo the value for CUENTAS_DECLARACION.FLG_ACTIVO
     * @mbg.generated Thu Mar 22 07:42:52 COT 2018
     */
    public void setFlgActivo(Short flgActivo) {
	this.flgActivo = flgActivo;
    }

	/**
	 * @return the nombreCuenta
	 */
	public String getNombreCuenta() {
		return nombreCuenta;
	}

	/**
	 * @param nombreCuenta the nombreCuenta to set
	 */
	public void setNombreCuenta(String nombreCuenta) {
		this.nombreCuenta = nombreCuenta;
	}
}