package co.gov.dafp.sigep2.entities;

import java.math.BigDecimal;
import java.util.Date;

import co.gov.dafp.sigep2.utils.ErrorMensajes;

public class DocumentosAdicionalesHv extends ErrorMensajes{
    /**
	 * 
	 */
	private static final long serialVersionUID = -874582262094556370L;

	 /**
		 * This field was generated by MyBatis Generator. This field corresponds to the database column DOCUMENTOS_ADICIONALES_HV.COD_DOCUMENTO_ADICIONAL
		 * @mbg.generated  Tue Apr 02 14:18:30 COT 2019
		 */
		private Long codDocumentoAdicional;
		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the database column DOCUMENTOS_ADICIONALES_HV.COD_PERSONA
		 * @mbg.generated  Tue Apr 02 14:18:30 COT 2019
		 */
		private BigDecimal codPersona;
		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the database column DOCUMENTOS_ADICIONALES_HV.URL_DOCUMENTO_ADICIONAL
		 * @mbg.generated  Tue Apr 02 14:18:30 COT 2019
		 */
		private String urlDocumentoAdicional;
		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the database column DOCUMENTOS_ADICIONALES_HV.COD_TIPO_DOCUMENTO_ADICIONAL
		 * @mbg.generated  Tue Apr 02 14:18:30 COT 2019
		 */
		private BigDecimal codTipoDocumentoAdicional;
		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the database column DOCUMENTOS_ADICIONALES_HV.FLG_ACTIVO
		 * @mbg.generated  Tue Apr 02 14:18:30 COT 2019
		 */
		private Short flgActivo;
		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the database column DOCUMENTOS_ADICIONALES_HV.FLG_VALIDADO
		 * @mbg.generated  Tue Apr 02 14:18:30 COT 2019
		 */
		private Short flgValidado;
		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the database column DOCUMENTOS_ADICIONALES_HV.AUD_COD_USUARIO
		 * @mbg.generated  Tue Apr 02 14:18:30 COT 2019
		 */
		private Long audCodUsuario;
		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the database column DOCUMENTOS_ADICIONALES_HV.AUD_COD_ROL
		 * @mbg.generated  Tue Apr 02 14:18:30 COT 2019
		 */
		private Integer audCodRol;
		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the database column DOCUMENTOS_ADICIONALES_HV.AUD_ACCION
		 * @mbg.generated  Tue Apr 02 14:18:30 COT 2019
		 */
		private Integer audAccion;
		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the database column DOCUMENTOS_ADICIONALES_HV.AUD_FECHA_ACTUALIZACION
		 * @mbg.generated  Tue Apr 02 14:18:30 COT 2019
		 */
		private Date audFechaActualizacion;

		/**
		 * This method was generated by MyBatis Generator. This method returns the value of the database column DOCUMENTOS_ADICIONALES_HV.COD_DOCUMENTO_ADICIONAL
		 * @return  the value of DOCUMENTOS_ADICIONALES_HV.COD_DOCUMENTO_ADICIONAL
		 * @mbg.generated  Tue Apr 02 14:18:30 COT 2019
		 */
		public Long getCodDocumentoAdicional() {
			return codDocumentoAdicional;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the value of the database column DOCUMENTOS_ADICIONALES_HV.COD_DOCUMENTO_ADICIONAL
		 * @param codDocumentoAdicional  the value for DOCUMENTOS_ADICIONALES_HV.COD_DOCUMENTO_ADICIONAL
		 * @mbg.generated  Tue Apr 02 14:18:30 COT 2019
		 */
		public void setCodDocumentoAdicional(Long codDocumentoAdicional) {
			this.codDocumentoAdicional = codDocumentoAdicional;
		}

		/**
		 * This method was generated by MyBatis Generator. This method returns the value of the database column DOCUMENTOS_ADICIONALES_HV.COD_PERSONA
		 * @return  the value of DOCUMENTOS_ADICIONALES_HV.COD_PERSONA
		 * @mbg.generated  Tue Apr 02 14:18:30 COT 2019
		 */
		public BigDecimal getCodPersona() {
			return codPersona;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the value of the database column DOCUMENTOS_ADICIONALES_HV.COD_PERSONA
		 * @param codPersona  the value for DOCUMENTOS_ADICIONALES_HV.COD_PERSONA
		 * @mbg.generated  Tue Apr 02 14:18:30 COT 2019
		 */
		public void setCodPersona(BigDecimal codPersona) {
			this.codPersona = codPersona;
		}

		/**
		 * This method was generated by MyBatis Generator. This method returns the value of the database column DOCUMENTOS_ADICIONALES_HV.URL_DOCUMENTO_ADICIONAL
		 * @return  the value of DOCUMENTOS_ADICIONALES_HV.URL_DOCUMENTO_ADICIONAL
		 * @mbg.generated  Tue Apr 02 14:18:30 COT 2019
		 */
		public String getUrlDocumentoAdicional() {
			return urlDocumentoAdicional;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the value of the database column DOCUMENTOS_ADICIONALES_HV.URL_DOCUMENTO_ADICIONAL
		 * @param urlDocumentoAdicional  the value for DOCUMENTOS_ADICIONALES_HV.URL_DOCUMENTO_ADICIONAL
		 * @mbg.generated  Tue Apr 02 14:18:30 COT 2019
		 */
		public void setUrlDocumentoAdicional(String urlDocumentoAdicional) {
			this.urlDocumentoAdicional = urlDocumentoAdicional;
		}

		/**
		 * This method was generated by MyBatis Generator. This method returns the value of the database column DOCUMENTOS_ADICIONALES_HV.COD_TIPO_DOCUMENTO_ADICIONAL
		 * @return  the value of DOCUMENTOS_ADICIONALES_HV.COD_TIPO_DOCUMENTO_ADICIONAL
		 * @mbg.generated  Tue Apr 02 14:18:30 COT 2019
		 */
		public BigDecimal getCodTipoDocumentoAdicional() {
			return codTipoDocumentoAdicional;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the value of the database column DOCUMENTOS_ADICIONALES_HV.COD_TIPO_DOCUMENTO_ADICIONAL
		 * @param codTipoDocumentoAdicional  the value for DOCUMENTOS_ADICIONALES_HV.COD_TIPO_DOCUMENTO_ADICIONAL
		 * @mbg.generated  Tue Apr 02 14:18:30 COT 2019
		 */
		public void setCodTipoDocumentoAdicional(BigDecimal codTipoDocumentoAdicional) {
			this.codTipoDocumentoAdicional = codTipoDocumentoAdicional;
		}

		/**
		 * This method was generated by MyBatis Generator. This method returns the value of the database column DOCUMENTOS_ADICIONALES_HV.FLG_ACTIVO
		 * @return  the value of DOCUMENTOS_ADICIONALES_HV.FLG_ACTIVO
		 * @mbg.generated  Tue Apr 02 14:18:30 COT 2019
		 */
		public Short getFlgActivo() {
			return flgActivo;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the value of the database column DOCUMENTOS_ADICIONALES_HV.FLG_ACTIVO
		 * @param flgActivo  the value for DOCUMENTOS_ADICIONALES_HV.FLG_ACTIVO
		 * @mbg.generated  Tue Apr 02 14:18:30 COT 2019
		 */
		public void setFlgActivo(Short flgActivo) {
			this.flgActivo = flgActivo;
		}

		/**
		 * This method was generated by MyBatis Generator. This method returns the value of the database column DOCUMENTOS_ADICIONALES_HV.FLG_VALIDADO
		 * @return  the value of DOCUMENTOS_ADICIONALES_HV.FLG_VALIDADO
		 * @mbg.generated  Tue Apr 02 14:18:30 COT 2019
		 */
		public Short getFlgValidado() {
			return flgValidado;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the value of the database column DOCUMENTOS_ADICIONALES_HV.FLG_VALIDADO
		 * @param flgValidado  the value for DOCUMENTOS_ADICIONALES_HV.FLG_VALIDADO
		 * @mbg.generated  Tue Apr 02 14:18:30 COT 2019
		 */
		public void setFlgValidado(Short flgValidado) {
			this.flgValidado = flgValidado;
		}

		/**
		 * This method was generated by MyBatis Generator. This method returns the value of the database column DOCUMENTOS_ADICIONALES_HV.AUD_COD_USUARIO
		 * @return  the value of DOCUMENTOS_ADICIONALES_HV.AUD_COD_USUARIO
		 * @mbg.generated  Tue Apr 02 14:18:30 COT 2019
		 */
		public Long getAudCodUsuario() {
			return audCodUsuario;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the value of the database column DOCUMENTOS_ADICIONALES_HV.AUD_COD_USUARIO
		 * @param audCodUsuario  the value for DOCUMENTOS_ADICIONALES_HV.AUD_COD_USUARIO
		 * @mbg.generated  Tue Apr 02 14:18:30 COT 2019
		 */
		public void setAudCodUsuario(Long audCodUsuario) {
			this.audCodUsuario = audCodUsuario;
		}

		/**
		 * This method was generated by MyBatis Generator. This method returns the value of the database column DOCUMENTOS_ADICIONALES_HV.AUD_COD_ROL
		 * @return  the value of DOCUMENTOS_ADICIONALES_HV.AUD_COD_ROL
		 * @mbg.generated  Tue Apr 02 14:18:30 COT 2019
		 */
		public Integer getAudCodRol() {
			return audCodRol;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the value of the database column DOCUMENTOS_ADICIONALES_HV.AUD_COD_ROL
		 * @param audCodRol  the value for DOCUMENTOS_ADICIONALES_HV.AUD_COD_ROL
		 * @mbg.generated  Tue Apr 02 14:18:30 COT 2019
		 */
		public void setAudCodRol(Integer audCodRol) {
			this.audCodRol = audCodRol;
		}

		/**
		 * This method was generated by MyBatis Generator. This method returns the value of the database column DOCUMENTOS_ADICIONALES_HV.AUD_ACCION
		 * @return  the value of DOCUMENTOS_ADICIONALES_HV.AUD_ACCION
		 * @mbg.generated  Tue Apr 02 14:18:30 COT 2019
		 */
		public Integer getAudAccion() {
			return audAccion;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the value of the database column DOCUMENTOS_ADICIONALES_HV.AUD_ACCION
		 * @param audAccion  the value for DOCUMENTOS_ADICIONALES_HV.AUD_ACCION
		 * @mbg.generated  Tue Apr 02 14:18:30 COT 2019
		 */
		public void setAudAccion(Integer audAccion) {
			this.audAccion = audAccion;
		}

		/**
		 * This method was generated by MyBatis Generator. This method returns the value of the database column DOCUMENTOS_ADICIONALES_HV.AUD_FECHA_ACTUALIZACION
		 * @return  the value of DOCUMENTOS_ADICIONALES_HV.AUD_FECHA_ACTUALIZACION
		 * @mbg.generated  Tue Apr 02 14:18:30 COT 2019
		 */
		public Date getAudFechaActualizacion() {
			return audFechaActualizacion;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the value of the database column DOCUMENTOS_ADICIONALES_HV.AUD_FECHA_ACTUALIZACION
		 * @param audFechaActualizacion  the value for DOCUMENTOS_ADICIONALES_HV.AUD_FECHA_ACTUALIZACION
		 * @mbg.generated  Tue Apr 02 14:18:30 COT 2019
		 */
		public void setAudFechaActualizacion(Date audFechaActualizacion) {
			this.audFechaActualizacion = audFechaActualizacion;
		}
}