package co.gov.dafp.sigep2.entities;

import java.math.BigDecimal;
import java.util.Date;

import co.gov.dafp.sigep2.utils.ErrorMensajes;

public class IngresosDeclaracion extends ErrorMensajes {
    /**
     * 
     */
    private static final long serialVersionUID = -5070224578483606374L;

    private int limitIni;

    private int limitFin;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column INGRESOS_DECLARACION.COD_INGRESO_DECLARACION
     * 
     * @mbg.generated Wed Mar 14 11:12:31 COT 2018
     */
    private Long codIngresoDeclaracion;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column INGRESOS_DECLARACION.COD_DECLARACION
     * 
     * @mbg.generated Wed Mar 14 11:12:31 COT 2018
     */
    private Long codDeclaracion;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column INGRESOS_DECLARACION.COD_TIPO_INGRESO
     * 
     * @mbg.generated Wed Mar 14 11:12:31 COT 2018
     */
    private Integer codTipoIngreso;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column INGRESOS_DECLARACION.VALOR
     * 
     * @mbg.generated Wed Mar 14 11:12:31 COT 2018
     */
    private BigDecimal valor;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column INGRESOS_DECLARACION.AUD_FECHA_ACTUALIZACION
     * 
     * @mbg.generated Wed Mar 14 11:12:31 COT 2018
     */
    private Date audFechaActualizacion;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column INGRESOS_DECLARACION.AUD_COD_USUARIO
     * 
     * @mbg.generated Wed Mar 14 11:12:31 COT 2018
     */
    private Long audCodUsuario;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column INGRESOS_DECLARACION.AUD_COD_ROL
     * 
     * @mbg.generated Wed Mar 14 11:12:31 COT 2018
     */
    private Integer audCodRol;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column INGRESOS_DECLARACION.AUD_ACCION
     * 
     * @mbg.generated Wed Mar 14 11:12:31 COT 2018
     */
    private Integer audAccion;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column INGRESOS_DECLARACION.FLG_ACTIVO
     * 
     * @mbg.generated Wed Mar 14 11:12:31 COT 2018
     */
    private Integer flgActivo;

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column INGRESOS_DECLARACION.COD_INGRESO_DECLARACION
     * 
     * @return the value of INGRESOS_DECLARACION.COD_INGRESO_DECLARACION
     * @mbg.generated Wed Mar 14 11:12:31 COT 2018
     */
    public Long getCodIngresoDeclaracion() {
	return codIngresoDeclaracion;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column INGRESOS_DECLARACION.COD_INGRESO_DECLARACION
     * 
     * @param codIngresoDeclaracion
     *            the value for INGRESOS_DECLARACION.COD_INGRESO_DECLARACION
     * @mbg.generated Wed Mar 14 11:12:31 COT 2018
     */
    public void setCodIngresoDeclaracion(Long codIngresoDeclaracion) {
	this.codIngresoDeclaracion = codIngresoDeclaracion;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column INGRESOS_DECLARACION.COD_DECLARACION
     * 
     * @return the value of INGRESOS_DECLARACION.COD_DECLARACION
     * @mbg.generated Wed Mar 14 11:12:31 COT 2018
     */
    public Long getCodDeclaracion() {
	return codDeclaracion;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column INGRESOS_DECLARACION.COD_DECLARACION
     * 
     * @param codDeclaracion
     *            the value for INGRESOS_DECLARACION.COD_DECLARACION
     * @mbg.generated Wed Mar 14 11:12:31 COT 2018
     */
    public void setCodDeclaracion(Long codDeclaracion) {
	this.codDeclaracion = codDeclaracion;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column INGRESOS_DECLARACION.COD_TIPO_INGRESO
     * 
     * @return the value of INGRESOS_DECLARACION.COD_TIPO_INGRESO
     * @mbg.generated Wed Mar 14 11:12:31 COT 2018
     */
    public Integer getCodTipoIngreso() {
	return codTipoIngreso;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column INGRESOS_DECLARACION.COD_TIPO_INGRESO
     * 
     * @param codTipoIngreso
     *            the value for INGRESOS_DECLARACION.COD_TIPO_INGRESO
     * @mbg.generated Wed Mar 14 11:12:31 COT 2018
     */
    public void setCodTipoIngreso(Integer codTipoIngreso) {
	this.codTipoIngreso = codTipoIngreso;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column INGRESOS_DECLARACION.VALOR
     * 
     * @return the value of INGRESOS_DECLARACION.VALOR
     * @mbg.generated Wed Mar 14 11:12:31 COT 2018
     */
    public BigDecimal getValor() {
	return valor;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column INGRESOS_DECLARACION.VALOR
     * 
     * @param valor
     *            the value for INGRESOS_DECLARACION.VALOR
     * @mbg.generated Wed Mar 14 11:12:31 COT 2018
     */
    public void setValor(BigDecimal valor) {
	this.valor = valor;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column INGRESOS_DECLARACION.AUD_FECHA_ACTUALIZACION
     * 
     * @return the value of INGRESOS_DECLARACION.AUD_FECHA_ACTUALIZACION
     * @mbg.generated Wed Mar 14 11:12:31 COT 2018
     */
    public Date getAudFechaActualizacion() {
	return audFechaActualizacion;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column INGRESOS_DECLARACION.AUD_FECHA_ACTUALIZACION
     * 
     * @param audFechaActualizacion
     *            the value for INGRESOS_DECLARACION.AUD_FECHA_ACTUALIZACION
     * @mbg.generated Wed Mar 14 11:12:31 COT 2018
     */
    public void setAudFechaActualizacion(Date audFechaActualizacion) {
	this.audFechaActualizacion = audFechaActualizacion;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column INGRESOS_DECLARACION.AUD_COD_USUARIO
     * 
     * @return the value of INGRESOS_DECLARACION.AUD_COD_USUARIO
     * @mbg.generated Wed Mar 14 11:12:31 COT 2018
     */
    public Long getAudCodUsuario() {
	return audCodUsuario;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column INGRESOS_DECLARACION.AUD_COD_USUARIO
     * 
     * @param audCodUsuario
     *            the value for INGRESOS_DECLARACION.AUD_COD_USUARIO
     * @mbg.generated Wed Mar 14 11:12:31 COT 2018
     */
    public void setAudCodUsuario(Long audCodUsuario) {
	this.audCodUsuario = audCodUsuario;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column INGRESOS_DECLARACION.AUD_COD_ROL
     * 
     * @return the value of INGRESOS_DECLARACION.AUD_COD_ROL
     * @mbg.generated Wed Mar 14 11:12:31 COT 2018
     */
    public Integer getAudCodRol() {
	return audCodRol;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column INGRESOS_DECLARACION.AUD_COD_ROL
     * 
     * @param audCodRol
     *            the value for INGRESOS_DECLARACION.AUD_COD_ROL
     * @mbg.generated Wed Mar 14 11:12:31 COT 2018
     */
    public void setAudCodRol(Integer audCodRol) {
	this.audCodRol = audCodRol;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column INGRESOS_DECLARACION.AUD_ACCION
     * 
     * @return the value of INGRESOS_DECLARACION.AUD_ACCION
     * @mbg.generated Wed Mar 14 11:12:31 COT 2018
     */
    public Integer getAudAccion() {
	return audAccion;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column INGRESOS_DECLARACION.AUD_ACCION
     * 
     * @param audAccion
     *            the value for INGRESOS_DECLARACION.AUD_ACCION
     * @mbg.generated Wed Mar 14 11:12:31 COT 2018
     */
    public void setAudAccion(Integer audAccion) {
	this.audAccion = audAccion;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column INGRESOS_DECLARACION.FLG_ACTIVO
     * 
     * @return the value of INGRESOS_DECLARACION.FLG_ACTIVO
     * @mbg.generated Wed Mar 14 11:12:31 COT 2018
     */
    public Integer getFlgActivo() {
	return flgActivo;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column INGRESOS_DECLARACION.FLG_ACTIVO
     * 
     * @param flgActivo
     *            the value for INGRESOS_DECLARACION.FLG_ACTIVO
     * @mbg.generated Wed Mar 14 11:12:31 COT 2018
     */
    public void setFlgActivo(Integer flgActivo) {
	this.flgActivo = flgActivo;
    }

    /**
     * @return the limitIni
     */
    public int getLimitIni() {
	return limitIni;
    }

    /**
     * @param limitIni
     *            the limitIni to set
     */
    public void setLimitIni(int limitIni) {
	this.limitIni = limitIni;
    }

    /**
     * @return the limitFin
     */
    public int getLimitFin() {
	return limitFin;
    }

    /**
     * @param limitFin
     *            the limitFin to set
     */
    public void setLimitFin(int limitFin) {
	this.limitFin = limitFin;
    }

}