package co.gov.dafp.sigep2.entities;

import java.math.BigDecimal;
import java.util.Date;

import co.gov.dafp.sigep2.utils.ErrorMensajes;

public class PepRespuestaCuestionario extends ErrorMensajes{
    /**
	 * 
	 */
	private static final long serialVersionUID = -1051681290201355735L;

	 /**
		 * This field was generated by MyBatis Generator. This field corresponds to the database column PEP_RESPUESTA_CUESTIONARIO.ID_RESPUESTA_CUESTIONARIO
		 * @mbg.generated  Tue Apr 16 11:00:23 COT 2019
		 */
		private Long idRespuestaCuestionario;
		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the database column PEP_RESPUESTA_CUESTIONARIO.ID_TIPO_CUESTIONARIO
		 * @mbg.generated  Tue Apr 16 11:00:23 COT 2019
		 */
		private Long idTipoCuestionario;
		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the database column PEP_RESPUESTA_CUESTIONARIO.COD_ENTIDAD
		 * @mbg.generated  Tue Apr 16 11:00:23 COT 2019
		 */
		private BigDecimal codEntidad;
		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the database column PEP_RESPUESTA_CUESTIONARIO.AUD_FECHA_ACTUALIZACION
		 * @mbg.generated  Tue Apr 16 11:00:23 COT 2019
		 */
		private Date audFechaActualizacion;
		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the database column PEP_RESPUESTA_CUESTIONARIO.AUD_COD_USUARIO
		 * @mbg.generated  Tue Apr 16 11:00:23 COT 2019
		 */
		private BigDecimal audCodUsuario;
		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the database column PEP_RESPUESTA_CUESTIONARIO.AUD_COD_ROL
		 * @mbg.generated  Tue Apr 16 11:00:23 COT 2019
		 */
		private Integer audCodRol;
		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the database column PEP_RESPUESTA_CUESTIONARIO.AUD_ACCION
		 * @mbg.generated  Tue Apr 16 11:00:23 COT 2019
		 */
		private Integer audAccion;
		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the database column PEP_RESPUESTA_CUESTIONARIO.FLG_ACTIVO
		 * @mbg.generated  Tue Apr 16 11:00:23 COT 2019
		 */
		private Short flgActivo;

		/**
		 * This method was generated by MyBatis Generator. This method returns the value of the database column PEP_RESPUESTA_CUESTIONARIO.ID_RESPUESTA_CUESTIONARIO
		 * @return  the value of PEP_RESPUESTA_CUESTIONARIO.ID_RESPUESTA_CUESTIONARIO
		 * @mbg.generated  Tue Apr 16 11:00:23 COT 2019
		 */
		public Long getIdRespuestaCuestionario() {
			return idRespuestaCuestionario;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the value of the database column PEP_RESPUESTA_CUESTIONARIO.ID_RESPUESTA_CUESTIONARIO
		 * @param idRespuestaCuestionario  the value for PEP_RESPUESTA_CUESTIONARIO.ID_RESPUESTA_CUESTIONARIO
		 * @mbg.generated  Tue Apr 16 11:00:23 COT 2019
		 */
		public void setIdRespuestaCuestionario(Long idRespuestaCuestionario) {
			this.idRespuestaCuestionario = idRespuestaCuestionario;
		}

		/**
		 * This method was generated by MyBatis Generator. This method returns the value of the database column PEP_RESPUESTA_CUESTIONARIO.ID_TIPO_CUESTIONARIO
		 * @return  the value of PEP_RESPUESTA_CUESTIONARIO.ID_TIPO_CUESTIONARIO
		 * @mbg.generated  Tue Apr 16 11:00:23 COT 2019
		 */
		public Long getIdTipoCuestionario() {
			return idTipoCuestionario;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the value of the database column PEP_RESPUESTA_CUESTIONARIO.ID_TIPO_CUESTIONARIO
		 * @param idTipoCuestionario  the value for PEP_RESPUESTA_CUESTIONARIO.ID_TIPO_CUESTIONARIO
		 * @mbg.generated  Tue Apr 16 11:00:23 COT 2019
		 */
		public void setIdTipoCuestionario(Long idTipoCuestionario) {
			this.idTipoCuestionario = idTipoCuestionario;
		}

		/**
		 * This method was generated by MyBatis Generator. This method returns the value of the database column PEP_RESPUESTA_CUESTIONARIO.COD_ENTIDAD
		 * @return  the value of PEP_RESPUESTA_CUESTIONARIO.COD_ENTIDAD
		 * @mbg.generated  Tue Apr 16 11:00:23 COT 2019
		 */
		public BigDecimal getCodEntidad() {
			return codEntidad;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the value of the database column PEP_RESPUESTA_CUESTIONARIO.COD_ENTIDAD
		 * @param codEntidad  the value for PEP_RESPUESTA_CUESTIONARIO.COD_ENTIDAD
		 * @mbg.generated  Tue Apr 16 11:00:23 COT 2019
		 */
		public void setCodEntidad(BigDecimal codEntidad) {
			this.codEntidad = codEntidad;
		}

		/**
		 * This method was generated by MyBatis Generator. This method returns the value of the database column PEP_RESPUESTA_CUESTIONARIO.AUD_FECHA_ACTUALIZACION
		 * @return  the value of PEP_RESPUESTA_CUESTIONARIO.AUD_FECHA_ACTUALIZACION
		 * @mbg.generated  Tue Apr 16 11:00:23 COT 2019
		 */
		public Date getAudFechaActualizacion() {
			return audFechaActualizacion;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the value of the database column PEP_RESPUESTA_CUESTIONARIO.AUD_FECHA_ACTUALIZACION
		 * @param audFechaActualizacion  the value for PEP_RESPUESTA_CUESTIONARIO.AUD_FECHA_ACTUALIZACION
		 * @mbg.generated  Tue Apr 16 11:00:23 COT 2019
		 */
		public void setAudFechaActualizacion(Date audFechaActualizacion) {
			this.audFechaActualizacion = audFechaActualizacion;
		}

		/**
		 * This method was generated by MyBatis Generator. This method returns the value of the database column PEP_RESPUESTA_CUESTIONARIO.AUD_COD_USUARIO
		 * @return  the value of PEP_RESPUESTA_CUESTIONARIO.AUD_COD_USUARIO
		 * @mbg.generated  Tue Apr 16 11:00:23 COT 2019
		 */
		public BigDecimal getAudCodUsuario() {
			return audCodUsuario;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the value of the database column PEP_RESPUESTA_CUESTIONARIO.AUD_COD_USUARIO
		 * @param audCodUsuario  the value for PEP_RESPUESTA_CUESTIONARIO.AUD_COD_USUARIO
		 * @mbg.generated  Tue Apr 16 11:00:23 COT 2019
		 */
		public void setAudCodUsuario(BigDecimal audCodUsuario) {
			this.audCodUsuario = audCodUsuario;
		}

		/**
		 * This method was generated by MyBatis Generator. This method returns the value of the database column PEP_RESPUESTA_CUESTIONARIO.AUD_COD_ROL
		 * @return  the value of PEP_RESPUESTA_CUESTIONARIO.AUD_COD_ROL
		 * @mbg.generated  Tue Apr 16 11:00:23 COT 2019
		 */
		public Integer getAudCodRol() {
			return audCodRol;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the value of the database column PEP_RESPUESTA_CUESTIONARIO.AUD_COD_ROL
		 * @param audCodRol  the value for PEP_RESPUESTA_CUESTIONARIO.AUD_COD_ROL
		 * @mbg.generated  Tue Apr 16 11:00:23 COT 2019
		 */
		public void setAudCodRol(Integer audCodRol) {
			this.audCodRol = audCodRol;
		}

		/**
		 * This method was generated by MyBatis Generator. This method returns the value of the database column PEP_RESPUESTA_CUESTIONARIO.AUD_ACCION
		 * @return  the value of PEP_RESPUESTA_CUESTIONARIO.AUD_ACCION
		 * @mbg.generated  Tue Apr 16 11:00:23 COT 2019
		 */
		public Integer getAudAccion() {
			return audAccion;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the value of the database column PEP_RESPUESTA_CUESTIONARIO.AUD_ACCION
		 * @param audAccion  the value for PEP_RESPUESTA_CUESTIONARIO.AUD_ACCION
		 * @mbg.generated  Tue Apr 16 11:00:23 COT 2019
		 */
		public void setAudAccion(Integer audAccion) {
			this.audAccion = audAccion;
		}

		/**
		 * This method was generated by MyBatis Generator. This method returns the value of the database column PEP_RESPUESTA_CUESTIONARIO.FLG_ACTIVO
		 * @return  the value of PEP_RESPUESTA_CUESTIONARIO.FLG_ACTIVO
		 * @mbg.generated  Tue Apr 16 11:00:23 COT 2019
		 */
		public Short getFlgActivo() {
			return flgActivo;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the value of the database column PEP_RESPUESTA_CUESTIONARIO.FLG_ACTIVO
		 * @param flgActivo  the value for PEP_RESPUESTA_CUESTIONARIO.FLG_ACTIVO
		 * @mbg.generated  Tue Apr 16 11:00:23 COT 2019
		 */
		public void setFlgActivo(Short flgActivo) {
			this.flgActivo = flgActivo;
		}
}