package co.gov.dafp.sigep2.entities;

import java.math.BigDecimal;
import java.util.Date;

import co.gov.dafp.sigep2.utils.ErrorMensajes;

public class Persona extends ErrorMensajes{
	
	 /**
    *
    */
    private static final long serialVersionUID = -8605276399564331690L;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column PERSONA.COD_PERSONA
     *
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    private BigDecimal codPersona;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column PERSONA.COD_GENERO
     *
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    private Integer codGenero;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column PERSONA.COD_ESTADO_CIVIL
     *
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    private Integer codEstadoCivil;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column PERSONA.COD_MUNICIPIO_NACIMIENTO
     *
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    private Integer codMunicipioNacimiento;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column PERSONA.COD_DEPARTAMENTO_NACIMIENTO
     *
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    private Integer codDepartamentoNacimiento;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column PERSONA.COD_PAIS_NACIMIENTO
     *
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    private Integer codPaisNacimiento;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column PERSONA.COD_FACTOR_RH
     *
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    private Integer codFactorRh;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column PERSONA.COD_TIPO_IDENTIFICACION
     *
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    private String codTipoIdentificacion;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column PERSONA.NUMERO_IDENTIFICACION
     *
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    private String numeroIdentificacion;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column PERSONA.PRIMER_NOMBRE
     *
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    private String primerNombre;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column PERSONA.SEGUNDO_NOMBRE
     *
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    private String segundoNombre;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column PERSONA.PRIMER_APELLIDO
     *
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    private String primerApellido;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column PERSONA.SEGUNDO_APELLIDO
     *
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    private String segundoApellido;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column PERSONA.RESUMEN_PROFESIONAL
     *
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    private String resumenProfesional;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column PERSONA.NUMERO_LIBRETA_MILITAR
     *
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    private String numeroLibretaMilitar;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column PERSONA.DISTRITO_MILITAR
     *
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    private String distritoMilitar;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column PERSONA.CLASE_LIBRETA_MILITAR
     *
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    private String claseLibretaMilitar;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column PERSONA.LIBRETA_MILITAR_URL
     *
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    private String libretaMilitarUrl;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column PERSONA.FOTO_URL
     *
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    private String fotoUrl;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column PERSONA.DOCUMENTO_IDENTIFICACION_URL
     *
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    private String documentoIdentificacionUrl;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column PERSONA.FECHA_NACIMIENTO
     *
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    private Date fechaNacimiento;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column PERSONA.EXPUESTO_POLITICAMENTE
     *
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    private Short expuestoPoliticamente;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column PERSONA.CORREO_ELECTRONICO
     *
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    private String correoElectronico;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column PERSONA.CORREO_ALTERNATIVO
     *
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    private String correoAlternativo;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column PERSONA.FLG_ACTIVO
     *
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    private Short flgActivo;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column PERSONA.FLG_ESTADO
     *
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    private Short flgEstado;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column PERSONA.AUD_FECHA_ACTUALIZACION
     *
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    private Date audFechaActualizacion;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column PERSONA.AUD_COD_USUARIO
     *
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    private BigDecimal audCodUsuario;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column PERSONA.AUD_COD_ROL
     *
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    private BigDecimal audCodRol;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column PERSONA.AUD_ACCION
     *
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    private Integer audAccion;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column PERSONA.COD_PERTENENCIA_ETNICA
     *
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    private Integer codPertenenciaEtnica;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column PERSONA.COD_SIGEP
     *
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    private String codSigep;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column PERSONA.FLG_DOCUMENTO_IDENTIFICACION_VALIDADO
     *
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    private Short flgDocumentoIdentificacionValidado;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column PERSONA.FLG_LIBRETA_MILITAR_VALIDADA
     *
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    private Short flgLibretaMilitarValidada;
    private Short flgDiscapacidadValidada;

    private Date fechaMarcacionPep;
    
    private Short marcacionPepVinc;
    
    private BigDecimal porcentajeHV;
    private String documentoDiscapacidadUrl;
    
    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column PERSONA.COD_PERSONA
     *
     * @return the value of PERSONA.COD_PERSONA
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    public BigDecimal getCodPersona()
    {
	return codPersona;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column PERSONA.COD_PERSONA
     *
     * @param codPersona the value for PERSONA.COD_PERSONA
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    public void setCodPersona(BigDecimal codPersona)
    {
	this.codPersona = codPersona;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column PERSONA.COD_GENERO
     *
     * @return the value of PERSONA.COD_GENERO
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    public Integer getCodGenero()
    {
	return codGenero;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column PERSONA.COD_GENERO
     *
     * @param codGenero the value for PERSONA.COD_GENERO
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    public void setCodGenero(Integer codGenero)
    {
	this.codGenero = codGenero;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column PERSONA.COD_ESTADO_CIVIL
     *
     * @return the value of PERSONA.COD_ESTADO_CIVIL
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    public Integer getCodEstadoCivil()
    {
	return codEstadoCivil;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column PERSONA.COD_ESTADO_CIVIL
     *
     * @param codEstadoCivil the value for PERSONA.COD_ESTADO_CIVIL
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    public void setCodEstadoCivil(Integer codEstadoCivil)
    {
	this.codEstadoCivil = codEstadoCivil;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column PERSONA.COD_MUNICIPIO_NACIMIENTO
     *
     * @return the value of PERSONA.COD_MUNICIPIO_NACIMIENTO
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    public Integer getCodMunicipioNacimiento()
    {
	return codMunicipioNacimiento;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column PERSONA.COD_MUNICIPIO_NACIMIENTO
     *
     * @param codMunicipioNacimiento the value for PERSONA.COD_MUNICIPIO_NACIMIENTO
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    public void setCodMunicipioNacimiento(Integer codMunicipioNacimiento)
    {
	this.codMunicipioNacimiento = codMunicipioNacimiento;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column PERSONA.COD_DEPARTAMENTO_NACIMIENTO
     *
     * @return the value of PERSONA.COD_DEPARTAMENTO_NACIMIENTO
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    public Integer getCodDepartamentoNacimiento()
    {
	return codDepartamentoNacimiento;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column PERSONA.COD_DEPARTAMENTO_NACIMIENTO
     *
     * @param codDepartamentoNacimiento the value for
     *                                  PERSONA.COD_DEPARTAMENTO_NACIMIENTO
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    public void setCodDepartamentoNacimiento(Integer codDepartamentoNacimiento)
    {
	this.codDepartamentoNacimiento = codDepartamentoNacimiento;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column PERSONA.COD_PAIS_NACIMIENTO
     *
     * @return the value of PERSONA.COD_PAIS_NACIMIENTO
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    public Integer getCodPaisNacimiento()
    {
	return codPaisNacimiento;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column PERSONA.COD_PAIS_NACIMIENTO
     *
     * @param codPaisNacimiento the value for PERSONA.COD_PAIS_NACIMIENTO
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    public void setCodPaisNacimiento(Integer codPaisNacimiento)
    {
	this.codPaisNacimiento = codPaisNacimiento;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column PERSONA.COD_FACTOR_RH
     *
     * @return the value of PERSONA.COD_FACTOR_RH
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    public Integer getCodFactorRh()
    {
	return codFactorRh;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column PERSONA.COD_FACTOR_RH
     *
     * @param codFactorRh the value for PERSONA.COD_FACTOR_RH
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    public void setCodFactorRh(Integer codFactorRh)
    {
	this.codFactorRh = codFactorRh;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column PERSONA.COD_TIPO_IDENTIFICACION
     *
     * @return the value of PERSONA.COD_TIPO_IDENTIFICACION
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    public String getCodTipoIdentificacion()
    {
	return codTipoIdentificacion;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column PERSONA.COD_TIPO_IDENTIFICACION
     *
     * @param codTipoIdentificacion the value for PERSONA.COD_TIPO_IDENTIFICACION
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    public void setCodTipoIdentificacion(String codTipoIdentificacion)
    {
	this.codTipoIdentificacion = codTipoIdentificacion;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column PERSONA.NUMERO_IDENTIFICACION
     *
     * @return the value of PERSONA.NUMERO_IDENTIFICACION
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    public String getNumeroIdentificacion()
    {
	return numeroIdentificacion;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column PERSONA.NUMERO_IDENTIFICACION
     *
     * @param numeroIdentificacion the value for PERSONA.NUMERO_IDENTIFICACION
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    public void setNumeroIdentificacion(String numeroIdentificacion)
    {
	this.numeroIdentificacion = numeroIdentificacion;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column PERSONA.PRIMER_NOMBRE
     *
     * @return the value of PERSONA.PRIMER_NOMBRE
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    public String getPrimerNombre()
    {
    	return primerNombre;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column PERSONA.PRIMER_NOMBRE
     *
     * @param primerNombre the value for PERSONA.PRIMER_NOMBRE
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    public void setPrimerNombre(String primerNombre)
    {
    	this.primerNombre = primerNombre;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column PERSONA.SEGUNDO_NOMBRE
     *
     * @return the value of PERSONA.SEGUNDO_NOMBRE
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    public String getSegundoNombre()
    {
    	return segundoNombre;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column PERSONA.SEGUNDO_NOMBRE
     *
     * @param segundoNombre the value for PERSONA.SEGUNDO_NOMBRE
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    public void setSegundoNombre(String segundoNombre)
    {
    	this.segundoNombre = segundoNombre;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column PERSONA.PRIMER_APELLIDO
     *
     * @return the value of PERSONA.PRIMER_APELLIDO
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    public String getPrimerApellido()
    {
    	return primerApellido;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column PERSONA.PRIMER_APELLIDO
     *
     * @param primerApellido the value for PERSONA.PRIMER_APELLIDO
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    public void setPrimerApellido(String primerApellido)
    {
    	this.primerApellido = primerApellido;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column PERSONA.SEGUNDO_APELLIDO
     *
     * @return the value of PERSONA.SEGUNDO_APELLIDO
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    public String getSegundoApellido()
    {
    	return segundoApellido;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column PERSONA.SEGUNDO_APELLIDO
     *
     * @param segundoApellido the value for PERSONA.SEGUNDO_APELLIDO
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    public void setSegundoApellido(String segundoApellido)
    {
    	this.segundoApellido = segundoApellido;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column PERSONA.RESUMEN_PROFESIONAL
     *
     * @return the value of PERSONA.RESUMEN_PROFESIONAL
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    public String getResumenProfesional()
    {
	return resumenProfesional;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column PERSONA.RESUMEN_PROFESIONAL
     *
     * @param resumenProfesional the value for PERSONA.RESUMEN_PROFESIONAL
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    public void setResumenProfesional(String resumenProfesional)
    {
	this.resumenProfesional = resumenProfesional;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column PERSONA.NUMERO_LIBRETA_MILITAR
     *
     * @return the value of PERSONA.NUMERO_LIBRETA_MILITAR
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    public String getNumeroLibretaMilitar()
    {
	return numeroLibretaMilitar;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column PERSONA.NUMERO_LIBRETA_MILITAR
     *
     * @param numeroLibretaMilitar the value for PERSONA.NUMERO_LIBRETA_MILITAR
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    public void setNumeroLibretaMilitar(String numeroLibretaMilitar)
    {
	this.numeroLibretaMilitar = numeroLibretaMilitar;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column PERSONA.DISTRITO_MILITAR
     *
     * @return the value of PERSONA.DISTRITO_MILITAR
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    public String getDistritoMilitar()
    {
	return distritoMilitar;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column PERSONA.DISTRITO_MILITAR
     *
     * @param distritoMilitar the value for PERSONA.DISTRITO_MILITAR
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    public void setDistritoMilitar(String distritoMilitar)
    {
	this.distritoMilitar = distritoMilitar;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column PERSONA.CLASE_LIBRETA_MILITAR
     *
     * @return the value of PERSONA.CLASE_LIBRETA_MILITAR
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    public String getClaseLibretaMilitar()
    {
	return claseLibretaMilitar;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column PERSONA.CLASE_LIBRETA_MILITAR
     *
     * @param claseLibretaMilitar the value for PERSONA.CLASE_LIBRETA_MILITAR
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    public void setClaseLibretaMilitar(String claseLibretaMilitar)
    {
	this.claseLibretaMilitar = claseLibretaMilitar;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column PERSONA.LIBRETA_MILITAR_URL
     *
     * @return the value of PERSONA.LIBRETA_MILITAR_URL
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    public String getLibretaMilitarUrl()
    {
	return libretaMilitarUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column PERSONA.LIBRETA_MILITAR_URL
     *
     * @param libretaMilitarUrl the value for PERSONA.LIBRETA_MILITAR_URL
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    public void setLibretaMilitarUrl(String libretaMilitarUrl)
    {
	this.libretaMilitarUrl = libretaMilitarUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column PERSONA.FOTO_URL
     *
     * @return the value of PERSONA.FOTO_URL
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    public String getFotoUrl()
    {
	return fotoUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column PERSONA.FOTO_URL
     *
     * @param fotoUrl the value for PERSONA.FOTO_URL
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    public void setFotoUrl(String fotoUrl)
    {
	this.fotoUrl = fotoUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column PERSONA.DOCUMENTO_IDENTIFICACION_URL
     *
     * @return the value of PERSONA.DOCUMENTO_IDENTIFICACION_URL
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    public String getDocumentoIdentificacionUrl()
    {
	return documentoIdentificacionUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column PERSONA.DOCUMENTO_IDENTIFICACION_URL
     *
     * @param documentoIdentificacionUrl the value for
     *                                   PERSONA.DOCUMENTO_IDENTIFICACION_URL
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    public void setDocumentoIdentificacionUrl(String documentoIdentificacionUrl)
    {
	this.documentoIdentificacionUrl = documentoIdentificacionUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column PERSONA.FECHA_NACIMIENTO
     *
     * @return the value of PERSONA.FECHA_NACIMIENTO
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    public Date getFechaNacimiento()
    {
	return fechaNacimiento;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column PERSONA.FECHA_NACIMIENTO
     *
     * @param fechaNacimiento the value for PERSONA.FECHA_NACIMIENTO
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    public void setFechaNacimiento(Date fechaNacimiento)
    {
	this.fechaNacimiento = fechaNacimiento;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column PERSONA.EXPUESTO_POLITICAMENTE
     *
     * @return the value of PERSONA.EXPUESTO_POLITICAMENTE
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    public boolean getExpuestoPoliticamente(){
    	return this.expuestoPoliticamente != null && this.expuestoPoliticamente == 1;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column PERSONA.EXPUESTO_POLITICAMENTE
     *
     * @param expuestoPoliticamente the value for PERSONA.EXPUESTO_POLITICAMENTE
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    public void setExpuestoPoliticamente(Short expuestoPoliticamente)
    {
	this.expuestoPoliticamente = expuestoPoliticamente;
    }

    public void setExpuestoPoliticamente(boolean expuestoPoliticamente){
    	if (expuestoPoliticamente) 
    		this.expuestoPoliticamente = 1;
    	else 
    		this.expuestoPoliticamente = 0;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column PERSONA.CORREO_ELECTRONICO
     *
     * @return the value of PERSONA.CORREO_ELECTRONICO
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    public String getCorreoElectronico()
    {
	return correoElectronico;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column PERSONA.CORREO_ELECTRONICO
     *
     * @param correoElectronico the value for PERSONA.CORREO_ELECTRONICO
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    public void setCorreoElectronico(String correoElectronico)
    {
	this.correoElectronico = correoElectronico;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column PERSONA.CORREO_ALTERNATIVO
     *
     * @return the value of PERSONA.CORREO_ALTERNATIVO
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    public String getCorreoAlternativo()
    {
	return correoAlternativo;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column PERSONA.CORREO_ALTERNATIVO
     *
     * @param correoAlternativo the value for PERSONA.CORREO_ALTERNATIVO
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    public void setCorreoAlternativo(String correoAlternativo)
    {
	this.correoAlternativo = correoAlternativo;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column PERSONA.FLG_ACTIVO
     *
     * @return the value of PERSONA.FLG_ACTIVO
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    public Short getFlgActivo()
    {
	return flgActivo;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column PERSONA.FLG_ACTIVO
     *
     * @param flgActivo the value for PERSONA.FLG_ACTIVO
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    public void setFlgActivo(Short flgActivo)
    {
	this.flgActivo = flgActivo;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column PERSONA.FLG_ESTADO
     *
     * @return the value of PERSONA.FLG_ESTADO
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    public Short getFlgEstado()
    {
	return flgEstado;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column PERSONA.FLG_ESTADO
     *
     * @param flgEstado the value for PERSONA.FLG_ESTADO
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    public void setFlgEstado(Short flgEstado)
    {
	this.flgEstado = flgEstado;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column PERSONA.AUD_FECHA_ACTUALIZACION
     *
     * @return the value of PERSONA.AUD_FECHA_ACTUALIZACION
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    public Date getAudFechaActualizacion()
    {
	return audFechaActualizacion;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column PERSONA.AUD_FECHA_ACTUALIZACION
     *
     * @param audFechaActualizacion the value for PERSONA.AUD_FECHA_ACTUALIZACION
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    public void setAudFechaActualizacion(Date audFechaActualizacion)
    {
	this.audFechaActualizacion = audFechaActualizacion;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column PERSONA.AUD_COD_USUARIO
     *
     * @return the value of PERSONA.AUD_COD_USUARIO
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    public BigDecimal getAudCodUsuario()
    {
	return audCodUsuario;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column PERSONA.AUD_COD_USUARIO
     *
     * @param audCodUsuario the value for PERSONA.AUD_COD_USUARIO
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    public void setAudCodUsuario(BigDecimal audCodUsuario)
    {
	this.audCodUsuario = audCodUsuario;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column PERSONA.AUD_COD_ROL
     *
     * @return the value of PERSONA.AUD_COD_ROL
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    public BigDecimal getAudCodRol()
    {
	return audCodRol;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column PERSONA.AUD_COD_ROL
     *
     * @param audCodRol the value for PERSONA.AUD_COD_ROL
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    public void setAudCodRol(BigDecimal audCodRol)
    {
	this.audCodRol = audCodRol;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column PERSONA.AUD_ACCION
     *
     * @return the value of PERSONA.AUD_ACCION
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    public Integer getAudAccion()
    {
	return audAccion;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column PERSONA.AUD_ACCION
     *
     * @param audAccion the value for PERSONA.AUD_ACCION
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    public void setAudAccion(Integer audAccion)
    {
	this.audAccion = audAccion;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column PERSONA.COD_PERTENENCIA_ETNICA
     *
     * @return the value of PERSONA.COD_PERTENENCIA_ETNICA
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    public Integer getCodPertenenciaEtnica()
    {
	return codPertenenciaEtnica;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column PERSONA.COD_PERTENENCIA_ETNICA
     *
     * @param codPertenenciaEtnica the value for PERSONA.COD_PERTENENCIA_ETNICA
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    public void setCodPertenenciaEtnica(Integer codPertenenciaEtnica)
    {
	this.codPertenenciaEtnica = codPertenenciaEtnica;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column PERSONA.COD_SIGEP
     *
     * @return the value of PERSONA.COD_SIGEP
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    public String getCodSigep()
    {
	return codSigep;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column PERSONA.COD_SIGEP
     *
     * @param codSigep the value for PERSONA.COD_SIGEP
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    public void setCodSigep(String codSigep)
    {
	this.codSigep = codSigep;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column PERSONA.FLG_DOCUMENTO_IDENTIFICACION_VALIDADO
     *
     * @return the value of PERSONA.FLG_DOCUMENTO_IDENTIFICACION_VALIDADO
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    public boolean getFlgDocumentoIdentificacionValidado(){
    	 return this.flgDocumentoIdentificacionValidado != null && this.flgDocumentoIdentificacionValidado == 1 ? true: false;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column PERSONA.FLG_DOCUMENTO_IDENTIFICACION_VALIDADO
     *
     * @param flgDocumentoIdentificacionValidado the value for
     *                                           PERSONA.FLG_DOCUMENTO_IDENTIFICACION_VALIDADO
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    public void setFlgDocumentoIdentificacionValidado(Short flgDocumentoIdentificacionValidado)
    {
	this.flgDocumentoIdentificacionValidado = flgDocumentoIdentificacionValidado;
    }

    public void setFlgDocumentoIdentificacionValidado(boolean flgDocumentoIdentificacionValidado){
    	if (flgDocumentoIdentificacionValidado)
    		this.flgDocumentoIdentificacionValidado = 1;
    	else
    		this.flgDocumentoIdentificacionValidado = 0;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column PERSONA.FLG_LIBRETA_MILITAR_VALIDADA
     *
     * @return the value of PERSONA.FLG_LIBRETA_MILITAR_VALIDADA
     * @mbg.generated Thu Feb 08 14:16:06 COT 2018
     */
    public boolean getFlgLibretaMilitarValidada(){
    	return this.flgLibretaMilitarValidada != null && this.flgLibretaMilitarValidada.intValue() == 1 ? true: false;
    }

    public void setFlgLibretaMilitarValidada(Short flgLibretaMilitarValidada)
    {
	this.flgLibretaMilitarValidada = flgLibretaMilitarValidada;
    }

    public void setFlgLibretaMilitarValidada(boolean flgLibretaMilitarValidada){
    	if (flgLibretaMilitarValidada) 
    		this.flgLibretaMilitarValidada = 1;
    	else 
    		this.flgLibretaMilitarValidada = 0;
    }
    
    
    public boolean getFlgDiscapacidadValidada(){
    	return this.flgDiscapacidadValidada != null && this.flgDiscapacidadValidada.intValue() == 1 ? true: false;
    }

    public void setFlgDiscapacidadValidada(Short flgDiscapacidadValidada)
    {
	this.flgDiscapacidadValidada = flgDiscapacidadValidada;
    }

    public void setFlgDiscapacidadValidada(boolean flgDiscapacidadValidada){
    	if (flgDiscapacidadValidada) 
    		this.flgDiscapacidadValidada = 1;
    	else 
    		this.flgDiscapacidadValidada = 0;
    }

    private long total;

    private Integer limitInit;

    private Integer limitEnd;

    public Integer getLimitInit()
    {
	return limitInit;
    }

    public void setLimitInit(Integer limitInit)
    {
	this.limitInit = limitInit;
    }

    public Integer getLimitEnd()
    {
	return limitEnd;
    }

    public void setLimitEnd(Integer limitEnd)
    {
	this.limitEnd = limitEnd;
    }

    public long getTotal()
    {
	return total;
    }

    public void setTotal(long total)
    {
	this.total = total;
    }
    
    /**
	 * @return the fechaMarcacionPep
	 */
	public Date getFechaMarcacionPep() {
		return fechaMarcacionPep;
	}

	/**
	 * @param fechaMarcacionPep the fechaMarcacionPep to set
	 */
	public void setFechaMarcacionPep(Date fechaMarcacionPep) {
		this.fechaMarcacionPep = fechaMarcacionPep;
	}

	/**
	 * @return the marcacionPepVinc
	 */
	public Short getMarcacionPepVinc() {
		return marcacionPepVinc;
	}

	/**
	 * @param marcacionPepVinc the marcacionPepVinc to set
	 */
	public void setMarcacionPepVinc(Short marcacionPepVinc) {
		this.marcacionPepVinc = marcacionPepVinc;
	}

	/**
	 * @return the porcentajeHV
	 */
	public BigDecimal getPorcentajeHV() {
		return porcentajeHV;
	}

	/**
	 * @param porcentajeHV the porcentajeHV to set
	 */
	public void setPorcentajeHV(BigDecimal porcentajeHV) {
		this.porcentajeHV = porcentajeHV;
	}
	
	public String getDocumentoDiscapacidadUrl() {
		return documentoDiscapacidadUrl;
	}

	public void setDocumentoDiscapacidadUrl(String documentoDiscapacidadUrl) {
		this.documentoDiscapacidadUrl = documentoDiscapacidadUrl;
	}

	public String getNombres() {
		String nombre = this.primerNombre;
		if(this.segundoNombre != null) {
			nombre += " "+this.segundoNombre;
		}
		nombre += " "+this.primerApellido;
		if(this.segundoApellido != null) {
			nombre += " "+this.segundoApellido;
		}
		return nombre;
	}
}