package co.gov.dafp.sigep2.entities;

import java.util.Date;

import co.gov.dafp.sigep2.utils.ErrorMensajes;

public class ProcesosCargaMasiva extends ErrorMensajes{
    /**
	 * 
	 */
	private static final long serialVersionUID = -6171266126830099299L;
	
	public static final String NOMBRE_SEQUENCIA_TABLA = "PROCESO_CARGA_MASIVA";

	 /**
		 * This field was generated by MyBatis Generator. This field corresponds to the database column PROCESOS_CARGA_MASIVA.COD_PROCESO_CARGA_MASIVA
		 * @mbg.generated  Fri Feb 08 08:00:42 COT 2019
		 */
		private Long codProcesoCargaMasiva;


		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the database column PROCESOS_CARGA_MASIVA.FECHA_INICIO
		 * @mbg.generated  Fri Feb 08 08:00:42 COT 2019
		 */
		private Date fechaInicio;


		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the database column PROCESOS_CARGA_MASIVA.FECHA_FIN
		 * @mbg.generated  Fri Feb 08 08:00:42 COT 2019
		 */
		private Date fechaFin;


		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the database column PROCESOS_CARGA_MASIVA.COD_ENTIDAD
		 * @mbg.generated  Fri Feb 08 08:00:42 COT 2019
		 */
		private Short codEntidad;


		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the database column PROCESOS_CARGA_MASIVA.TIPO_CARGUE
		 * @mbg.generated  Fri Feb 08 08:00:42 COT 2019
		 */
		private Short tipoCargue;


		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the database column PROCESOS_CARGA_MASIVA.ESTADO
		 * @mbg.generated  Fri Feb 08 08:00:42 COT 2019
		 */
		private Short estado;


		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the database column PROCESOS_CARGA_MASIVA.REGISTROS_EXITOSOS
		 * @mbg.generated  Fri Feb 08 08:00:42 COT 2019
		 */
		private Short registrosExitosos;


		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the database column PROCESOS_CARGA_MASIVA.REGISTROS_FALLIDOS
		 * @mbg.generated  Fri Feb 08 08:00:42 COT 2019
		 */
		private Short registrosFallidos;


		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the database column PROCESOS_CARGA_MASIVA.AUD_FECHA_ACTUALIZACION
		 * @mbg.generated  Fri Feb 08 08:00:42 COT 2019
		 */
		private Date audFechaActualizacion;


		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the database column PROCESOS_CARGA_MASIVA.AUD_COD_USUARIO
		 * @mbg.generated  Fri Feb 08 08:00:42 COT 2019
		 */
		private Long audCodUsuario;


		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the database column PROCESOS_CARGA_MASIVA.AUD_COD_ROL
		 * @mbg.generated  Fri Feb 08 08:00:42 COT 2019
		 */
		private Integer audCodRol;


		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the database column PROCESOS_CARGA_MASIVA.AUD_ACCION
		 * @mbg.generated  Fri Feb 08 08:00:42 COT 2019
		 */
		private Integer audAccion;


		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the database column PROCESOS_CARGA_MASIVA.FLG_ACTIVO
		 * @mbg.generated  Fri Feb 08 08:00:42 COT 2019
		 */
		private Short flgActivo;


		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the database column PROCESOS_CARGA_MASIVA.RESULTADO
		 * @mbg.generated  Fri Feb 08 08:00:42 COT 2019
		 */
		private String resultado;


		/**
		 * This field was generated by MyBatis Generator. This field corresponds to the database column PROCESOS_CARGA_MASIVA.URL_ARCHIVO_LOGS
		 * @mbg.generated  Fri Feb 08 08:00:42 COT 2019
		 */
		private String urlArchivoLogs;

		
		private Short flgNotificado;
		/**
		 * This method was generated by MyBatis Generator. This method returns the value of the database column PROCESOS_CARGA_MASIVA.COD_PROCESO_CARGA_MASIVA
		 * @return  the value of PROCESOS_CARGA_MASIVA.COD_PROCESO_CARGA_MASIVA
		 * @mbg.generated  Fri Feb 08 08:00:42 COT 2019
		 */
		public Long getCodProcesoCargaMasiva() {
			return codProcesoCargaMasiva;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the value of the database column PROCESOS_CARGA_MASIVA.COD_PROCESO_CARGA_MASIVA
		 * @param codProcesoCargaMasiva  the value for PROCESOS_CARGA_MASIVA.COD_PROCESO_CARGA_MASIVA
		 * @mbg.generated  Fri Feb 08 08:00:42 COT 2019
		 */
		public void setCodProcesoCargaMasiva(Long codProcesoCargaMasiva) {
			this.codProcesoCargaMasiva = codProcesoCargaMasiva;
		}

		/**
		 * This method was generated by MyBatis Generator. This method returns the value of the database column PROCESOS_CARGA_MASIVA.FECHA_INICIO
		 * @return  the value of PROCESOS_CARGA_MASIVA.FECHA_INICIO
		 * @mbg.generated  Fri Feb 08 08:00:42 COT 2019
		 */
		public Date getFechaInicio() {
			return fechaInicio;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the value of the database column PROCESOS_CARGA_MASIVA.FECHA_INICIO
		 * @param fechaInicio  the value for PROCESOS_CARGA_MASIVA.FECHA_INICIO
		 * @mbg.generated  Fri Feb 08 08:00:42 COT 2019
		 */
		public void setFechaInicio(Date fechaInicio) {
			this.fechaInicio = fechaInicio;
		}

		/**
		 * This method was generated by MyBatis Generator. This method returns the value of the database column PROCESOS_CARGA_MASIVA.FECHA_FIN
		 * @return  the value of PROCESOS_CARGA_MASIVA.FECHA_FIN
		 * @mbg.generated  Fri Feb 08 08:00:42 COT 2019
		 */
		public Date getFechaFin() {
			return fechaFin;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the value of the database column PROCESOS_CARGA_MASIVA.FECHA_FIN
		 * @param fechaFin  the value for PROCESOS_CARGA_MASIVA.FECHA_FIN
		 * @mbg.generated  Fri Feb 08 08:00:42 COT 2019
		 */
		public void setFechaFin(Date fechaFin) {
			this.fechaFin = fechaFin;
		}

		/**
		 * This method was generated by MyBatis Generator. This method returns the value of the database column PROCESOS_CARGA_MASIVA.COD_ENTIDAD
		 * @return  the value of PROCESOS_CARGA_MASIVA.COD_ENTIDAD
		 * @mbg.generated  Fri Feb 08 08:00:42 COT 2019
		 */
		public Short getCodEntidad() {
			return codEntidad;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the value of the database column PROCESOS_CARGA_MASIVA.COD_ENTIDAD
		 * @param codEntidad  the value for PROCESOS_CARGA_MASIVA.COD_ENTIDAD
		 * @mbg.generated  Fri Feb 08 08:00:42 COT 2019
		 */
		public void setCodEntidad(Short codEntidad) {
			this.codEntidad = codEntidad;
		}

		/**
		 * This method was generated by MyBatis Generator. This method returns the value of the database column PROCESOS_CARGA_MASIVA.TIPO_CARGUE
		 * @return  the value of PROCESOS_CARGA_MASIVA.TIPO_CARGUE
		 * @mbg.generated  Fri Feb 08 08:00:42 COT 2019
		 */
		public Short getTipoCargue() {
			return tipoCargue;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the value of the database column PROCESOS_CARGA_MASIVA.TIPO_CARGUE
		 * @param tipoCargue  the value for PROCESOS_CARGA_MASIVA.TIPO_CARGUE
		 * @mbg.generated  Fri Feb 08 08:00:42 COT 2019
		 */
		public void setTipoCargue(Short tipoCargue) {
			this.tipoCargue = tipoCargue;
		}

		/**
		 * This method was generated by MyBatis Generator. This method returns the value of the database column PROCESOS_CARGA_MASIVA.ESTADO
		 * @return  the value of PROCESOS_CARGA_MASIVA.ESTADO
		 * @mbg.generated  Fri Feb 08 08:00:42 COT 2019
		 */
		public Short getEstado() {
			return estado;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the value of the database column PROCESOS_CARGA_MASIVA.ESTADO
		 * @param estado  the value for PROCESOS_CARGA_MASIVA.ESTADO
		 * @mbg.generated  Fri Feb 08 08:00:42 COT 2019
		 */
		public void setEstado(Short estado) {
			this.estado = estado;
		}

		/**
		 * This method was generated by MyBatis Generator. This method returns the value of the database column PROCESOS_CARGA_MASIVA.REGISTROS_EXITOSOS
		 * @return  the value of PROCESOS_CARGA_MASIVA.REGISTROS_EXITOSOS
		 * @mbg.generated  Fri Feb 08 08:00:42 COT 2019
		 */
		public Short getRegistrosExitosos() {
			return registrosExitosos;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the value of the database column PROCESOS_CARGA_MASIVA.REGISTROS_EXITOSOS
		 * @param registrosExitosos  the value for PROCESOS_CARGA_MASIVA.REGISTROS_EXITOSOS
		 * @mbg.generated  Fri Feb 08 08:00:42 COT 2019
		 */
		public void setRegistrosExitosos(Short registrosExitosos) {
			this.registrosExitosos = registrosExitosos;
		}

		/**
		 * This method was generated by MyBatis Generator. This method returns the value of the database column PROCESOS_CARGA_MASIVA.REGISTROS_FALLIDOS
		 * @return  the value of PROCESOS_CARGA_MASIVA.REGISTROS_FALLIDOS
		 * @mbg.generated  Fri Feb 08 08:00:42 COT 2019
		 */
		public Short getRegistrosFallidos() {
			return registrosFallidos;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the value of the database column PROCESOS_CARGA_MASIVA.REGISTROS_FALLIDOS
		 * @param registrosFallidos  the value for PROCESOS_CARGA_MASIVA.REGISTROS_FALLIDOS
		 * @mbg.generated  Fri Feb 08 08:00:42 COT 2019
		 */
		public void setRegistrosFallidos(Short registrosFallidos) {
			this.registrosFallidos = registrosFallidos;
		}

		/**
		 * This method was generated by MyBatis Generator. This method returns the value of the database column PROCESOS_CARGA_MASIVA.AUD_FECHA_ACTUALIZACION
		 * @return  the value of PROCESOS_CARGA_MASIVA.AUD_FECHA_ACTUALIZACION
		 * @mbg.generated  Fri Feb 08 08:00:42 COT 2019
		 */
		public Date getAudFechaActualizacion() {
			return audFechaActualizacion;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the value of the database column PROCESOS_CARGA_MASIVA.AUD_FECHA_ACTUALIZACION
		 * @param audFechaActualizacion  the value for PROCESOS_CARGA_MASIVA.AUD_FECHA_ACTUALIZACION
		 * @mbg.generated  Fri Feb 08 08:00:42 COT 2019
		 */
		public void setAudFechaActualizacion(Date audFechaActualizacion) {
			this.audFechaActualizacion = audFechaActualizacion;
		}

		/**
		 * This method was generated by MyBatis Generator. This method returns the value of the database column PROCESOS_CARGA_MASIVA.AUD_COD_USUARIO
		 * @return  the value of PROCESOS_CARGA_MASIVA.AUD_COD_USUARIO
		 * @mbg.generated  Fri Feb 08 08:00:42 COT 2019
		 */
		public Long getAudCodUsuario() {
			return audCodUsuario;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the value of the database column PROCESOS_CARGA_MASIVA.AUD_COD_USUARIO
		 * @param audCodUsuario  the value for PROCESOS_CARGA_MASIVA.AUD_COD_USUARIO
		 * @mbg.generated  Fri Feb 08 08:00:42 COT 2019
		 */
		public void setAudCodUsuario(Long audCodUsuario) {
			this.audCodUsuario = audCodUsuario;
		}

		/**
		 * This method was generated by MyBatis Generator. This method returns the value of the database column PROCESOS_CARGA_MASIVA.AUD_COD_ROL
		 * @return  the value of PROCESOS_CARGA_MASIVA.AUD_COD_ROL
		 * @mbg.generated  Fri Feb 08 08:00:42 COT 2019
		 */
		public Integer getAudCodRol() {
			return audCodRol;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the value of the database column PROCESOS_CARGA_MASIVA.AUD_COD_ROL
		 * @param audCodRol  the value for PROCESOS_CARGA_MASIVA.AUD_COD_ROL
		 * @mbg.generated  Fri Feb 08 08:00:42 COT 2019
		 */
		public void setAudCodRol(Integer audCodRol) {
			this.audCodRol = audCodRol;
		}

		/**
		 * This method was generated by MyBatis Generator. This method returns the value of the database column PROCESOS_CARGA_MASIVA.AUD_ACCION
		 * @return  the value of PROCESOS_CARGA_MASIVA.AUD_ACCION
		 * @mbg.generated  Fri Feb 08 08:00:42 COT 2019
		 */
		public Integer getAudAccion() {
			return audAccion;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the value of the database column PROCESOS_CARGA_MASIVA.AUD_ACCION
		 * @param audAccion  the value for PROCESOS_CARGA_MASIVA.AUD_ACCION
		 * @mbg.generated  Fri Feb 08 08:00:42 COT 2019
		 */
		public void setAudAccion(Integer audAccion) {
			this.audAccion = audAccion;
		}

		/**
		 * This method was generated by MyBatis Generator. This method returns the value of the database column PROCESOS_CARGA_MASIVA.FLG_ACTIVO
		 * @return  the value of PROCESOS_CARGA_MASIVA.FLG_ACTIVO
		 * @mbg.generated  Fri Feb 08 08:00:42 COT 2019
		 */
		public Short getFlgActivo() {
			return flgActivo;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the value of the database column PROCESOS_CARGA_MASIVA.FLG_ACTIVO
		 * @param flgActivo  the value for PROCESOS_CARGA_MASIVA.FLG_ACTIVO
		 * @mbg.generated  Fri Feb 08 08:00:42 COT 2019
		 */
		public void setFlgActivo(Short flgActivo) {
			this.flgActivo = flgActivo;
		}

		/**
		 * This method was generated by MyBatis Generator. This method returns the value of the database column PROCESOS_CARGA_MASIVA.RESULTADO
		 * @return  the value of PROCESOS_CARGA_MASIVA.RESULTADO
		 * @mbg.generated  Fri Feb 08 08:00:42 COT 2019
		 */
		public String getResultado() {
			return resultado;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the value of the database column PROCESOS_CARGA_MASIVA.RESULTADO
		 * @param resultado  the value for PROCESOS_CARGA_MASIVA.RESULTADO
		 * @mbg.generated  Fri Feb 08 08:00:42 COT 2019
		 */
		public void setResultado(String resultado) {
			this.resultado = resultado;
		}

		/**
		 * This method was generated by MyBatis Generator. This method returns the value of the database column PROCESOS_CARGA_MASIVA.URL_ARCHIVO_LOGS
		 * @return  the value of PROCESOS_CARGA_MASIVA.URL_ARCHIVO_LOGS
		 * @mbg.generated  Fri Feb 08 08:00:42 COT 2019
		 */
		public String getUrlArchivoLogs() {
			return urlArchivoLogs;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the value of the database column PROCESOS_CARGA_MASIVA.URL_ARCHIVO_LOGS
		 * @param urlArchivoLogs  the value for PROCESOS_CARGA_MASIVA.URL_ARCHIVO_LOGS
		 * @mbg.generated  Fri Feb 08 08:00:42 COT 2019
		 */
		public void setUrlArchivoLogs(String urlArchivoLogs) {
			this.urlArchivoLogs = urlArchivoLogs;
		}
   
    /**
		 * @return the flgNotificado
		 */
		public Short getFlgNotificado() {
			return flgNotificado;
		}

		/**
		 * @param flgNotificado the flgNotificado to set
		 */
		public void setFlgNotificado(Short flgNotificado) {
			this.flgNotificado = flgNotificado;
		}

	/**
	 * @return the limitInit
	 */
	public int getLimitInit() {
		return limitInit;
	}

	/**
	 * @param limitInit the limitInit to set
	 */
	public void setLimitInit(int limitInit) {
		this.limitInit = limitInit;
	}

	/**
	 * @return the limitEnd
	 */
	public int getLimitEnd() {
		return limitEnd;
	}

	/**
	 * @param limitEnd the limitEnd to set
	 */
	public void setLimitEnd(int limitEnd) {
		this.limitEnd = limitEnd;
	}

	private int limitInit;
    
    
    private int limitEnd;
    
}