package co.gov.dafp.sigep2.entities;

import java.math.BigDecimal;
import java.util.Date;

import co.gov.dafp.sigep2.utils.ErrorMensajes;

public class Token extends ErrorMensajes{
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TOKEN.COD_TOKEN
	 * @mbg.generated  Fri Sep 07 08:55:22 COT 2018
	 */
	private BigDecimal codToken;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TOKEN.COD_USUARIO
	 * @mbg.generated  Fri Sep 07 08:55:22 COT 2018
	 */
	private BigDecimal codUsuario;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TOKEN.COD_ENTIDAD
	 * @mbg.generated  Fri Sep 07 08:55:22 COT 2018
	 */
	private Long codEntidad;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TOKEN.TOKEN
	 * @mbg.generated  Fri Sep 07 08:55:22 COT 2018
	 */
	private String token;
	
	
	private Short origen;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TOKEN.FECHA_GENERACION
	 * @mbg.generated  Fri Sep 07 08:55:22 COT 2018
	 */
	private Date fechaGeneracion;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TOKEN.FLG_ACTIVO
	 * @mbg.generated  Fri Sep 07 08:55:22 COT 2018
	 */
	private Short flgActivo;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TOKEN.AUD_FECHA_ACTUALIZACION
	 * @mbg.generated  Fri Sep 07 08:55:22 COT 2018
	 */
	private Date audFechaActualizacion;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TOKEN.AUD_COD_USUARIO
	 * @mbg.generated  Fri Sep 07 08:55:22 COT 2018
	 */
	private Long audCodUsuario;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TOKEN.AUD_COD_ROL
	 * @mbg.generated  Fri Sep 07 08:55:22 COT 2018
	 */
	private Integer audCodRol;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TOKEN.AUD_ACCION
	 * @mbg.generated  Fri Sep 07 08:55:22 COT 2018
	 */
	private Integer audAccion;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TOKEN.FECHA_ACK
	 * @mbg.generated  Fri Sep 07 08:55:22 COT 2018
	 */
	private Date fechaAck;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TOKEN.COD_TOKEN
	 * @return  the value of TOKEN.COD_TOKEN
	 * @mbg.generated  Fri Sep 07 08:55:22 COT 2018
	 */
	public BigDecimal getCodToken() {
		return codToken;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TOKEN.COD_TOKEN
	 * @param codToken  the value for TOKEN.COD_TOKEN
	 * @mbg.generated  Fri Sep 07 08:55:22 COT 2018
	 */
	public void setCodToken(BigDecimal codToken) {
		this.codToken = codToken;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TOKEN.COD_USUARIO
	 * @return  the value of TOKEN.COD_USUARIO
	 * @mbg.generated  Fri Sep 07 08:55:22 COT 2018
	 */
	public BigDecimal getCodUsuario() {
		return codUsuario;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TOKEN.COD_USUARIO
	 * @param codUsuario  the value for TOKEN.COD_USUARIO
	 * @mbg.generated  Fri Sep 07 08:55:22 COT 2018
	 */
	public void setCodUsuario(BigDecimal codUsuario) {
		this.codUsuario = codUsuario;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TOKEN.COD_ENTIDAD
	 * @return  the value of TOKEN.COD_ENTIDAD
	 * @mbg.generated  Fri Sep 07 08:55:22 COT 2018
	 */
	public Long getCodEntidad() {
		return codEntidad;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TOKEN.COD_ENTIDAD
	 * @param codEntidad  the value for TOKEN.COD_ENTIDAD
	 * @mbg.generated  Fri Sep 07 08:55:22 COT 2018
	 */
	public void setCodEntidad(Long codEntidad) {
		this.codEntidad = codEntidad;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TOKEN.TOKEN
	 * @return  the value of TOKEN.TOKEN
	 * @mbg.generated  Fri Sep 07 08:55:22 COT 2018
	 */
	public String getToken() {
		return token;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TOKEN.TOKEN
	 * @param token  the value for TOKEN.TOKEN
	 * @mbg.generated  Fri Sep 07 08:55:22 COT 2018
	 */
	public void setToken(String token) {
		this.token = token;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TOKEN.FECHA_GENERACION
	 * @return  the value of TOKEN.FECHA_GENERACION
	 * @mbg.generated  Fri Sep 07 08:55:22 COT 2018
	 */
	public Date getFechaGeneracion() {
		return fechaGeneracion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TOKEN.FECHA_GENERACION
	 * @param fechaGeneracion  the value for TOKEN.FECHA_GENERACION
	 * @mbg.generated  Fri Sep 07 08:55:22 COT 2018
	 */
	public void setFechaGeneracion(Date fechaGeneracion) {
		this.fechaGeneracion = fechaGeneracion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TOKEN.FLG_ACTIVO
	 * @return  the value of TOKEN.FLG_ACTIVO
	 * @mbg.generated  Fri Sep 07 08:55:22 COT 2018
	 */
	public Short getFlgActivo() {
		return flgActivo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TOKEN.FLG_ACTIVO
	 * @param flgActivo  the value for TOKEN.FLG_ACTIVO
	 * @mbg.generated  Fri Sep 07 08:55:22 COT 2018
	 */
	public void setFlgActivo(Short flgActivo) {
		this.flgActivo = flgActivo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TOKEN.AUD_FECHA_ACTUALIZACION
	 * @return  the value of TOKEN.AUD_FECHA_ACTUALIZACION
	 * @mbg.generated  Fri Sep 07 08:55:22 COT 2018
	 */
	public Date getAudFechaActualizacion() {
		return audFechaActualizacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TOKEN.AUD_FECHA_ACTUALIZACION
	 * @param audFechaActualizacion  the value for TOKEN.AUD_FECHA_ACTUALIZACION
	 * @mbg.generated  Fri Sep 07 08:55:22 COT 2018
	 */
	public void setAudFechaActualizacion(Date audFechaActualizacion) {
		this.audFechaActualizacion = audFechaActualizacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TOKEN.AUD_COD_USUARIO
	 * @return  the value of TOKEN.AUD_COD_USUARIO
	 * @mbg.generated  Fri Sep 07 08:55:22 COT 2018
	 */
	public Long getAudCodUsuario() {
		return audCodUsuario;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TOKEN.AUD_COD_USUARIO
	 * @param audCodUsuario  the value for TOKEN.AUD_COD_USUARIO
	 * @mbg.generated  Fri Sep 07 08:55:22 COT 2018
	 */
	public void setAudCodUsuario(Long audCodUsuario) {
		this.audCodUsuario = audCodUsuario;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TOKEN.AUD_COD_ROL
	 * @return  the value of TOKEN.AUD_COD_ROL
	 * @mbg.generated  Fri Sep 07 08:55:22 COT 2018
	 */
	public Integer getAudCodRol() {
		return audCodRol;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TOKEN.AUD_COD_ROL
	 * @param audCodRol  the value for TOKEN.AUD_COD_ROL
	 * @mbg.generated  Fri Sep 07 08:55:22 COT 2018
	 */
	public void setAudCodRol(Integer audCodRol) {
		this.audCodRol = audCodRol;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TOKEN.AUD_ACCION
	 * @return  the value of TOKEN.AUD_ACCION
	 * @mbg.generated  Fri Sep 07 08:55:22 COT 2018
	 */
	public Integer getAudAccion() {
		return audAccion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TOKEN.AUD_ACCION
	 * @param audAccion  the value for TOKEN.AUD_ACCION
	 * @mbg.generated  Fri Sep 07 08:55:22 COT 2018
	 */
	public void setAudAccion(Integer audAccion) {
		this.audAccion = audAccion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TOKEN.FECHA_ACK
	 * @return  the value of TOKEN.FECHA_ACK
	 * @mbg.generated  Fri Sep 07 08:55:22 COT 2018
	 */
	public Date getFechaAck() {
		return fechaAck;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TOKEN.FECHA_ACK
	 * @param fechaAck  the value for TOKEN.FECHA_ACK
	 * @mbg.generated  Fri Sep 07 08:55:22 COT 2018
	 */
	public void setFechaAck(Date fechaAck) {
		this.fechaAck = fechaAck;
	}

	/**
	 * 
	 */
	private static final long serialVersionUID = -6901185842138415163L;

	private long timeOut;

    /**
	 * @return the timeOut
	 */
	public long getTimeOut() {
		return timeOut;
	}

	/**
	 * @param timeOut the timeOut to set
	 */
	public void setTimeOut(long timeOut) {
		this.timeOut = timeOut;
	}

	/**
	 * @return the origen
	 */
	public Short getOrigen() {
		return origen;
	}

	/**
	 * @param origen the origen to set
	 */
	public void setOrigen(Short origen) {
		this.origen = origen;
	}

}