package co.gov.dafp.sigep2.constante;

import java.util.Locale;
import java.util.ResourceBundle;
import java.util.ResourceBundle.Control;

public final class MenuBundleConstants {

	public static final String MENU_BUNDLE_CONSTANTS = "co.gov.dafp.sigep2.menu";

	public static final String MENU_INICIO 												= "MENU_INICIO";
	public static final String MENU_INICIO_RECAUDO 										= "MENU_INICIO_RECAUDO";
	public static final String SUBMENU_RECAUDO_CARGUE_ARCHIVO 							= "SUBMENU_RECAUDO_CARGUE_ARCHIVO";
	public static final String SUBMENU_RECAUDO_MULTAS 									= "SUBMENU_RECAUDO_MULTAS";
	public static final String SUBMENU_RECAUDO_MULTAS_CREAR 							= "SUBMENU_RECAUDO_MULTAS_CREAR";
	public static final String SUBMENU_RECAUDO_MULTAS_BUSCAR 							= "SUBMENU_RECAUDO_MULTAS_BUSCAR";
	public static final String MENU_INICIO_PRESUPUESTO 									= "MENU_INICIO_PRESUPUESTO";
	public static final String SUBMENU_PRESUPUESTO_CARGUE_ARCHIVO 						= "SUBMENU_PRESUPUESTO_CARGUE_ARCHIVO";
	public static final String SUBMENU_PRESUPUESTO_PROYECTOS 							= "SUBMENU_PRESUPUESTO_PROYECTOS";
	public static final String SUBMENU_PRESUPUESTO_RESOLUCION 							= "SUBMENU_PRESUPUESTO_RESOLUCION";
	public static final String SUBMENU_PRESUPUESTO_PROYECTOS_CREAR 						= "SUBMENU_PRESUPUESTO_PROYECTOS_CREAR";
	public static final String SUBMENU_PRESUPUESTO_PROYECTOS_EDITAR 					= "SUBMENU_PRESUPUESTO_PROYECTOS_EDITAR";
	public static final String SUBMENU_PRESUPUESTO_PROYECTOS_SUSPENDER 					= "SUBMENU_PRESUPUESTO_PROYECTOS_SUSPENDER";
	public static final String SUBMENU_PRESUPUESTO_PROYECTOS_ACTIVAR 					= "SUBMENU_PRESUPUESTO_PROYECTOS_ACTIVAR";
	public static final String SUBMENU_PRESUPUESTO_PARAMETRIZAR_RESOLUCION 				= "SUBMENU_PRESUPUESTO_PARAMETRIZAR_RESOLUCION";
	public static final String SUBMENU_PRESUPUESTO_APROBAR_RESOLUCION 					= "SUBMENU_PRESUPUESTO_APROBAR_RESOLUCION";
	public static final String MENU_INICIO_PRIORIZACION 								= "MENU_INICIO_PRIORIZACION";
	public static final String SUBMENU_PRIORIZACION_CARGUE_ARCHIVO_NOVEDADES 			= "SUBMENU_PRIORIZACION_CARGUE_ARCHIVO_NOVEDADES";
	public static final String SUBMENU_PRIORIZACION_TOTAL 								= "SUBMENU_PRIORIZACION_TOTAL";
	public static final String SUBMENU_PRIORIZACION_PARAMETRIZACION_ADMIN_PRIORIZACION_TOTAL 		= "SUBMENU_PRIORIZACION_PARAMETRIZACION_ADMIN_PRIORIZACION_TOTAL";
	public static final String SUBMENU_PRIORIZACION_PARAMETRIZACION_ADMIN_PRIORIZACION_TOTAL_CREAR 	= "SUBMENU_PRIORIZACION_PARAMETRIZACION_ADMIN_PRIORIZACION_TOTAL_CREAR";
	public static final String SUBMENU_PRIORIZACION_PARAMETRIZACION_ADMIN_PRIORIZACION_TOTAL_EDITAR = "SUBMENU_PRIORIZACION_PARAMETRIZACION_ADMIN_PRIORIZACION_TOTAL_EDITAR";
	public static final String MENU_INICIO_SISTEMA 										= "MENU_INICIO_SISTEMA";
	public static final String SUBMENU_SISTEMA_PARAMETRIZACION 							= "SUBMENU_SISTEMA_PARAMETRIZACION";
	public static final String SUBMENU_SISTEMA_PARAMETRIZACION_ADMIN_MAESTRO 			= "SUBMENU_SISTEMA_PARAMETRIZACION_ADMIN_MAESTRO";
	public static final String SUBMENU_SISTEMA_PARAMETRIZACION_ADMIN_MAESTRO_CREAR 		= "SUBMENU_SISTEMA_PARAMETRIZACION_ADMIN_MAESTRO_CREAR";
	public static final String SUBMENU_SISTEMA_PARAMETRIZACION_ADMIN_MAESTRO_EDITAR 	= "SUBMENU_SISTEMA_PARAMETRIZACION_ADMIN_MAESTRO_EDITAR";
	public static final String SUBMENU_SISTEMA_PARAMETRIZACION_ADMIN_PLANTILLA 			= "SUBMENU_SISTEMA_PARAMETRIZACION_ADMIN_PLANTILLA";
	public static final String SUBMENU_SISTEMA_PARAMETRIZACION_ADMIN_PLANTILLA_CREAR 	= "SUBMENU_SISTEMA_PARAMETRIZACION_ADMIN_PLANTILLA_CREAR";
	public static final String SUBMENU_SISTEMA_PARAMETRIZACION_ADMIN_PLANTILLA_EDITAR 	= "SUBMENU_SISTEMA_PARAMETRIZACION_ADMIN_PLANTILLA_EDITAR";
	public static final String SUBMENU_SISTEMA_PARAMETRIZACION_TERCERO 					= "SUBMENU_SISTEMA_PARAMETRIZACION_TERCERO";
	public static final String SUBMENU_SISTEMA_PARAMETRIZACION_TERCERO_CREAR 			= "SUBMENU_SISTEMA_PARAMETRIZACION_TERCERO_CREAR";
	public static final String SUBMENU_SISTEMA_PARAMETRIZACION_TERCERO_EDITAR 			= "SUBMENU_SISTEMA_PARAMETRIZACION_TERCERO_EDITAR";
	public static final String SUBMENU_SISTEMA_PARAMETRIZACION_PERSONA 					= "SUBMENU_SISTEMA_PARAMETRIZACION_PERSONA";
	public static final String SUBMENU_SISTEMA_PARAMETRIZACION_PERSONA_CREAR 			= "SUBMENU_SISTEMA_PARAMETRIZACION_PERSONA_CREAR";
	public static final String SUBMENU_SISTEMA_PARAMETRIZACION_PERSONA_EDITAR 			= "SUBMENU_SISTEMA_PARAMETRIZACION_PERSONA_EDITAR";
	public static final String SUBMENU_SISTEMA_SEGURIDAD 								= "SUBMENU_SISTEMA_SEGURIDAD";
	public static final String SUBMENU_SISTEMA_SEGURIDAD_RECURSOS_MENU 					= "SUBMENU_SISTEMA_SEGURIDAD_RECURSOS_MENU";
	public static final String SUBMENU_SISTEMA_SEGURIDAD_RECURSOS_MENU_RECURSOS 		= "SUBMENU_SISTEMA_SEGURIDAD_RECURSOS_MENU_RECURSOS";
	public static final String SUBMENU_SISTEMA_SEGURIDAD_RECURSOS_MENU_RECURSOS_PERFIL 	= "SUBMENU_SISTEMA_SEGURIDAD_RECURSOS_MENU_RECURSOS_PERFIL";
	public static final String SUBMENU_SISTEMA_SEGURIDAD_USUARIOS 						= "SUBMENU_SISTEMA_SEGURIDAD_USUARIOS";
	public static final String SUBMENU_SISTEMA_SEGURIDAD_USUARIOS_CRER 					= "SUBMENU_SISTEMA_SEGURIDAD_USUARIOS_CRER";
	public static final String SUBMENU_SISTEMA_SEGURIDAD_USUARIOS_EDITAR 				= "SUBMENU_SISTEMA_SEGURIDAD_USUARIOS_EDITAR";
	public static final String SUBMENU_SISTEMA_SEGURIDAD_LOG_AUDITORIA 					= "SUBMENU_SISTEMA_SEGURIDAD_LOG_AUDITORIA";
	public static final String SUBMENU_SISTEMA_SEGURIDAD_LOG_AUDITORIA_CONSULTAR 		= "SUBMENU_SISTEMA_SEGURIDAD_LOG_AUDITORIA_CONSULTAR";
	public static final String MENU_REPORTES 											= "MENU_REPORTES";
	public static final String SUBMENU_REPORTES_RECAUDOS 								= "SUBMENU_REPORTES_RECAUDOS";
	public static final String SUBMENU_REPORTES_RECAUDOS_SUBSISTENCIA 					= "SUBMENU_REPORTES_RECAUDOS_SUBSISTENCIA";
	public static final String SUBMENU_REPORTES_RECAUDOS_SOLIDARIDAD 					= "SUBMENU_REPORTES_RECAUDOS_SOLIDARIDAD";
	public static final String SUBMENU_REPORTES_PRESUPUESTO 							= "SUBMENU_REPORTES_PRESUPUESTO";
	public static final String SUBMENU_REPORTES_PRIORIZACION 							= "SUBMENU_REPORTES_PRIORIZACION";
	public static final String SUBMENU_REPORTES_RECAUDO_EXTRACTO_LOG_BANCARIO 			= "SUBMENU_REPORTES_RECAUDO_EXTRACTO_LOG_BANCARIO";
	public static final String SUBMENU_REPORTES_RECAUDO_EXTRACTO_LOG_BANCARIO_PILA 		= "SUBMENU_REPORTES_RECAUDO_EXTRACTO_LOG_BANCARIO_PILA";
	public static final String SUBMENU_REPORTES_RECAUDO_EXTRACTO_LOG_BANCARIO_AFP 		= "SUBMENU_REPORTES_RECAUDO_EXTRACTO_LOG_BANCARIO_AFP";
	public static final String SUBMENU_REPORTES_RECAUDO_CONSOLIDADO_SUBSISTENCIA 		= "SUBMENU_REPORTES_RECAUDO_CONSOLIDADO_SUBSISTENCIA";
	public static final String SUBMENU_REPORTES_RECAUDO_CONSOLIDADO_SOLIDARIDAD 		= "SUBMENU_REPORTES_RECAUDO_CONSOLIDADO_SOLIDARIDAD";
	public static final String SUBMENU_REPORTES_RECAUDO_CONSULTAS_REPORTE_SOLIDARIDAD_EXTRACTO_BANCARIO = "SUBMENU_REPORTES_RECAUDO_CONSULTAS_REPORTE_SOLIDARIDAD_EXTRACTO_BANCARIO";
	public static final String SUBMENU_REPORTES_RECAUDO_CONSULTAS_REPORTE_TERCERO_FALTANTE_CONCILIACION = "SUBMENU_REPORTES_RECAUDO_CONSULTAS_REPORTE_TERCERO_FALTANTE_CONCILIACION";
	public static final String SUBMENU_REPORTES_RECAUDO_EXTRACTO_BANCARIO_Y_CONSOLIDADO = "SUBMENU_REPORTES_RECAUDO_EXTRACTO_BANCARIO_Y_CONSOLIDADO";
	public static final String SUBMENU_REPORTES_RECAUDO_PROCESO_CARGUE_ARCHIVO 			= "SUBMENU_REPORTES_RECAUDO_PROCESO_CARGUE_ARCHIVO";
	public static final String SUBMENU_REPORTES_PRESUPUESTO_CONSULTA_GENERAL_EJECUCION_PRESUPUESTAL 	= "SUBMENU_REPORTES_PRESUPUESTO_CONSULTA_GENERAL_EJECUCION_PRESUPUESTAL";
	public static final String SUBMENU_REPORTES_PRESUPUESTO_CONSULTA_PAGO_VIGENCIAS_ANTERIORES 			= "SUBMENU_REPORTES_PRESUPUESTO_CONSULTA_PAGO_VIGENCIAS_ANTERIORES";
	public static final String SUBMENU_REPORTES_PRESUPUESTO_CONSULTA_CONSOLIDADA_PROYECTO 				= "SUBMENU_REPORTES_PRESUPUESTO_CONSULTA_CONSOLIDADA_PROYECTO";
	public static final String SUBMENU_REPORTES_PRESUPUESTO_PROCESO_CARGUE_ARCHIVO 		= "SUBMENU_REPORTES_PRESUPUESTO_PROCESO_CARGUE_ARCHIVO";
	public static final String SUBMENU_REPORTES_PRIORIZACION_PROCESO_CARGUE_ARCHIVO 	= "SUBMENU_REPORTES_PRIORIZACION_PROCESO_CARGUE_ARCHIVO";
	public static final String SUBMENU_REPORTES_PRIORIZACION_RESULTADO_VALIDACION_ARCHIVO_SALIDAS 		= "SUBMENU_REPORTES_PRIORIZACION_RESULTADO_VALIDACION_ARCHIVO_SALIDAS";
	public static final String SUBMENU_REPORTES_PRIORIZACION_MUNICIPIOS_SIN_PRIORIZACION 				= "SUBMENU_REPORTES_PRIORIZACION_MUNICIPIOS_SIN_PRIORIZACION";
	public static final String SUBMENU_REPORTES_PRIORIZACION_RECHAZOS 					= "SUBMENU_REPORTES_PRIORIZACION_RECHAZOS";
	public static final String SUBMENU_REPORTES_PRIORIZACION_INDIVIDUAL_CC 				= "SUBMENU_REPORTES_PRIORIZACION_INDIVIDUAL_CC";
	public static final String SUBMENU_REPORTES_PRIORIZACION_RESULTADO_CONCILIACION_CIFRAS = "SUBMENU_REPORTES_PRIORIZACION_RESULTADO_CONCILIACION_CIFRAS";
	public static final String SUBMENU_REPORTES_PRIORIZACION_RECHAZOS_FIRMA_DIGITADORA 	= "SUBMENU_REPORTES_PRIORIZACION_RECHAZOS_FIRMA_DIGITADORA";
	public static final String SUBMENU_REPORTES_PRIORIZACION_LISTADO_PRIORIZACION 		= "SUBMENU_REPORTES_PRIORIZACION_LISTADO_PRIORIZACION";
	public static final String MENU_AYUDA 												= "MENU_AYUDA";
	public static final String MENU_SALIR 												= "MENU_SALIR";

	public static String getValue(String key) {
		try {
			Control control = Control.getControl(Control.FORMAT_PROPERTIES);
			ResourceBundle bundle = ResourceBundle.getBundle(MENU_BUNDLE_CONSTANTS, control);
			return bundle.getString(key);
		} catch (Exception e) {
			return key;
		}
	}

	public static String getValue(String key, Locale locale) {
		try {
			Control control = Control.getControl(Control.FORMAT_PROPERTIES);
			ResourceBundle bundle = ResourceBundle.getBundle(MENU_BUNDLE_CONSTANTS, locale, control);
			return bundle.getString(key);
		} catch (Exception e) {
			return key;
		}
	}
}
