package co.gov.dafp.sigep2.interfaces;

import co.gov.dafp.sigep2.bean.AsignacionSalarial;
import co.gov.dafp.sigep2.bean.AsignacionSalarialExample;
import co.gov.dafp.sigep2.bean.ext.AsignacionSalarialExt;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AsignacionSalarialMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ASIGNACION_SALARIAL
	 * @mbg.generated  Fri Oct 26 16:09:26 COT 2018
	 */
	long countByExample(AsignacionSalarialExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ASIGNACION_SALARIAL
	 * @mbg.generated  Fri Oct 26 16:09:26 COT 2018
	 */
	int deleteByExample(AsignacionSalarialExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ASIGNACION_SALARIAL
	 * @mbg.generated  Fri Oct 26 16:09:26 COT 2018
	 */
	int deleteByPrimaryKey(Long codAsignacionSalarial);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ASIGNACION_SALARIAL
	 * @mbg.generated  Fri Oct 26 16:09:26 COT 2018
	 */
	int insert(AsignacionSalarial record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ASIGNACION_SALARIAL
	 * @mbg.generated  Fri Oct 26 16:09:26 COT 2018
	 */
	int insertSelective(AsignacionSalarial record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ASIGNACION_SALARIAL
	 * @mbg.generated  Fri Oct 26 16:09:26 COT 2018
	 */
	List<AsignacionSalarial> selectByExample(AsignacionSalarialExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ASIGNACION_SALARIAL
	 * @mbg.generated  Fri Oct 26 16:09:26 COT 2018
	 */
	AsignacionSalarial selectByPrimaryKey(Long codAsignacionSalarial);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ASIGNACION_SALARIAL
	 * @mbg.generated  Fri Oct 26 16:09:26 COT 2018
	 */
	int updateByExampleSelective(@Param("record") AsignacionSalarial record,
			@Param("example") AsignacionSalarialExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ASIGNACION_SALARIAL
	 * @mbg.generated  Fri Oct 26 16:09:26 COT 2018
	 */
	int updateByExample(@Param("record") AsignacionSalarial record,
			@Param("example") AsignacionSalarialExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ASIGNACION_SALARIAL
	 * @mbg.generated  Fri Oct 26 16:09:26 COT 2018
	 */
	int updateByPrimaryKeySelective(AsignacionSalarial record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ASIGNACION_SALARIAL
	 * @mbg.generated  Fri Oct 26 16:09:26 COT 2018
	 */
	int updateByPrimaryKey(AsignacionSalarial record);
	
	List<AsignacionSalarialExt> selectAsignacionSalarialFiltro(AsignacionSalarialExt aSignacionSalarialExt);
}