package co.gov.dafp.sigep2.interfaces;

import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import co.gov.dafp.sigep2.bean.Autonomia;
import co.gov.dafp.sigep2.bean.AutonomiaExample;
import co.gov.dafp.sigep2.bean.ext.AutonomiaExt;

public interface AutonomiaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTONOMIA
     *
     * @mbg.generated Fri Jan 04 10:43:05 COT 2019
     */
    long countByExample(AutonomiaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTONOMIA
     *
     * @mbg.generated Fri Jan 04 10:43:05 COT 2019
     */
    int deleteByExample(AutonomiaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTONOMIA
     *
     * @mbg.generated Fri Jan 04 10:43:05 COT 2019
     */
    int deleteByPrimaryKey(BigDecimal codAutonomia);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTONOMIA
     *
     * @mbg.generated Fri Jan 04 10:43:05 COT 2019
     */
    int insert(Autonomia record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTONOMIA
     *
     * @mbg.generated Fri Jan 04 10:43:05 COT 2019
     */
    int insertSelective(Autonomia record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTONOMIA
     *
     * @mbg.generated Fri Jan 04 10:43:05 COT 2019
     */
    List<AutonomiaExt> selectByExample(AutonomiaExample example);
    
    List<AutonomiaExt> selectByfiltro(Autonomia autonomia);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTONOMIA
     *
     * @mbg.generated Fri Jan 04 10:43:05 COT 2019
     */
    Autonomia selectByPrimaryKey(BigDecimal codAutonomia);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTONOMIA
     *
     * @mbg.generated Fri Jan 04 10:43:05 COT 2019
     */
    int updateByExampleSelective(@Param("record") Autonomia record, @Param("example") AutonomiaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTONOMIA
     *
     * @mbg.generated Fri Jan 04 10:43:05 COT 2019
     */
    int updateByExample(@Param("record") Autonomia record, @Param("example") AutonomiaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTONOMIA
     *
     * @mbg.generated Fri Jan 04 10:43:05 COT 2019
     */
    int updateByPrimaryKeySelective(Autonomia record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTONOMIA
     *
     * @mbg.generated Fri Jan 04 10:43:05 COT 2019
     */
    int updateByPrimaryKey(Autonomia record);
}