package co.gov.dafp.sigep2.interfaces;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import co.gov.dafp.sigep2.bean.BienesPatrimonio;
import co.gov.dafp.sigep2.bean.BienesPatrimonioExample;
import co.gov.dafp.sigep2.bean.ext.BienesPatrimonioExt;

public interface BienesPatrimonioMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BIENES_PATRIMONIO
	 * @mbg.generated  Tue Mar 13 09:39:59 COT 2018
	 */
	long countByExample(BienesPatrimonioExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BIENES_PATRIMONIO
	 * @mbg.generated  Tue Mar 13 09:39:59 COT 2018
	 */
	int deleteByExample(BienesPatrimonioExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BIENES_PATRIMONIO
	 * @mbg.generated  Tue Mar 13 09:39:59 COT 2018
	 */
	int deleteByPrimaryKey(Long codBienPatrimonio);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BIENES_PATRIMONIO
	 * @mbg.generated  Tue Mar 13 09:39:59 COT 2018
	 */
	int insert(BienesPatrimonio record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BIENES_PATRIMONIO
	 * @mbg.generated  Tue Mar 13 09:39:59 COT 2018
	 */
	int insertSelective(BienesPatrimonio record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BIENES_PATRIMONIO
	 * @mbg.generated  Tue Mar 13 09:39:59 COT 2018
	 */
	List<BienesPatrimonioExt> selectByExample(BienesPatrimonioExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BIENES_PATRIMONIO
	 * @mbg.generated  Tue Mar 13 09:39:59 COT 2018
	 */
	BienesPatrimonioExt selectByPrimaryKey(Long codBienPatrimonio);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BIENES_PATRIMONIO
	 * @mbg.generated  Tue Mar 13 09:39:59 COT 2018
	 */
	int updateByExampleSelective(@Param("record") BienesPatrimonio record,
			@Param("example") BienesPatrimonioExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BIENES_PATRIMONIO
	 * @mbg.generated  Tue Mar 13 09:39:59 COT 2018
	 */
	int updateByExample(@Param("record") BienesPatrimonio record, @Param("example") BienesPatrimonioExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BIENES_PATRIMONIO
	 * @mbg.generated  Tue Mar 13 09:39:59 COT 2018
	 */
	int updateByPrimaryKeySelective(BienesPatrimonio record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table BIENES_PATRIMONIO
	 * @mbg.generated  Tue Mar 13 09:39:59 COT 2018
	 */
	int updateByPrimaryKey(BienesPatrimonio record);
}