package co.gov.dafp.sigep2.interfaces;

import co.gov.dafp.sigep2.bean.CmHvEducacionDesaHumano;
import co.gov.dafp.sigep2.bean.CmHvEducacionDesaHumanoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmHvEducacionDesaHumanoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CM_HV_EDUCACION_DESA_HUMANO
	 * @mbg.generated  Thu Aug 16 07:59:13 COT 2018
	 */
	long countByExample(CmHvEducacionDesaHumanoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CM_HV_EDUCACION_DESA_HUMANO
	 * @mbg.generated  Thu Aug 16 07:59:13 COT 2018
	 */
	int deleteByExample(CmHvEducacionDesaHumanoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CM_HV_EDUCACION_DESA_HUMANO
	 * @mbg.generated  Thu Aug 16 07:59:13 COT 2018
	 */
	int deleteByPrimaryKey(Long codCmHvEducacionDesaHumano);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CM_HV_EDUCACION_DESA_HUMANO
	 * @mbg.generated  Thu Aug 16 07:59:13 COT 2018
	 */
	int insert(CmHvEducacionDesaHumano record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CM_HV_EDUCACION_DESA_HUMANO
	 * @mbg.generated  Thu Aug 16 07:59:13 COT 2018
	 */
	int insertSelective(CmHvEducacionDesaHumano record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CM_HV_EDUCACION_DESA_HUMANO
	 * @mbg.generated  Thu Aug 16 07:59:13 COT 2018
	 */
	List<CmHvEducacionDesaHumano> selectByExample(CmHvEducacionDesaHumanoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CM_HV_EDUCACION_DESA_HUMANO
	 * @mbg.generated  Thu Aug 16 07:59:13 COT 2018
	 */
	CmHvEducacionDesaHumano selectByPrimaryKey(Long codCmHvEducacionDesaHumano);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CM_HV_EDUCACION_DESA_HUMANO
	 * @mbg.generated  Thu Aug 16 07:59:13 COT 2018
	 */
	int updateByExampleSelective(@Param("record") CmHvEducacionDesaHumano record,
			@Param("example") CmHvEducacionDesaHumanoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CM_HV_EDUCACION_DESA_HUMANO
	 * @mbg.generated  Thu Aug 16 07:59:13 COT 2018
	 */
	int updateByExample(@Param("record") CmHvEducacionDesaHumano record,
			@Param("example") CmHvEducacionDesaHumanoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CM_HV_EDUCACION_DESA_HUMANO
	 * @mbg.generated  Thu Aug 16 07:59:13 COT 2018
	 */
	int updateByPrimaryKeySelective(CmHvEducacionDesaHumano record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CM_HV_EDUCACION_DESA_HUMANO
	 * @mbg.generated  Thu Aug 16 07:59:13 COT 2018
	 */
	int updateByPrimaryKey(CmHvEducacionDesaHumano record);
}