package co.gov.dafp.sigep2.interfaces;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import co.gov.dafp.sigep2.bean.CuentasDeclaracion;
import co.gov.dafp.sigep2.bean.CuentasDeclaracionExample;
import co.gov.dafp.sigep2.bean.ext.CuentasDeclaracionExt;

public interface CuentasDeclaracionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUENTAS_DECLARACION
     *
     * @mbg.generated Wed Feb 28 10:04:35 COT 2018
     */
    long countByExample(CuentasDeclaracionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUENTAS_DECLARACION
     *
     * @mbg.generated Wed Feb 28 10:04:35 COT 2018
     */
    int deleteByExample(CuentasDeclaracionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUENTAS_DECLARACION
     *
     * @mbg.generated Wed Feb 28 10:04:35 COT 2018
     */
    int deleteByPrimaryKey(Long codCuentaDeclaracion);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUENTAS_DECLARACION
     *
     * @mbg.generated Wed Feb 28 10:04:35 COT 2018
     */
    int insert(CuentasDeclaracion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUENTAS_DECLARACION
     *
     * @mbg.generated Wed Feb 28 10:04:35 COT 2018
     */
    int insertSelective(CuentasDeclaracion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUENTAS_DECLARACION
     *
     * @mbg.generated Wed Feb 28 10:04:35 COT 2018
     */
    List<CuentasDeclaracionExt> selectByExample(CuentasDeclaracionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUENTAS_DECLARACION
     *
     * @mbg.generated Wed Feb 28 10:04:35 COT 2018
     */
    CuentasDeclaracion selectByPrimaryKey(Long codCuentaDeclaracion);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUENTAS_DECLARACION
     *
     * @mbg.generated Wed Feb 28 10:04:35 COT 2018
     */
    int updateByExampleSelective(@Param("record") CuentasDeclaracion record, @Param("example") CuentasDeclaracionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUENTAS_DECLARACION
     *
     * @mbg.generated Wed Feb 28 10:04:35 COT 2018
     */
    int updateByExample(@Param("record") CuentasDeclaracion record, @Param("example") CuentasDeclaracionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUENTAS_DECLARACION
     *
     * @mbg.generated Wed Feb 28 10:04:35 COT 2018
     */
    int updateByPrimaryKeySelective(CuentasDeclaracion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUENTAS_DECLARACION
     *
     * @mbg.generated Wed Feb 28 10:04:35 COT 2018
     */
    int updateByPrimaryKey(CuentasDeclaracion record);
}