package co.gov.dafp.sigep2.interfaces;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import co.gov.dafp.sigep2.bean.DatoContacto;
import co.gov.dafp.sigep2.bean.DatoContactoExample;
import co.gov.dafp.sigep2.bean.ext.DatoContactoExt;

public interface DatoContactoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATO_CONTACTO
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    long countByExample(DatoContactoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATO_CONTACTO
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    int deleteByExample(DatoContactoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATO_CONTACTO
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    int deleteByPrimaryKey(Long codDatosContacto);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATO_CONTACTO
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    int insert(DatoContacto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATO_CONTACTO
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    int insertSelective(DatoContacto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATO_CONTACTO
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    List<DatoContacto> selectByExample(DatoContactoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATO_CONTACTO
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    DatoContacto selectByPrimaryKey(Long codDatosContacto);
    
    
    DatoContactoExt selectByDatoContacto(Long codPersona);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATO_CONTACTO
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    int updateByExampleSelective(@Param("record") DatoContacto record, @Param("example") DatoContactoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATO_CONTACTO
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    int updateByExample(@Param("record") DatoContacto record, @Param("example") DatoContactoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATO_CONTACTO
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    int updateByPrimaryKeySelective(DatoContacto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATO_CONTACTO
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    int updateByPrimaryKey(DatoContacto record);
}