package co.gov.dafp.sigep2.interfaces;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import co.gov.dafp.sigep2.bean.DocumentosAdicionalesHv;
import co.gov.dafp.sigep2.bean.DocumentosAdicionalesHvExample;
import co.gov.dafp.sigep2.bean.ext.DocumentosAdicionalesHvExt;

public interface DocumentosAdicionalesHvMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOCUMENTOS_ADICIONALES_HV
     *
     * @mbg.generated Tue Mar 12 14:59:17 COT 2019
     */
    long countByExample(DocumentosAdicionalesHvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOCUMENTOS_ADICIONALES_HV
     *
     * @mbg.generated Tue Mar 12 14:59:17 COT 2019
     */
    int deleteByExample(DocumentosAdicionalesHvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOCUMENTOS_ADICIONALES_HV
     *
     * @mbg.generated Tue Mar 12 14:59:17 COT 2019
     */
    int deleteByPrimaryKey(Long codDocumentoAdicional);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOCUMENTOS_ADICIONALES_HV
     *
     * @mbg.generated Tue Mar 12 14:59:17 COT 2019
     */
    int insert(DocumentosAdicionalesHv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOCUMENTOS_ADICIONALES_HV
     *
     * @mbg.generated Tue Mar 12 14:59:17 COT 2019
     */
    int insertSelective(DocumentosAdicionalesHv record);
  
    int deleteDoc(DocumentosAdicionalesHv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOCUMENTOS_ADICIONALES_HV
     *
     * @mbg.generated Tue Mar 12 14:59:17 COT 2019
     */
    List<DocumentosAdicionalesHv> selectByExample(DocumentosAdicionalesHvExample example);
 
    
    List<DocumentosAdicionalesHvExt> selectByFiltro(DocumentosAdicionalesHv documentosAdicionalesHv);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOCUMENTOS_ADICIONALES_HV
     *
     * @mbg.generated Tue Mar 12 14:59:17 COT 2019
     */
    DocumentosAdicionalesHv selectByPrimaryKey(Long codDocumentoAdicional);
 
    DocumentosAdicionalesHvExt selectByPrimaryKeyExt(Long codDocumentoAdicional);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOCUMENTOS_ADICIONALES_HV
     *
     * @mbg.generated Tue Mar 12 14:59:17 COT 2019
     */
    int updateByExampleSelective(@Param("record") DocumentosAdicionalesHv record, @Param("example") DocumentosAdicionalesHvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOCUMENTOS_ADICIONALES_HV
     *
     * @mbg.generated Tue Mar 12 14:59:17 COT 2019
     */
    int updateByExample(@Param("record") DocumentosAdicionalesHv record, @Param("example") DocumentosAdicionalesHvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOCUMENTOS_ADICIONALES_HV
     *
     * @mbg.generated Tue Mar 12 14:59:17 COT 2019
     */
    int updateByPrimaryKeySelective(DocumentosAdicionalesHv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DOCUMENTOS_ADICIONALES_HV
     *
     * @mbg.generated Tue Mar 12 14:59:17 COT 2019
     */
    int updateByPrimaryKey(DocumentosAdicionalesHv record);
}