package co.gov.dafp.sigep2.interfaces;

import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import co.gov.dafp.sigep2.bean.EntidadSistemaRegimen;
import co.gov.dafp.sigep2.bean.EntidadSistemaRegimenExample;
import co.gov.dafp.sigep2.bean.ext.EntidadSistemaRegimenExt;
import co.gov.dafp.sigep2.portal.NaturalezaEmpleo;
import co.gov.dafp.sigep2.portal.RegimenSalarial;
import co.gov.dafp.sigep2.portal.SistemaCarrera;

public interface EntidadSistemaRegimenMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table ENTIDAD_SISTEMA_REGIMEN
     *
     * @mbg.generated Sat Jun 30 23:45:39 COT 2018
     */
    long countByExample(EntidadSistemaRegimenExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table ENTIDAD_SISTEMA_REGIMEN
     *
     * @mbg.generated Sat Jun 30 23:45:39 COT 2018
     */
    int deleteByExample(EntidadSistemaRegimenExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table ENTIDAD_SISTEMA_REGIMEN
     *
     * @mbg.generated Sat Jun 30 23:45:39 COT 2018
     */
    int deleteByPrimaryKey(BigDecimal codEntidadSistemaRegimen);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table ENTIDAD_SISTEMA_REGIMEN
     *
     * @mbg.generated Sat Jun 30 23:45:39 COT 2018
     */
    int insert(EntidadSistemaRegimen record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table ENTIDAD_SISTEMA_REGIMEN
     *
     * @mbg.generated Sat Jun 30 23:45:39 COT 2018
     */
    int insertSelective(EntidadSistemaRegimen record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table ENTIDAD_SISTEMA_REGIMEN
     *
     * @mbg.generated Sat Jun 30 23:45:39 COT 2018
     */
    List<EntidadSistemaRegimen> selectByExample(EntidadSistemaRegimenExample example);

    /**
     * Busca los registros <code>EntidadSistemaRegimen</code> de una entidad
     * @param codEntidad
     * @return 
     */
    List<EntidadSistemaRegimenExt> selectByCodEntidad(BigDecimal codEntidad);
 
    
    List<EntidadSistemaRegimenExt> selectByFiltro(EntidadSistemaRegimen entidadSistemaRegimen);

    List<RegimenSalarial> selectRegimen(BigDecimal codEntidad);
    List<NaturalezaEmpleo> selectNaturalezaEmpleo(BigDecimal codEntidad);
    List<SistemaCarrera> selectSistemaCarrera(BigDecimal codEntidad);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table ENTIDAD_SISTEMA_REGIMEN
     *
     * @mbg.generated Sat Jun 30 23:45:39 COT 2018
     */
    EntidadSistemaRegimen selectByPrimaryKey(BigDecimal codEntidadSistemaRegimen);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table ENTIDAD_SISTEMA_REGIMEN
     *
     * @mbg.generated Sat Jun 30 23:45:39 COT 2018
     */
    int updateByExampleSelective(@Param("record") EntidadSistemaRegimen record, @Param("example") EntidadSistemaRegimenExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table ENTIDAD_SISTEMA_REGIMEN
     *
     * @mbg.generated Sat Jun 30 23:45:39 COT 2018
     */
    int updateByExample(@Param("record") EntidadSistemaRegimen record, @Param("example") EntidadSistemaRegimenExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table ENTIDAD_SISTEMA_REGIMEN
     *
     * @mbg.generated Sat Jun 30 23:45:39 COT 2018
     */
    int updateByPrimaryKeySelective(EntidadSistemaRegimen record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table ENTIDAD_SISTEMA_REGIMEN
     *
     * @mbg.generated Sat Jun 30 23:45:39 COT 2018
     */
    int updateByPrimaryKey(EntidadSistemaRegimen record);
}
