package co.gov.dafp.sigep2.interfaces;

import co.gov.dafp.sigep2.bean.EntidadFusion;
import co.gov.dafp.sigep2.bean.EntidadFusionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EntidadFusionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ENTIDAD_FUSION
     *
     * @mbg.generated Wed Oct 10 16:38:24 COT 2018
     */
    long countByExample(EntidadFusionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ENTIDAD_FUSION
     *
     * @mbg.generated Wed Oct 10 16:38:24 COT 2018
     */
    int deleteByExample(EntidadFusionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ENTIDAD_FUSION
     *
     * @mbg.generated Wed Oct 10 16:38:24 COT 2018
     */
    int insert(EntidadFusion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ENTIDAD_FUSION
     *
     * @mbg.generated Wed Oct 10 16:38:24 COT 2018
     */
    int insertSelective(EntidadFusion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ENTIDAD_FUSION
     *
     * @mbg.generated Wed Oct 10 16:38:24 COT 2018
     */
    List<EntidadFusion> selectByExample(EntidadFusionExample example);
  
    
    List<EntidadFusion> selectByFiltro(EntidadFusion entidadFusion);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ENTIDAD_FUSION
     *
     * @mbg.generated Wed Oct 10 16:38:24 COT 2018
     */
    int updateByExampleSelective(@Param("record") EntidadFusion record, @Param("example") EntidadFusionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ENTIDAD_FUSION
     *
     * @mbg.generated Wed Oct 10 16:38:24 COT 2018
     */
    int updateByExample(@Param("record") EntidadFusion record, @Param("example") EntidadFusionExample example);
    
    /**
     * 
     * @author: Jose Viscaya 
     * @fecha 10/10/2018 - 5:52:19 p. m.
     * @param record
     * @return
     */
    int updateByPrimaryKey(EntidadFusion record);
}