package co.gov.dafp.sigep2.interfaces;

import co.gov.dafp.sigep2.bean.EntidadEscision;
import co.gov.dafp.sigep2.bean.EntidadEscisionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import java.math.BigDecimal;

public interface EntidadEscisionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ENTIDAD_ESCISION
	 * @mbg.generated  Thu Jul 26 17:26:19 COT 2018
	 */
	long countByExample(EntidadEscisionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ENTIDAD_ESCISION
	 * @mbg.generated  Thu Jul 26 17:26:19 COT 2018
	 */
	int deleteByExample(EntidadEscisionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ENTIDAD_ESCISION
	 * @mbg.generated  Thu Jul 26 17:26:19 COT 2018
	 */
	int deleteByPrimaryKey(BigDecimal codEscision);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ENTIDAD_ESCISION
	 * @mbg.generated  Thu Jul 26 17:26:19 COT 2018
	 */
	int insert(EntidadEscision record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ENTIDAD_ESCISION
	 * @mbg.generated  Thu Jul 26 17:26:19 COT 2018
	 */
	int insertSelective(EntidadEscision record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ENTIDAD_ESCISION
	 * @mbg.generated  Thu Jul 26 17:26:19 COT 2018
	 */
	List<EntidadEscision> selectByExample(EntidadEscisionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ENTIDAD_ESCISION
	 * @mbg.generated  Thu Jul 26 17:26:19 COT 2018
	 */
	EntidadEscision selectByPrimaryKey(BigDecimal codEscision);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ENTIDAD_ESCISION
	 * @mbg.generated  Thu Jul 26 17:26:19 COT 2018
	 */
	int updateByExampleSelective(@Param("record") EntidadEscision record,
			@Param("example") EntidadEscisionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ENTIDAD_ESCISION
	 * @mbg.generated  Thu Jul 26 17:26:19 COT 2018
	 */
	int updateByExample(@Param("record") EntidadEscision record, @Param("example") EntidadEscisionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ENTIDAD_ESCISION
	 * @mbg.generated  Thu Jul 26 17:26:19 COT 2018
	 */
	int updateByPrimaryKeySelective(EntidadEscision record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ENTIDAD_ESCISION
	 * @mbg.generated  Thu Jul 26 17:26:19 COT 2018
	 */
	int updateByPrimaryKey(EntidadEscision record);

	List<EntidadEscision> selectFiltro(EntidadEscision entidadEscision);
}