package co.gov.dafp.sigep2.interfaces;

import co.gov.dafp.sigep2.bean.EstructuraDependenciaEntidad;
import co.gov.dafp.sigep2.bean.EstructuraDependenciaEntidadExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EstructuraDependenciaEntidadMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ESTRUCTURA_DEPENDENCIA_ENTIDAD
     * @mbg.generated  Fri Sep 14 11:19:45 COT 2018
     */
    long countByExample(EstructuraDependenciaEntidadExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ESTRUCTURA_DEPENDENCIA_ENTIDAD
     * @mbg.generated  Fri Sep 14 11:19:45 COT 2018
     */
    int deleteByExample(EstructuraDependenciaEntidadExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ESTRUCTURA_DEPENDENCIA_ENTIDAD
     * @mbg.generated  Fri Sep 14 11:19:45 COT 2018
     */
    int deleteByPrimaryKey(Long codEstructuraDependenciaEntidad);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ESTRUCTURA_DEPENDENCIA_ENTIDAD
     * @mbg.generated  Fri Sep 14 11:19:45 COT 2018
     */
    int insert(EstructuraDependenciaEntidad record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ESTRUCTURA_DEPENDENCIA_ENTIDAD
     * @mbg.generated  Fri Sep 14 11:19:45 COT 2018
     */
    int insertSelective(EstructuraDependenciaEntidad record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ESTRUCTURA_DEPENDENCIA_ENTIDAD
     * @mbg.generated  Fri Sep 14 11:19:45 COT 2018
     */
    List<EstructuraDependenciaEntidad> selectByExample(EstructuraDependenciaEntidadExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ESTRUCTURA_DEPENDENCIA_ENTIDAD
     * @mbg.generated  Fri Sep 14 11:19:45 COT 2018
     */
    EstructuraDependenciaEntidad selectByPrimaryKey(Long codEstructuraDependenciaEntidad);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ESTRUCTURA_DEPENDENCIA_ENTIDAD
     * @mbg.generated  Fri Sep 14 11:19:45 COT 2018
     */
    int updateByExampleSelective(@Param("record") EstructuraDependenciaEntidad record, @Param("example") EstructuraDependenciaEntidadExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ESTRUCTURA_DEPENDENCIA_ENTIDAD
     * @mbg.generated  Fri Sep 14 11:19:45 COT 2018
     */
    int updateByExample(@Param("record") EstructuraDependenciaEntidad record, @Param("example") EstructuraDependenciaEntidadExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ESTRUCTURA_DEPENDENCIA_ENTIDAD
     * @mbg.generated  Fri Sep 14 11:19:45 COT 2018
     */
    int updateByPrimaryKeySelective(EstructuraDependenciaEntidad record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ESTRUCTURA_DEPENDENCIA_ENTIDAD
     * @mbg.generated  Fri Sep 14 11:19:45 COT 2018
     */
    int updateByPrimaryKey(EstructuraDependenciaEntidad record);
}