package co.gov.dafp.sigep2.interfaces;

import co.gov.dafp.sigep2.bean.HistoricoEntidadesDeclaracion;
import co.gov.dafp.sigep2.bean.HistoricoEntidadesDeclaracionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HistoricoEntidadesDeclaracionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HISTORICO_ENTIDADES_DECLARACION
     *
     * @mbggenerated Tue Sep 08 07:17:06 COT 2020
     */
    int countByExample(HistoricoEntidadesDeclaracionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HISTORICO_ENTIDADES_DECLARACION
     *
     * @mbggenerated Tue Sep 08 07:17:06 COT 2020
     */
    int deleteByExample(HistoricoEntidadesDeclaracionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HISTORICO_ENTIDADES_DECLARACION
     *
     * @mbggenerated Tue Sep 08 07:17:06 COT 2020
     */
    int deleteByPrimaryKey(Long codDeclaracionEntidad);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HISTORICO_ENTIDADES_DECLARACION
     *
     * @mbggenerated Tue Sep 08 07:17:06 COT 2020
     */
    int insert(HistoricoEntidadesDeclaracion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HISTORICO_ENTIDADES_DECLARACION
     *
     * @mbggenerated Tue Sep 08 07:17:06 COT 2020
     */
    int insertSelective(HistoricoEntidadesDeclaracion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HISTORICO_ENTIDADES_DECLARACION
     *
     * @mbggenerated Tue Sep 08 07:17:06 COT 2020
     */
    List<HistoricoEntidadesDeclaracion> selectByExample(HistoricoEntidadesDeclaracionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HISTORICO_ENTIDADES_DECLARACION
     *
     * @mbggenerated Tue Sep 08 07:17:06 COT 2020
     */
    HistoricoEntidadesDeclaracion selectByPrimaryKey(Long codDeclaracionEntidad);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HISTORICO_ENTIDADES_DECLARACION
     *
     * @mbggenerated Tue Sep 08 07:17:06 COT 2020
     */
    int updateByExampleSelective(@Param("record") HistoricoEntidadesDeclaracion record, @Param("example") HistoricoEntidadesDeclaracionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HISTORICO_ENTIDADES_DECLARACION
     *
     * @mbggenerated Tue Sep 08 07:17:06 COT 2020
     */
    int updateByExample(@Param("record") HistoricoEntidadesDeclaracion record, @Param("example") HistoricoEntidadesDeclaracionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HISTORICO_ENTIDADES_DECLARACION
     *
     * @mbggenerated Tue Sep 08 07:17:06 COT 2020
     */
    int updateByPrimaryKeySelective(HistoricoEntidadesDeclaracion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HISTORICO_ENTIDADES_DECLARACION
     *
     * @mbggenerated Tue Sep 08 07:17:06 COT 2020
     */
    int updateByPrimaryKey(HistoricoEntidadesDeclaracion record);
    List<HistoricoEntidadesDeclaracion> selectByfiltro(HistoricoEntidadesDeclaracion example);
}