package co.gov.dafp.sigep2.interfaces;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import co.gov.dafp.sigep2.bean.Idioma;
import co.gov.dafp.sigep2.bean.IdiomaExample;
import co.gov.dafp.sigep2.bean.ext.IdiomaExt;

public interface IdiomaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IDIOMA
     *
     * @mbg.generated Fri Feb 02 16:56:24 COT 2018
     */
    long countByExample(IdiomaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IDIOMA
     *
     * @mbg.generated Fri Feb 02 16:56:24 COT 2018
     */
    int deleteByExample(IdiomaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IDIOMA
     *
     * @mbg.generated Fri Feb 02 16:56:24 COT 2018
     */
    int deleteByPrimaryKey(Integer codIdioma);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IDIOMA
     *
     * @mbg.generated Fri Feb 02 16:56:24 COT 2018
     */
    int insert(Idioma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IDIOMA
     *
     * @mbg.generated Fri Feb 02 16:56:24 COT 2018
     */
    int insertSelective(Idioma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IDIOMA
     *
     * @mbg.generated Fri Feb 02 16:56:24 COT 2018
     */
    List<Idioma> selectByExample(IdiomaExample example);
 
    List<Idioma> selectByFiltro(Idioma Idioma);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IDIOMA
     *
     * @mbg.generated Fri Feb 02 16:56:24 COT 2018
     */
    Idioma selectByPrimaryKey(Integer codIdioma);
    
    
    IdiomaExt selectIdiomaComplPersona(long codPersona);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IDIOMA
     *
     * @mbg.generated Fri Feb 02 16:56:24 COT 2018
     */
    int updateByExampleSelective(@Param("record") Idioma record, @Param("example") IdiomaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IDIOMA
     *
     * @mbg.generated Fri Feb 02 16:56:24 COT 2018
     */
    int updateByExample(@Param("record") Idioma record, @Param("example") IdiomaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IDIOMA
     *
     * @mbg.generated Fri Feb 02 16:56:24 COT 2018
     */
    int updateByPrimaryKeySelective(Idioma record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IDIOMA
     *
     * @mbg.generated Fri Feb 02 16:56:24 COT 2018
     */
    int updateByPrimaryKey(Idioma record);
    List<Idioma> selectIdiomaDuplicado(Idioma Idioma);
    
}