package co.gov.dafp.sigep2.interfaces;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import co.gov.dafp.sigep2.bean.Municipio;
import co.gov.dafp.sigep2.bean.MunicipioExample;
import co.gov.dafp.sigep2.bean.ext.MunicipioExt;

public interface MunicipioMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MUNICIPIO
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    long countByExample(MunicipioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MUNICIPIO
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    int deleteByExample(MunicipioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MUNICIPIO
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    int deleteByPrimaryKey(Integer codMunicipio);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MUNICIPIO
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    int insert(Municipio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MUNICIPIO
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    int insertSelective(Municipio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MUNICIPIO
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    List<Municipio> selectByExample(MunicipioExample example);
 
    List<Municipio> selectByFiltro(Municipio municipio);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MUNICIPIO
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    Municipio selectByPrimaryKey(Integer codMunicipio);
   
    
    Municipio selectByDane(Integer codMunicipioDane);
    
    

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MUNICIPIO
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    int updateByExampleSelective(@Param("record") Municipio record, @Param("example") MunicipioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MUNICIPIO
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    int updateByExample(@Param("record") Municipio record, @Param("example") MunicipioExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MUNICIPIO
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    int updateByPrimaryKeySelective(Municipio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MUNICIPIO
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    int updateByPrimaryKey(Municipio record);
    List<Municipio> selectMunicipioDuplicado(Municipio municipio);
    
    List<MunicipioExt> selectMunicipioPorDepartamento(Municipio municipio);


}