package co.gov.dafp.sigep2.interfaces;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import co.gov.dafp.sigep2.bean.ParticipacionProyecto;
import co.gov.dafp.sigep2.bean.ParticipacionProyectoExample;
import co.gov.dafp.sigep2.bean.ext.ParticipacionProyectoExt;

public interface ParticipacionProyectoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTICIPACION_PROYECTO
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    long countByExample(ParticipacionProyectoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTICIPACION_PROYECTO
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    int deleteByExample(ParticipacionProyectoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTICIPACION_PROYECTO
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    int deleteByPrimaryKey(Long codParticipacionProyecto);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTICIPACION_PROYECTO
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    int insert(ParticipacionProyecto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTICIPACION_PROYECTO
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    int insertSelective(ParticipacionProyecto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTICIPACION_PROYECTO
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    List<ParticipacionProyecto> selectByExample(ParticipacionProyectoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTICIPACION_PROYECTO
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    ParticipacionProyecto selectByPrimaryKey(Long codParticipacionProyecto);
   
    
    List<ParticipacionProyectoExt> selectParticipacionProyectoByPersona(Long codPersona);
 
    List<ParticipacionProyectoExt> selectByFiltro(ParticipacionProyecto participacionProyecto);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTICIPACION_PROYECTO
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    int updateByExampleSelective(@Param("record") ParticipacionProyecto record, @Param("example") ParticipacionProyectoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTICIPACION_PROYECTO
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    int updateByExample(@Param("record") ParticipacionProyecto record, @Param("example") ParticipacionProyectoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTICIPACION_PROYECTO
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    int updateByPrimaryKeySelective(ParticipacionProyecto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTICIPACION_PROYECTO
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    int updateByPrimaryKey(ParticipacionProyecto record);
}