package co.gov.dafp.sigep2.interfaces;

import co.gov.dafp.sigep2.bean.PepRespuestaCuestionarioDetalle;
import co.gov.dafp.sigep2.bean.PepRespuestaCuestionarioDetalleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PepRespuestaCuestionarioDetalleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PEP_RESPUESTA_CUESTIONARIO_DETALLE
	 * @mbg.generated  Tue Dec 04 14:58:33 COT 2018
	 */
	long countByExample(PepRespuestaCuestionarioDetalleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PEP_RESPUESTA_CUESTIONARIO_DETALLE
	 * @mbg.generated  Tue Dec 04 14:58:33 COT 2018
	 */
	int deleteByExample(PepRespuestaCuestionarioDetalleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PEP_RESPUESTA_CUESTIONARIO_DETALLE
	 * @mbg.generated  Tue Dec 04 14:58:33 COT 2018
	 */
	int deleteByPrimaryKey(Long idRespuestaCuestionarioDetalle);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PEP_RESPUESTA_CUESTIONARIO_DETALLE
	 * @mbg.generated  Tue Dec 04 14:58:33 COT 2018
	 */
	int insert(PepRespuestaCuestionarioDetalle record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PEP_RESPUESTA_CUESTIONARIO_DETALLE
	 * @mbg.generated  Tue Dec 04 14:58:33 COT 2018
	 */
	int insertSelective(PepRespuestaCuestionarioDetalle record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PEP_RESPUESTA_CUESTIONARIO_DETALLE
	 * @mbg.generated  Tue Dec 04 14:58:33 COT 2018
	 */
	List<PepRespuestaCuestionarioDetalle> selectByExample(PepRespuestaCuestionarioDetalleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PEP_RESPUESTA_CUESTIONARIO_DETALLE
	 * @mbg.generated  Tue Dec 04 14:58:33 COT 2018
	 */
	PepRespuestaCuestionarioDetalle selectByPrimaryKey(Long idRespuestaCuestionarioDetalle);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PEP_RESPUESTA_CUESTIONARIO_DETALLE
	 * @mbg.generated  Tue Dec 04 14:58:33 COT 2018
	 */
	int updateByExampleSelective(@Param("record") PepRespuestaCuestionarioDetalle record,
			@Param("example") PepRespuestaCuestionarioDetalleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PEP_RESPUESTA_CUESTIONARIO_DETALLE
	 * @mbg.generated  Tue Dec 04 14:58:33 COT 2018
	 */
	int updateByExample(@Param("record") PepRespuestaCuestionarioDetalle record,
			@Param("example") PepRespuestaCuestionarioDetalleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PEP_RESPUESTA_CUESTIONARIO_DETALLE
	 * @mbg.generated  Tue Dec 04 14:58:33 COT 2018
	 */
	int updateByPrimaryKeySelective(PepRespuestaCuestionarioDetalle record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PEP_RESPUESTA_CUESTIONARIO_DETALLE
	 * @mbg.generated  Tue Dec 04 14:58:33 COT 2018
	 */
	int updateByPrimaryKey(PepRespuestaCuestionarioDetalle record);
}