package co.gov.dafp.sigep2.interfaces;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import co.gov.dafp.sigep2.bean.Publicacion;
import co.gov.dafp.sigep2.bean.PublicacionExample;
import co.gov.dafp.sigep2.bean.ext.PublicacionExt;

public interface PublicacionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLICACION
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    long countByExample(PublicacionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLICACION
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    int deleteByExample(PublicacionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLICACION
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    int deleteByPrimaryKey(Long codPublicacion);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLICACION
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    int insert(Publicacion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLICACION
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    int insertSelective(Publicacion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLICACION
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    List<Publicacion> selectByExample(PublicacionExample example);
  
    
    List<PublicacionExt> selectPublicacionByPersona(Long codPesona);
   
    
    List<PublicacionExt> selectByFiltro(Publicacion publicacion);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLICACION
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    Publicacion selectByPrimaryKey(Long codPublicacion);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLICACION
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    int updateByExampleSelective(@Param("record") Publicacion record, @Param("example") PublicacionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLICACION
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    int updateByExample(@Param("record") Publicacion record, @Param("example") PublicacionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLICACION
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    int updateByPrimaryKeySelective(Publicacion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLICACION
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    int updateByPrimaryKey(Publicacion record);
}