package co.gov.dafp.sigep2.interfaces;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import co.gov.dafp.sigep2.bean.Reconocimiento;
import co.gov.dafp.sigep2.bean.ReconocimientoExample;
import co.gov.dafp.sigep2.bean.ext.ReconocimientoExt;

public interface ReconocimientoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RECONOCIMIENTO
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    long countByExample(ReconocimientoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RECONOCIMIENTO
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    int deleteByExample(ReconocimientoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RECONOCIMIENTO
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    int deleteByPrimaryKey(Long codReconocimiento);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RECONOCIMIENTO
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    int insert(Reconocimiento record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RECONOCIMIENTO
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    int insertSelective(Reconocimiento record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RECONOCIMIENTO
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    List<Reconocimiento> selectByExample(ReconocimientoExample example);
    
    List<ReconocimientoExt> selectReconocimientoByPersona(Long codPersona);
  
    List<ReconocimientoExt> selectByFiltro(Reconocimiento peconocimiento);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RECONOCIMIENTO
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    Reconocimiento selectByPrimaryKey(Long codReconocimiento);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RECONOCIMIENTO
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    int updateByExampleSelective(@Param("record") Reconocimiento record, @Param("example") ReconocimientoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RECONOCIMIENTO
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    int updateByExample(@Param("record") Reconocimiento record, @Param("example") ReconocimientoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RECONOCIMIENTO
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    int updateByPrimaryKeySelective(Reconocimiento record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RECONOCIMIENTO
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    int updateByPrimaryKey(Reconocimiento record);
}