package co.gov.dafp.sigep2.interfaces;

import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import co.gov.dafp.sigep2.bean.Rol;
import co.gov.dafp.sigep2.bean.RolExample;
import co.gov.dafp.sigep2.bean.ext.PersonaExt;
import co.gov.dafp.sigep2.bean.ext.RolExt;

public interface RolMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROL
     *
     * @mbg.generated Thu Jan 25 12:04:19 COT 2018
     */
    long countByExample(RolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROL
     *
     * @mbg.generated Thu Jan 25 12:04:19 COT 2018
     */
    int deleteByExample(RolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROL
     *
     * @mbg.generated Thu Jan 25 12:04:19 COT 2018
     */
    int deleteByPrimaryKey(BigDecimal codRol);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROL
     *
     * @mbg.generated Thu Jan 25 12:04:19 COT 2018
     */
    int insert(Rol record);
    int desactivarRoles();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROL
     *
     * @mbg.generated Thu Jan 25 12:04:19 COT 2018
     */
    int insertSelective(Rol record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROL
     *
     * @mbg.generated Thu Jan 25 12:04:19 COT 2018
     */
    List<Rol> selectByExample(RolExample example);
    
    
    List<Rol> selectLike(RolExt rol);
    
    List<Rol> selectRolesT(RolExt rol);

    
    List<RolExt> selectByPersona(PersonaExt persona);
    
    List<RolExt> selectRolesByPerosnaEntidad(RolExt rolExt);
 
    List<Rol> rolesPersona(PersonaExt persona);
    
    List<Rol> selectHijosRol(Rol rol);
    
    List<Rol> selectRolesBase();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROL
     *
     * @mbg.generated Thu Jan 25 12:04:19 COT 2018
     */
    Rol selectByPrimaryKey(BigDecimal codRol);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROL
     *
     * @mbg.generated Thu Jan 25 12:04:19 COT 2018
     */
    int updateByExampleSelective(@Param("record") Rol record, @Param("example") RolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROL
     *
     * @mbg.generated Thu Jan 25 12:04:19 COT 2018
     */
    int updateByExample(@Param("record") Rol record, @Param("example") RolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROL
     *
     * @mbg.generated Thu Jan 25 12:04:19 COT 2018
     */
    int updateByPrimaryKeySelective(Rol record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROL
     *
     * @mbg.generated Thu Jan 25 12:04:19 COT 2018
     */
    int updateByPrimaryKey(Rol record);
    
    List<Rol> selectHijosRolJefeTH(Rol rol);
    List<Rol> selectHijosRolJefeTHYContratos(Rol rol);
    
    List<Rol> selectRolPorNombre(Rol rol);
    
}