package co.gov.dafp.sigep2.interfaces;

import co.gov.dafp.sigep2.bean.TablasAud;
import co.gov.dafp.sigep2.bean.TablasAudExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TablasAudMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TABLAS_AUD
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    long countByExample(TablasAudExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TABLAS_AUD
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    int deleteByExample(TablasAudExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TABLAS_AUD
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    int insert(TablasAud record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TABLAS_AUD
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    int insertSelective(TablasAud record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TABLAS_AUD
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    List<TablasAud> selectByExample(TablasAudExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TABLAS_AUD
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    int updateByExampleSelective(@Param("record") TablasAud record, @Param("example") TablasAudExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TABLAS_AUD
     *
     * @mbg.generated Mon Jan 29 14:57:36 COT 2018
     */
    int updateByExample(@Param("record") TablasAud record, @Param("example") TablasAudExample example);
}