package co.gov.dafp.sigep2.interfaces;

import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import co.gov.dafp.sigep2.bean.Vinculacion;
import co.gov.dafp.sigep2.bean.VinculacionExample;
import co.gov.dafp.sigep2.bean.ext.EntidadExt;
import co.gov.dafp.sigep2.bean.ext.PersonaExt;
import co.gov.dafp.sigep2.bean.ext.SituacionAdminVinculacionExt;
import co.gov.dafp.sigep2.bean.ext.VinculacionExt;
import co.gov.dafp.sigep2.portal.BusquedaPortal;

public interface VinculacionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table VINCULACION
	 * @mbg.generated  Tue Jul 03 10:44:48 COT 2018
	 */
	long countByExample(VinculacionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table VINCULACION
	 * @mbg.generated  Tue Jul 03 10:44:48 COT 2018
	 */
	int deleteByExample(VinculacionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table VINCULACION
	 * @mbg.generated  Tue Jul 03 10:44:48 COT 2018
	 */
	int deleteByPrimaryKey(BigDecimal codVinculacion);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table VINCULACION
	 * @mbg.generated  Tue Jul 03 10:44:48 COT 2018
	 */
	int insert(Vinculacion record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table VINCULACION
	 * @mbg.generated  Tue Jul 03 10:44:48 COT 2018
	 */
	int insertSelective(Vinculacion record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table VINCULACION
	 * @mbg.generated  Tue Jul 03 10:44:48 COT 2018
	 */
	List<Vinculacion> selectByExample(VinculacionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table VINCULACION
	 * @mbg.generated  Tue Jul 03 10:44:48 COT 2018
	 */
	Vinculacion selectByPrimaryKey(BigDecimal codVinculacion);
	
	Vinculacion selectPersona(PersonaExt persona);
	
	Vinculacion selectVinculacionDes(VinculacionExt vinculacionExt);
	
	Vinculacion vinculacionPersona(SituacionAdminVinculacionExt situacionAdministrativaExt);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table VINCULACION
	 * @mbg.generated  Tue Jul 03 10:44:48 COT 2018
	 */
	int updateByExampleSelective(@Param("record") Vinculacion record, @Param("example") VinculacionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table VINCULACION
	 * @mbg.generated  Tue Jul 03 10:44:48 COT 2018
	 */
	int updateByExample(@Param("record") Vinculacion record, @Param("example") VinculacionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table VINCULACION
	 * @mbg.generated  Tue Jul 03 10:44:48 COT 2018
	 */
	int updateByPrimaryKeySelective(Vinculacion record);
	
	Long selectPersonaEntidad(BusquedaPortal busquedaPortal);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table VINCULACION
	 * @mbg.generated  Tue Jul 03 10:44:48 COT 2018
	 */
	int updateByPrimaryKey(Vinculacion record);
	
	List<VinculacionExt> selectVinculacionFilter(VinculacionExt vinculacionExt);
	List<VinculacionExt> selectVinculacionDiferenteEntidad(VinculacionExt vinculacionExt);
	List<VinculacionExt> vinculacionPersonafiltro(VinculacionExt vinculacionExt);
	List<VinculacionExt> selectMostrarVinculaciones(VinculacionExt vinculacionExt);
	List<VinculacionExt> selectVinculacionSituacionAdmin(VinculacionExt vinculacionExt);
	List<VinculacionExt> selectVinculacionSituacionAdminPeriodoPrueba(VinculacionExt vinculacionExt);
	List<VinculacionExt> selectMostrarVinculacionActual(VinculacionExt vinculacionExt);
	List<VinculacionExt> selectMostrarVinculacionPeriodoDePrueba(VinculacionExt vinculacionExt);
	List<VinculacionExt> selectUltimaVinDesv(VinculacionExt vinculacionExt);
	List<VinculacionExt> selectVacantes(VinculacionExt vinculacionExt);
	List<VinculacionExt> selectVacantesTempGlobal(VinculacionExt vinculacionExt);
	List<VinculacionExt> selectVacantesTemyPermGlobal(VinculacionExt vinculacionExt);
	List<VinculacionExt> selectVacantesGlobal(VinculacionExt vinculacionExt);
	List<VinculacionExt> selectCargosFuncionario(VinculacionExt vinculacionExt);
	List<Vinculacion> selectVinculacionesActivas(BigDecimal codPersona);
	List<VinculacionExt> selectVinculacionPorPlantaPersonal(VinculacionExt vinculacionExt);
	int updateDesvinculacionAutomaticaPlanta(VinculacionExt vinculacionExt);
	List<VinculacionExt> selectVinculacionMismaEntidad(VinculacionExt vinculacionExt);
	List<VinculacionExt> selectVinculacionSenadoresCongresistas(EntidadExt entidad);
	List<VinculacionExt> selectVacantesTemyPermGlobalyEstructural(VinculacionExt vinculacionExt);
	List<VinculacionExt> selectVinDesvAlerta(VinculacionExt vinculacionExt);
	List<VinculacionExt> selectSituacionesAdmAlerta(VinculacionExt vinculacionExt);
	List<VinculacionExt> selectVinculacionSinSAXProcesar(VinculacionExt vinculacionExt);
	VinculacionExt selectUltimaVinculacionByCargo(VinculacionExt vinculacionExt);
}