package co.gov.dafp.sigep2.utils;

/**
 * 
* @author Jose Viscaya.
* @version 1.0
* @Class Clase  TipoParametro.java
* @Proyect SIGEPII
* @Company ADA S.A
* @Module exposicion de servicios Rest
 */
public enum TipoParametro {
	NIVEL_EDUCATIVO(580), AREA_CONOCIMIENTO(302), JORNADA_LABORAL(256), MOTIVO_RETIRO(260), TIPO_DISCAPACIDAD(236),
    TIPO_VIA(336), TIPO_ORIENTACION(348), TIPO_LETRA(356), TIPOS_DE_IDENTIFICACION(23), FACTOR_RH(43), GENERO(44),
    ESTADO_CIVIL(45), TIPOS_ASOCIACION(108), TIPOS_ENTIDAD(141), POBLACION_ETNICA(226), REPORTE(121), NATURALEZA_EMPLEO(126),
    REGIMEN_SALARIAL(131), CLASE_LIBRETA_MIL(163), TIPO_ARTICULO(441), NIVEL_IDIOMA(456), ORIENTACION_SEXUAL(376),
    TIPO_ZONA(221), CABEZA_DE_FAMILIA(383), TIPO_INSTITUCION(417), NIVEL_JERARQUICO(497), COD_NIVEL_CUMPLIMIENTO(538),
    COD_TIPO_EVALUACION(539), VICTIMA_DESPLAZAMIENTO(387), DEMAS_TIPOS_PRODUCCION_BIBLIOGRAFICA(450),
    LIBRO_RESULTADO_INVESTIGACION(445), MEDIO_DE_CAPACITACION(638), MODALIDAD_DE_ESTUDIO(645), FORMA_DE_PARTICIPACION(755),
    TIPO_BIEN(781), TIPO_INGRESO(748), TIPO_DECLARACION(740), TIPO_MONEDA(838), TIPO_FUENTE_FINANCIACION(843),
    MOTIVOS_SUSPENSION_CONTRATO(858), PARENTESCO(706), TIPO_CUENTA(918), TIPO_VINCULACION_JUNTA(808),
    CALIDAD_MIEMBRO_BR(941), CALIDAD_SOCIO_BR(944), TIPO_MODALIDAD(1013), TIPOS_MODIFICACION_CONTRATOS(878), DATA_EXAMPLE(1020),
    TIPO_VINCULACION_CONTRATISTA(109), TIPO_VINCULACION_SERV_PUBLICO(110), 
    AUDITORIA_INSERT(785), AUDITORIA_CREATE(201),AUDITORIA_UPDATE(63), AUDITORIA_DELETE (62),
    GI_ALERTAS_ACTIVAS(960), GI_ALERTAS_VINCULACIONES_ACTIVA(961), GI_ALERTAS_DESVINCULACIONES_ACTIVA(962),GI_ALERTAS_SITUACIONESADMINISTRATIVAS_ACTIVA(963),
    GI_ALERTAS_CALENDARIONOTIFICACION(964),GI_ALERTAS_CUERPO_MULTIENTIDAD(965),GI_ALERTAS_CUERPO_MONOENTIDAD(966),
    GI_ALERTAS_ASUNTO_VINCULACIONES(967),GI_ALERTAS_ASUNTO_DESVINCULACIONES(968),GI_ALERTAS_ASUNTO_SITUACIONES_ADMINISTRATIVAS(969),
    GI_ALERTAS_MESES_INACTIVIDAD(970),GI_ALERTAS_DIAS_INACTIVIDAD(971),GI_ALERTAS_ROLES_MULTIENTIDAD(972),GI_ALERTAS_ROLES_MONOENTIDAD(973),
    CARGA_MASIVA_ACTIVA_NOTIFICACIONES(5713), CARGA_MASIVA_CALENDARIO_NOTIFICACION(5714), CM_ESTADO_FINALIZADO(1952),
    CM_NUMERO_DIAS_REPORTE_DISPONIBLE(2188),
    CONTRATO_MODIFICACION_TERMINACION_AUTOMATICA(1321),CONTRATO_MOTIVO_SUSPENSION_CUMPLIMIENTO_OBJETO(1319);

    private int value;

    /**
     * Constructor.
     * 
     * @param value value
     */
    TipoParametro(int value) {
    		this.setValue(value);
    }

    public void setValue(int value){
    		this.value = value;
    }

    public int getValue(){
	    return value;
    }	

}
