package co.gov.dafp.sigep2.entity.jpa.seguridad;
// Generated 24/11/2017 03:31:14 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.ColumnResult;
import javax.persistence.ConstructorResult;
import javax.persistence.Convert;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SqlResultSetMapping;
import javax.persistence.SqlResultSetMappings;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import co.gov.dafp.sigep2.converter.BooleanToNumberConverter;
import co.gov.dafp.sigep2.converter.UpperCaseConverter;
import co.gov.dafp.sigep2.entity.EntidadBase;
import co.gov.dafp.sigep2.entity.EntidadBaseDTO;
import co.gov.dafp.sigep2.entity.seguridad.RolDTO;

/**
 * Rol generated by hbm2java
 */
@Entity(name = "Rol")
@Table(name = "ROL")
@SqlResultSetMappings({ @SqlResultSetMapping(name = Rol.ROL_MAPPING, classes = {
		@ConstructorResult(targetClass = RolDTO.class, columns = { @ColumnResult(name = "COD_ROL", type = Long.class),
				@ColumnResult(name = "COD_ROL_PADRE", type = Long.class),
				@ColumnResult(name = "NOMBRE", type = String.class),
				@ColumnResult(name = "DESCRIPCION_ROL", type = String.class),
				@ColumnResult(name = "FLG_ACTIVO", type = Boolean.class),
				@ColumnResult(name = "FLG_ESTADO", type = Boolean.class) }) }) })
public class Rol extends EntidadBase implements java.io.Serializable {
	private static final long serialVersionUID = 1199910631827376668L;

	public static final String ROL_MAPPING = "co.gov.dafp.sigep2.entity.jpa.seguridad.mapping.Rol";

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "cod_rol", unique = true, nullable = false, precision = 22, scale = 0)
	private long id;

	
	@Column(name = "COD_ROL_PADRE", nullable = true)
	private Long rolPadre;

	@Convert(converter = UpperCaseConverter.class)
	@Column(name = "NOMBRE", nullable = false, length = 50)
	private String nombre;

	@Convert(converter = UpperCaseConverter.class)
	@Column(name = "DESCRIPCION_ROL")
	private String descripcionRol;

	@Column(name = "FLG_ACTIVO", nullable = false, precision = 1, scale = 0)
	@Convert(converter = BooleanToNumberConverter.class)
	private boolean flgActivo;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHA_MODIFICACION", nullable = false, length = 7)
	private Date fechaModificacion;

	@Column(name = "FLG_ESTADO", precision = 22, scale = 0)
	@Convert(converter = BooleanToNumberConverter.class)
	private Boolean flgEstado = Boolean.TRUE;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rol", targetEntity = UsuarioRolEntidad.class)
	private List<UsuarioRolEntidad> usuarioRolEntidads;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rol", targetEntity = PermisoRol.class)
	private List<PermisoRol> permisoRols;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "AUD_FECHA_ACTUALIZACION", nullable = false, length = 7)
	protected Date audFechaActualizacion;

	@Column(name = "AUD_COD_USUARIO", nullable = false, precision = 22, scale = 0)
	protected Long audCodUsuario;

	@Column(name = "AUD_COD_ROL", nullable = false, precision = 22, scale = 0)
	protected Long audCodRol;

	@Column(name = "AUD_ACCION", nullable = false, precision = 22, scale = 0)
	protected Long audAccion;

	public Rol() {
		super();
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getRolPadre() {
		return rolPadre;
	}

	public void setRolPadre(Long rolPadre) {
		this.rolPadre = rolPadre;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcionRol() {
		return this.descripcionRol;
	}

	public void setDescripcionRol(String descripcionRol) {
		this.descripcionRol = descripcionRol;
	}

	public boolean isFlgActivo() {
		return this.flgActivo;
	}

	public void setFlgActivo(boolean flgActivo) {
		this.flgActivo = flgActivo;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public Boolean getFlgEstado() {
		return this.flgEstado;
	}

	public void setFlgEstado(Boolean flgEstado) {
		this.flgEstado = flgEstado;
	}

	public List<UsuarioRolEntidad> getUsuarioRolEntidads() {
		return this.usuarioRolEntidads;
	}

	public void setUsuarioRolEntidads(List<UsuarioRolEntidad> usuarioRolEntidads) {
		this.usuarioRolEntidads = usuarioRolEntidads;
	}

	public List<PermisoRol> getPermisoRols() {
		return this.permisoRols;
	}

	public void setPermisoRols(List<PermisoRol> permisoRols) {
		this.permisoRols = permisoRols;
	}

	public Date getAudFechaActualizacion() {
		return audFechaActualizacion;
	}

	public void setAudFechaActualizacion(Date audFechaActualizacion) {
		this.audFechaActualizacion = audFechaActualizacion;
	}

	public Long getAudCodUsuario() {
		return audCodUsuario;
	}

	public void setAudCodUsuario(Long audCodUsuario) {
		this.audCodUsuario = audCodUsuario;
	}

	public Long getAudCodRol() {
		return audCodRol;
	}

	public void setAudCodRol(Long audCodRol) {
		this.audCodRol = audCodRol;
	}

	public Long getAudAccion() {
		return audAccion;
	}

	public void setAudAccion(Long audAccion) {
		this.audAccion = audAccion;
	}

	@Override
	public String toString() {
		return "Rol [id=" + id  + ", nombre=" + nombre + ", descripcionRol=" + descripcionRol
				+ ", flgActivo=" + flgActivo + ", flgEstado=" + flgEstado + "]";
	}

	@Override
	public EntidadBaseDTO getDTO() {
		return new RolDTO(id, rolPadre != null ? rolPadre : null, nombre, descripcionRol, flgActivo, flgEstado);
	}

}
